Radiation Scheme in CCPP: working_src/gloopr.f File Reference
gloopr.f File Reference
Functions/Subroutines
subroutine gloopr (grid_fld, g3d_fld, aoi_fld, lats_nodes_r, global_lats_r, lonsperlar, phour, deltim, xlon, xlat, coszdg, COSZEN, slmsk, snwdph, SNCOVR, SNOALB, ZORL, TSEA, HPRIME, SFALB, ALVSF, ALNSF,ALVWF,ALNWF, FACSF,FACWF, CV, CVT, CVB ,SWH, swhc, HLW, hlwc, SFCNSW, SFCDLW, FICE,TISFC, SFCDSW, sfcemis, TSFLW, FLUXR, phy_f3d, phy_f2d, slag, sdec, cdec, NBLCK, KDT
NCEP/GFS shortwave (SW) radiation module. radiation driver, gloopr.f, calls grrad.f, which prepares atmospheric profiles, invokes main radiation calculations, and computes radiative fluxes and heating rates for some arbitrary number of vertical columns.
Function/Subroutine Documentation
subroutine gloopr (type(grid_var_data) grid_fld, type(g3d_var_data) g3d_fld, type(aoi_var_data) aoi_fld, integer, dimension(nodes), intent(in) lats_nodes_r, integer, dimension(latr), intent(in) global_lats_r, integer, dimension(latr), intent(in) lonsperlar, real (kind=kind_phys), intent(inout) phour, real (kind=kind_phys), intent(inout) deltim, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) xlon, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) xlat, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) coszdg, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) COSZEN, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) slmsk, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) snwdph, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) SNCOVR, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) SNOALB, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) ZORL, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) TSEA, real (kind=kind_phys), dimension(nmtvr,lonr,lats_node_r), intent(inout) HPRIME, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) SFALB, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) ALVSF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) ALNSF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) ALVWF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) ALNWF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) FACSF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) FACWF, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) CV, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) CVT, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) CVB, real (kind=kind_phys), dimension (ngptc,levs,nblck,lats_node_r), intent(out) SWH, real (kind=kind_phys), dimension (ngptc,levs,nblck,lats_node_r), intent(out) swhc, real (kind=kind_phys), dimension (ngptc,levs,nblck,lats_node_r), intent(out) HLW, real (kind=kind_phys), dimension (ngptc,levs,nblck,lats_node_r), intent(out) hlwc, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) SFCNSW, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) SFCDLW, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) FICE, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(in) TISFC, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) SFCDSW, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) sfcemis, real (kind=kind_phys), dimension(lonr,lats_node_r), intent(out) TSFLW, real (kind=kind_phys), dimension (nfxr,lonr,lats_node_r), intent(inout) FLUXR, real (kind=kind_phys), dimension(ngptc,levs,ntot3d,nblck,lats_node_r), intent(inout) phy_f3d, real (kind=kind_phys), dimension(lonr,lats_node_r,ntot2d), intent(inout) phy_f2d, real (kind=kind_phys), intent(out) slag, real (kind=kind_phys), intent(out) sdec, real (kind=kind_phys), intent(out) cdec, integer, intent(in) NBLCK, integer, intent(in) KDT)
Definition at line 20 of file gloopr.f.
References physcons::con_fvirt, physcons::con_rerth, physcons::con_rocp, physcons::dxinv, physcons::dxmin, module_radiation_driver::grrad(), physparam::iaerflg, physparam::ipsd0, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, module_radiation_driver::radinit(), and module_radiation_driver::radupdate().