Radiation Scheme in CCPP: module_radsw_main
module_radsw_main
RRTMG Radiation Scheme
This module includes ncep's modifications of the rrtm-sw radiation code from aer inc.
Modules
Module_radsw_cldprtb
This module contains coefficients of cloud optical properties for each of the spectral bands. It is modified from AER/ECMWF RRTM SW radiation package subroutine "susrtop".
Module_radsw_kgb16
This module sets up absorption coefficients for band 16: 2600-3250 cm-1 (low - h2o, ch4; high - ch4)
Module_radsw_kgb17
This module sets up absorption coeffients for band 17: 3250-4000 cm-1 (low - h2o,co2; high - h2o,co2)
Module_radsw_kgb18
This module sets up absorption coeffients for band 18: 4000-4650 cm-1 (low - h2o,ch4; high - ch4)
Module_radsw_kgb19
This module sets up absorption coeffients for band 19: 4650-5150 cm-1 (low - h2o,co2; high - co2)
Module_radsw_kgb20
This module sets up absorption coeffients for band 20: 5150-6150 cm-1 (low - h2o; high - h2o)
Module_radsw_kgb21
This module sets up absorption coeffients for band 21: 6150-7700 cm-1 (low - h2o,co2; high - h2o,co2)
Module_radsw_kgb22
This module sets up absorption coeffients for band 22: 7700-8050 cm-1 (low - h2o, o2; high - o2)
Module_radsw_kgb23
This module sets up absorption coeffients for band 23: 8050-12850 cm-1 (low - h2o; high - nothing)
Module_radsw_kgb24
This module sets up absorption coeffients for band 24: 12850-16000 cm-1 (low - h2o, o2; high - o2)
Module_radsw_kgb25
This module sets up absorption coeffients for band 25: 16000-22650 cm-1 (low - h2o; high - nothing)
Module_radsw_kgb26
This module sets up absorption coeffients for band 26: 22650-29000 cm-1 (low - nothing; high - nothing)
Module_radsw_kgb27
This module sets up absorption coeffients for band 27: 29000-38000 cm-1 (low - o3; high - o3)
Module_radsw_kgb28
This module sets up absorption coeffients for band 28: 38000-50000 cm-1 (low - o3,o2; high - o3,o2)
Module_radsw_kgb29
This module sets up absorption coeffients for band 29: 820-2600 cm-1 (low - h2o; high - co2)
Module_radsw_parameters
This module contains SW band parameters set up.
Module_radsw_ref
This module contains reference temperature and pressure.
Module_radsw_sflux
This module contains spectral distribution of solar radiation flux used to obtain the incoming solar flux at toa.
Modules
module module_radsw_ref
module module_radsw_cldprtb
module module_radsw_sflux
module module_radsw_kgb16
module module_radsw_kgb17
module module_radsw_kgb18
module module_radsw_kgb19
module module_radsw_kgb20
module module_radsw_kgb21
module module_radsw_kgb22
module module_radsw_kgb23
module module_radsw_kgb24
module module_radsw_kgb25
module module_radsw_kgb26
module module_radsw_kgb27
module module_radsw_kgb28
module module_radsw_kgb29
module module_radsw_main
module module_radsw_parameters
Data Types
type module_radsw_parameters::sfcfsw_type
define type construct for radiation fluxes at surface
type module_radsw_parameters::profsw_type
define type construct for optional radiation flux profiles
type module_radsw_parameters::cmpfsw_type
define type construct for optional component downward fluxes at surface
Functions/Subroutines
subroutine, public module_radsw_main::rswinit
This subroutine initializes non-varying module variables, conversion factors, and look-up tables.
subroutine module_radsw_main::mcica_subcol
This subroutine computes the sub-colum cloud profile flag array.
subroutine module_radsw_main::setcoef
This subroutine computes various coefficients needed in radiative transfer calculation.
subroutine module_radsw_main::spcvrtm
This subroutine computes the shortwave radiative fluxes using two-stream method of h. barder and mcica,the monte-carlo independent column approximation, for the representation of sub-grid cloud variability (i.e. cloud overlap).
subroutine module_radsw_main::taumol
This subroutine calculates optical depths for gaseous absorption and rayleigh scattering
subroutine called taugb## (## = 16-29)
subroutine taumol16
The subroutine computes the optical depth in band 16: 2600-3250 cm-1 (low - h2o,ch4; high - ch4)
Variables
real(kind=kind_phys), dimension(59) module_radsw_ref::tref
real(kind=kind_phys), dimension(58, nblow:nbhgh), public module_radsw_cldprtb::ssaliq1
real(kind=kind_phys), dimension(58, nblow:nbhgh), public module_radsw_cldprtb::asyliq1
real(kind=kind_phys), dimension(43, nblow:nbhgh), public module_radsw_cldprtb::extice2
real(kind=kind_phys), dimension(43, nblow:nbhgh), public module_radsw_cldprtb::ssaice2
real(kind=kind_phys), dimension(43, nblow:nbhgh), public module_radsw_cldprtb::asyice2
real(kind=kind_phys), dimension(46, nblow:nbhgh), public module_radsw_cldprtb::extice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public module_radsw_cldprtb::ssaice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public module_radsw_cldprtb::asyice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public module_radsw_cldprtb::fdlice3
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::abari
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::bbari
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::cbari
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::dbari
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::ebari
real(kind=kind_phys), dimension(5), public module_radsw_cldprtb::fbari
real(kind=kind_phys), public module_radsw_cldprtb::a0r
real(kind=kind_phys), public module_radsw_cldprtb::a1r
real(kind=kind_phys), public module_radsw_cldprtb::a0s
real(kind=kind_phys), public module_radsw_cldprtb::a1s
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0r
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0s
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b1s
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0r
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0s
integer, parameter module_radsw_sflux::mfs02 = 5
integer, parameter module_radsw_sflux::mfs03 = 9
integer, parameter module_radsw_sflux::mfb01 = 7
integer, parameter module_radsw_sflux::mfb02 = 2
integer, parameter module_radsw_sflux::mfb03 = 5
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_sflux::strrat
real(kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_sflux::specwt
integer, dimension(nblow:nbhgh), public module_radsw_sflux::layreffr
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ix1
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ix2
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ibx
real(kind=kind_phys), parameter, public module_radsw_sflux::scalekur =50.15/48.37
real(kind=kind_phys), dimension(ngmax, mfs01, mfb01), target, public module_radsw_sflux::sfluxref01
real(kind=kind_phys), dimension(ngmax, mfs02, mfb02), target, public module_radsw_sflux::sfluxref02
real(kind=kind_phys), dimension(ngmax, mfs03, mfb03), target, public module_radsw_sflux::sfluxref03
integer, public module_radsw_kgb16::msb16
integer, public module_radsw_kgb16::msf16
integer, public module_radsw_kgb16::mfr16
real(kind=kind_phys), dimension(msf16, ng16), public module_radsw_kgb16::selfref
real(kind=kind_phys), dimension(msa16, ng16), public module_radsw_kgb16::absa
real(kind=kind_phys), dimension(msb16, ng16), public module_radsw_kgb16::absb
real(kind=kind_phys), dimension(mfr16, ng16), public module_radsw_kgb16::forref
real(kind=kind_phys), parameter, public module_radsw_kgb16::rayl = 2.91e-10
integer, public module_radsw_kgb17::msb17
integer, public module_radsw_kgb17::msf17
integer, public module_radsw_kgb17::mfr17
real(kind=kind_phys), dimension(msf17, ng17), public module_radsw_kgb17::selfref
real(kind=kind_phys), dimension(msa17, ng17), public module_radsw_kgb17::absa
real(kind=kind_phys), dimension(msb17, ng17), public module_radsw_kgb17::absb
real(kind=kind_phys), dimension(mfr17, ng17), public module_radsw_kgb17::forref
real(kind=kind_phys), parameter, public module_radsw_kgb17::rayl = 6.86e-10
integer, public module_radsw_kgb18::msb18
integer, public module_radsw_kgb18::msf18
integer, public module_radsw_kgb18::mfr18
real(kind=kind_phys), dimension(msf18, ng18), public module_radsw_kgb18::selfref
real(kind=kind_phys), dimension(msa18, ng18), public module_radsw_kgb18::absa
real(kind=kind_phys), dimension(msb18, ng18), public module_radsw_kgb18::absb
real(kind=kind_phys), dimension(mfr18, ng18), public module_radsw_kgb18::forref
real(kind=kind_phys), parameter, public module_radsw_kgb18::rayl = 1.39e-09
integer, public module_radsw_kgb19::msb19
integer, public module_radsw_kgb19::msf19
integer, public module_radsw_kgb19::mfr19
real(kind=kind_phys), dimension(msf19, ng19), public module_radsw_kgb19::selfref
real(kind=kind_phys), dimension(msa19, ng19), public module_radsw_kgb19::absa
real(kind=kind_phys), dimension(msb19, ng19), public module_radsw_kgb19::absb
real(kind=kind_phys), dimension(mfr19, ng19), public module_radsw_kgb19::forref
real(kind=kind_phys), parameter, public module_radsw_kgb19::rayl = 2.29e-09
integer, public module_radsw_kgb20::msb20
integer, public module_radsw_kgb20::msf20
integer, public module_radsw_kgb20::mfr20
real(kind=kind_phys), dimension(mfr20, ng20), public module_radsw_kgb20::forref
real(kind=kind_phys), dimension(ng20), public module_radsw_kgb20::absch4
real(kind=kind_phys), dimension(msa20, ng20), public module_radsw_kgb20::absa
real(kind=kind_phys), dimension(msb20, ng20), public module_radsw_kgb20::absb
real(kind=kind_phys), dimension(msf20, ng20), public module_radsw_kgb20::selfref
real(kind=kind_phys), parameter, public module_radsw_kgb20::rayl = 4.12e-09
integer, public module_radsw_kgb21::msb21
integer, public module_radsw_kgb21::msf21
integer, public module_radsw_kgb21::mfr21
real(kind=kind_phys), dimension(mfr21, ng21), public module_radsw_kgb21::forref
real(kind=kind_phys), dimension(msa21, ng21), public module_radsw_kgb21::absa
real(kind=kind_phys), dimension(msb21, ng21), public module_radsw_kgb21::absb
real(kind=kind_phys), dimension(msf21, ng21), public module_radsw_kgb21::selfref
real(kind=kind_phys), parameter, public module_radsw_kgb21::rayl = 9.41e-09
integer, public module_radsw_kgb22::msb22
integer, public module_radsw_kgb22::msf22
integer, public module_radsw_kgb22::mfr22
real(kind=kind_phys), dimension(mfr22, ng22), public module_radsw_kgb22::forref
real(kind=kind_phys), dimension(msa22, ng22), public module_radsw_kgb22::absa
real(kind=kind_phys), dimension(msb22, ng22), public module_radsw_kgb22::absb
real(kind=kind_phys), dimension(msf22, ng22), public module_radsw_kgb22::selfref
real(kind=kind_phys), parameter, public module_radsw_kgb22::rayl = 1.54e-08
integer, public module_radsw_kgb23::msf23
integer, public module_radsw_kgb23::mfr23
real(kind=kind_phys), dimension(mfr23, ng23), public module_radsw_kgb23::forref
real(kind=kind_phys), dimension(msa23, ng23), public module_radsw_kgb23::absa
real(kind=kind_phys), dimension(msf23, ng23), public module_radsw_kgb23::selfref
real(kind=kind_phys), dimension(ng23), public module_radsw_kgb23::rayl
real(kind=kind_phys), parameter, public module_radsw_kgb23::givfac = 1.029
integer, public module_radsw_kgb24::msb24
integer, public module_radsw_kgb24::msf24
integer, public module_radsw_kgb24::mfr24
integer, public module_radsw_kgb24::mfx24
real(kind=kind_phys), dimension(mfr24, ng24), public module_radsw_kgb24::forref
real(kind=kind_phys), dimension(msa24, ng24), public module_radsw_kgb24::absa
real(kind=kind_phys), dimension(msb24, ng24), public module_radsw_kgb24::absb
real(kind=kind_phys), dimension(msf24, ng24), public module_radsw_kgb24::selfref
real(kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3a
real(kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3b
real(kind=kind_phys), dimension(ng24, mfx24), public module_radsw_kgb24::rayla
real(kind=kind_phys), dimension(ng24), public module_radsw_kgb24::raylb
real(kind=kind_phys), dimension(msa25, ng25), public module_radsw_kgb25::absa
real(kind=kind_phys), dimension(ng25), public module_radsw_kgb25::rayl
real(kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3a
real(kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3b
integer, public module_radsw_kgb27::msb27
real(kind=kind_phys), dimension(msa27, ng27), public module_radsw_kgb27::absa
real(kind=kind_phys), dimension(msb27, ng27), public module_radsw_kgb27::absb
real(kind=kind_phys), dimension(ng27), public module_radsw_kgb27::rayl
integer, public module_radsw_kgb28::msb28
real(kind=kind_phys), dimension(msa28, ng28), public module_radsw_kgb28::absa
real(kind=kind_phys), dimension(msb28, ng28), public module_radsw_kgb28::absb
real(kind=kind_phys), parameter, public module_radsw_kgb28::rayl = 2.02e-05
integer, public module_radsw_kgb29::msb29
integer, public module_radsw_kgb29::msf29
integer, public module_radsw_kgb29::mfr29
real(kind=kind_phys), dimension(mfr29, ng29), public module_radsw_kgb29::forref
real(kind=kind_phys), dimension(msa29, ng29), public module_radsw_kgb29::absa
real(kind=kind_phys), dimension(msb29, ng29), public module_radsw_kgb29::absb
real(kind=kind_phys), dimension(msf29, ng29), public module_radsw_kgb29::selfref
real(kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absh2o
real(kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absco2
real(kind=kind_phys), parameter, public module_radsw_kgb29::rayl = 9.30e-11
real(kind=kind_phys), parameter module_radsw_main::eps = 1.0e-6
real(kind=kind_phys), parameter module_radsw_main::oneminus = 1.0 - eps
real(kind=kind_phys), parameter module_radsw_main::bpade = 1.0/0.278
real(kind=kind_phys), parameter module_radsw_main::stpfac = 296.0/1013.0
real(kind=kind_phys), parameter module_radsw_main::ftiny = 1.0e-12
real(kind=kind_phys), parameter module_radsw_main::s0 = 1368.22
real(kind=kind_phys), parameter module_radsw_main::f_zero = 0.0
real(kind=kind_phys), parameter module_radsw_main::f_one = 1.0
real(kind=kind_phys), parameter module_radsw_main::amdw = con_amd/con_amw
real(kind=kind_phys), parameter module_radsw_main::amdo3 = con_amd/con_amo3
integer, dimension(nblow:nbhgh) module_radsw_main::nspa
integer, dimension(nblow:nbhgh) module_radsw_main::nspb
integer, dimension(nblow:nbhgh) module_radsw_main::idxebc
integer, dimension(nblow:nbhgh) module_radsw_main::idxsfc
integer, parameter module_radsw_main::nuvb = 27
logical module_radsw_main::lhswb = .false.
logical module_radsw_main::lhsw0 = .false.
logical module_radsw_main::lflxprf = .false.
logical module_radsw_main::lfdncmp = .false.
real(kind=kind_phys), dimension(0:ntbmx) module_radsw_main::exp_tbl
real(kind=kind_phys) module_radsw_main::heatfac
integer, parameter module_radsw_main::ipsdsw0 = 1
real(kind=kind_phys) module_radsw_parameters::topfsw_type::upfxc
total sky upward flux at toa
real(kind=kind_phys) module_radsw_parameters::topfsw_type::dnfxc
total sky downward flux at toa
real(kind=kind_phys) module_radsw_parameters::topfsw_type::upfx0
clear sky upward flux at toa
real(kind=kind_phys) module_radsw_parameters::sfcfsw_type::upfxc
total sky upward flux at sfc
real(kind=kind_phys) module_radsw_parameters::sfcfsw_type::dnfxc
total sky downward flux at sfc
real(kind=kind_phys) module_radsw_parameters::sfcfsw_type::upfx0
clear sky upward flux at sfc
real(kind=kind_phys) module_radsw_parameters::sfcfsw_type::dnfx0
clear sky downward flux at sfc
real(kind=kind_phys) module_radsw_parameters::profsw_type::upfxc
total sky level upward flux
real(kind=kind_phys) module_radsw_parameters::profsw_type::dnfxc
total sky level downward flux
real(kind=kind_phys) module_radsw_parameters::profsw_type::upfx0
clear sky level upward flux
real(kind=kind_phys) module_radsw_parameters::profsw_type::dnfx0
clear sky level downward flux
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::uvbfc
total sky downward uv-b flux at sfc
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::uvbf0
clear sky downward uv-b flux at sfc
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::nirbm
sfc downward nir direct beam flux
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::nirdf
sfc downward nir diffused flux
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::visbm
sfc downward uv+vis direct beam flux
real(kind=kind_phys) module_radsw_parameters::cmpfsw_type::visdf
sfc downward uv=vis diffused flux
integer, parameter module_radsw_parameters::nblow = 16
band range lower limit
integer, parameter module_radsw_parameters::nbhgh = 29
band range upper limit
integer, parameter module_radsw_parameters::nbands = NBHGH-NBLOW+1
number of spectral bands
integer, parameter module_radsw_parameters::ngptsw = 112
total number of g-point in all bands
integer, parameter module_radsw_parameters::ngmax = 16
max num of g-point in one band
integer, parameter module_radsw_parameters::maxgas = 7
max num of absorbing gases
integer, parameter module_radsw_parameters::ntbmx = 10000
index upper limit of trans table
integer, parameter module_radsw_parameters::nswstr = 1
integer, parameter module_radsw_parameters::nbdsw = NBANDS
integer module_radsw_parameters::ng16
integer module_radsw_parameters::ng17
integer module_radsw_parameters::ng18
integer module_radsw_parameters::ng19
integer module_radsw_parameters::ng20
integer module_radsw_parameters::ng21
integer module_radsw_parameters::ng22
integer module_radsw_parameters::ng23
integer module_radsw_parameters::ng24
integer module_radsw_parameters::ng25
integer module_radsw_parameters::ng26
integer module_radsw_parameters::ng27
integer module_radsw_parameters::ng28
integer module_radsw_parameters::ng29
integer, dimension(nblow:nbhgh) module_radsw_parameters::ng
integer module_radsw_parameters::ns16
integer module_radsw_parameters::ns17
integer module_radsw_parameters::ns18
integer module_radsw_parameters::ns19
integer module_radsw_parameters::ns20
integer module_radsw_parameters::ns21
integer module_radsw_parameters::ns22
integer module_radsw_parameters::ns23
integer module_radsw_parameters::ns24
integer module_radsw_parameters::ns25
integer module_radsw_parameters::ns26
integer module_radsw_parameters::ns27
integer module_radsw_parameters::ns28
integer module_radsw_parameters::ns29
integer, dimension(nblow:nbhgh) module_radsw_parameters::ngs
integer, dimension(ngptsw) module_radsw_parameters::ngb
real(kind=kind_phys), dimension(nbands) module_radsw_parameters::wvnum1
real(kind=kind_phys), dimension(nbands) module_radsw_parameters::wvnum2
subroutine, public module_radsw_main::swrad
This subroutine is the main sw radiation routine.
subroutine module_radsw_main::cldprop
This subroutine computes the cloud optical properties for each cloudy layer and g-point interval.
subroutine module_radsw_main::spcvrtc
This subroutine computes the shortwave radiative fluxes using two-stream method.
subroutine module_radsw_main::swflux
This subroutine computes the upward and downward radiation fluxes.
Detailed Description
Data Type Documentation
type module_radsw_parameters::sfcfsw_type
Definition at line 91 of file radsw_param.f.
Class Members
real(kind=kind_phys) dnfx0 clear sky downward flux at sfc
real(kind=kind_phys) dnfxc total sky downward flux at sfc
real(kind=kind_phys) upfx0 clear sky upward flux at sfc
real(kind=kind_phys) upfxc total sky upward flux at sfc
type module_radsw_parameters::profsw_type
Definition at line 105 of file radsw_param.f.
Class Members
real(kind=kind_phys) dnfx0 clear sky level downward flux
real(kind=kind_phys) dnfxc total sky level downward flux
real(kind=kind_phys) upfx0 clear sky level upward flux
real(kind=kind_phys) upfxc total sky level upward flux
type module_radsw_parameters::cmpfsw_type
Definition at line 119 of file radsw_param.f.
Class Members
real(kind=kind_phys) nirbm sfc downward nir direct beam flux
real(kind=kind_phys) nirdf sfc downward nir diffused flux
real(kind=kind_phys) uvbf0 clear sky downward uv-b flux at sfc
real(kind=kind_phys) uvbfc total sky downward uv-b flux at sfc
real(kind=kind_phys) visbm sfc downward uv+vis direct beam flux
real(kind=kind_phys) visdf sfc downward uv=vis diffused flux
Function/Subroutine Documentation
subroutine module_radsw_main::cldprop () private
Parameters
[in] cfrac real, (nlay), layer cloud fraction
..... for physparam::iswcliq > 0 (prognostic cloud scheme) - - -
[in] cliqp real, (nlay), layer in-cloud liq water path (\(g/m^2\))
[in] reliq real, (nlay), mean eff radius for liq cloud (micron)
[in] cicep real, (nlay), layer in-cloud ice water path (\(g/m^2\))
[in] reice real, (nlay), mean eff radius for ice cloud (micron)
[in] cdat1 real, (nlay), layer rain drop water path (\(g/m^2\))
[in] cdat2 real, (nlay), effective radius for rain drop (micron)
[in] cdat3 real, (nlay), layer snow flake water path(\(g/m^2\))
[in] cdat4 real, (nlay), mean eff radius for snow flake(micron)
..... for physparam::iswcliq = 0 (diagnostic cloud scheme) - - -
[in] cliqp real, (nlay), not used
[in] cicep real, (nlay), not used
[in] reliq real, (nlay), not used
[in] reice real, (nlay), not used
[in] cdat1 real, (nlay), layer cloud optical depth
[in] cdat2 real, (nlay), layer cloud single scattering albedo
[in] cdat3 real, (nlay), layer cloud asymmetry factor
[in] cdat4 real, (nlay), optional use
[in] cf1 real, 1, effective total cloud cover at surface
[in] nlay integer, 1, vertical layer number
[in] ipseed integer, 1, permutation seed for generating random numbers (isubcsw>0)
[out] taucw real,(nlay,nbdsw), cloud optical depth, w/o delta scaled
[out] ssacw real,(nlay,nbdsw), weighted cloud single scattering albedo (ssa = ssacw / taucw)
[out] asycw real,(nlay,nbdsw), weighted cloud asymmetry factor (asy = asycw / ssacw)
[out] cldfrc real,(nlay), cloud fraction of grid mean value
[out] cldfmc real,(nlay,ngptsw), cloud fraction for each sub-column
General Algorithm
Compute cloud radiative properties for a cloudy column.
Compute optical properties for rain and snow
For rain: tauran/ssaran/asyran
For snow: tausnw/ssasnw/asysnw
Calculation of absorption coefficients due to water clouds
For water clouds: tauliq/ssaliq/asyliq
Calculation of absorption coefficients due to ice clouds
For ice clouds: tauice/ssaice/asyice
For Prognostic cloud scheme: sum up the cloud optical property:
\(taucw=tauliq+tauice+tauran+tausnw \)
\(ssacw=ssaliq+ssaice+ssaran+ssasnw \)
\(asycw=asyliq+asyice+asyran+asysnw \)
if physparam::isubcsw > 0, call mcica_subcol() to distribute cloud properties to each g-point
Definition at line 1454 of file radsw_main.f.
References module_radsw_cldprtb::a0r, module_radsw_cldprtb::a0s, module_radsw_cldprtb::a1s, module_radsw_cldprtb::abari, module_radsw_cldprtb::asyice2, module_radsw_cldprtb::asyice3, module_radsw_cldprtb::asyliq1, module_radsw_cldprtb::b0r, module_radsw_cldprtb::b0s, module_radsw_cldprtb::b1s, module_radsw_cldprtb::bbari, module_radsw_cldprtb::c0r, module_radsw_cldprtb::c0s, module_radsw_cldprtb::cbari, module_radsw_cldprtb::dbari, module_radsw_cldprtb::ebari, module_radsw_cldprtb::extice2, module_radsw_cldprtb::extice3, module_radsw_cldprtb::extliq1, f_one, f_zero, module_radsw_cldprtb::fbari, ftiny, idxebc, mcica_subcol(), module_radsw_parameters::nbdsw, module_radsw_parameters::nbhgh, module_radsw_parameters::nblow, module_radsw_parameters::ngptsw, module_radsw_cldprtb::ssaice2, module_radsw_cldprtb::ssaice3, and module_radsw_cldprtb::ssaliq1.
Referenced by swrad().
subroutine module_radsw_main::mcica_subcol () private
Parameters
[in] cldf real, (nlay), layer cloud fraction
[in] nlay integer, 1, number of model vertical layers
[in] ipseed integer, 1, permute seed for random num generator
[out] lcloudy logical, (nlay,ngptsw), sub-colum cloud profile flag array
External Module Variables
physparam::iovrsw - control flag for cloud overlapping method
=0:random; =1:maximum/random; =2:maximum
Definition at line 1817 of file radsw_main.f.
References f_one, and module_radsw_parameters::ngptsw.
Referenced by cldprop().
subroutine, public module_radsw_main::rswinit ()
Parameters
[in] me integer, print control for parallel process
[out] NONE
External Module Variables
physparam::iswrate - heating rate unit selections
=1: output in k/day
=2: output in k/second
physparam::iswrgas - control flag for rare gases (ch4,n2o,o2, etc.)
=0: do not include rare gases
>0: include all rare gases
physparam::iswcliq - liquid cloud optical properties contrl flag
=0: input cloud opt depth from diagnostic scheme
>0: input cwp,rew, and other cloud content parameters
physparam::isubcsw - sub-column cloud approximation control flag
=0: no sub-col cld treatment, use grid-mean cld quantities
=1: mcica sub-col, prescribed seeds to get random numbers
=2: mcica sub-col, providing array icseed for random numbers
physparam::icldflg - cloud scheme control flag
=0: diagnostic scheme gives cloud tau, omiga, and g.
=1: prognostic scheme gives cloud liq/ice path, etc.
physparam::iovrsw - clouds vertical overlapping control flag
=0: random overlapping clouds
=1: maximum/random overlapping clouds
=2: maximum overlap cloud
physparam::iswmode - control flag for 2-stream transfer scheme
=1; delta-eddington (joseph et al., 1976)
=2: pifm (zdunkowski et al., 1980)
=3: discrete ordinates (liou, 1973)
Definition at line 1271 of file radsw_main.f.
References bpade, exp_tbl, heatfac, module_radsw_parameters::ntbmx, and vtagsw.
Referenced by module_radiation_driver::radinit().
subroutine module_radsw_main::setcoef () private
Parameters
[in] pavel real, (nlay), layer pressure (mb)
[in] tavel real, (nlay), layer temperature (k)
[in] h2ovmr real, (nlay), layer w.v. volumn mixing ratio (kg/kg)
[in] nlay integer,1, total number of vertical layers
[in] nlp1 integer,1, total number of vertical levels
[out] laytrop integer,1, tropopause layer index (unitless)
[out] jp integer, (nlay), indices of lower reference pressure
[out] jt,jt1 integer, (nlay), indices of lower reference temperatures at levels of jp and jp+1
[out] facij real, (nlay), factors mltiply the reference ks,i,j=0/1 for lower/higher of the 2 appropriate temperature and altitudes.
[out] selffac real, (nlay), scale factor for w. v. self-continuum equals (w.v. density)/(atmospheric density at 296k and 1013 mb)
[out] seffrac real, (nlay), factor for temperature interpolation of reference w.v. self-continuum data
[out] indself integer, (nlay), index of lower ref temp for selffac
[out] forfac real, (nlay), scale factor for w. v. foreign-continuum
[out] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[out] indfor integer, (nlay), index of lower ref temp for forfac
Definition at line 1991 of file radsw_main.f.
References f_one, f_zero, module_radsw_ref::preflog, stpfac, and module_radsw_ref::tref.
Referenced by swrad().
subroutine module_radsw_main::spcvrtc () private
Parameters
[in] ssolar real, 1, incoming solar flux at top
[in] cosz real, 1, cosine solar zenith angle
[in] sntz real, 1, secant solar zenith angle
[in] albbm real, 2, surface albedo for direct beam radiation
[in] albdf real, 2, surface albedo for diffused radiation
[in] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[in] cldfrc real, (nlay),layer cloud fraction
[in] cf1 real, 1, >0: cloudy sky, otherwise: clear sky
[in] cf0 real, 1, =1-cf1
[in] taug real, (nlay,ngptsw), spectral optical depth for gases
[in] taur real, (nlay,ngptsw), optical depth for rayleigh scattering
[in] tauae real, (nlay,nbdsw), aerosols optical depth
[in] ssaae real, (nlay,nbdsw), aerosols single scattering albedo
[in] asyae real, (nlay,nbdsw), aerosols asymmetry factor
[in] taucw real, (nlay,nbdsw), weighted cloud optical depth
[in] ssacw real, (nlay,nbdsw), weighted cloud single scat albedo
[in] asycw real, (nlay,nbdsw), weighted cloud asymmetry factor
[in] nlay,nlp1 integer, 1, number of layers/levels
[out] fxupc real, (nlp1,nbdsw), tot sky upward flux
[out] fxdnc real, (nlp1,nbdsw), tot sky downward flux
[out] fxup0 real, (nlp1,nbdsw), clr sky upward flux
[out] fxdn0 real, (nlp1,nbdsw), clr sky downward flux
[out] ftoauc real, 1, tot sky toa upwd flux
[out] ftoau0 real, 1, clr sky toa upwd flux
[out] ftoadc real, 1, toa downward (incoming) solar flux
[out] fsfcuc real, 1, tot sky sfc upwd flux
[out] fsfcu0 real, 1, clr sky sfc upwd flux
[out] fsfcdc real, 1, tot sky sfc dnwd flux
[out] fsfcd0 real, 1, clr sky sfc dnwd flux
[out] sfbmc real, 2, tot sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdfc real, 2, tot sky sfc dnwd diff flux (nir/uv+vis)
[out] sfbm0 real, 2, clr sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdf0 real, 2, clr sky sfc dnwd diff flux (nir/uv+vis)
[out] suvbfc real, 1, tot sky sfc dnwd uv-b flux
[out] suvbf0 real, 1, clr sky sfc dnwd uv-b flux
External Module Variables
physparam::iswmode - control flag for 2-stream transfer schemes
= 1 delta-eddington (joseph et al., 1976)
= 2 pifm (zdunkowski et al., 1980)
= 3 discrete ordinates (liou, 1973)
General Algorithm
Initialization of output fluxes
Compute clear-sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for clear-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for both conservative and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Compute total sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for total-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for conservative scattering and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Process and save outputs
Definition at line 2185 of file radsw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, ftiny, idxsfc, module_radsw_parameters::nbdsw, module_radsw_parameters::nblow, module_radsw_parameters::ngb, module_radsw_parameters::ngptsw, module_radsw_parameters::ntbmx, nuvb, oneminus, and swflux().
Referenced by swrad().
subroutine module_radsw_main::spcvrtm () private
Parameters
[in] ssolar real, 1, incoming solar flux at top
[in] cosz real, 1, cosine solar zenith angle
[in] sntz real, 1, secant solar zenith angle
[in] albbm real, 2, surface albedo for direct beam radiation
[in] albdf real, 2, surface albedo for diffused radiation
[in] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[in] cldfmc real, (nlay,ngptsw), layer cloud fraction for g-point
[in] cf1 real, 1, >0: cloudy sky, otherwise: clear sky
[in] cf0 real, 1, =1-cf1
[in] taug real, (nlay,ngptsw), spectral optical depth for gases
[in] taur real, (nlay,ngptsw), optical depth for rayleigh scattering
[in] tauae real, (nlay,nbdsw), aerosols optical depth
[in] ssaae real, (nlay,nbdsw), aerosols single scattering albedo
[in] asyae real, (nlay,nbdsw), aerosols asymmetry factor
[in] taucw real, (nlay,nbdsw), weighted cloud optical depth
[in] ssacw real, (nlay,nbdsw), weighted cloud single scat albedo
[in] asycw real, (nlay,nbdsw), weighted cloud asymmetry factor
[in] nlay,nlp1 integer, 1, number of layers/levels
[out] fxupc real, (nlp1,nbdsw), tot sky upward flux
[out] fxdnc real, (nlp1,nbdsw), tot sky downward flux
[out] fxup0 real, (nlp1,nbdsw), clr sky upward flux
[out] fxdn0 real, (nlp1,nbdsw), clr sky downward flux
[out] ftoauc real, 1, tot sky toa upwd flux
[out] ftoau0 real, 1, clr sky toa upwd flux
[out] ftoadc real, 1, toa downward (incoming) solar flux
[out] fsfcuc real, 1, tot sky sfc upwd flux
[out] fsfcu0 real, 1, clr sky sfc upwd flux
[out] fsfcdc real, 1, tot sky sfc dnwd flux
[out] fsfcd0 real, 1, clr sky sfc dnwd flux
[out] sfbmc real, 2, tot sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdfc real, 2, tot sky sfc dnwd diff flux (nir/uv+vis)
[out] sfbm0 real, 2, clr sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdf0 real, 2, clr sky sfc dnwd diff flux (nir/uv+vis)
[out] suvbfc real, 1, tot sky sfc dnwd uv-b flux
[out] suvbf0 real, 1, clr sky sfc dnwd uv-b flux
Initialization of output fluxes
Compute clear-sky optical parameters, layer reflectance andtransmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for clear-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for both conservative and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Compute total sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for total-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for conservative scattering and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Process and save outputs — ... surface downward beam/diffused flux components
Definition at line 2941 of file radsw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, ftiny, idxsfc, module_radsw_parameters::nbdsw, module_radsw_parameters::nblow, module_radsw_parameters::ngb, module_radsw_parameters::ngptsw, module_radsw_parameters::ntbmx, nuvb, oneminus, and swflux().
Referenced by swrad().
subroutine module_radsw_main::swflux () private
Parameters
[in] zrefb real, (NLP1), layer direct beam reflectivity
[in] zrefd real, (NLP1), layer diffuse reflectivity
[in] ztrab real, (NLP1), layer direct beam transmissivity
[in] ztrad real, (NLP1), layer diffuse transmissivity
[in] zldbt real, (NLP1), layer mean beam transmittance
[in] ztdbt real, (NLP1), total beam transmittance at levels
[in] NLAY,NLP1 integer, number of layers/levels
[out] zfu real, (NLP1), upward flux at layer interface
[out] zfd real, (NLP1), downward flux at layer interface
General Algorithm
Link lowest layer with surface
Pass from bottom to top
Upper boundary conditions
Pass from top to bottom
Up and down-welling fluxes at levels
Definition at line 3642 of file radsw_main.f.
References f_one, and f_zero.
Referenced by spcvrtc(), and spcvrtm().
subroutine, public module_radsw_main::swrad ()
Parameters
[in] plyr (npts,nlay),model layer mean pressure in mb
[in] plvl (npts,nlp1),model level pressure in mb
[in] tlyr (npts,nlay),model layer mean temperature in K
[in] tlvl (npts,nlp1),model level temperature in K (not in use)
[in] qlyr (npts,nlay),layer specific humidity in gm/gm *see inside
[in] olyr (npts,nlay),layer ozone concentration in gm/gm
[in] gasvmr (npts,nlay,:),atmospheric constent gases:(check module_radiation_gases for definition)
(:,:,1) - co2 volume mixing ratio
(:,:,2) - n2o volume mixing ratio
(:,:,3) - ch4 volume mixing ratio
(:,:,4) - o2 volume mixing ratio
(:,:,5) - co volume mixing ratio (not used)
(:,:,6) - cfc11 volume mixing ratio (not used)
(:,:,7) - cfc12 volume mixing ratio (not used)
(:,:,8) - cfc22 volume mixing ratio (not used)
(:,:,9) - ccl4 volume mixing ratio (not used)
[in] clouds (npts,nlay,:),cloud profile(check module_radiation_clouds for definition)
— for iswcliq > 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer in-cloud liq water path (g/m**2)
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer in-cloud ice water path (g/m**2)
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path (g/m**2)
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path (g/m**2)
(:,:,9) - mean eff radius for snow flake (micron)
— for iswcliq = 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud optical depth
(:,:,3) - layer cloud single scattering albedo
(:,:,4) - layer cloud asymmetry factor
[in] icseed (npts),auxiliary special cloud related array.when module variable isubcsw=2, it provides permutation seed for each column profile that are used for generating random numbers.when isubcsw /=2, it will not be used.
[in] aerosols (npts,nlay,nbdsw,:),aerosol optical properties (check module_radiation_aerosols for definition)
(:,:,:,1) - optical depth
(:,:,:,2) - single scattering albedo
(:,:,:,3) - asymmetry parameter
[in] sfcalb (npts, :),surface albedo in fraction(check module_radiation_surface for definition)
(:,1) - near ir direct beam albedo
(:,2) - near ir diffused albedo
(:,3) - uv+vis direct beam albedo
(:,4) - uv+vis diffused albedo
[in] cosz (npts),cosine of solar zenith angle
[in] solcon solar constant(w/m**2)
[in] NDAY num of daytime points
[in] idxday (npts),index array for daytime points
[in] npts number of horizontal points
[in] nlay,nlp1 vertical layer/lavel numbers
[in] lprnt logical check print flag
[out] hswc (npts,nlay),total sky heating rates (k/sec or k/day)
[out] topflx (npts),radiation fluxes at toa (w/m**2), components (check module_radsw_parameters for definition)
upfxc - total sky upward flux at toa
dnflx - total sky downward flux at toa
upfx0 - clear sky upward flux at toa
[out] sfcflx (npts),radiation fluxes at sfc (w/m**2), components (check module_radsw_parameters for definition)
upfxc - total sky upward flux at sfc
dnfxc - total sky downward flux at sfc
upfx0 - clear sky upward flux at sfc
dnfx0 - clear sky downward flux at sfc
Optional:
[out] hswb (npts,nlay,nbdsw),spectral band total sky heating rates
[out] hsw0 (npts,nlay),clear sky heating rates (k/sec or k/day)
[out] flxprf (npts,nlp1),level radiation fluxes (w/m**2), components (check module_radsw_parameters for definition)
dnfxc - total sky downward flux at interface
upfxc - total sky upward flux at interface
dnfx0 - clear sky downward flux at interface
upfx0 - clear sky upward flux at interface
[out] fdncmp (npts),component surface downward fluxes (w/m**2)(check module_radsw_parameters for definition) !
uvbfc - total sky downward uv-b flux at sfc
uvbf0 - clear sky downward uv-b flux at sfc
nirbm - downward surface nir direct beam flux
nirdf - downward surface nir diffused flux
visbm - downward surface uv+vis direct beam flux
visdf - downward surface uv+vis diffused flux
General Algorithm
Compute solar constant adjustment factor (s0fac) according to solcon.
\(s0fac = solcon/s0 \)
where s0, the solar constant at toa in \(w/m^2 \), is hard-coded with each spectran band, the total flux is about 1368.22 \(w/m^2 \).
Initial output arrays (and optional) as zero
Change random number seed value for each radiation invocation (isubcsw =1 or 2).
Prepare surface albedo: bm,df - dir,dif; 1,2 - nir,uvv
Prepare atmospheric profile for use in rrtm:
pavel(nlay):layer pressure (mb)
tavel(nlay):layer temperature (k)
delp (nlay):layer pressure thickness (mb)
Set absorber and gas column amount, convert from volume mixing ratio to molec/cm2 based on coldry (scaled to 1.0e-20)
colamt(nlay,maxgas):column amounts of absorbing gases 1 to maxgas are for h2o,co2,o3,n2o,ch4,o2,co, respectively (\(mol/cm^2 \))
Read aerosol optical properties from aerosols (:,:,:,:)
Read cloud optical properties from clouds(:,:,:)
Compute fractions of clear sky view in different overlapping scenario:
random overlapping
max/ran overlapping
maximum overlapping
For cloudy sky column, call cldprop() to compute the cloud optical properties for each cloudy layer
Calling setcoef() to compute various coefficients needed in radiative transfer calculations.
Calling taumol() to calculate optical depths for gaseous absorption and rayleigh scattering
call the 2-stream radiation transfer model
if physparam::isubcsw .le.0, using standard cloud scheme, call spcvrtc().
if physparam::isubcsw .gt.0, using mcica cloud scheme, call spcvrtm().
Save outputs
Definition at line 447 of file radsw_main.f.
References amdo3, amdw, cldprop(), f_one, f_zero, ftiny, heatfac, ipsdsw0, lfdncmp, lflxprf, lhsw0, lhswb, module_radsw_parameters::nbdsw, oneminus, s0, setcoef(), spcvrtc(), spcvrtm(), and taumol().
Referenced by module_radiation_driver::grrad().
subroutine module_radsw_main::taumol () private
Parameters
[in] colamt real, (nlay,maxgas), column amounts of absorbing gases the index are for h2o, co2, o3, n2o, ch4, and o2,respectively \((mol/cm^2)\)
[in] colmol real, (nlay), total column amount (dry air+water vapor)
[in] facij real, (nlay), for each layer, these are factors that are needed to compute the interpolation factors that multiply the appropriate reference k-values. a value of 0/1 for i,j indicates that the corresponding factor multiplies reference k-value for the lower/higher of the two appropriate temperatures, and altitudes, respectively.
[in] jp integer, (nlay), the index of the lower (in altitude) of the two appropriate ref pressure levels needed for interpolation.
[in] jt,jt1 integer, (nlay), the indices of the lower of the two approp ref temperatures needed for interpolation (for pressure levels jp and jp+1, respectively)
[in] laytrop integer, 1, tropopause layer index
[in] forfac real, (nlay), scale factor needed to foreign-continuum.
[in] forfrac real, (nlay), factor needed for temperature interpolation
[in] indfor integer, (nlay), index of the lower of the two appropriate reference temperatures needed for foreign-continuum interpolation
[in] selffac real, (nlay), scale factor needed to h2o self-continuum.
[in] selffrac real, (nlay), factor needed for temperature interpolation of reference h2o self-continuum data
[in] indself integer, (nlay), index of the lower of the two appropriate reference temperatures needed for the self-continuum interpolation
[in] nlay integer, 1, number of vertical layers
[out] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[out] taug real, (nlay,ngptsw), spectral optical depth for gases
[out] taur real, (nlay,ngptsw), opt depth for rayleigh scattering
Definition at line 3766 of file radsw_main.f.
References f_one, module_radsw_sflux::ibx, module_radsw_sflux::ix1, module_radsw_sflux::ix2, module_radsw_sflux::layreffr, module_radsw_parameters::nbhgh, module_radsw_parameters::nblow, module_radsw_parameters::ng, module_radsw_parameters::ngs, nspa, nspb, oneminus, module_radsw_sflux::scalekur, module_radsw_sflux::sfluxref01, module_radsw_sflux::sfluxref02, module_radsw_sflux::sfluxref03, module_radsw_sflux::specwt, module_radsw_sflux::strrat, taumol16(), taumol17(), taumol18(), taumol19(), taumol20(), taumol21(), taumol22(), taumol23(), taumol24(), taumol25(), taumol26(), taumol27(), taumol28(), and taumol29().
Referenced by swrad().
subroutine taumol::taumol16 () private
Definition at line 4007 of file radsw_main.f.
References module_radsw_kgb16::absa, module_radsw_kgb16::absb, f_one, module_radsw_kgb16::forref, module_radsw_parameters::ng16, module_radsw_parameters::ns16, oneminus, module_radsw_kgb16::rayl, module_radsw_kgb16::selfref, and module_radsw_sflux::strrat.
Referenced by taumol().
Variable Documentation
real (kind=kind_phys), public module_radsw_cldprtb::a0r
Definition at line 1817 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), public module_radsw_cldprtb::a0s
Definition at line 1817 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), public module_radsw_cldprtb::a1r
Definition at line 1817 of file radsw_datatb.f.
real (kind=kind_phys), public module_radsw_cldprtb::a1s
Definition at line 1817 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::abari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(msa16,ng16), public module_radsw_kgb16::absa
Definition at line 2181 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(msa17,ng17), public module_radsw_kgb17::absa
Definition at line 3331 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(msa18,ng18), public module_radsw_kgb18::absa
Definition at line 7932 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(msa19,ng19), public module_radsw_kgb19::absa
Definition at line 9439 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(msa20,ng20), public module_radsw_kgb20::absa
Definition at line 10947 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), dimension(msa21,ng21), public module_radsw_kgb21::absa
Definition at line 11718 of file radsw_datatb.f.
Referenced by taumol21().
real (kind=kind_phys), dimension(msa22,ng22), public module_radsw_kgb22::absa
Definition at line 15564 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(msa23,ng23), public module_radsw_kgb23::absa
Definition at line 15999 of file radsw_datatb.f.
Referenced by taumol23().
real (kind=kind_phys), dimension(msa24,ng24), public module_radsw_kgb24::absa
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(msa25,ng25), public module_radsw_kgb25::absa
Definition at line 17778 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), dimension(msa27,ng27), public module_radsw_kgb27::absa
Definition at line 17967 of file radsw_datatb.f.
Referenced by taumol27().
real (kind=kind_phys), dimension(msa28,ng28), public module_radsw_kgb28::absa
Definition at line 18564 of file radsw_datatb.f.
Referenced by taumol28().
real (kind=kind_phys), dimension(msa29,ng29), public module_radsw_kgb29::absa
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(msb16,ng16), public module_radsw_kgb16::absb
Definition at line 2181 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(msb17,ng17), public module_radsw_kgb17::absb
Definition at line 3331 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(msb18,ng18), public module_radsw_kgb18::absb
Definition at line 7932 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(msb19,ng19), public module_radsw_kgb19::absb
Definition at line 9439 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(msb20,ng20), public module_radsw_kgb20::absb
Definition at line 10947 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), dimension(msb21,ng21), public module_radsw_kgb21::absb
Definition at line 11718 of file radsw_datatb.f.
Referenced by taumol21().
real (kind=kind_phys), dimension(msb22,ng22), public module_radsw_kgb22::absb
Definition at line 15564 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(msb24,ng24), public module_radsw_kgb24::absb
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(msb27,ng27), public module_radsw_kgb27::absb
Definition at line 17967 of file radsw_datatb.f.
Referenced by taumol27().
real (kind=kind_phys), dimension(msb28,ng28), public module_radsw_kgb28::absb
Definition at line 18564 of file radsw_datatb.f.
Referenced by taumol28().
real (kind=kind_phys), dimension(msb29,ng29), public module_radsw_kgb29::absb
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng20), public module_radsw_kgb20::absch4
Definition at line 10947 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absco2
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absh2o
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3a
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3a
Definition at line 17778 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3b
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3b
Definition at line 17778 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), parameter module_radsw_main::amdo3 = con_amd/con_amo3 private
Definition at line 312 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), parameter module_radsw_main::amdw = con_amd/con_amw private
Definition at line 311 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::asyice2
Definition at line 196 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::asyice3
Definition at line 198 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(58,nblow:nbhgh), public module_radsw_cldprtb::asyliq1
Definition at line 194 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0r
Definition at line 1820 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0s
Definition at line 1820 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b1s
Definition at line 1820 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::bbari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radsw_main::bpade = 1.0/0.278 private
Definition at line 302 of file radsw_main.f.
Referenced by rswinit(), spcvrtc(), and spcvrtm().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0r
Definition at line 1820 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0s
Definition at line 1820 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::cbari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::dbari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys) module_radsw_parameters::sfcfsw_type::dnfx0
Definition at line 99 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::profsw_type::dnfx0
Definition at line 113 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::topfsw_type::dnfxc
Definition at line 83 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::sfcfsw_type::dnfxc
Definition at line 95 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::profsw_type::dnfxc
Definition at line 109 of file radsw_param.f.
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::ebari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radsw_main::eps = 1.0e-6 private
Definition at line 300 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
real (kind=kind_phys), dimension(0:ntbmx) module_radsw_main::exp_tbl private
Definition at line 348 of file radsw_main.f.
Referenced by rswinit(), spcvrtc(), and spcvrtm().
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::extice2
Definition at line 196 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::extice3
Definition at line 198 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radsw_main::f_one = 1.0 private
Definition at line 308 of file radsw_main.f.
Referenced by cldprop(), mcica_subcol(), setcoef(), spcvrtc(), spcvrtm(), swflux(), swrad(), taumol(), taumol16(), taumol17(), taumol18(), taumol19(), taumol21(), taumol22(), taumol24(), and taumol28().
real (kind=kind_phys), parameter module_radsw_main::f_zero = 0.0 private
Definition at line 307 of file radsw_main.f.
Referenced by cldprop(), setcoef(), spcvrtc(), spcvrtm(), swflux(), swrad(), taumol23(), and taumol26().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::fbari
Definition at line 200 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::fdlice3
Definition at line 198 of file radsw_datatb.f.
real (kind=kind_phys), dimension(mfr16,ng16), public module_radsw_kgb16::forref
Definition at line 2181 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(mfr17,ng17), public module_radsw_kgb17::forref
Definition at line 3331 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(mfr18,ng18), public module_radsw_kgb18::forref
Definition at line 7932 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(mfr19,ng19), public module_radsw_kgb19::forref
Definition at line 9439 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(mfr20,ng20), public module_radsw_kgb20::forref
Definition at line 10947 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), dimension(mfr21,ng21), public module_radsw_kgb21::forref
Definition at line 11718 of file radsw_datatb.f.
Referenced by taumol21().
real (kind=kind_phys), dimension(mfr22,ng22), public module_radsw_kgb22::forref
Definition at line 15564 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(mfr23,ng23), public module_radsw_kgb23::forref
Definition at line 15999 of file radsw_datatb.f.
Referenced by taumol23().
real (kind=kind_phys), dimension(mfr24,ng24), public module_radsw_kgb24::forref
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(mfr29,ng29), public module_radsw_kgb29::forref
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), parameter module_radsw_main::ftiny = 1.0e-12 private
Definition at line 304 of file radsw_main.f.
Referenced by cldprop(), spcvrtc(), spcvrtm(), and swrad().
real (kind=kind_phys), parameter, public module_radsw_kgb23::givfac = 1.029
Definition at line 16003 of file radsw_datatb.f.
Referenced by taumol23().
real (kind=kind_phys) module_radsw_main::heatfac private
Definition at line 353 of file radsw_main.f.
Referenced by rswinit(), and swrad().
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ibx
Definition at line 1885 of file radsw_datatb.f.
Referenced by taumol().
integer, dimension(nblow:nbhgh) module_radsw_main::idxebc private
Definition at line 315 of file radsw_main.f.
Referenced by cldprop().
integer, dimension(nblow:nbhgh) module_radsw_main::idxsfc private
Definition at line 315 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
integer, parameter module_radsw_main::ipsdsw0 = 1 private
Definition at line 357 of file radsw_main.f.
Referenced by swrad().
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ix1
Definition at line 1885 of file radsw_datatb.f.
Referenced by taumol().
integer, dimension(nblow:nbhgh), public module_radsw_sflux::ix2
Definition at line 1885 of file radsw_datatb.f.
Referenced by taumol().
integer, dimension(nblow:nbhgh), public module_radsw_sflux::layreffr
Definition at line 1885 of file radsw_datatb.f.
Referenced by taumol().
logical module_radsw_main::lfdncmp = .false. private
Definition at line 344 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lflxprf = .false. private
Definition at line 343 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lhsw0 = .false. private
Definition at line 342 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lhswb = .false. private
Definition at line 341 of file radsw_main.f.
Referenced by swrad().
integer, parameter module_radsw_parameters::maxgas = 7
Definition at line 147 of file radsw_param.f.
integer, parameter module_radsw_sflux::mfb01 = 7
Definition at line 1867 of file radsw_datatb.f.
integer, parameter module_radsw_sflux::mfb02 = 2
Definition at line 1868 of file radsw_datatb.f.
integer, parameter module_radsw_sflux::mfb03 = 5
Definition at line 1869 of file radsw_datatb.f.
integer, public module_radsw_kgb16::mfr16
Definition at line 2178 of file radsw_datatb.f.
integer, public module_radsw_kgb17::mfr17
Definition at line 3328 of file radsw_datatb.f.
integer, public module_radsw_kgb18::mfr18
Definition at line 7929 of file radsw_datatb.f.
integer, public module_radsw_kgb19::mfr19
Definition at line 9436 of file radsw_datatb.f.
integer, public module_radsw_kgb20::mfr20
Definition at line 10944 of file radsw_datatb.f.
integer, public module_radsw_kgb21::mfr21
Definition at line 11715 of file radsw_datatb.f.
integer, public module_radsw_kgb22::mfr22
Definition at line 15561 of file radsw_datatb.f.
integer, public module_radsw_kgb23::mfr23
Definition at line 15996 of file radsw_datatb.f.
integer, public module_radsw_kgb24::mfr24
Definition at line 16243 of file radsw_datatb.f.
integer, public module_radsw_kgb29::mfr29
Definition at line 20872 of file radsw_datatb.f.
integer, parameter module_radsw_sflux::mfs02 = 5
Definition at line 1865 of file radsw_datatb.f.
integer, parameter module_radsw_sflux::mfs03 = 9
Definition at line 1866 of file radsw_datatb.f.
integer, public module_radsw_kgb24::mfx24
Definition at line 16243 of file radsw_datatb.f.
integer, public module_radsw_kgb16::msb16
Definition at line 2178 of file radsw_datatb.f.
integer, public module_radsw_kgb17::msb17
Definition at line 3328 of file radsw_datatb.f.
integer, public module_radsw_kgb18::msb18
Definition at line 7929 of file radsw_datatb.f.
integer, public module_radsw_kgb19::msb19
Definition at line 9436 of file radsw_datatb.f.
integer, public module_radsw_kgb20::msb20
Definition at line 10944 of file radsw_datatb.f.
integer, public module_radsw_kgb21::msb21
Definition at line 11715 of file radsw_datatb.f.
integer, public module_radsw_kgb22::msb22
Definition at line 15561 of file radsw_datatb.f.
integer, public module_radsw_kgb24::msb24
Definition at line 16243 of file radsw_datatb.f.
integer, public module_radsw_kgb27::msb27
Definition at line 17964 of file radsw_datatb.f.
integer, public module_radsw_kgb28::msb28
Definition at line 18560 of file radsw_datatb.f.
integer, public module_radsw_kgb29::msb29
Definition at line 20872 of file radsw_datatb.f.
integer, public module_radsw_kgb16::msf16
Definition at line 2178 of file radsw_datatb.f.
integer, public module_radsw_kgb17::msf17
Definition at line 3328 of file radsw_datatb.f.
integer, public module_radsw_kgb18::msf18
Definition at line 7929 of file radsw_datatb.f.
integer, public module_radsw_kgb19::msf19
Definition at line 9436 of file radsw_datatb.f.
integer, public module_radsw_kgb20::msf20
Definition at line 10944 of file radsw_datatb.f.
integer, public module_radsw_kgb21::msf21
Definition at line 11715 of file radsw_datatb.f.
integer, public module_radsw_kgb22::msf22
Definition at line 15561 of file radsw_datatb.f.
integer, public module_radsw_kgb23::msf23
Definition at line 15996 of file radsw_datatb.f.
integer, public module_radsw_kgb24::msf24
Definition at line 16243 of file radsw_datatb.f.
integer, public module_radsw_kgb29::msf29
Definition at line 20872 of file radsw_datatb.f.
integer, parameter module_radsw_parameters::nbands = NBHGH-NBLOW+1
Definition at line 141 of file radsw_param.f.
integer, parameter module_radsw_parameters::nbdsw = NBANDS
Definition at line 153 of file radsw_param.f.
Referenced by module_radiation_aerosols::aer_init(), module_radiation_aerosols::aer_property(), cldprop(), module_radiation_aerosols::gocart_init(), module_radiation_driver::grrad(), module_radiation_aerosols::setaer(), module_radiation_aerosols::setgocartaer(), spcvrtc(), spcvrtm(), and swrad().
integer, parameter module_radsw_parameters::nbhgh = 29
Definition at line 139 of file radsw_param.f.
Referenced by cldprop(), and taumol().
integer, parameter module_radsw_parameters::nblow = 16
Definition at line 137 of file radsw_param.f.
Referenced by cldprop(), spcvrtc(), spcvrtm(), and taumol().
integer, dimension(nblow:nbhgh) module_radsw_parameters::ng
Definition at line 162 of file radsw_param.f.
Referenced by taumol().
integer module_radsw_parameters::ng16
Definition at line 156 of file radsw_param.f.
Referenced by taumol16().
integer module_radsw_parameters::ng17
Definition at line 156 of file radsw_param.f.
Referenced by taumol17().
integer module_radsw_parameters::ng18
Definition at line 156 of file radsw_param.f.
Referenced by taumol18().
integer module_radsw_parameters::ng19
Definition at line 156 of file radsw_param.f.
Referenced by taumol19().
integer module_radsw_parameters::ng20
Definition at line 156 of file radsw_param.f.
Referenced by taumol20().
integer module_radsw_parameters::ng21
Definition at line 156 of file radsw_param.f.
Referenced by taumol21().
integer module_radsw_parameters::ng22
Definition at line 156 of file radsw_param.f.
Referenced by taumol22().
integer module_radsw_parameters::ng23
Definition at line 156 of file radsw_param.f.
Referenced by taumol23().
integer module_radsw_parameters::ng24
Definition at line 156 of file radsw_param.f.
Referenced by taumol24().
integer module_radsw_parameters::ng25
Definition at line 156 of file radsw_param.f.
Referenced by taumol25().
integer module_radsw_parameters::ng26
Definition at line 156 of file radsw_param.f.
Referenced by taumol26().
integer module_radsw_parameters::ng27
Definition at line 156 of file radsw_param.f.
Referenced by taumol27().
integer module_radsw_parameters::ng28
Definition at line 156 of file radsw_param.f.
Referenced by taumol28().
integer module_radsw_parameters::ng29
Definition at line 156 of file radsw_param.f.
Referenced by taumol29().
integer, dimension(ngptsw) module_radsw_parameters::ngb
Definition at line 180 of file radsw_param.f.
Referenced by spcvrtc(), and spcvrtm().
integer, parameter module_radsw_parameters::ngmax = 16
Definition at line 145 of file radsw_param.f.
integer, parameter module_radsw_parameters::ngptsw = 112
Definition at line 143 of file radsw_param.f.
Referenced by cldprop(), mcica_subcol(), spcvrtc(), and spcvrtm().
integer, dimension(nblow:nbhgh) module_radsw_parameters::ngs
Definition at line 175 of file radsw_param.f.
Referenced by taumol().
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::nirbm
Definition at line 125 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::nirdf
Definition at line 127 of file radsw_param.f.
integer module_radsw_parameters::ns16
Definition at line 167 of file radsw_param.f.
Referenced by taumol16().
integer module_radsw_parameters::ns17
Definition at line 167 of file radsw_param.f.
Referenced by taumol17().
integer module_radsw_parameters::ns18
Definition at line 167 of file radsw_param.f.
Referenced by taumol18().
integer module_radsw_parameters::ns19
Definition at line 167 of file radsw_param.f.
Referenced by taumol19().
integer module_radsw_parameters::ns20
Definition at line 167 of file radsw_param.f.
Referenced by taumol20().
integer module_radsw_parameters::ns21
Definition at line 167 of file radsw_param.f.
Referenced by taumol21().
integer module_radsw_parameters::ns22
Definition at line 167 of file radsw_param.f.
Referenced by taumol22().
integer module_radsw_parameters::ns23
Definition at line 167 of file radsw_param.f.
Referenced by taumol23().
integer module_radsw_parameters::ns24
Definition at line 167 of file radsw_param.f.
Referenced by taumol24().
integer module_radsw_parameters::ns25
Definition at line 167 of file radsw_param.f.
Referenced by taumol25().
integer module_radsw_parameters::ns26
Definition at line 167 of file radsw_param.f.
Referenced by taumol26().
integer module_radsw_parameters::ns27
Definition at line 167 of file radsw_param.f.
Referenced by taumol27().
integer module_radsw_parameters::ns28
Definition at line 167 of file radsw_param.f.
Referenced by taumol28().
integer module_radsw_parameters::ns29
Definition at line 167 of file radsw_param.f.
Referenced by taumol29().
integer, dimension(nblow:nbhgh) module_radsw_main::nspa private
Definition at line 315 of file radsw_main.f.
Referenced by taumol().
integer, dimension(nblow:nbhgh) module_radsw_main::nspb private
Definition at line 315 of file radsw_main.f.
Referenced by taumol().
integer, parameter module_radsw_parameters::nswstr = 1
Definition at line 151 of file radsw_param.f.
Referenced by module_radiation_aerosols::gocart_init(), set_aercoef(), and module_radiation_aerosols::setaer().
integer, parameter module_radsw_parameters::ntbmx = 10000
Definition at line 149 of file radsw_param.f.
Referenced by rswinit(), spcvrtc(), and spcvrtm().
integer, parameter module_radsw_main::nuvb = 27 private
Definition at line 337 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
real (kind=kind_phys), parameter module_radsw_main::oneminus = 1.0 - eps private
Definition at line 301 of file radsw_main.f.
Referenced by spcvrtc(), spcvrtm(), swrad(), taumol(), taumol16(), taumol17(), taumol18(), taumol19(), taumol21(), taumol22(), taumol24(), and taumol28().
real (kind=kind_phys), parameter, public module_radsw_kgb16::rayl = 2.91e-10
Definition at line 2185 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), parameter, public module_radsw_kgb17::rayl = 6.86e-10
Definition at line 3335 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), parameter, public module_radsw_kgb18::rayl = 1.39e-09
Definition at line 7936 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), parameter, public module_radsw_kgb19::rayl = 2.29e-09
Definition at line 9443 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), parameter, public module_radsw_kgb20::rayl = 4.12e-09
Definition at line 10951 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), parameter, public module_radsw_kgb21::rayl = 9.41e-09
Definition at line 11722 of file radsw_datatb.f.
Referenced by taumol21().
real (kind=kind_phys), parameter, public module_radsw_kgb22::rayl = 1.54e-08
Definition at line 15568 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(ng23), public module_radsw_kgb23::rayl
Definition at line 15999 of file radsw_datatb.f.
Referenced by taumol23().
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::rayl
Definition at line 17778 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), dimension(ng27), public module_radsw_kgb27::rayl
Definition at line 17967 of file radsw_datatb.f.
Referenced by taumol27().
real (kind=kind_phys), parameter, public module_radsw_kgb28::rayl = 2.02e-05
Definition at line 18568 of file radsw_datatb.f.
Referenced by taumol28().
real (kind=kind_phys), parameter, public module_radsw_kgb29::rayl = 9.30e-11
Definition at line 20880 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng24,mfx24), public module_radsw_kgb24::rayla
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::raylb
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), parameter module_radsw_main::s0 = 1368.22 private
Definition at line 305 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), parameter, public module_radsw_sflux::scalekur =50.15/48.37
Definition at line 1892 of file radsw_datatb.f.
Referenced by taumol().
real (kind=kind_phys), dimension(msf16,ng16), public module_radsw_kgb16::selfref
Definition at line 2181 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(msf17,ng17), public module_radsw_kgb17::selfref
Definition at line 3331 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(msf18,ng18), public module_radsw_kgb18::selfref
Definition at line 7932 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(msf19,ng19), public module_radsw_kgb19::selfref
Definition at line 9439 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(msf20,ng20), public module_radsw_kgb20::selfref
Definition at line 10947 of file radsw_datatb.f.
Referenced by taumol20().
real (kind=kind_phys), dimension(msf21,ng21), public module_radsw_kgb21::selfref
Definition at line 11718 of file radsw_datatb.f.
Referenced by taumol21().
real (kind=kind_phys), dimension(msf22,ng22), public module_radsw_kgb22::selfref
Definition at line 15564 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(msf23,ng23), public module_radsw_kgb23::selfref
Definition at line 15999 of file radsw_datatb.f.
Referenced by taumol23().
real (kind=kind_phys), dimension(msf24,ng24), public module_radsw_kgb24::selfref
Definition at line 16246 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(msf29,ng29), public module_radsw_kgb29::selfref
Definition at line 20875 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ngmax,mfs01,mfb01), target, public module_radsw_sflux::sfluxref01
Definition at line 1894 of file radsw_datatb.f.
Referenced by taumol().
real (kind=kind_phys), dimension(ngmax,mfs02,mfb02), target, public module_radsw_sflux::sfluxref02
Definition at line 1894 of file radsw_datatb.f.
Referenced by taumol().
real (kind=kind_phys), dimension(ngmax,mfs03,mfb03), target, public module_radsw_sflux::sfluxref03
Definition at line 1894 of file radsw_datatb.f.
Referenced by taumol().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_sflux::specwt
Definition at line 1871 of file radsw_datatb.f.
Referenced by taumol().
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::ssaice2
Definition at line 196 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::ssaice3
Definition at line 198 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(58,nblow:nbhgh), public module_radsw_cldprtb::ssaliq1
Definition at line 194 of file radsw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radsw_main::stpfac = 296.0/1013.0 private
Definition at line 303 of file radsw_main.f.
Referenced by setcoef().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_sflux::strrat
Definition at line 1871 of file radsw_datatb.f.
Referenced by taumol(), taumol16(), taumol17(), taumol18(), taumol19(), taumol21(), taumol22(), taumol24(), and taumol28().
real (kind=kind_phys), dimension(59) module_radsw_ref::tref
Definition at line 82 of file radsw_datatb.f.
Referenced by setcoef().
real (kind=kind_phys) module_radsw_parameters::topfsw_type::upfx0
Definition at line 85 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::sfcfsw_type::upfx0
Definition at line 97 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::profsw_type::upfx0
Definition at line 111 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::topfsw_type::upfxc
Definition at line 81 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::sfcfsw_type::upfxc
Definition at line 93 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::profsw_type::upfxc
Definition at line 107 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::uvbf0
Definition at line 123 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::uvbfc
Definition at line 121 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::visbm
Definition at line 129 of file radsw_param.f.
real (kind=kind_phys) module_radsw_parameters::cmpfsw_type::visdf
Definition at line 131 of file radsw_param.f.
real (kind=kind_phys), dimension(nbands) module_radsw_parameters::wvnum1
Definition at line 197 of file radsw_param.f.
real (kind=kind_phys), dimension(nbands) module_radsw_parameters::wvnum2
Definition at line 197 of file radsw_param.f.