Radiation Scheme in CCPP: module_radiation_clouds
module_radiation_clouds
RRTMG Radiation Scheme
This module computes cloud related quantities for radiation computations.
Modules
module module_radiation_clouds
Functions/Subroutines
subroutine module_radiation_clouds::gethml
This subroutine computes high, mid, low, total, and boundary cloud fractions and cloud top/bottom layer indices for model diagnostic output.
subroutine module_radiation_clouds::rhtable
cld-rh relations obtained from mitchell-hahn procedure.
Variables
real(kind=kind_phys), parameter module_radiation_clouds::gfac =1.0e5/con_g
real(kind=kind_phys), parameter module_radiation_clouds::gord =con_g/con_rd
integer, parameter, public module_radiation_clouds::nf_clds = 9
number of fields in cloud array
integer, parameter, public module_radiation_clouds::nk_clds = 3
number of cloud vertical domains
real(kind=kind_phys), dimension(nk_clds+1, 2), save module_radiation_clouds::ptopc
real(kind=kind_phys), parameter module_radiation_clouds::climit = 0.001
real(kind=kind_phys), parameter module_radiation_clouds::climit2 =0.05
real(kind=kind_phys), parameter module_radiation_clouds::ovcst = 1.0 - 1.0e-8
real(kind=kind_phys), parameter module_radiation_clouds::reliq_def = 10.0
real(kind=kind_phys), parameter module_radiation_clouds::reice_def = 50.0
real(kind=kind_phys), parameter module_radiation_clouds::rrain_def = 1000.0
real(kind=kind_phys), parameter module_radiation_clouds::rsnow_def = 250.0
integer, parameter module_radiation_clouds::nbin =100
integer, parameter module_radiation_clouds::nlon =2
integer, parameter module_radiation_clouds::nlat =4
integer, parameter module_radiation_clouds::mcld =4
integer, parameter module_radiation_clouds::nseal =2
real(kind=kind_phys), parameter module_radiation_clouds::cldssa_def = 0.99
real(kind=kind_phys), parameter module_radiation_clouds::cldasy_def = 0.84
real(kind=kind_phys), parameter module_radiation_clouds::xlim =5.0
real(kind=kind_phys), dimension(3) module_radiation_clouds::xlabdy
real(kind=kind_phys), dimension(3) module_radiation_clouds::xlobdy
real(kind=kind_phys), parameter module_radiation_clouds::vvcld1 = 0.0003e0
real(kind=kind_phys), parameter module_radiation_clouds::vvcld2 =-0.0005e0
real(kind=kind_phys), dimension(nbin, nlon, nlat, mcld, nseal) module_radiation_clouds::rhcl
integer module_radiation_clouds::llyr = 2
integer module_radiation_clouds::iovr = 1
subroutine module_microphysics::rsipath2
This subroutine is a modified version of ferrier's original "rsipath" subprogram. It computes layer's cloud liquid, ice, rain, and snow water condensate path and the partical effective radius for liquid droplet, rain drop, and snow flake.
subroutine, public module_radiation_clouds::cld_init
This subroutine is an initialization program for cloud-radiation calculations. It sets up boundary layer cloud top.
subroutine, public module_radiation_clouds::progcld1
This subroutine computes cloud related quantities using zhao/moorthi's prognostic cloud microphysics scheme.
subroutine, public module_radiation_clouds::progcld2
This subroutine computes cloud related quantities using ferrier's prognostic cloud microphysics scheme.
subroutine, public module_radiation_clouds::progcld3
This subroutine computes cloud related quantities using zhao/moorthi's prognostic cloud microphysics scheme + pdfcld.
subroutine, public module_radiation_clouds::diagcld1
This subroutine computes cloud fractions for radiation calculations.
Detailed Description
Function/Subroutine Documentation
subroutine, public module_radiation_clouds::cld_init ()
Parameters
[in] si real, model vertical sigma layer interface
[in] NLAY integer, vertical layer number
[in] me integer, print control flag
[out] NONE
General Algorithm
Calling rhtable, set up tuned rh table
- subroutine rhtable: cld-rh relations obtained from mitchell-hahn procedure
Compute llyr - the top of BL cld and is topmost non cld(low) layer for stratiform (at or above lowest 0.1 of the atmosphere)
Definition at line 237 of file radiation_clouds.f.
References iovr, llyr, rhtable(), and vtagcld.
Referenced by module_radiation_driver::radinit().
subroutine, public module_radiation_clouds::diagcld1 ()
Parameters
[in] plyr real, (IX,NLAY), model layer mean pressure in mb (100Pa)
[in] plvl real, (IX,NLP1), model level pressure in mb (100Pa)
[in] tlyr real, (IX,NLAY), model layer mean temperature in K
[in] rhly real, (IX,NLAY), layer relative humidity
[in] vvel real, (IX,NLAY), layer mean vertical velocity in mb/sec
[in] cv real, (IX), fraction of convective cloud
[in] cvt,cvb real, (IX), conv cloud top/bottom pressure in mb
[in] xlat real, (IX), grid latitude in radians, default to pi/2 -> -pi/2 range, otherwise see in-line comment
[in] xlon real, (IX), grid longitude in radians, ok for both 0->2pi or -pi -> +pi ranges
[in] slmsk real, (IX), sea/land mask array (sea:0,land:1,sea-ice:2)
[in] IX integer, horizontal dimention
[in] NLAY,NLP1 integer, vertical layer/level dimensions
[out] clouds real, (IX,NLAY,NF_CLDS), cloud profiles
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud optical depth
(:,:,3) - layer cloud single scattering albedo
(:,:,4) - layer cloud asymmetry factor
[out] clds real, (IX,5), fraction of clouds for low, mid, hi, tot, bl
[out] mtop integer, (IX,3), vertical indices for low, mid, hi cloud tops
[out] mbot real, (IX,3), vertical indices for low, mid, hi cloud bases
General Algorithm
Get rh-cld relation for this lat
Linear transition betweeen latitudinal regions
Get rh-cld relationship for each grid point, interpolating longitudinally between regions if necessary.
Find top pressure for each cloud domain
Compute stratiform cloud optical depth
Compute potential temperature and its lapse rate
Diagnostic method to find cloud amount cldtot, cldcnv
Find the lowest low cloud top sigma level, computed for each lat cause domain definition changes with latitude.
Find the stratosphere cut off layer for high cloud (about 250mb). It is assumed to be above the layerwith dthdp less than -0.25 in the high cloud domain
Put convective cloud into 'cldcnv', no merge at this point.
Calculate stratiform cloud and put into array 'cldtot' using the cld-rh relationship from table look-up.where tables obtained using k.mitchell frequency distribution tuning
Compute vertical velocity adjustment on low clouds
Compute diagnostic cloud optical depth
Calling gethml, to compute low, mid, high, total, and boundary layer cloud fractions and cloud top/bottom layer indices for low, mid, and high clouds.
Definition at line 1780 of file radiation_clouds.f.
References cldasy_def, cldssa_def, climit, gethml(), llyr, mcld, nbin, nlon, nseal, ptopc, rhcl, vvcld1, vvcld2, xlabdy, xlim, and xlobdy.
Referenced by module_radiation_driver::grrad().
subroutine module_radiation_clouds::gethml () private
Definition at line 2396 of file radiation_clouds.f.
References climit, iovr, llyr, nk_clds, and ovcst.
Referenced by diagcld1(), progcld1(), progcld2(), and progcld3().
subroutine, public module_radiation_clouds::progcld1 ()
Parameters
[in] plyr real, (IX,NLAY), model layer mean pressure in mb (100Pa)
[in] plvl real, (IX,NLP1), model level pressure in mb (100Pa)
[in] tlyr real, (IX,NLAY), model layer mean temperature in K
[in] tvly real, (IX,NLAY), model layer virtual temperature in K
[in] qlyr real, (IX,NLAY), layer specific humidity in gm/gm
[in] qstl real, (IX,NLAY), layer saturate humidity in gm/gm
[in] rhly real, (IX,NLAY), layer relative humidity \((=qlyr/qstl) \)
[in] clw real, (IX,NLAY), layer cloud condensate amount
[in] xlat real, (IX), grid latitude in radians, default to pi/2 -> -pi/2 range, otherwise see in-line comment
[in] xlon real, (IX), grid longitude in radians (not used)
[in] slmsk real, (IX), sea/land mask array (sea:0,land:1,sea-ice:2)
[in] IX integer, horizontal dimention
[in] NLAY,NLP1 integer, vertical layer/level dimensions
[out] clouds real, (IX,NLAY,NF_CLDS), cloud profiles
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud liq water path \((g/m^2)\)
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer cloud ice water path \((g/m^2)\)
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path (not assigned)
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path (not assigned)
(:,:,9) - mean eff radius for snow flake (micron)
*** fu's scheme need to be normalized by snow density \((g/m^3/1.0e6)\)
[out] clds real, (IX,5), fraction of clouds for low, mid, hi, tot, bl
[out] mtop integer, (IX,3), vertical indices for low, mid, hi cloud tops
[out] mbot integer, (IX,3), vertical indices for low, mid, hi cloud bases
General Algorithm
Find top pressure for each cloud domain for given latitude
Compute liquid/ice condensate path in \(g/m^2 \)
Compute effective liquid cloud droplet radius over land
Compute effective ice cloud droplet radius
For ice clouds, following Heymsfield and McFarquhar (1996),the effective ice droplet radius is made to be an empirical function of ice water concentration (IWC) and environmental temperature as:
\(r_{ei} = (1250/9.917)IWC^{0.109},T<-50^oC \)
\(r_{ei} = (1250/9.337)IWC^{0.080},-50^oC<=T<-40^oC \)
\(r_{ei} = (1250/9.208)IWC^{0.055},-40^oC<=T<-30^oC \)
Call gethml to compute low,mid,high,total, and boundary layer cloud fractions
Definition at line 387 of file radiation_clouds.f.
References climit, climit2, gethml(), gfac, gord, nf_clds, ptopc, reice_def, reliq_def, rrain_def, and rsnow_def.
Referenced by module_radiation_driver::grrad().
subroutine, public module_radiation_clouds::progcld2 ()
Parameters
[in] plyr real, (IX,NLAY), model layer mean pressure in mb (100Pa)
[in] plvl real, (IX,NLP1), model level pressure in mb (100Pa)
[in] tlyr real, (IX,NLAY), model layer mean temperature in K
[in] tvly real, (IX,NLAY), model layer virtual temperature in K
[in] qlyr real, (IX,NLAY), layer specific humidity in gm/gm
[in] qstl real, (IX,NLAY), layer saturate humidity in gm/gm
[in] rhly real, (IX,NLAY), layer relative humidity (=qlyr/qstl)
[in] clw real, (IX,NLAY), layer cloud condensate amount
[in] f_ice real, (IX,NLAY), fraction of layer cloud ice (ferrier micro-phys)
[in] f_rain real, (IX,NLAY), fraction of layer rain water (ferrier micro-phys)
[in] r_rime real, (IX,NLAY), mass ratio of total ice to unrimed ice (>=1)
[in] flgmin real, (IX), minimim large ice fraction
[in] xlat real, (IX), grid latitude in radians, default to pi/2 -> -pi/2 range, otherwise see in-line comment
[in] xlon real, (IX), grid longitude in radians (not used)
[in] slmsk real, (IX), sea/land mask array (sea:0,land:1,sea-ice:2)
[in] IX integer, horizontal dimention
[in] NLAY,NLP1 integer, vertical layer/level dimensions
[out] clouds real, (IX,NLAY,NF_CLDS), cloud profiles
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud liq water path \((g/m^2)\)
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer cloud ice water path \((g/m^2)\)
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path \((g/m^2)\)
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path \((g/m^2)\)
(:,:,9) - mean eff radius for snow flake (micron)
*** fu's scheme need to be normalized by snow density (g/m**3/1.0e6)
[out] clds real, (IX,5), fraction of clouds for low, mid, hi, tot, bl
[out] mtop integer, (IX,3), vertical indices for low, mid, hi cloud tops
[out] mbot integer, (IX,3), vertical indices for low, mid, hi cloud bases
General Algorithm
Find top pressure for each cloud domain for given latitude
ptopc(k,i): top pressure of each cld domain (k=1-4 are sfc,l,m,h; i=1,2 are low-lat (<45 degree) and pole regions)
Seperate cloud condensate into liquid, ice, and rain types, and save the liquid+ice condensate in array clw2 for later calculation of cloud fraction
Call module_microphysics::rsipath2, in ferrier's scheme,to compute layer's cloud liquid, ice, rain, and snow water condensate path and the partical effective radius for liquid droplet, rain drop, and snow flake.
Compute layer cloud fraction
Compute effective ice cloud droplet radius
Call gethml, to compute low, mid, high, total, and boundary layer cloud fractions and clouds top/bottom layer indices for low, mid, and high clouds.
Definition at line 843 of file radiation_clouds.f.
References climit, climit2, gethml(), ptopc, reice_def, reliq_def, rrain_def, module_microphysics::rsipath2(), and rsnow_def.
Referenced by module_radiation_driver::grrad().
subroutine, public module_radiation_clouds::progcld3 ()
Parameters
[in] plyr real, (ix,nlay), model layer mean pressure in mb (100pa)
[in] plvl real, (ix,nlp1), model level pressure in mb (100pa)
[in] tlyr real, (ix,nlay), model layer mean temperature in K
[in] tvly real, (ix,nlay), model layer virtual temperature in K
[in] qlyr real, (ix,nlay), layer specific humidity in gm/gm
[in] qstl real, (ix,nlay), layer saturate humidity in gm/gm
[in] rhly real, (ix,nlay), layer relative humidity (=qlyr/qstl)
[in] clw real, (ix,nlay), layer cloud condensate amount
[in] xlat real, (ix), grid latitude in radians, default to pi/2 -> -pi/2 range, otherwise see in-line comment
[in] xlon real, (ix), grid longitude in radians (not used)
[in] slmsk real, (ix), sea/land mask array (sea:0,land:1,sea-ice:2)
[in] ix integer, horizontal dimention
[in] nlay,nlp1 integer, vertical layer/level dimensions
[in] deltaq real, (ix,nlay), half total water distribution width
[in] sup real, supersaturation
[in] kdt integer
[in] me integer, print control flag
[out] clouds real, (ix,nlay,nf_clds), cloud profiles
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud liq water path (g/m**2)
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer cloud ice water path (g/m**2)
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path not assigned
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path not assigned
(:,:,9) - mean eff radius for snow flake(micron)
[out] clds real, (ix,5), fraction of clouds for low, mid, hi, tot, bl
[out] mtop integer, (ix,3), vertical indices for low, mid, hi cloud tops
[out] mbot integer, (ix,3), vertical indices for low, mid, hi cloud bases
General Algorithm
Find top pressure for each cloud domain for given latitude
Compute liquid/ice condensate path in \(g/m^2 \)
Compute effective liquid cloud droplet radius over land
Compute effective ice cloud droplet radius
For ice clouds, following Heymsfield and McFarquhar (1996),the effective ice droplet radius is made to be an empirical function of ice water concentration (IWC) and environmental temperature as:
\(r_{ei} = (1250/9.917)IWC^{0.109},T<-50^oC \)
\(r_{ei} = (1250/9.337)IWC^{0.080},-50^oC<=T<-40^oC \)
\(r_{ei} = (1250/9.208)IWC^{0.055},-40^oC<=T<-30^oC \)
Call gethml to compute low,mid,high,total, and boundary layer cloud fractions
Definition at line 1352 of file radiation_clouds.f.
References climit, climit2, gethml(), gfac, gord, nf_clds, ptopc, reice_def, reliq_def, rrain_def, and rsnow_def.
Referenced by module_radiation_driver::grrad().
subroutine module_radiation_clouds::rhtable () private
Definition at line 2715 of file radiation_clouds.f.
References mcld, nbin, nlat, nlon, nseal, and rhcl.
Referenced by cld_init().
subroutine module_microphysics::rsipath2 ()
Parameters
[in] plyr real, (IM,LEVS), model layer mean pressure in mb (100Pa)
[in] plvl real, (IM,LEVS+1), model level pressure in mb (100Pa)
[in] tlyr real, (IM,LEVS), model layer mean temperature in K
[in] qlyr real, (IM,LEVS), layer specific humidity in gm/gm
[in] qcwat real, (IM,LEVS), layer cloud liquid water condensate amount
[in] qcice real, (IM,LEVS), layer cloud ice water condensate amount
[in] qrain real, (IM,LEVS), layer rain drop water amount
[in] rrime real, (IM,LEVS), mass ratio of total to unrimed ice (>= 1)
[in] IM integer, horizontal dimention
[in] LEVS integer, vertical layer dimensions
[in] iflip integer, control flag for in/out vertical indexing
=0: index from toa to surface
=1: index from surface to toa
[in] flgmin real, minimum large ice fraction
[in] lprnt logical, logical check print control flag
[out] cwatp real, (IM,LEVS), layer cloud liquid water path
[out] cicep real, (IM,LEVS), layer cloud ice water path
[out] rainp real, (IM,LEVS), layer rain water path
[out] snowp real, (IM,LEVS), layer snow water path
[out] recwat real, (IM,LEVS), layer cloud eff radius for liqid water (micron)
[out] rerain real, (IM,LEVS), layer rain water effective radius (micron)
[out] resnow real, (IM,LEVS), layer snow flake effective radius (micron)
[out] snden real, (IM,LEVS), 1/snow density
General Algorithm
Set up pressure related arrays, convert unit from mb to cb (10Pa). The rest part uses cb in computation.
Compute air density (rho), model mass thickness (cpath), and temperature in C (tc)
For cloud water, compute effective raius (recwat) and total water path (cwatp): assume monodisperse distribution of droplets (no factor of 1.5)
For rain water, compute effective radius (rerain) and total water path (rainp): factor of 1.5 accounts for \(r^3/r^2 \) moments for exponentially distributed drops in effective raius calculations (from m.d. chou's code provided to y.-t. hou)
For cloud ice,
- mean particle size following houze et al. (jas, 1979, p.160), converted from fig.5 plot of lamdas. An analogous set of relationships also shown by fig.8 of ryan (bams, 1996, p.66), but with a variaty of different relationships parallel the houze curves.
Definition at line 2933 of file module_bfmicrophysics.f.
References module_microphysics::cn0r0, module_microphysics::indexsmin, module_microphysics::massi, module_microphysics::mdimax, module_microphysics::mdimin, module_microphysics::nlimin, module_microphysics::rerainmin, module_microphysics::sdens, module_microphysics::tnw, module_microphysics::xmimax, module_microphysics::xmrmax, and module_microphysics::xmrmin.
Referenced by progcld2().
Variable Documentation
real (kind=kind_phys), parameter module_radiation_clouds::cldasy_def = 0.84 private
Definition at line 199 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), parameter module_radiation_clouds::cldssa_def = 0.99 private
Definition at line 198 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), parameter module_radiation_clouds::climit = 0.001 private
Definition at line 182 of file radiation_clouds.f.
Referenced by diagcld1(), gethml(), progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::climit2 =0.05 private
Definition at line 182 of file radiation_clouds.f.
Referenced by progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::gfac =1.0e5/con_g private
Definition at line 168 of file radiation_clouds.f.
Referenced by progcld1(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::gord =con_g/con_rd private
Definition at line 168 of file radiation_clouds.f.
Referenced by progcld1(), and progcld3().
integer module_radiation_clouds::iovr = 1 private
Definition at line 218 of file radiation_clouds.f.
Referenced by cld_init(), and gethml().
integer module_radiation_clouds::llyr = 2 private
Definition at line 217 of file radiation_clouds.f.
Referenced by cld_init(), diagcld1(), and gethml().
integer, parameter module_radiation_clouds::mcld =4 private
Definition at line 195 of file radiation_clouds.f.
Referenced by diagcld1(), and rhtable().
integer, parameter module_radiation_clouds::nbin =100 private
Definition at line 192 of file radiation_clouds.f.
Referenced by diagcld1(), and rhtable().
integer, parameter, public module_radiation_clouds::nf_clds = 9
Definition at line 171 of file radiation_clouds.f.
Referenced by progcld1(), and progcld3().
integer, parameter, public module_radiation_clouds::nk_clds = 3
Definition at line 173 of file radiation_clouds.f.
Referenced by gethml().
integer, parameter module_radiation_clouds::nlat =4 private
Definition at line 194 of file radiation_clouds.f.
Referenced by rhtable().
integer, parameter module_radiation_clouds::nlon =2 private
Definition at line 193 of file radiation_clouds.f.
Referenced by diagcld1(), and rhtable().
integer, parameter module_radiation_clouds::nseal =2 private
Definition at line 196 of file radiation_clouds.f.
Referenced by diagcld1(), and rhtable().
real (kind=kind_phys), parameter module_radiation_clouds::ovcst = 1.0 - 1.0e-8 private
Definition at line 183 of file radiation_clouds.f.
Referenced by gethml().
real (kind=kind_phys), dimension(nk_clds+1,2), save module_radiation_clouds::ptopc private
Definition at line 176 of file radiation_clouds.f.
Referenced by diagcld1(), progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::reice_def = 50.0 private
Definition at line 187 of file radiation_clouds.f.
Referenced by progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::reliq_def = 10.0 private
Definition at line 186 of file radiation_clouds.f.
Referenced by progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), dimension(nbin,nlon,nlat,mcld,nseal) module_radiation_clouds::rhcl private
Definition at line 215 of file radiation_clouds.f.
Referenced by diagcld1(), and rhtable().
real (kind=kind_phys), parameter module_radiation_clouds::rrain_def = 1000.0 private
Definition at line 188 of file radiation_clouds.f.
Referenced by progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::rsnow_def = 250.0 private
Definition at line 189 of file radiation_clouds.f.
Referenced by progcld1(), progcld2(), and progcld3().
real (kind=kind_phys), parameter module_radiation_clouds::vvcld1 = 0.0003e0 private
Definition at line 209 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), parameter module_radiation_clouds::vvcld2 =-0.0005e0 private
Definition at line 210 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), dimension(3) module_radiation_clouds::xlabdy private
Definition at line 204 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), parameter module_radiation_clouds::xlim =5.0 private
Definition at line 203 of file radiation_clouds.f.
Referenced by diagcld1().
real (kind=kind_phys), dimension(3) module_radiation_clouds::xlobdy private
Definition at line 204 of file radiation_clouds.f.
Referenced by diagcld1().