Radiation Scheme in CCPP: module_radiation_astronomy
module_radiation_astronomy
RRTMG Radiation Scheme
This module sets up astronomy quantities for solar radiation calculations.
Modules
module module_radiation_astronomy
Functions/Subroutines
subroutine, public module_radiation_astronomy::sol_update
This subroutine computes solar parameters at forecast time.
subroutine module_radiation_astronomy::solar
This subroutine computes radius vector, declination and right ascension of sun, and equation of time.
subroutine, public module_radiation_astronomy::coszmn
This subroutine computes mean cos solar zenith angle over SW calling interval.
subroutine module_radiation_astronomy::prtime
This subroutine prints out forecast date, time, and astronomy quantities.
Variables
real(kind=kind_phys), parameter module_radiation_astronomy::degrad = 180.0/con_pi
real(kind=kind_phys), parameter module_radiation_astronomy::tpi = 2.0 * con_pi
real(kind=kind_phys), parameter module_radiation_astronomy::hpi = 0.5 * con_pi
real(kind=kind_phys), parameter module_radiation_astronomy::f12 = 12.0
real(kind=kind_phys), parameter module_radiation_astronomy::f3600 = 3600.0
real(kind=kind_phys), parameter module_radiation_astronomy::czlimt = 0.0001
real(kind=kind_phys), parameter module_radiation_astronomy::pid12 = (2.0*asin(1.0))/f12
real(kind=kind_phys), public module_radiation_astronomy::solc0 = con_solr
integer module_radiation_astronomy::isolflg = 10
character(26) module_radiation_astronomy::solar_fname = ' '
real(kind=kind_phys) module_radiation_astronomy::sollag =0.0
real(kind=kind_phys) module_radiation_astronomy::sindec =0.0
real(kind=kind_phys) module_radiation_astronomy::cosdec =0.0
real(kind=kind_phys) module_radiation_astronomy::anginc =0.0
real(kind=kind_phys), dimension(12) module_radiation_astronomy::smon_sav
integer module_radiation_astronomy::iyr_sav =0
integer module_radiation_astronomy::nstp =6
subroutine, public module_radiation_astronomy::sol_init
This subroutine initializes astronomy process, and set up module constants.
Detailed Description
Function/Subroutine Documentation
subroutine, public module_radiation_astronomy::coszmn ()
Parameters
[in] xlon real, (IM), grids' longitudes in radians, work both on zonal, 0->2pi and -pi->+pi arrangements
[in] sinlat real, (IM), sine of the corresponding latitudes
[in] coslat real, (IM), cosine of the corresponding latitudes
[in] solhr real, time after 00z in hours
[in] IM integer, num of grids in horizontal dimension
[in] me integer, print message control flag
[out] coszen real, (IM), average of cosz for daytime only in sw call interval
[out] coszdg real, (IM), average of cosz over entire sw call interval
Definition at line 784 of file radiation_astronomy.f.
References anginc, cosdec, czlimt, f12, nstp, pid12, sindec, and sollag.
Referenced by module_radiation_driver::grrad().
subroutine module_radiation_astronomy::prtime () private
Definition at line 872 of file radiation_astronomy.f.
References degrad, f12, hpi, and sollag.
Referenced by sol_update().
subroutine, public module_radiation_astronomy::sol_init ()
Parameters
[in] me print message control flag
[out] NONE
External Module Variables
physparam::isolar
- = 0: use the old fixed solar constant in "physcon"
- =10: use the new fixed solar constant in "physcon"
- = 1: use noaa ann-mean tsi tbl abs-scale with cyc apprx
- = 2: use noaa ann-mean tsi tbl tim-scale with cyc apprx
- = 3: use cmip5 ann-mean tsi tbl tim-scale with cyc apprx
- = 4: use cmip5 mon-mean tsi tbl tim-scale with cyc apprx
Definition at line 143 of file radiation_astronomy.f.
References isolflg, iyr_sav, nstp, solar_fname, solc0, and vtagast.
Referenced by module_radiation_driver::radinit().
subroutine, public module_radiation_astronomy::sol_update ()
Parameters
[in] jdate integer, 1, ncep absolute date and time at fcst time (yr, mon, day, t-zone, hr, min, sec, mil-sec)
[in] kyear integer, 1, usually kyear=jdate(1). if not, it is for hindcast mode, and it is usually the init cond time and serves as the upper limit of data can be used.
[in] deltsw real, 1, time duration in seconds per sw calculation
[in] deltim real, 1, timestep in seconds
[in] lsol_chg logical flags for change solar constant
[in] me integer, print message control flag
[out] slag real, equation of time in radians
[out] sdec,cdec real, sin and cos of the solar declination angle
[out] solcon real, sun-earth distance adjusted solar constant \((w/m^2)\)
Definition at line 312 of file radiation_astronomy.f.
References anginc, cosdec, f3600, isolflg, iyr_sav, nstp, pid12, prtime(), sindec, smon_sav, solar(), solar_fname, solc0, and sollag.
Referenced by module_radiation_driver::radupdate().
subroutine module_radiation_astronomy::solar () private
Definition at line 619 of file radiation_astronomy.f.
References cosdec, degrad, sindec, sollag, and tpi.
Referenced by sol_update().
Variable Documentation
real (kind=kind_phys) module_radiation_astronomy::anginc =0.0 private
Definition at line 115 of file radiation_astronomy.f.
Referenced by coszmn(), and sol_update().
real (kind=kind_phys) module_radiation_astronomy::cosdec =0.0 private
Definition at line 114 of file radiation_astronomy.f.
Referenced by coszmn(), sol_update(), and solar().
real (kind=kind_phys), parameter module_radiation_astronomy::czlimt = 0.0001 private
Definition at line 102 of file radiation_astronomy.f.
Referenced by coszmn().
real (kind=kind_phys), parameter module_radiation_astronomy::degrad = 180.0/con_pi private
Definition at line 97 of file radiation_astronomy.f.
Referenced by prtime(), and solar().
real (kind=kind_phys), parameter module_radiation_astronomy::f12 = 12.0 private
Definition at line 100 of file radiation_astronomy.f.
Referenced by coszmn(), and prtime().
real (kind=kind_phys), parameter module_radiation_astronomy::f3600 = 3600.0 private
Definition at line 101 of file radiation_astronomy.f.
Referenced by sol_update().
real (kind=kind_phys), parameter module_radiation_astronomy::hpi = 0.5 * con_pi private
Definition at line 99 of file radiation_astronomy.f.
Referenced by prtime().
integer module_radiation_astronomy::isolflg = 10 private
Definition at line 108 of file radiation_astronomy.f.
Referenced by sol_init(), and sol_update().
integer module_radiation_astronomy::iyr_sav =0 private
Definition at line 119 of file radiation_astronomy.f.
Referenced by sol_init(), and sol_update().
integer module_radiation_astronomy::nstp =6 private
Definition at line 120 of file radiation_astronomy.f.
Referenced by coszmn(), sol_init(), and sol_update().
real (kind=kind_phys), parameter module_radiation_astronomy::pid12 = (2.0*asin(1.0))/f12 private
Definition at line 104 of file radiation_astronomy.f.
Referenced by coszmn(), and sol_update().
real (kind=kind_phys) module_radiation_astronomy::sindec =0.0 private
Definition at line 113 of file radiation_astronomy.f.
Referenced by coszmn(), sol_update(), and solar().
real (kind=kind_phys), dimension(12) module_radiation_astronomy::smon_sav private
Definition at line 116 of file radiation_astronomy.f.
Referenced by sol_update().
character(26) module_radiation_astronomy::solar_fname = ' ' private
Definition at line 109 of file radiation_astronomy.f.
Referenced by sol_init(), and sol_update().
real (kind=kind_phys), public module_radiation_astronomy::solc0 = con_solr
Definition at line 107 of file radiation_astronomy.f.
Referenced by sol_init(), and sol_update().
real (kind=kind_phys) module_radiation_astronomy::sollag =0.0 private
Definition at line 112 of file radiation_astronomy.f.
Referenced by coszmn(), prtime(), sol_update(), and solar().
real (kind=kind_phys), parameter module_radiation_astronomy::tpi = 2.0 * con_pi private
Definition at line 98 of file radiation_astronomy.f.
Referenced by solar().