Radiation Scheme in CCPP: module_radiation_aerosols
module_radiation_aerosols
RRTMG Radiation Scheme
This module contains climatological atmospheric aerosol schemes for radiation computations.
Modules
module module_radiation_aerosols
Data Types
type module_radiation_aerosols::gocart_index_type
type module_radiation_aerosols::tracer_index_type
Functions/Subroutines
subroutine, public module_radiation_aerosols::aer_init
The initialization program to set up necessary parameters and working arrays.
subroutine wrt_aerlog
This subroutine writes aerosol parameter configuration to run log file.
subroutine set_spectrum
This subroutine defines the one wavenumber solar fluxes based on toa solar spectral distribution, and define the one wavenumber IR fluxes based on black-body emission distribution at a predefined temperature.
subroutine set_volcaer
The initialization program for stratospheric volcanic aerosols.
subroutine module_radiation_aerosols::clim_aerinit
This subroutine is the opac-climatology aerosol initialization program to set up necessary parameters and working arrays.
subroutine set_aercoef
the initialization program for climatological aerosols. the program reads and maps the pre-tabulated aerosol optical spectral data onto corresponding SW radiation spectral bands.
subroutine optavg
compute mean aerosols optical properties over each SW radiation spectral band for each of the species components. This program follows GFDL's approach for thick cloud optical property in SW radiation scheme (2000).
subroutine, public module_radiation_aerosols::aer_update
This subroutine checks and updates time varying climatology aerosol data sets.
subroutine trop_update
update the monthly global distribution of aerosol profiles in five degree horizontal resolution.
subroutine volc_update
search historical volcanic data sets to find and read in monthly 45-degree lat-zone band of optical depth.
subroutine module_radiation_aerosols::gocart_init
the initialization program for gocart aerosols
subroutine set_aerspc (raddt, fdaer)
determine merging coefficients ctaer; setup aerosol specification.
subroutine rd_gocart_luts
This subroutine reads input gocart aerosol optical data from Mie code calculations.
subroutine optavg_grt
This subroutine computes mean aerosols optical properties over each SW/LW radiation spectral band for each of the species components. This program follows GFDL's approach for thick cloud optical property in SW radiation scheme (2000)
subroutine rd_gocart_clim
This subroutine:
subroutine module_radiation_aerosols::setgocartaer
This subroutine computes SW + LW aerosol optical properties for gocart aerosol species (merged from fcst and clim fields).
subroutine map_aermr
This subroutine maps input tracer fields (trcly) to local tracer array (aermr).
subroutine aeropt_grt
This subroutine computes aerosols optical properties in NSWLWBD SW/LW bands. Aerosol distribution at each grid point is composed from up to NMXG aerosol species (from NUM_GRIDCOMP components).
Variables
integer, parameter, public module_radiation_aerosols::nf_aesw = 3
num of output fields for sw rad
integer, parameter, public module_radiation_aerosols::nf_aelw = 3
num of output fields for lw rad
integer, parameter, public module_radiation_aerosols::nlwstr = 1
starting band number in ir region
integer, parameter, public module_radiation_aerosols::nspc = 5
num of species for output aod (opnl)
integer, parameter, public module_radiation_aerosols::nspc1 = NSPC + 1
total+species
real(kind=kind_phys), parameter module_radiation_aerosols::f_zero = 0.0
real(kind=kind_phys), parameter module_radiation_aerosols::f_one = 1.0
integer, save module_radiation_aerosols::nswbnd = NBDSW
integer, save module_radiation_aerosols::nlwbnd = NBDLW
integer, save module_radiation_aerosols::nswlwbd = NBDSW+NBDLW
integer, parameter, public module_radiation_aerosols::nwvsol = 151
num of wvnum regions where solar flux is constant
integer, parameter, public module_radiation_aerosols::nwvtot = 57600
total num of wvnum included
integer, parameter, public module_radiation_aerosols::nwvtir = 4000
total num of wvnum in ir range
integer, dimension(nwvsol), save module_radiation_aerosols::nwvns0
real(kind=kind_phys), dimension(nwvsol), save module_radiation_aerosols::s0intv
integer, parameter module_radiation_aerosols::minvyr = 1850
integer, parameter module_radiation_aerosols::maxvyr = 1999
integer, dimension(:,:,:), allocatable, save module_radiation_aerosols::ivolae
integer module_radiation_aerosols::kyrstr
integer module_radiation_aerosols::kyrend
integer module_radiation_aerosols::kyrsav
integer module_radiation_aerosols::kmonsav
integer, parameter module_radiation_aerosols::nxc = 5
integer, parameter module_radiation_aerosols::nae = 7
integer, parameter module_radiation_aerosols::ndm = 5
integer, parameter module_radiation_aerosols::imxae = 72
integer, parameter module_radiation_aerosols::jmxae = 37
integer, parameter module_radiation_aerosols::naerbnd =61
integer, parameter module_radiation_aerosols::nrhlev =8
integer, parameter module_radiation_aerosols::ncm1 = 6
integer, parameter module_radiation_aerosols::ncm2 = 4
integer, parameter module_radiation_aerosols::ncm = NCM1+NCM2
real(kind=kind_phys), dimension(nrhlev), save module_radiation_aerosols::rhlev
real(kind=kind_phys), dimension(ndm, nae), save module_radiation_aerosols::haer
real(kind=kind_phys), dimension(ndm, nae), save module_radiation_aerosols::prsref
real(kind=kind_phys), dimension(ndm, nae), save module_radiation_aerosols::sigref
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::scarhi
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::scarhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd
real(kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::extstra
real(kind=kind_phys), dimension(nxc, imxae, jmxae), save module_radiation_aerosols::cmixg
real(kind=kind_phys), dimension(2,imxae, jmxae), save module_radiation_aerosols::denng
integer, dimension(nxc, imxae, jmxae), save module_radiation_aerosols::idxcg
integer, dimension(imxae, jmxae), save module_radiation_aerosols::kprfg
integer, parameter module_radiation_aerosols::kaerbnd =61
integer, parameter module_radiation_aerosols::krhlev =36
integer, save module_radiation_aerosols::kcm1 = 0
integer, save module_radiation_aerosols::kcm2 = 0
integer, save module_radiation_aerosols::kcm
real(kind=kind_phys), dimension(:) module_radiation_aerosols::rhlev_grt
real(kind=kind_phys), dimension(krhlev) module_radiation_aerosols::data
integer, dimension(:), allocatable module_radiation_aerosols::iendwv_grt
real(kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidext0_grt
real(kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidssa0_grt
real(kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidasy0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpext0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpssa0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpasy0_grt
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi_grt
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi_grt
real(kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd_grt
integer, parameter module_radiation_aerosols::imxg = 144
integer, parameter module_radiation_aerosols::jmxg = 91
integer, parameter module_radiation_aerosols::kmxg = 30
integer, save module_radiation_aerosols::nmxg
real(kind=kind_phys), parameter module_radiation_aerosols::dltx = 360.0 / float(IMXG)
real(kind=kind_phys), parameter module_radiation_aerosols::dlty = 180.0 / float(JMXG-1)
real(kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::psclmg
real(kind=kind_phys), dimension(:,:,:,:), allocatable, save module_radiation_aerosols::dmclmg
real(kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlon
real(kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlat
character *4, save module_radiation_aerosols::gocart_climo = 'xxxx'
real(kind=kind_io4), dimension(:), allocatable module_radiation_aerosols::molwgt
logical, save module_radiation_aerosols::lgrtint = .true.
logical, save module_radiation_aerosols::lckprnt = .false.
real(kind=kind_phys), save module_radiation_aerosols::ctaer = f_zero
logical, save module_radiation_aerosols::get_fcst = .true.
logical, save module_radiation_aerosols::get_clim = .true.
integer, save module_radiation_aerosols::isoot
integer, save module_radiation_aerosols::iwaso
integer, save module_radiation_aerosols::isuso
integer, save module_radiation_aerosols::issam
integer, save module_radiation_aerosols::isscm
integer module_radiation_aerosols::gocart_index_type::dust1
integer module_radiation_aerosols::gocart_index_type::dust2
integer module_radiation_aerosols::gocart_index_type::dust3
integer module_radiation_aerosols::gocart_index_type::dust4
integer module_radiation_aerosols::gocart_index_type::dust5
integer module_radiation_aerosols::gocart_index_type::ssam
integer module_radiation_aerosols::gocart_index_type::sscm
integer module_radiation_aerosols::gocart_index_type::suso
integer module_radiation_aerosols::gocart_index_type::waso_phobic
integer module_radiation_aerosols::gocart_index_type::waso_philic
integer module_radiation_aerosols::gocart_index_type::soot_phobic
integer module_radiation_aerosols::gocart_index_type::soot_philic
type(gocart_index_type), save module_radiation_aerosols::dm_indx
integer module_radiation_aerosols::tracer_index_type::du001
integer module_radiation_aerosols::tracer_index_type::du002
integer module_radiation_aerosols::tracer_index_type::du003
integer module_radiation_aerosols::tracer_index_type::du004
integer module_radiation_aerosols::tracer_index_type::du005
integer module_radiation_aerosols::tracer_index_type::ss001
integer module_radiation_aerosols::tracer_index_type::ss002
integer module_radiation_aerosols::tracer_index_type::ss003
integer module_radiation_aerosols::tracer_index_type::ss004
integer module_radiation_aerosols::tracer_index_type::ss005
integer module_radiation_aerosols::tracer_index_type::so4
integer module_radiation_aerosols::tracer_index_type::ocphobic
integer module_radiation_aerosols::tracer_index_type::ocphilic
integer module_radiation_aerosols::tracer_index_type::bcphobic
integer module_radiation_aerosols::tracer_index_type::bcphilic
type(tracer_index_type), save module_radiation_aerosols::dmfcs_indx
integer, save module_radiation_aerosols::num_gridcomp = 0
character, dimension(:), allocatable, save module_radiation_aerosols::gridcomp
integer, parameter module_radiation_aerosols::max_num_gridcomp = 5
character *2, dimension(max_num_gridcomp) module_radiation_aerosols::max_gridcomp
integer, dimension(ncm) module_radiation_aerosols::idxspc
real(kind=kind_phys), parameter module_radiation_aerosols::wvn550 = 1.0e4/0.55
integer, save module_radiation_aerosols::nv_aod = 1
subroutine, public module_radiation_aerosols::setaer
This subroutine computes aerosols optical properties.
subroutine module_radiation_aerosols::aer_property
This subroutine maps the 5 degree global climatological aerosol data set onto model grids, and compute aerosol optical properties for SW and LW radiations.
subroutine radclimaer
This subroutine computes aerosols optical properties in NSWLWBD bands. there are seven different vertical profile structures. in the troposphere, aerosol distribution at each grid point is composed from up to six components out of ten different substances.
Detailed Description
Function/Subroutine Documentation
subroutine, public module_radiation_aerosols::aer_init ()
Parameters
[in] NLAY integer, number of model vertical layers (not used)
[in] me integer, print message control flag
[in] NONE
External Module Variables
physparam::iaermdl: tropospheric aerosol model scheme flag. =0 opac-clim; =1 gocart-clim; =2 gocart-prognostic
physparam::lalwflg: logical lw aerosol effect control flag. =t compute lw aerosol optical property
physparam::laswflg: logical sw aerosols effect control flag. =t compute sw aerosol optical property
physparam::lavoflg: logical stratosphere volcanic aerosol control flag. =t include volcanic aerosol effect
physparam::lalw1bd: logical lw aerosol property 1 band vs multi-band control flag. =t use 1 broad band optical property; =f use multi bands optical property
Subprograms Called
- clim_aerinit: This subprogram is the opac-climatology aerosol initialization program to set up necessary parameters and working arrays.
- wrt_aerlog: This subprogram writes aerosol parameter configuration to run log file.
- set_volcaer: This is the initialization program for stratospheric volcanic aerosols.
- set_spectrum: This subprogram defines the one wavenumber solar fluxes based on toa solar spectral distribution, and define the one wavenumber ir fluxes based on black-body emission distribution at a predefined temperature.
- set_aercoef: This is the initialization program for climatological aerosols. The program reads and maps the pre-tabulated aerosol optical spectral data onto corresponding sw radiation spectral bands.
- optavg: This subprogram computes mean aerosols optical properties over each sw radiation spectral band for each of the species components. This program follows gfdl's approach for thick cloud optical property in sw radiation scheme.
Definition at line 571 of file radiation_aerosols.f.
References clim_aerinit(), kmonsav, kyrend, kyrsav, kyrstr, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nswbnd, nswlwbd, set_spectrum(), set_volcaer(), and wrt_aerlog().
Referenced by module_radiation_driver::radinit().
subroutine module_radiation_aerosols::aer_property () private
Parameters
[in] prsi real, (IMAX,NLP1), pressure at interface in mb
[in] prsl real, (IMAX,NLAY), layer mean pressure(not used)
[in] prslk real, (IMAX,NLAY), exner function= \((p/p0)^{rocp}\) (not used)
[in] tvly real, (IMAX,NLAY), layer virtual temperature (not used)
[in] rhlay real, (IMAX,NLAY), layer mean relative humidity
[in] dz real, (IMAX,NLAY), layer thickness in m
[in] hz real, (IMAX,NLP1), level high in m
[in] tracer real, (IMAX,NLAY,NTRAC), aer tracer concentrations (not used)
[in] alon,alat real, (IMAX), longitude and latitude of given points in degree
[in] slmsk real, (IMAX), sea/land mask (sea:0,land:1,sea-ice:2)
[in] laersw,laerlw logical, 1, logical flag for sw/lw aerosol calculations
[in] IMAX integer, 1, horizontal dimension of arrays
[in] NLAY,NLP1 integer, 1, vertical dimensions of arrays
[in] NSPC integer, 1, num of species for optional aod output fields
[out] aerosw real, (IMAX,NLAY,NBDSW,NF_AESW), aeros opt properties for sw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerolw real, (IMAX,NLAY,NBDLW,NF_AELW), aeros opt properties for lw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerodp real, (IMAX,NSPC+1), vertically integrated aer-opt-depth
Map aerosol data to model grids
Map grid in longitude direction, lon from 0 to 355 deg resolution
Map grid in latitude direction, lat from 90n to 90s in 5 deg resolution
Determin the type of aerosol profile (kp) and scale hight for domain 1 (h1) to be used at this grid point
Compute horizontal bi-linear interpolation weights
Do horizontal bi-linear interpolation on aerosol partical density (denn)
Do horizontal bi-linear interpolation on mixing ratios
Prepare to setup domain index array and effective layer thickness. also convert pressure level to sigma level to follow the terrain
Call radclimaer() to calculate sw/lw aerosol optical properties for the corresponding frequency bands
Definition at line 2603 of file radiation_aerosols.f.
References cmixg, denng, f_one, f_zero, haer, idxcg, imxae, jmxae, kprfg, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nspc, nswbnd, nv_aod, nxc, prsref, radclimaer(), and sigref.
Referenced by setaer().
subroutine, public module_radiation_aerosols::aer_update ()
Parameters
[in] iyear integer, 1, 4-digit calender year
[in] imon integer, 1, month of the year
[in] me integer, 1, print message control flag
[out] NONE
External Module Variables
physparam::lalwflg - control flag for tropospheric lw aerosol
physparam::laswflg - control flag for tropospheric sw aerosol
physparam::lavoflg - control flag for stratospheric volcanic aerosol
Subprograms Called
- trop_update: This subprogram updates the monthly global distribution of aerosol profiles in five degree horizontal resolution.
- volc_update: This subprogram searches historical volcanic data sets to find and read in monthly 45-degree lat-zone band data of optical depth
Definition at line 1649 of file radiation_aerosols.f.
References trop_update(), and volc_update().
Referenced by module_radiation_driver::radupdate().
subroutine setgocartaer::aeropt_grt () private
Definition at line 5058 of file radiation_aerosols.f.
References asyrhd_grt, asyrhi_grt, dm_indx, extrhd_grt, extrhi_grt, f_one, f_zero, gridcomp, isoot, issam, isuso, iwaso, kcm1, krhlev, max_gridcomp, max_num_gridcomp, num_gridcomp, nv_aod, rhlev_grt, ssarhd_grt, and ssarhi_grt.
Referenced by setgocartaer().
subroutine module_radiation_aerosols::clim_aerinit () private
Parameters
[in] solfwv real, (NWVTOT), solar flux for each individual wavenumber \((w/m^2)\)
[in] eirfwv real, (NWVTIR), ir flux(273k) for each individual wavenum \((w/m^2)\)
[in] me integer, 1, print message control flag
Definition at line 950 of file radiation_aerosols.f.
References set_aercoef().
Referenced by aer_init().
subroutine module_radiation_aerosols::gocart_init () private
determine weight and index for aerosol composition/luts
read in monthly global distribution of gocart aerosols
read and map the tabulated aerosol optical spectral data onto corresponding SW/LW radiation spectral bands.
Definition at line 3365 of file radiation_aerosols.f.
References extrhd_grt, extrhi_grt, f_zero, get_clim, iendwv_grt, kaerbnd, krhlev, lckprnt, lgrtint, module_radsw_parameters::nbdsw, nlwbnd, nswlwbd, module_radsw_parameters::nswstr, nv_aod, nwvtir, nwvtot, optavg_grt(), rd_gocart_clim(), rd_gocart_luts(), rhdpasy0_grt, rhdpext0_grt, rhdpssa0_grt, rhidasy0_grt, rhidext0_grt, rhidssa0_grt, rhlev_grt, set_aerspc(), module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
subroutine setgocartaer::map_aermr () private
Definition at line 4972 of file radiation_aerosols.f.
References dm_indx, dmfcs_indx, and f_zero.
Referenced by setgocartaer().
subroutine clim_aerinit::optavg () private
Definition at line 1375 of file radiation_aerosols.f.
References asyrhd, asyrhi, extrhd, extrhi, extstra, f_one, f_zero, ncm1, ncm2, nlwbnd, nrhlev, nswbnd, scarhd, scarhi, ssarhd, and ssarhi.
Referenced by set_aercoef().
subroutine gocart_init::optavg_grt () private
Definition at line 4155 of file radiation_aerosols.f.
References asyrhd_grt, asyrhi_grt, extrhd_grt, extrhi_grt, f_one, f_zero, kcm1, kcm2, krhlev, rhdpasy0_grt, rhdpext0_grt, rhdpssa0_grt, rhidasy0_grt, rhidext0_grt, rhidssa0_grt, ssarhd_grt, and ssarhi_grt.
Referenced by gocart_init().
subroutine aer_property::radclimaer () private
Parameters
[in] cmix real, (NCM), mixing ratioes of aerosol components
[in] denn real, 2, aerosol number densities
[in] rh1 real, (NLAY), relative humidity
[in] delz real, (NLAY), effective layer thickness in km
[in] idmaer integer, (NLAY), aerosol domain index
[in] NXC integer, 1number of different aerosol components
[in] NLAY integer, 1, vertical dimensions
[out] tauae real, (NLAY, NSWLWBD), optical depth
[out] ssaae real, (NLAY, NSWLWBD), single scattering albedo
[out] asyae real, (NLAY, NSWLWBD), asymmetry parameter
[out] aerodp real, (IMAX, NSPC+1), vertically integrated aer-opt-depth
Todo:
radclimaer has no arguments; need to remove the parameter specifications above
Definition at line 3051 of file radiation_aerosols.f.
References asyrhd, asyrhi, extrhd, extrhi, extstra, f_one, f_zero, idxspc, ncm, ncm1, nrhlev, nswbnd, nswlwbd, nv_aod, rhlev, scarhd, scarhi, ssarhd, and ssarhi.
Referenced by aer_property().
subroutine gocart_init::rd_gocart_clim () private
read in aerosol dry mass and surface pressure from GEOS3-GOCART C3.1 2000 monthly dataset or aerosol mixing ratio and surface pressure from GEOS4-GOCART 2000-2007 averaged monthly data set.
compute goes lat/lon array (for horizontal mapping)
Definition at line 4373 of file radiation_aerosols.f.
References dltx, dlty, dm_indx, dmclmg, f_zero, geos_rlat, geos_rlon, gocart_climo, gridcomp, imxg, jmxg, kmxg, molwgt, nmxg, num_gridcomp, and psclmg.
Referenced by gocart_init().
subroutine gocart_init::rd_gocart_luts () private
Definition at line 3979 of file radiation_aerosols.f.
References iendwv_grt, isoot, issam, isscm, isuso, iwaso, kaerbnd, kcm1, kcm2, krhlev, lckprnt, rhdpasy0_grt, rhdpext0_grt, rhdpssa0_grt, rhidasy0_grt, rhidext0_grt, and rhidssa0_grt.
Referenced by gocart_init().
subroutine clim_aerinit::set_aercoef () private
Definition at line 1038 of file radiation_aerosols.f.
References asyrhd, asyrhi, extrhd, extrhi, extstra, f_zero, haer, imxae, jmxae, naerbnd, ncm1, ncm2, nlwbnd, nlwstr, nrhlev, nswbnd, nswlwbd, module_radsw_parameters::nswstr, nv_aod, optavg(), prsref, scarhd, scarhi, sigref, ssarhd, ssarhi, wvn550, module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
Referenced by clim_aerinit().
subroutine gocart_init::set_aerspc (real (kind=kind_phys), intent(in) raddt, real (kind=kind_phys), intent(in) fdaer) private
Definition at line 3680 of file radiation_aerosols.f.
References ctaer, dm_indx, dmfcs_indx, f_one, f_zero, get_clim, get_fcst, gridcomp, isoot, issam, isscm, isuso, iwaso, kcm, kcm1, kcm2, lckprnt, max_gridcomp, max_num_gridcomp, nmxg, and num_gridcomp.
Referenced by gocart_init().
subroutine aer_init::set_spectrum () private
Definition at line 814 of file radiation_aerosols.f.
References nwvns0, nwvsol, nwvtir, and s0intv.
Referenced by aer_init().
subroutine aer_init::set_volcaer () private
Definition at line 903 of file radiation_aerosols.f.
References ivolae.
Referenced by aer_init().
subroutine, public module_radiation_aerosols::setaer ()
Parameters
[in] prsi (IMAX,NLP1), pressure at interface in mb
[in] prsl (IMAX,NLAY), layer mean pressure in mb
[in] prslk (IMAX,NLAY), exner function = \((p/p0)^{rocp}\)
[in] tvly (IMAX,NLAY), layer virtual temperature in K
[in] rhlay (IMAX,NLAY), layer mean relative humidity
[in] slmsk (IMAX), sea/land mask (sea:0,land:1,sea-ice:2)
[in] tracer (IMAX,NLAY,NTRAC), aerosol tracer concentration
[in] xlon (IMAX), longitude of given points in radiance, ok for both 0->2pi or -pi->+pi ranges
[in] xlat (IMAX), latitude of given points in radiance, default to pi/2 -> -pi/2, otherwise see in-line comment
[in] IMAX 1, horizontal dimension of arrays
[in] NLAY,NLP1 1, vertical dimensions of arrays
[in] lsswr,lslwr logical flags for sw/lw radiation calls
[out] aerosw (IMAX,NLAY,NBDSW,NF_AESW), aeros opt properties for sw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerolw (IMAX,NLAY,NBDLW,NF_AELW), aeros opt properties for lw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] tau_gocart (IMAX,NLAY,MAX_NUM_GRIDCOMP), 550nm aeros opt depth
[out] aerodp (IMAX,NSPC1), vertically integrated optical depth
General Algorithm
Convert lat/lon from radiance to degree
Compute level height and layer thickness
Calculate sw aerosol optical properties for the corresponding frequency bands
if opac aerosol climatology is used, call aer_property(): this subroutine maps the 5 degree global climatological aerosol data set onto model grids, and compute aerosol optical properties for sw and lw radiations.
if gocart aerosol scheme is used, call setgocartaer(): this subroutine computes sw + lw aerosol optical properties for gocart aerosol species (merged from fcst and clim fields)
Compute stratosphere volcanic forcing
select data in 4 lat bands, interpolation at the boundaries
Find lower boundary of stratosphere: polar, fixed at 25000pa (250mb); tropic, fixed at 15000pa (150mb); mid-lat, interpolation
sw: add volcanic aerosol optical depth to the background value
Smoothing profile at boundary if needed
lw: add volcanic aerosol optical depth to the background value
Definition at line 2018 of file radiation_aerosols.f.
References aer_property(), f_one, f_zero, ivolae, kmonsav, kyrsav, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nf_aelw, nf_aesw, nlwbnd, nspc1, nswlwbd, module_radsw_parameters::nswstr, setgocartaer(), module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
Referenced by module_radiation_driver::grrad().
subroutine module_radiation_aerosols::setgocartaer () private
Definition at line 4694 of file radiation_aerosols.f.
References aeropt_grt(), ctaer, dmclmg, f_one, f_zero, geos_rlat, geos_rlon, get_clim, get_fcst, gocart_climo, imxg, jmxg, kmxg, map_aermr(), molwgt, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nmxg, nswlwbd, and psclmg.
Referenced by setaer().
subroutine aer_update::trop_update () private
Definition at line 1708 of file radiation_aerosols.f.
References cmixg, denng, f_one, f_zero, idxcg, imxae, jmxae, kprfg, and nxc.
Referenced by aer_update().
subroutine aer_update::volc_update () private
Definition at line 1866 of file radiation_aerosols.f.
References ivolae, kmonsav, kyrend, kyrsav, kyrstr, maxvyr, and minvyr.
Referenced by aer_update().
subroutine aer_init::wrt_aerlog () private
Definition at line 717 of file radiation_aerosols.f.
References vtagaer.
Referenced by aer_init().
Variable Documentation
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd private
Definition at line 306 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd_grt private
Definition at line 392 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi private
Definition at line 304 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi_grt private
Definition at line 390 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
integer module_radiation_aerosols::tracer_index_type::bcphilic private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::bcphobic private
Definition at line 502 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(nxc,imxae,jmxae), save module_radiation_aerosols::cmixg private
Definition at line 318 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
real (kind=kind_phys), save module_radiation_aerosols::ctaer = f_zero private
Definition at line 457 of file radiation_aerosols.f.
Referenced by set_aerspc(), and setgocartaer().
real (kind=kind_phys), dimension(krhlev) module_radiation_aerosols::data private
Definition at line 338 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(2 ,imxae,jmxae), save module_radiation_aerosols::denng private
Definition at line 319 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
real (kind=kind_phys), parameter module_radiation_aerosols::dltx = 360.0 / float(IMXG) private
Definition at line 417 of file radiation_aerosols.f.
Referenced by rd_gocart_clim().
real (kind=kind_phys), parameter module_radiation_aerosols::dlty = 180.0 / float(JMXG-1) private
Definition at line 418 of file radiation_aerosols.f.
Referenced by rd_gocart_clim().
type (gocart_index_type), save module_radiation_aerosols::dm_indx private
Definition at line 498 of file radiation_aerosols.f.
Referenced by aeropt_grt(), map_aermr(), rd_gocart_clim(), and set_aerspc().
real (kind=kind_phys), dimension(:,:,:,:), allocatable, save module_radiation_aerosols::dmclmg private
Definition at line 426 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
type (tracer_index_type), save module_radiation_aerosols::dmfcs_indx private
Definition at line 508 of file radiation_aerosols.f.
Referenced by map_aermr(), and set_aerspc().
integer module_radiation_aerosols::tracer_index_type::du001 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::du002 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::du003 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::du004 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::du005 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::dust1 private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::dust2 private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::dust3 private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::dust4 private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::dust5 private
Definition at line 492 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd private
Definition at line 306 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd_grt private
Definition at line 392 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi private
Definition at line 304 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi_grt private
Definition at line 390 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), and optavg_grt().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::extstra private
Definition at line 308 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), parameter module_radiation_aerosols::f_one = 1.0 private
Definition at line 163 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), optavg(), optavg_grt(), radclimaer(), set_aerspc(), setaer(), setgocartaer(), and trop_update().
real (kind=kind_phys), parameter module_radiation_aerosols::f_zero = 0.0 private
Definition at line 162 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), gocart_init(), map_aermr(), optavg(), optavg_grt(), radclimaer(), rd_gocart_clim(), set_aercoef(), set_aerspc(), setaer(), setgocartaer(), and trop_update().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlat private
Definition at line 430 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlon private
Definition at line 430 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
logical, save module_radiation_aerosols::get_clim = .true. private
Definition at line 461 of file radiation_aerosols.f.
Referenced by gocart_init(), set_aerspc(), and setgocartaer().
logical, save module_radiation_aerosols::get_fcst = .true. private
Definition at line 460 of file radiation_aerosols.f.
Referenced by set_aerspc(), and setgocartaer().
character*4, save module_radiation_aerosols::gocart_climo = 'xxxx' private
Definition at line 435 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
character, dimension(:), allocatable, save module_radiation_aerosols::gridcomp private
Definition at line 512 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_clim(), and set_aerspc().
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::haer private
Definition at line 281 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
integer, dimension(nxc,imxae,jmxae), save module_radiation_aerosols::idxcg private
Definition at line 320 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
integer, dimension(ncm) module_radiation_aerosols::idxspc private
Definition at line 531 of file radiation_aerosols.f.
Referenced by radclimaer().
integer, dimension(:), allocatable module_radiation_aerosols::iendwv_grt private
Definition at line 375 of file radiation_aerosols.f.
Referenced by gocart_init(), and rd_gocart_luts().
integer, parameter module_radiation_aerosols::imxae = 72 private
Definition at line 263 of file radiation_aerosols.f.
Referenced by aer_property(), set_aercoef(), and trop_update().
integer, parameter module_radiation_aerosols::imxg = 144 private
Definition at line 411 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, save module_radiation_aerosols::isoot private
Definition at line 483 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::issam private
Definition at line 483 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::isscm private
Definition at line 483 of file radiation_aerosols.f.
Referenced by rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::isuso private
Definition at line 483 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, dimension(:,:,:), allocatable, save module_radiation_aerosols::ivolae private
Definition at line 249 of file radiation_aerosols.f.
Referenced by set_volcaer(), setaer(), and volc_update().
integer, save module_radiation_aerosols::iwaso private
Definition at line 483 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, parameter module_radiation_aerosols::jmxae = 37 private
Definition at line 264 of file radiation_aerosols.f.
Referenced by aer_property(), set_aercoef(), and trop_update().
integer, parameter module_radiation_aerosols::jmxg = 91 private
Definition at line 412 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, parameter module_radiation_aerosols::kaerbnd =61 private
Definition at line 329 of file radiation_aerosols.f.
Referenced by gocart_init(), and rd_gocart_luts().
integer, save module_radiation_aerosols::kcm private
Definition at line 336 of file radiation_aerosols.f.
Referenced by set_aerspc().
integer, save module_radiation_aerosols::kcm1 = 0 private
Definition at line 334 of file radiation_aerosols.f.
Referenced by aeropt_grt(), optavg_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::kcm2 = 0 private
Definition at line 335 of file radiation_aerosols.f.
Referenced by optavg_grt(), rd_gocart_luts(), and set_aerspc().
integer module_radiation_aerosols::kmonsav private
Definition at line 252 of file radiation_aerosols.f.
Referenced by aer_init(), setaer(), and volc_update().
integer, parameter module_radiation_aerosols::kmxg = 30 private
Definition at line 413 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, dimension(imxae,jmxae), save module_radiation_aerosols::kprfg private
Definition at line 321 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
integer, parameter module_radiation_aerosols::krhlev =36 private
Definition at line 330 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), optavg_grt(), and rd_gocart_luts().
integer module_radiation_aerosols::kyrend private
Definition at line 252 of file radiation_aerosols.f.
Referenced by aer_init(), and volc_update().
integer module_radiation_aerosols::kyrsav private
Definition at line 252 of file radiation_aerosols.f.
Referenced by aer_init(), setaer(), and volc_update().
integer module_radiation_aerosols::kyrstr private
Definition at line 252 of file radiation_aerosols.f.
Referenced by aer_init(), and volc_update().
logical, save module_radiation_aerosols::lckprnt = .false. private
Definition at line 452 of file radiation_aerosols.f.
Referenced by gocart_init(), rd_gocart_luts(), and set_aerspc().
logical, save module_radiation_aerosols::lgrtint = .true. private
Definition at line 448 of file radiation_aerosols.f.
Referenced by gocart_init().
character*2, dimension(max_num_gridcomp) module_radiation_aerosols::max_gridcomp private
Definition at line 516 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and set_aerspc().
integer, parameter module_radiation_aerosols::max_num_gridcomp = 5 private
Definition at line 515 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and set_aerspc().
integer, parameter module_radiation_aerosols::maxvyr = 1999 private
Definition at line 246 of file radiation_aerosols.f.
Referenced by volc_update().
integer, parameter module_radiation_aerosols::minvyr = 1850 private
Definition at line 245 of file radiation_aerosols.f.
Referenced by volc_update().
real (kind=kind_io4), dimension(:), allocatable module_radiation_aerosols::molwgt private
Definition at line 438 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, parameter module_radiation_aerosols::nae = 7 private
Definition at line 261 of file radiation_aerosols.f.
integer, parameter module_radiation_aerosols::naerbnd =61 private
Definition at line 265 of file radiation_aerosols.f.
Referenced by set_aercoef().
integer, parameter module_radiation_aerosols::ncm = NCM1+NCM2 private
Definition at line 269 of file radiation_aerosols.f.
Referenced by radclimaer().
integer, parameter module_radiation_aerosols::ncm1 = 6 private
Definition at line 267 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
integer, parameter module_radiation_aerosols::ncm2 = 4 private
Definition at line 268 of file radiation_aerosols.f.
Referenced by optavg(), and set_aercoef().
integer, parameter module_radiation_aerosols::ndm = 5 private
Definition at line 262 of file radiation_aerosols.f.
integer, parameter, public module_radiation_aerosols::nf_aelw = 3
Definition at line 154 of file radiation_aerosols.f.
Referenced by setaer().
integer, parameter, public module_radiation_aerosols::nf_aesw = 3
Definition at line 152 of file radiation_aerosols.f.
Referenced by setaer().
integer, save module_radiation_aerosols::nlwbnd = NBDLW private
Definition at line 168 of file radiation_aerosols.f.
Referenced by aer_init(), aer_property(), gocart_init(), optavg(), set_aercoef(), setaer(), and setgocartaer().
integer, parameter, public module_radiation_aerosols::nlwstr = 1
Definition at line 156 of file radiation_aerosols.f.
Referenced by set_aercoef().
integer, save module_radiation_aerosols::nmxg private
Definition at line 415 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), set_aerspc(), and setgocartaer().
integer, parameter module_radiation_aerosols::nrhlev =8 private
Definition at line 266 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
integer, parameter, public module_radiation_aerosols::nspc = 5
Definition at line 158 of file radiation_aerosols.f.
Referenced by aer_property().
integer, parameter, public module_radiation_aerosols::nspc1 = NSPC + 1
Definition at line 160 of file radiation_aerosols.f.
Referenced by setaer().
integer, save module_radiation_aerosols::nswbnd = NBDSW private
Definition at line 166 of file radiation_aerosols.f.
Referenced by aer_init(), aer_property(), optavg(), radclimaer(), and set_aercoef().
integer, save module_radiation_aerosols::nswlwbd = NBDSW+NBDLW private
Definition at line 170 of file radiation_aerosols.f.
Referenced by aer_init(), gocart_init(), radclimaer(), set_aercoef(), setaer(), and setgocartaer().
integer, save module_radiation_aerosols::num_gridcomp = 0 private
Definition at line 511 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_clim(), and set_aerspc().
integer, save module_radiation_aerosols::nv_aod = 1 private
Definition at line 538 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), gocart_init(), radclimaer(), and set_aercoef().
integer, dimension(nwvsol), save module_radiation_aerosols::nwvns0 private
Definition at line 187 of file radiation_aerosols.f.
Referenced by set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvsol = 151
Definition at line 179 of file radiation_aerosols.f.
Referenced by set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvtir = 4000
Definition at line 184 of file radiation_aerosols.f.
Referenced by gocart_init(), and set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvtot = 57600
Definition at line 182 of file radiation_aerosols.f.
Referenced by gocart_init().
integer, parameter module_radiation_aerosols::nxc = 5 private
Definition at line 260 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
integer module_radiation_aerosols::tracer_index_type::ocphilic private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ocphobic private
Definition at line 502 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::prsref private
Definition at line 281 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::psclmg private
Definition at line 426 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpasy0_grt private
Definition at line 378 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpext0_grt private
Definition at line 378 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpssa0_grt private
Definition at line 378 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidasy0_grt private
Definition at line 376 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidext0_grt private
Definition at line 376 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidssa0_grt private
Definition at line 376 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(nrhlev), save module_radiation_aerosols::rhlev private
Definition at line 271 of file radiation_aerosols.f.
Referenced by radclimaer().
real (kind=kind_phys), dimension (:) module_radiation_aerosols::rhlev_grt private
Definition at line 338 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and gocart_init().
real (kind=kind_phys), dimension(nwvsol), save module_radiation_aerosols::s0intv private
Definition at line 203 of file radiation_aerosols.f.
Referenced by set_spectrum().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::scarhd private
Definition at line 306 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::scarhi private
Definition at line 304 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::sigref private
Definition at line 281 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
integer module_radiation_aerosols::tracer_index_type::so4 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::soot_philic private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::soot_phobic private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ss001 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ss002 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ss003 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ss004 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::tracer_index_type::ss005 private
Definition at line 502 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::ssam private
Definition at line 492 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd private
Definition at line 306 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd_grt private
Definition at line 392 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi private
Definition at line 304 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi_grt private
Definition at line 390 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
integer module_radiation_aerosols::gocart_index_type::sscm private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::suso private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::waso_philic private
Definition at line 492 of file radiation_aerosols.f.
integer module_radiation_aerosols::gocart_index_type::waso_phobic private
Definition at line 492 of file radiation_aerosols.f.
real (kind=kind_phys), parameter module_radiation_aerosols::wvn550 = 1.0e4/0.55 private
Definition at line 537 of file radiation_aerosols.f.
Referenced by set_aercoef().