Radiation Scheme in CCPP: module_radlw_main
module_radlw_main
RRTMG Radiation Scheme
This module includes ncep's modifications of the rrtm-lw radiation code from aer inc.
Modules
Module_radlw_avplank
This module contains plank flux data.
Module_radlw_cldprlw
This module contains cloud property coefficients.
Module_radlw_kgb01
This module sets up absorption coefficients for band 01: 10-250 cm-1 (low - h2o; high - h2o)
Module_radlw_kgb02
This module sets up absorption coefficients for band 02: 250-500 cm-1 (low - h2o; high - h2o)
Module_radlw_kgb03
This module sets up absorption coefficients for band 03: 500-630 cm-1 (low - h2o, co2; high - h2o, co2)
Module_radlw_kgb04
This module sets up absorption coefficients for band 04: 630-700 cm-1 (low - h2o, co2; high - co2, o3)
Module_radlw_kgb05
This module sets up absorption coefficients for band 05: 700-820 cm-1 (low - h2o, co2; high - co2, o3)
Module_radlw_kgb06
This module sets up absorption coefficients for band 06: 820-980 cm-1 (low - h2o; high - /)
Module_radlw_kgb07
This module sets up absorption coefficients for band 07: 980-1080 cm-1 (low - h2o, o3; high - o3)
Module_radlw_kgb08
This module sets up absorption coefficients for band 08: 1080-1180 cm-1 (low - h2o; high - o3)
Module_radlw_kgb09
This module sets up absorption coefficients for band 09: 1180-1390 cm-1 (low - h2o, ch4; high - ch4)
Module_radlw_kgb10
This module sets up absorption coefficients for band 10: 1390-1480 cm-1 (low - h2o; high - h2o)
Module_radlw_kgb11
This module sets up absorption coefficients for band 11: 1480-1800 cm-1 (low - h2o; high - h2o)
Module_radlw_kgb12
This module sets up absorption coefficients for band 12: 1800-2080 cm-1 (low - h2o, co2; high - /)
Module_radlw_kgb13
This module sets up absorption coefficients for band 13: 2080-2250 cm-1 (low - h2o, n2o; high - /)
Module_radlw_kgb14
This module sets up absorption coefficients for band 14: 2250-2380 cm-1 (low - co2; high - co2)
Module_radlw_kgb15
This module sets up absorption coefficients for band 15: 2380-2600 cm-1 (low - n2o, co2; high - /)
Module_radlw_kgb16
This module sets up absorption coefficients for band 16: 2600-3000 cm-1 (low - h2o, ch4; high - /)
Module_radlw_parameters
This module contains LW band parameters set up.
Module_radlw_ref
This module contains reference temperature and pressure.
Modules
module module_radlw_avplank
module module_radlw_ref
module module_radlw_cldprlw
module module_radlw_kgb01
module module_radlw_kgb02
module module_radlw_kgb03
module module_radlw_kgb04
module module_radlw_kgb05
module module_radlw_kgb06
module module_radlw_kgb07
module module_radlw_kgb08
module module_radlw_kgb09
module module_radlw_kgb10
module module_radlw_kgb11
module module_radlw_kgb12
module module_radlw_kgb13
module module_radlw_kgb14
module module_radlw_kgb15
module module_radlw_kgb16
module module_radlw_main
module module_radlw_parameters
Data Types
type module_radlw_parameters::sfcflw_type
define type construct for radiation fluxes at surface
type module_radlw_parameters::proflw_type
define type construct for optional radiation flux profiles
Functions/Subroutines
subroutine, public module_radlw_main::rlwinit
This subroutine performs calculations necessary for the initialization of the longwave model. lookup tables are computed for use in the lw radiative transfer, and input absorption coefficient data for each spectral band are reduced from 256 g-point intervals to 140.
subroutine module_radlw_main::mcica_subcol
This suroutine computes sub-colum cloud profile flag array.
subroutine module_radlw_main::setcoef
This subroutine computes various coefficients needed in radiative transfer calculations.
subroutine module_radlw_main::rtrn
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds assumed as randomly overlaping in a vertical column.
subroutine module_radlw_main::taumol
This subroutine contains optical depths developed for the rapid radiative transfer model.
subroutine taugb01
Variables
real(kind=kind_phys), dimension(59) module_radlw_ref::preflog
real(kind=kind_phys), dimension(59) module_radlw_ref::tref
real(kind=kind_phys), dimension(7, 59) module_radlw_ref::chi_mls
real(kind=kind_phys), parameter module_radlw_cldprlw::absrain = 0.33e-3
absrain is the rain drop absorption coefficient (m2/g)
real(kind=kind_phys), parameter module_radlw_cldprlw::abssnow0 = 1.5
abssnow0 is the snow flake absorption coefficient (micron), fu coeff
real(kind=kind_phys), parameter module_radlw_cldprlw::abssnow1 = 2.34e-3
abssnow1 is the snow flake absorption coefficient (m2/g), ncar coeff
real(kind=kind_phys), dimension(58, nbands) module_radlw_cldprlw::absliq1
Hu and Stamnes method. the liquid water absorption coefficients are listed for a range of effective radii from 2.5 to 59.5 microns in increments of 1.0 micron.
real(kind=kind_phys), dimension(2) module_radlw_cldprlw::absice0
for iflagice = 2 or 3, absice0 are the ice water absorption coefficients used for large ice partical size such as refice > 131 microns.
real(kind=kind_phys), dimension(2, 5) module_radlw_cldprlw::absice1
for iflagice = 1, absice1 are the ice water absorption coefficients used for ebert and curry method
real(kind=kind_phys), dimension(43, nbands) module_radlw_cldprlw::absice2
for iflagice =2, absice2 are the ice water absorption coefficients used for streamer method. the absorption coefficients are listed for a range of effective radii from 5.0 to 131.0 microns in increments of 3.0 microns. spherical ice particle parameterization absorption units (abs coef/iwc): [(m^-1)/(g m^-3)]
real(kind=kind_phys), dimension(46, nbands) module_radlw_cldprlw::absice3
for iflagice = 3, absice3 are the ice water absorption coefficients used for fu parameterization. particle size 5 - 140 micron in increments of 3 microns. units = m2/g. hexagonal ice particle parameterization absorption units (abs coef/iwc): [(m^-1)/(g m^-3)]
integer, public module_radlw_kgb01::msb01
integer, public module_radlw_kgb01::msf01
integer, public module_radlw_kgb01::mfr01
integer, public module_radlw_kgb01::mmn01
real(kind=kind_phys), dimension(ng01, msa01), public module_radlw_kgb01::absa
real(kind=kind_phys), dimension(ng01, msb01), public module_radlw_kgb01::absb
real(kind=kind_phys), dimension(ng01, msf01), public module_radlw_kgb01::selfref
real(kind=kind_phys), dimension(ng01, mfr01), public module_radlw_kgb01::forref
real(kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefa
real(kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefb
real(kind=kind_phys), dimension(ng01, mmn01), public module_radlw_kgb01::ka_mn2
real(kind=kind_phys), dimension(ng01, mmn01), public module_radlw_kgb01::kb_mn2
integer, public module_radlw_kgb02::msb02
integer, public module_radlw_kgb02::msf02
integer, public module_radlw_kgb02::mfr02
real(kind=kind_phys), dimension(ng02, msa02), public module_radlw_kgb02::absa
real(kind=kind_phys), dimension(ng02, msb02), public module_radlw_kgb02::absb
real(kind=kind_phys), dimension(ng02, msf02), public module_radlw_kgb02::selfref
real(kind=kind_phys), dimension(ng02, mfr02), public module_radlw_kgb02::forref
real(kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefa
real(kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefb
integer, public module_radlw_kgb03::msb03
integer, public module_radlw_kgb03::msf03
integer, public module_radlw_kgb03::mfr03
integer, public module_radlw_kgb03::maf03
integer, public module_radlw_kgb03::mbf03
integer, public module_radlw_kgb03::mmn03
real(kind=kind_phys), dimension(ng03, mfr03), public module_radlw_kgb03::forref
real(kind=kind_phys), dimension(ng03, msa03), public module_radlw_kgb03::absa
real(kind=kind_phys), dimension(ng03, msb03), public module_radlw_kgb03::absb
real(kind=kind_phys), dimension(ng03, msf03), public module_radlw_kgb03::selfref
real(kind=kind_phys), dimension(ng03, maf03), public module_radlw_kgb03::fracrefa
real(kind=kind_phys), dimension(ng03, mbf03), public module_radlw_kgb03::fracrefb
real(kind=kind_phys), dimension(ng03, maf03, mmn03), public module_radlw_kgb03::ka_mn2o
real(kind=kind_phys), dimension(ng03, mbf03, mmn03), public module_radlw_kgb03::kb_mn2o
integer, public module_radlw_kgb04::msb04
integer, public module_radlw_kgb04::msf04
integer, public module_radlw_kgb04::mfr04
integer, public module_radlw_kgb04::maf04
integer, public module_radlw_kgb04::mbf04
real(kind=kind_phys), dimension(ng04, mfr04), public module_radlw_kgb04::forref
real(kind=kind_phys), dimension(ng04, msa04), public module_radlw_kgb04::absa
real(kind=kind_phys), dimension(ng04, msb04), public module_radlw_kgb04::absb
real(kind=kind_phys), dimension(ng04, msf04), public module_radlw_kgb04::selfref
real(kind=kind_phys), dimension(ng04, maf04), public module_radlw_kgb04::fracrefa
real(kind=kind_phys), dimension(ng04, mbf04), public module_radlw_kgb04::fracrefb
integer, public module_radlw_kgb05::msb05
integer, public module_radlw_kgb05::msf05
integer, public module_radlw_kgb05::mfr05
integer, public module_radlw_kgb05::maf05
integer, public module_radlw_kgb05::mbf05
integer, public module_radlw_kgb05::mmo05
real(kind=kind_phys), dimension(ng05, mfr05), public module_radlw_kgb05::forref
real(kind=kind_phys), dimension(ng05, msa05), public module_radlw_kgb05::absa
real(kind=kind_phys), dimension(ng05, msb05), public module_radlw_kgb05::absb
real(kind=kind_phys), dimension(ng05, msf05), public module_radlw_kgb05::selfref
real(kind=kind_phys), dimension(ng05, maf05), public module_radlw_kgb05::fracrefa
real(kind=kind_phys), dimension(ng05, mbf05), public module_radlw_kgb05::fracrefb
real(kind=kind_phys), dimension(ng05, maf05, mmo05), public module_radlw_kgb05::ka_mo3
real(kind=kind_phys), dimension(ng05), public module_radlw_kgb05::ccl4
integer, public module_radlw_kgb06::msf06
integer, public module_radlw_kgb06::mfr06
integer, public module_radlw_kgb06::mmc06
real(kind=kind_phys), dimension(ng06, mfr06), public module_radlw_kgb06::forref
real(kind=kind_phys), dimension(ng06, msa06), public module_radlw_kgb06::absa
real(kind=kind_phys), dimension(ng06), public module_radlw_kgb06::fracrefa
real(kind=kind_phys), dimension(ng06, msf06), public module_radlw_kgb06::selfref
real(kind=kind_phys), dimension(ng06, mmc06), public module_radlw_kgb06::ka_mco2
real(kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc11adj
real(kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc12
integer, public module_radlw_kgb07::msb07
integer, public module_radlw_kgb07::msf07
integer, public module_radlw_kgb07::mfr07
integer, public module_radlw_kgb07::maf07
integer, public module_radlw_kgb07::mmc07
real(kind=kind_phys), dimension(ng07, mfr07), public module_radlw_kgb07::forref
real(kind=kind_phys), dimension(ng07, msa07), public module_radlw_kgb07::absa
real(kind=kind_phys), dimension(ng07, msb07), public module_radlw_kgb07::absb
real(kind=kind_phys), dimension(ng07, msf07), public module_radlw_kgb07::selfref
real(kind=kind_phys), dimension(ng07, maf07), public module_radlw_kgb07::fracrefa
real(kind=kind_phys), dimension(ng07), public module_radlw_kgb07::fracrefb
real(kind=kind_phys), dimension(ng07, maf07, mmc07), public module_radlw_kgb07::ka_mco2
real(kind=kind_phys), dimension(ng07, mmc07), public module_radlw_kgb07::kb_mco2
integer, public module_radlw_kgb08::msb08
integer, public module_radlw_kgb08::msf08
integer, public module_radlw_kgb08::mfr08
integer, public module_radlw_kgb08::mmc08
real(kind=kind_phys), dimension(ng08, mfr08), public module_radlw_kgb08::forref
real(kind=kind_phys), dimension(ng08, msa08), public module_radlw_kgb08::absa
real(kind=kind_phys), dimension(ng08, msb08), public module_radlw_kgb08::absb
real(kind=kind_phys), dimension(ng08, msf08), public module_radlw_kgb08::selfref
real(kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefa
real(kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefb
real(kind=kind_phys), dimension(ng08, mmc08), public module_radlw_kgb08::ka_mo3
real(kind=kind_phys), dimension(ng08, mmc08), public module_radlw_kgb08::ka_mco2
real(kind=kind_phys), dimension(ng08, mmc08), public module_radlw_kgb08::kb_mco2
real(kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc12
real(kind=kind_phys), dimension(ng08, mmc08), public module_radlw_kgb08::ka_mn2o
real(kind=kind_phys), dimension(ng08, mmc08), public module_radlw_kgb08::kb_mn2o
real(kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc22adj
integer, public module_radlw_kgb09::msb09
integer, public module_radlw_kgb09::msf09
integer, public module_radlw_kgb09::mfr09
integer, public module_radlw_kgb09::maf09
integer, public module_radlw_kgb09::mmn09
real(kind=kind_phys), dimension(ng09, mfr09), public module_radlw_kgb09::forref
real(kind=kind_phys), dimension(ng09, msa09), public module_radlw_kgb09::absa
real(kind=kind_phys), dimension(ng09, msb09), public module_radlw_kgb09::absb
real(kind=kind_phys), dimension(ng09, msf09), public module_radlw_kgb09::selfref
real(kind=kind_phys), dimension(ng09, maf09), public module_radlw_kgb09::fracrefa
real(kind=kind_phys), dimension(ng09), public module_radlw_kgb09::fracrefb
real(kind=kind_phys), dimension(ng09, maf09, mmn09), public module_radlw_kgb09::ka_mn2o
real(kind=kind_phys), dimension(ng09, mmn09), public module_radlw_kgb09::kb_mn2o
integer, public module_radlw_kgb10::msb10
integer, public module_radlw_kgb10::msf10
integer, public module_radlw_kgb10::mfr10
real(kind=kind_phys), dimension(ng10, msa10), public module_radlw_kgb10::absa
real(kind=kind_phys), dimension(ng10, msb10), public module_radlw_kgb10::absb
real(kind=kind_phys), dimension(ng10, msf10), public module_radlw_kgb10::selfref
real(kind=kind_phys), dimension(ng10, mfr10), public module_radlw_kgb10::forref
real(kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefa
real(kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefb
integer, public module_radlw_kgb11::msb11
integer, public module_radlw_kgb11::msf11
integer, public module_radlw_kgb11::mfr11
integer, public module_radlw_kgb11::mmo11
real(kind=kind_phys), dimension(ng11, msa11), public module_radlw_kgb11::absa
real(kind=kind_phys), dimension(ng11, msb11), public module_radlw_kgb11::absb
real(kind=kind_phys), dimension(ng11, msf11), public module_radlw_kgb11::selfref
real(kind=kind_phys), dimension(ng11, mfr11), public module_radlw_kgb11::forref
real(kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefa
real(kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefb
real(kind=kind_phys), dimension(ng11, mmo11), public module_radlw_kgb11::ka_mo2
real(kind=kind_phys), dimension(ng11, mmo11), public module_radlw_kgb11::kb_mo2
integer, public module_radlw_kgb12::msf12
integer, public module_radlw_kgb12::mfr12
integer, public module_radlw_kgb12::maf12
real(kind=kind_phys), dimension(ng12, msa12), public module_radlw_kgb12::absa
real(kind=kind_phys), dimension(ng12, mfr12), public module_radlw_kgb12::forref
real(kind=kind_phys), dimension(ng12, msf12), public module_radlw_kgb12::selfref
real(kind=kind_phys), dimension(ng12, maf12), public module_radlw_kgb12::fracrefa
integer, public module_radlw_kgb13::msf13
integer, public module_radlw_kgb13::mfr13
integer, public module_radlw_kgb13::maf13
integer, public module_radlw_kgb13::mmo13
real(kind=kind_phys), dimension(ng13, msa13), public module_radlw_kgb13::absa
real(kind=kind_phys), dimension(ng13, mfr13), public module_radlw_kgb13::forref
real(kind=kind_phys), dimension(ng13, msf13), public module_radlw_kgb13::selfref
real(kind=kind_phys), dimension(ng13, maf13), public module_radlw_kgb13::fracrefa
real(kind=kind_phys), dimension(ng13), public module_radlw_kgb13::fracrefb
real(kind=kind_phys), dimension(ng13, maf13, mmo13), public module_radlw_kgb13::ka_mco2
real(kind=kind_phys), dimension(ng13, maf13, mmo13), public module_radlw_kgb13::ka_mco
real(kind=kind_phys), dimension(ng13, mmo13), public module_radlw_kgb13::kb_mo3
integer, public module_radlw_kgb14::msb14
integer, public module_radlw_kgb14::msf14
integer, public module_radlw_kgb14::mfr14
real(kind=kind_phys), dimension(ng14, msa14), public module_radlw_kgb14::absa
real(kind=kind_phys), dimension(ng14, msb14), public module_radlw_kgb14::absb
real(kind=kind_phys), dimension(ng14, msf14), public module_radlw_kgb14::selfref
real(kind=kind_phys), dimension(ng14, mfr14), public module_radlw_kgb14::forref
real(kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefa
real(kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefb
integer, public module_radlw_kgb15::msf15
integer, public module_radlw_kgb15::mfr15
integer, public module_radlw_kgb15::maf15
integer, public module_radlw_kgb15::mmn15
real(kind=kind_phys), dimension(ng15, msa15), public module_radlw_kgb15::absa
real(kind=kind_phys), dimension(ng15, mfr15), public module_radlw_kgb15::forref
real(kind=kind_phys), dimension(ng15, msf15), public module_radlw_kgb15::selfref
real(kind=kind_phys), dimension(ng15, maf15), public module_radlw_kgb15::fracrefa
real(kind=kind_phys), dimension(ng15, maf15, mmn15), public module_radlw_kgb15::ka_mn2
integer, public module_radlw_kgb16::msb16
integer, public module_radlw_kgb16::msf16
integer, public module_radlw_kgb16::mfr16
integer, public module_radlw_kgb16::maf16
real(kind=kind_phys), dimension(ng16, mfr16), public module_radlw_kgb16::forref
real(kind=kind_phys), dimension(ng16, msa16), public module_radlw_kgb16::absa
real(kind=kind_phys), dimension(ng16, msb16), public module_radlw_kgb16::absb
real(kind=kind_phys), dimension(ng16, msf16), public module_radlw_kgb16::selfref
real(kind=kind_phys), dimension(ng16, maf16), public module_radlw_kgb16::fracrefa
real(kind=kind_phys), dimension(ng16), public module_radlw_kgb16::fracrefb
real(kind=kind_phys), parameter module_radlw_main::eps = 1.0e-6
real(kind=kind_phys), parameter module_radlw_main::oneminus = 1.0-eps
real(kind=kind_phys), parameter module_radlw_main::cldmin = 1.0e-80
real(kind=kind_phys), parameter module_radlw_main::bpade = 1.0/0.278
real(kind=kind_phys), parameter module_radlw_main::stpfac = 296.0/1013.0
real(kind=kind_phys), parameter module_radlw_main::wtdiff = 0.5
real(kind=kind_phys), parameter module_radlw_main::tblint = ntbl
real(kind=kind_phys), parameter module_radlw_main::f_zero = 0.0
real(kind=kind_phys), parameter module_radlw_main::f_one = 1.0
real(kind=kind_phys), parameter module_radlw_main::amdw = con_amd/con_amw
real(kind=kind_phys), parameter module_radlw_main::amdo3 = con_amd/con_amo3
integer, dimension(nbands) module_radlw_main::nspa
integer, dimension(nbands) module_radlw_main::nspb
real(kind=kind_phys), dimension(nbands) module_radlw_main::a0
real(kind=kind_phys), dimension(nbands) module_radlw_main::a1
real(kind=kind_phys), dimension(nbands) module_radlw_main::a2
logical module_radlw_main::lhlwb = .false.
logical module_radlw_main::lhlw0 = .false.
logical module_radlw_main::lflxprf = .false.
real(kind=kind_phys) module_radlw_main::fluxfac
real(kind=kind_phys) module_radlw_main::heatfac
real(kind=kind_phys), dimension(nbands) module_radlw_main::semiss0
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::tau_tbl
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::exp_tbl
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::tfn_tbl
integer, parameter module_radlw_main::ipsdlw0 = ngptlw
real(kind=kind_phys) module_radlw_parameters::topflw_type::upfxc
total sky upward flux at toa
real(kind=kind_phys) module_radlw_parameters::topflw_type::upfx0
clear sky upward flux at toa
real(kind=kind_phys) module_radlw_parameters::sfcflw_type::upfxc
total sky upward flux at sfc
real(kind=kind_phys) module_radlw_parameters::sfcflw_type::upfx0
clear sky upward flux at sfc
real(kind=kind_phys) module_radlw_parameters::sfcflw_type::dnfxc
total sky downward flux at sfc
real(kind=kind_phys) module_radlw_parameters::sfcflw_type::dnfx0
clear sky downward flux at sfc
real(kind=kind_phys) module_radlw_parameters::proflw_type::upfxc
level up flux for total sky
real(kind=kind_phys) module_radlw_parameters::proflw_type::dnfxc
level dn flux for total sky
real(kind=kind_phys) module_radlw_parameters::proflw_type::upfx0
level up flux fro clear sky
real(kind=kind_phys) module_radlw_parameters::proflw_type::dnfx0
level dn flux for clear sky
integer, parameter module_radlw_parameters::nbands = 16
num of total spectral bands
integer, parameter module_radlw_parameters::ngptlw = 140
num of total g-points
integer, parameter module_radlw_parameters::ntbl = 10000
lookup table dimension
integer, parameter module_radlw_parameters::maxgas = 7
max num of absorbing gases
integer, parameter module_radlw_parameters::maxxsec = 4
num of halocarbon gasees
integer, parameter module_radlw_parameters::nrates = 6
num of ref rates of binary species
integer, parameter module_radlw_parameters::nplnk = 181
dim for plank function table
integer, parameter module_radlw_parameters::nbdlw = NBANDS
integer module_radlw_parameters::ng01
integer module_radlw_parameters::ng02
integer module_radlw_parameters::ng03
integer module_radlw_parameters::ng04
integer module_radlw_parameters::ng05
integer module_radlw_parameters::ng06
integer module_radlw_parameters::ng07
integer module_radlw_parameters::ng08
integer module_radlw_parameters::ng09
integer module_radlw_parameters::ng10
integer module_radlw_parameters::ng11
integer module_radlw_parameters::ng12
integer module_radlw_parameters::ng13
integer module_radlw_parameters::ng14
integer module_radlw_parameters::ng15
integer module_radlw_parameters::ng16
integer module_radlw_parameters::ns01
integer module_radlw_parameters::ns02
integer module_radlw_parameters::ns03
integer module_radlw_parameters::ns04
integer module_radlw_parameters::ns05
integer module_radlw_parameters::ns06
integer module_radlw_parameters::ns07
integer module_radlw_parameters::ns08
integer module_radlw_parameters::ns09
integer module_radlw_parameters::ns10
integer module_radlw_parameters::ns11
integer module_radlw_parameters::ns12
integer module_radlw_parameters::ns13
integer module_radlw_parameters::ns14
integer module_radlw_parameters::ns15
integer module_radlw_parameters::ns16
integer, dimension(ngptlw) module_radlw_parameters::ngb
real(kind=kind_phys), dimension(nbands) module_radlw_parameters::wvnlw1
real(kind=kind_phys), dimension(nbands) module_radlw_parameters::wvnlw2
real(kind=kind_phys), dimension(nbands) module_radlw_parameters::delwave
subroutine, public module_radlw_main::lwrad
This subroutine is the main lw radiation routine.
subroutine module_radlw_main::cldprop
This subroutine computes the cloud optical depth(s) for each cloudy layer and g-point interval.
subroutine module_radlw_main::rtrnmr
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds are assumed as in maximum-randomly overlaping in a vertical column.
subroutine module_radlw_main::rtrnmc
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere.Clouds are treated with the mcica stochastic approach.
Detailed Description
Data Type Documentation
type module_radlw_parameters::sfcflw_type
Definition at line 89 of file radlw_param.f.
Class Members
real(kind=kind_phys) dnfx0 clear sky downward flux at sfc
real(kind=kind_phys) dnfxc total sky downward flux at sfc
real(kind=kind_phys) upfx0 clear sky upward flux at sfc
real(kind=kind_phys) upfxc total sky upward flux at sfc
type module_radlw_parameters::proflw_type
Definition at line 103 of file radlw_param.f.
Class Members
real(kind=kind_phys) dnfx0 level dn flux for clear sky
real(kind=kind_phys) dnfxc level dn flux for total sky
real(kind=kind_phys) upfx0 level up flux fro clear sky
real(kind=kind_phys) upfxc level up flux for total sky
Function/Subroutine Documentation
subroutine module_radlw_main::cldprop () private
Parameters
[in] cfrac real, (0:nlp1), layer cloud fraction
..... for ilwcliq > 0 (prognostic cloud scheme) - - -
[in] cliqp real, (nlay), layer in-cloud liq water path (\(g/m^2\))
[in] reliq real, (nlay), mean eff radius for liq cloud (micron)
[in] cicep real, (nlay), layer in-cloud ice water path (\(g/m^2\))
[in] reice real, (nlay), mean eff radius for ice cloud (micron)
[in] cdat1 real, (nlay), layer rain drop water path (\(g/m^2\))
[in] cdat2 real, (nlay), effective radius for rain drop (micron)
[in] cdat3 real, (nlay), layer snow flake water path(\(g/m^2\))
[in] cdat4 real, (nlay), mean eff radius for snow flake(micron)
..... for ilwcliq = 0 (diagnostic cloud scheme) - - -
[in] cliqp real, (nlay), not used
[in] cicep real, (nlay), not used
[in] reliq real, (nlay), not used
[in] reice real, (nlay), not used
[in] cdat1 real, (nlay), layer cloud optical depth
[in] cdat2 real, (nlay), layer cloud single scattering albedo
[in] cdat3 real, (nlay), layer cloud asymmetry factor
[in] cdat4 real, (nlay), optional use
[in] nlay integer, 1, number of layer number
[in] nlp1 integer, 1, number of veritcal levels
[in] ipseed integer, 1, permutation seed for generating random numbers (isubclw>0)
[out] cldfmc real,(ngptlw,nlay), cloud fraction for each sub-column
[out] taucld real,(nbands,nlay), cloud optical depth for bands (non-mcica)
General Algorithm
Compute cloud radiative properties for a cloudy column
- Compute cloud radiative properties for rain and snow (tauran,tausnw)
- Calculation of absorption coefficients due to water clouds(tauliq)
- Calculation of absorption coefficients due to ice clouds (tauice).
- For prognostic cloud scheme: sum up the cloud optical property:
\(taucld=tauice+tauliq+tauran+tausnw \)
if physparam::isubclw > 0, call mcica_subcol() to distribute cloud properties to each g-point.
Definition at line 1474 of file radlw_main.f.
References module_radlw_cldprlw::absice1, module_radlw_cldprlw::absice2, module_radlw_cldprlw::absice3, module_radlw_cldprlw::absliq1, module_radlw_cldprlw::absrain, module_radlw_cldprlw::abssnow0, cldmin, f_one, f_zero, module_radlw_cldprlw::ipat, mcica_subcol(), module_radlw_parameters::nbands, and module_radlw_parameters::ngptlw.
Referenced by lwrad().
subroutine, public module_radlw_main::lwrad ()
Parameters
[in] plyr (npts,nlay),model layer mean pressure in mb
[in] plvl (npts,nlp1),model interface pressure in mb
[in] tlyr (npts,nlay),model layer mean temperature in K
[in] tlvl (npts,nlp1),model interface temperature in K
[in] qlyr (npts,nlay),layer specific humidity in gm/gm *see inside
[in] olyr (npts,nlay),layer ozone concentration in gm/gm *see inside
[in] gasvmr (npts,nlay,:),atmospheric gases amount:(check module_radiation_gases for definition)
(:,:,1) - co2 volume mixing ratio
(:,:,2) - n2o volume mixing ratio
(:,:,3) - ch4 volume mixing ratio
(:,:,4) - o2 volume mixing ratio
(:,:,5) - co volume mixing ratio
(:,:,6) - cfc11 volume mixing ratio
(:,:,7) - cfc12 volume mixing ratio
(:,:,8) - cfc22 volume mixing ratio
(:,:,9) - ccl4 volume mixing ratio
[in] clouds (npts,nlay,:),layer cloud profile(check module_radiation_clouds for definition)
— for ilwcliq > 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer in-cloud liq water path (\(g/m^2 \))
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer in-cloud ice water path (\(g/m^2 \))
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path (\(g/m^2 \))
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path (\(g/m^2 \))
(:,:,9) - mean eff radius for snow flake (micron)
— for ilwcliq = 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud optical depth
(:,:,3) - layer cloud single scattering albedo
(:,:,4) - layer cloud asymmetry factor
[in] icseed (npts),auxiliary special cloud related array.when module variable isubclw=2, it provides permutation seed for each column profile that are used for generating random numbers.when isubclw /=2, it will not be used.
[in] aerosols (npts,nlay,nbdsw,:),aerosol optical properties (check module_radiation_aerosols for definition)
(:,:,:,1) - optical depth
(:,:,:,2) - single scattering albedo
(:,:,:,3) - asymmetry parameter
[in] sfemis (npts),surface emissivity
[in] sfgtmp (npts),surface ground temperature in K
[in] npts total number of horizontal points
[in] nlay,nlp1 total number of vertical layers, levels
[in] lprnt cntl flag for diagnostic print out
[out] hlwc (npts,nlay),total sky heating rate in k/day or k/sec
[out] topflx (npts),radiation fluxes at top, components (check module_radlw_parameters for definition)
upfxc - total sky upward flux at top (\(w/m^2 \))
upfx0 - clear sky upward flux at top (\(w/m^2 \))
[out] sfcflx (npts),radiation fluxes at sfc, components (check module_radlw_parameters for definition)
upfxc - total sky upward flux at sfc (\(w/m^2 \))
dnfxc - total sky downward flux at sfc (\(w/m^2 \))
upfx0 - clear sky upward flux at sfc (\(w/m^2 \))
dnfx0 - clear sky downward flux at sfc (\(w/m^2 \))
Optional:
[out] hlwb (npts,nlay,nbands),spectral band total sky heating rates
[out] hlw0 (npts,nlay),clear sky heating rates (k/sec or k/day)
[out] flxprf (npts,nlp1),level radiation fluxes (\(w/m^2 \)), components (check module_radlw_parameters for definition)
dnfxc - total sky downward flux
upfxc - total sky upward flux
dnfx0 - clear sky downward flux
upfx0 - clear sky upward flux
General Algorithm
Change random number seed value for each radiation invocation (isubclw =1 or 2)
Read surface emissivity
Prepare atmospheric profile for use in rrtm
Set absorber amount for h2o, co2, and o3
Set up column amount for rare gases n2o,ch4,o2,co,ccl4,cf11,cf12,cf22, convert from volume mixing ratio to molec/cm2 based on coldry (scaled to 1.0e-20).
Set aerosol optical properties
Read cloud optical properties
Compute precipitable water vapor for diffusivity angle adjustments
Compute column amount for broadening gases
Compute diffusivity angle adjustments
For cloudy atmosphere, call cldprop() to set cloud optical properties
Calling setcoef() to compute various coefficients needed in radiative transfer calculations.
Call taumol to calculte the gaseous optical depths and Plank fractions for each longwave spectral band.
Call the radiative transfer routine based on cloud scheme selection. compute the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere.
- call rtrn(): clouds are assumed as randomly overlaping in a vertical column
- call rtrnmr(): clouds are assumed as in maximum-randomly overlaping in a vertical column;
- call rtrnmc(): clouds are treated with the mcica stochastic approach.
Save outputs
Definition at line 421 of file radlw_main.f.
References a0, a1, a2, amdo3, amdw, cldprop(), eps, f_one, f_zero, ipsdlw0, lflxprf, lhlw0, lhlwb, module_radlw_parameters::maxgas, module_radlw_parameters::nbands, rtrn(), rtrnmc(), rtrnmr(), semiss0, setcoef(), and taumol().
Referenced by module_radiation_driver::grrad().
subroutine module_radlw_main::mcica_subcol () private
Parameters
[in] cldf real, (nlay), layer cloud fraction
[in] nlay integer, 1, number of model vertical layers
[in] ipseed integer, 1, permute seed for random num generator
[out] lcloudy logical, (ngptlw,nlay),sub-colum cloud profile flag array
External Module Variables
physparam::iovrlw - control flag for cloud overlapping method
=0:random; =1:maximum/random: =2:maximum
Definition at line 1782 of file radlw_main.f.
References f_one, and module_radlw_parameters::ngptlw.
Referenced by cldprop().
subroutine, public module_radlw_main::rlwinit ()
Parameters
[in] me integer, print control for parallel process
[out] NONE
External Module Variables
physparam::ilwrate - heating rate unit selections
=1: output in k/day
=2: output in k/second
physparam::ilwrgas - control flag for rare gases (ch4,n2o,o2,cfcs, etc.)
=0: do not include rare gases
>0: include all rare gases
physparam::ilwcliq - liquid cloud optical properties contrl flag
=0: input cloud opt depth from diagnostic scheme
>0: input cwp,rew, and other cloud content parameters
physparam::isubclw - sub-column cloud approximation control flag
=0: no sub-col cld treatment, use grid-mean cld quantities
=1: mcica sub-col, prescribed seeds to get random numbers
=2: mcica sub-col, providing array icseed for random numbers
physparam::icldflg - cloud scheme control flag
=0: diagnostic scheme gives cloud tau, omiga, and g.
=1: prognostic scheme gives cloud liq/ice path, etc.
physparam::iovrlw - clouds vertical overlapping control flag
=0: random overlapping clouds
=1: maximum/random overlapping clouds
=2: maximum overlap cloud (isubcol>0 only)
Definition at line 1250 of file radlw_main.f.
References bpade, exp_tbl, f_one, f_zero, fluxfac, heatfac, module_radlw_parameters::ntbl, semiss0, tau_tbl, tfn_tbl, and vtaglw.
Referenced by module_radiation_driver::radinit().
subroutine module_radlw_main::rtrn () private
Original Code Description: this program calculates the upward fluxes, downward fluxes, and heating rates for an arbitrary clear or cloudy atmosphere. The input to this program is the atmospheric profile, all Planck function information, and the cloud fraction by layer. A variable diffusivity angle (secdif) is used for the angle integration. Bands 2-3 and 5-9 use a value for secdif that varies from 1.50 to 1.80 as a function of the column water vapor, and other bands use a value of 1.66. The gaussian weight appropriate to this angle (wtdiff =0.5) is applied here. Note that use of the emissivity angle for the flux integration can cause errors of 1 to 4 \(W/m^2\) within cloudy layers. Clouds are treated with a random cloud overlap method.
Parameters
[in] semiss real,(nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfrc real, (0:nlp1), layer cloud fraction
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux \((w/m^2)\)
[out] totdflux real, (0:nlay), total sky downward flux \((w/m^2)\)
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux \((w/m^2)\)
[out] totdclfl real, (0:nlay), clear sky downward flux \((w/m^2)\)
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay,nbands), spectral band lw heating rate (k/day)
General Algorithm
Downward radiative transfer loop
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop
Process longwave output from band for total and clear streams. Calculate upward, downward, and net flux.
Definition at line 2257 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::rtrnmc () private
Parameters
[in] semiss real, (nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfmc real, (ngptlw,nlay), layer cloud fraction (sub-column)
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux \((w/m^2)\)
[out] totdflux real, (0:nlay), total sky downward flux \((w/m^2)\)
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux \((w/m^2)\)
[out] totdclfl real, (0:nlay), clear sky downward flux \((w/m^2)\)
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay,nbands), spectral band lw heating rate (k/day)
General Algorithm
Downward radiative transfer loop.
- Clear sky, gases contribution
- Total sky, gases+clouds contribution
- Cloudy layer
- Total sky radiance
- Clear sky radiance
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop
- Compute total sky radiance
- Compute clear sky radiance
Process longwave output from band for total and clear streams. Calculate upward, downward, and net flux.
Definition at line 3240 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::rtrnmr () private
Parameters
[in] semiss real, (nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfrc real, (0:nlp1), layer cloud fraction
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands*0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands*0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux (\(w/m^2\))
[out] totdflux real, (0:nlay), total sky downward flux (\(w/m^2\))
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux (\(w/m^2\))
[out] totdclfl real, (0:nlay), clear sky downward flux (\(w/m^2\))
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay*nbands), spectral band lw heating rate (k/day)
General Algorithm
Setup maximum/random cloud overlap
Initialize for radiative transfer
Downward radiative transfer loop:
cloudy layer
total sky radiance
clear sky radiance
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop:
cloudy layer radiance
total sky radiance
clear sky radiance
Process longwave output from band for total and clear streams. calculate upward, downward, and net flux.
Definition at line 2645 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::setcoef () private
Parameters
[in] pavel real, (nlay), layer pressure (mb)
[in] tavel real, (nlay), layer temperature (K)
[in] tz real, (0:nlay), level(interface) temperatures (K)
[in] stemp real, 1, surface ground temperature (K)
[in] h2ovmr real, (nlay), layer w.v. volumn mixing ratio (kg/kg)
[in] colamt real, (nlay,maxgas), column amounts of absorbing gases. 2nd indices range: 1-maxgas, for watervapor,carbon dioxide, ozone, nitrous oxide, methane,oxigen, carbon monoxide,etc. \((mol/cm^2)\)
[in] coldry real, (nlay), dry air column amount
[in] colbrd real, (nlay), column amount of broadening gases
[in] nlay integer, 1, total number of vertical layers
[in] nlp1 integer, 1, total number of vertical levels
[out] laytrop integer, 1, tropopause layer index (unitless)
[out] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[out] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[out] jp integer, (nlay), indices of lower reference pressure
[out] jt,jt1 integer, (nlay), indices of lower reference temperatures
[out] rfrate real, (nlay,nrates,2), ref ratios of binary species param
(:,m,:)m=1-h2o/co2,2-h2o/o3,3-h2o/n2o,4-h2o/ch4,5-n2o/co2,6-o3/co2
(:,:,n)n=1,2: the rates of ref press at the 2 sides of the layer
[out] facij real, (nlay), factors multiply the reference ks, i,j=0/1 for lower/higher of the 2 appropriate temperatures and altitudes.
[out] selffac real, (nlay), scale factor for w. v. self-continuum equals (w. v. density)/(atmospheric density at 296k and 1013 mb)
[out] selffrac real, (nlay), factor for temperature interpolation of reference w. v. self-continuum data
[out] indself integer, (nlay), index of lower ref temp for selffac
[out] forfac real, (nlay), scale factor for w. v. foreign-continuum
[out] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[out] indfor integer, (nlay), index of lower ref temp for forfac
[out] minorfrac real, (nlay), factor for minor gases
[out] scaleminor,scaleminorn2 real, (nlay), scale factors for minor gases
[out] indminor integer, (nlay), index of lower ref temp for minor gases
Definition at line 1969 of file radlw_main.f.
References module_radlw_ref::chi_mls, module_radlw_parameters::delwave, f_one, f_zero, module_radlw_parameters::nbands, module_radlw_ref::preflog, stpfac, module_radlw_avplank::totplnk, and module_radlw_ref::tref.
Referenced by lwrad().
subroutine taumol::taugb01 () private
Definition at line 3827 of file radlw_main.f.
References module_radlw_kgb01::absa, module_radlw_kgb01::absb, f_one, module_radlw_kgb01::forref, module_radlw_kgb01::fracrefa, module_radlw_kgb01::fracrefb, module_radlw_kgb01::ka_mn2, module_radlw_kgb01::kb_mn2, module_radlw_parameters::ng01, nspa, nspb, and module_radlw_kgb01::selfref.
Referenced by taumol().
subroutine module_radlw_main::taumol () private
This file contains the subroutines taugbn (where n goes from 1 to 16). taugbn calculates the optical depths and planck fractions per g-value and layer for band n.
Parameters
[in] laytrop integer, 1, tropopause layer index (unitless) layer at which switch is made for key species
[in] pavel real, (nlay), layer pressures (mb)
[in] coldry real, (nlay), column amount for dry air \((mol/cm^2)\)
[in] colamt real, (nlay,maxgas), column amounts of h2o, co2, o3, n2o, ch4,o2, co \((mol/cm^2)\)
[in] colbrd real, (nlay), column amount of broadening gases
[in] wx real, (nlay,maxxsec), cross-section amounts \((mol/cm^2)\)
[in] tauaer real, (nbands,nlay), aerosol optical depth
[in] rfrate real, (nlay,nrates,2), reference ratios of binary species parameter
(:,m,:)m=1-h2o/co2,2-h2o/o3,3-h2o/n2o,4-h2o/ch4,5-n2o/co2,6-o3/co2
(:,:,n)n=1,2: the rates of ref press at the 2 sides of the layer
[in] facij real, (nlay), factors multiply the reference ks, i,j of 0/1 for lower/higher of the 2 appropriate temperatures and altitudes
[in] jp integer, (nlay), index of lower reference pressure
[in] jt,jt1 integer, (nlay), indices of lower reference temperatures for pressure levels jp and jp+1, respectively
[in] selffac real, (nlay), scale factor for water vapor self-continuum equals (water vapor density)/(atmospheric density at 296k and 1013 mb)
[in] selffrac real, (nlay), factor for temperature interpolation of reference water vapor self-continuum data
[in] indself integer, (nlay), index of lower reference temperature for the self-continuum interpolation
[in] forfac real, (nlay), scale factor for w. v. foreign-continuum
[in] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[in] indfor integer, (nlay), index of lower reference temperature for the foreign-continuum interpolation
[in] minorfrac real, (nlay), factor for minor gases
[in] scaleminor,scaleminorn2 real, (nlay), scale factors for minor gases
[in] indminor integer, (nlay), index of lower reference temperature for minor gases
[in] nlay integer, 1, total number of layers
[out] fracs real, (ngptlw,nlay), planck fractions
[out] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
Definition at line 3643 of file radlw_main.f.
References module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb12(), taugb13(), taugb14(), taugb15(), and taugb16().
Referenced by lwrad().
Variable Documentation
real (kind=kind_phys), dimension(nbands) module_radlw_main::a0 private
Definition at line 313 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(nbands) module_radlw_main::a1 private
Definition at line 313 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(nbands) module_radlw_main::a2 private
Definition at line 313 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(ng01,msa01), public module_radlw_kgb01::absa
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02,msa02), public module_radlw_kgb02::absa
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,msa03), public module_radlw_kgb03::absa
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,msa04), public module_radlw_kgb04::absa
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,msa05), public module_radlw_kgb05::absa
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng06,msa06), public module_radlw_kgb06::absa
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng07,msa07), public module_radlw_kgb07::absa
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,msa08), public module_radlw_kgb08::absa
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,msa09), public module_radlw_kgb09::absa
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10,msa10), public module_radlw_kgb10::absa
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11,msa11), public module_radlw_kgb11::absa
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng12,msa12), public module_radlw_kgb12::absa
Definition at line 29153 of file radlw_datatb.f.
Referenced by taugb12().
real (kind=kind_phys), dimension(ng13,msa13), public module_radlw_kgb13::absa
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng14,msa14), public module_radlw_kgb14::absa
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng15,msa15), public module_radlw_kgb15::absa
Definition at line 31287 of file radlw_datatb.f.
Referenced by taugb15().
real (kind=kind_phys), dimension(ng16,msa16), public module_radlw_kgb16::absa
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng01,msb01), public module_radlw_kgb01::absb
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02,msb02), public module_radlw_kgb02::absb
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,msb03), public module_radlw_kgb03::absb
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,msb04), public module_radlw_kgb04::absb
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,msb05), public module_radlw_kgb05::absb
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng07,msb07), public module_radlw_kgb07::absb
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,msb08), public module_radlw_kgb08::absb
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,msb09), public module_radlw_kgb09::absb
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10,msb10), public module_radlw_kgb10::absb
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11,msb11), public module_radlw_kgb11::absb
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng14,msb14), public module_radlw_kgb14::absb
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng16,msb16), public module_radlw_kgb16::absb
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(2) module_radlw_cldprlw::absice0
Definition at line 1204 of file radlw_datatb.f.
real (kind=kind_phys), dimension(2,5) module_radlw_cldprlw::absice1
Definition at line 1213 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(43,nbands) module_radlw_cldprlw::absice2
Definition at line 1227 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(46,nbands) module_radlw_cldprlw::absice3
Definition at line 1415 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(58,nbands) module_radlw_cldprlw::absliq1
Definition at line 967 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::absrain = 0.33e-3
Definition at line 943 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::abssnow0 = 1.5
Definition at line 947 of file radlw_datatb.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::abssnow1 = 2.34e-3
Definition at line 950 of file radlw_datatb.f.
real (kind=kind_phys), parameter module_radlw_main::amdo3 = con_amd/con_amo3 private
Definition at line 287 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), parameter module_radlw_main::amdw = con_amd/con_amw private
Definition at line 286 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), parameter module_radlw_main::bpade = 1.0/0.278 private
Definition at line 278 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(ng05), public module_radlw_kgb05::ccl4
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc11adj
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc12
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc12
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc22adj
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(7,59) module_radlw_ref::chi_mls
Definition at line 805 of file radlw_datatb.f.
Referenced by setcoef(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), parameter module_radlw_main::cldmin = 1.0e-80 private
Definition at line 277 of file radlw_main.f.
Referenced by cldprop().
real (kind=kind_phys), dimension(nbands) module_radlw_parameters::delwave
Definition at line 161 of file radlw_param.f.
Referenced by setcoef().
real (kind=kind_phys) module_radlw_parameters::sfcflw_type::dnfx0
Definition at line 97 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::proflw_type::dnfx0
Definition at line 111 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::sfcflw_type::dnfxc
Definition at line 95 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::proflw_type::dnfxc
Definition at line 107 of file radlw_param.f.
real (kind=kind_phys), parameter module_radlw_main::eps = 1.0e-6 private
Definition at line 275 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::exp_tbl private
Definition at line 338 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), parameter module_radlw_main::f_one = 1.0 private
Definition at line 283 of file radlw_main.f.
Referenced by cldprop(), lwrad(), mcica_subcol(), rlwinit(), rtrn(), rtrnmc(), rtrnmr(), setcoef(), taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), parameter module_radlw_main::f_zero = 0.0 private
Definition at line 282 of file radlw_main.f.
Referenced by cldprop(), lwrad(), rlwinit(), rtrn(), rtrnmc(), rtrnmr(), setcoef(), taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys) module_radlw_main::fluxfac private
Definition at line 334 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(ng01,mfr01), public module_radlw_kgb01::forref
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02,mfr02), public module_radlw_kgb02::forref
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,mfr03), public module_radlw_kgb03::forref
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,mfr04), public module_radlw_kgb04::forref
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,mfr05), public module_radlw_kgb05::forref
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng06,mfr06), public module_radlw_kgb06::forref
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng07,mfr07), public module_radlw_kgb07::forref
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,mfr08), public module_radlw_kgb08::forref
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,mfr09), public module_radlw_kgb09::forref
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10,mfr10), public module_radlw_kgb10::forref
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11,mfr11), public module_radlw_kgb11::forref
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng12,mfr12), public module_radlw_kgb12::forref
Definition at line 29153 of file radlw_datatb.f.
Referenced by taugb12().
real (kind=kind_phys), dimension(ng13,mfr13), public module_radlw_kgb13::forref
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng14,mfr14), public module_radlw_kgb14::forref
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng15,mfr15), public module_radlw_kgb15::forref
Definition at line 31287 of file radlw_datatb.f.
Referenced by taugb15().
real (kind=kind_phys), dimension(ng16,mfr16), public module_radlw_kgb16::forref
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefa
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefa
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,maf03), public module_radlw_kgb03::fracrefa
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,maf04), public module_radlw_kgb04::fracrefa
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,maf05), public module_radlw_kgb05::fracrefa
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::fracrefa
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng07,maf07), public module_radlw_kgb07::fracrefa
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefa
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,maf09), public module_radlw_kgb09::fracrefa
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefa
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefa
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng12,maf12), public module_radlw_kgb12::fracrefa
Definition at line 29153 of file radlw_datatb.f.
Referenced by taugb12().
real (kind=kind_phys), dimension(ng13,maf13), public module_radlw_kgb13::fracrefa
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefa
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng15,maf15), public module_radlw_kgb15::fracrefa
Definition at line 31287 of file radlw_datatb.f.
Referenced by taugb15().
real (kind=kind_phys), dimension(ng16,maf16), public module_radlw_kgb16::fracrefa
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefb
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefb
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,mbf03), public module_radlw_kgb03::fracrefb
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,mbf04), public module_radlw_kgb04::fracrefb
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,mbf05), public module_radlw_kgb05::fracrefb
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng07), public module_radlw_kgb07::fracrefb
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefb
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09), public module_radlw_kgb09::fracrefb
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefb
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefb
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng13), public module_radlw_kgb13::fracrefb
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefb
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng16), public module_radlw_kgb16::fracrefb
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys) module_radlw_main::heatfac private
Definition at line 334 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
integer, parameter module_radlw_main::ipsdlw0 = ngptlw private
Definition at line 346 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(ng13,maf13,mmo13), public module_radlw_kgb13::ka_mco
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng06,mmc06), public module_radlw_kgb06::ka_mco2
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng07,maf07,mmc07), public module_radlw_kgb07::ka_mco2
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mco2
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng13,maf13,mmo13), public module_radlw_kgb13::ka_mco2
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng01,mmn01), public module_radlw_kgb01::ka_mn2
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng15,maf15,mmn15), public module_radlw_kgb15::ka_mn2
Definition at line 31287 of file radlw_datatb.f.
Referenced by taugb15().
real (kind=kind_phys), dimension(ng03,maf03,mmn03), public module_radlw_kgb03::ka_mn2o
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mn2o
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,maf09,mmn09), public module_radlw_kgb09::ka_mn2o
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng11,mmo11), public module_radlw_kgb11::ka_mo2
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng05,maf05,mmo05), public module_radlw_kgb05::ka_mo3
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mo3
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng07,mmc07), public module_radlw_kgb07::kb_mco2
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::kb_mco2
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng01,mmn01), public module_radlw_kgb01::kb_mn2
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng03,mbf03,mmn03), public module_radlw_kgb03::kb_mn2o
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::kb_mn2o
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,mmn09), public module_radlw_kgb09::kb_mn2o
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng11,mmo11), public module_radlw_kgb11::kb_mo2
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng13,mmo13), public module_radlw_kgb13::kb_mo3
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
logical module_radlw_main::lflxprf = .false. private
Definition at line 326 of file radlw_main.f.
Referenced by lwrad().
logical module_radlw_main::lhlw0 = .false. private
Definition at line 325 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
logical module_radlw_main::lhlwb = .false. private
Definition at line 324 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
integer, public module_radlw_kgb03::maf03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb04::maf04
Definition at line 10077 of file radlw_datatb.f.
integer, public module_radlw_kgb05::maf05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb07::maf07
Definition at line 21969 of file radlw_datatb.f.
integer, public module_radlw_kgb09::maf09
Definition at line 25381 of file radlw_datatb.f.
integer, public module_radlw_kgb12::maf12
Definition at line 29150 of file radlw_datatb.f.
integer, public module_radlw_kgb13::maf13
Definition at line 30205 of file radlw_datatb.f.
integer, public module_radlw_kgb15::maf15
Definition at line 31284 of file radlw_datatb.f.
integer, public module_radlw_kgb16::maf16
Definition at line 31676 of file radlw_datatb.f.
integer, parameter module_radlw_parameters::maxgas = 7
Definition at line 123 of file radlw_param.f.
Referenced by lwrad().
integer, parameter module_radlw_parameters::maxxsec = 4
Definition at line 125 of file radlw_param.f.
integer, public module_radlw_kgb03::mbf03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb04::mbf04
Definition at line 10077 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mbf05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb01::mfr01
Definition at line 1633 of file radlw_datatb.f.
integer, public module_radlw_kgb02::mfr02
Definition at line 2430 of file radlw_datatb.f.
integer, public module_radlw_kgb03::mfr03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb04::mfr04
Definition at line 10077 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mfr05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb06::mfr06
Definition at line 21730 of file radlw_datatb.f.
integer, public module_radlw_kgb07::mfr07
Definition at line 21969 of file radlw_datatb.f.
integer, public module_radlw_kgb08::mfr08
Definition at line 24596 of file radlw_datatb.f.
integer, public module_radlw_kgb09::mfr09
Definition at line 25381 of file radlw_datatb.f.
integer, public module_radlw_kgb10::mfr10
Definition at line 28022 of file radlw_datatb.f.
integer, public module_radlw_kgb11::mfr11
Definition at line 28481 of file radlw_datatb.f.
integer, public module_radlw_kgb12::mfr12
Definition at line 29150 of file radlw_datatb.f.
integer, public module_radlw_kgb13::mfr13
Definition at line 30205 of file radlw_datatb.f.
integer, public module_radlw_kgb14::mfr14
Definition at line 31083 of file radlw_datatb.f.
integer, public module_radlw_kgb15::mfr15
Definition at line 31284 of file radlw_datatb.f.
integer, public module_radlw_kgb16::mfr16
Definition at line 31676 of file radlw_datatb.f.
integer, public module_radlw_kgb06::mmc06
Definition at line 21730 of file radlw_datatb.f.
integer, public module_radlw_kgb07::mmc07
Definition at line 21969 of file radlw_datatb.f.
integer, public module_radlw_kgb08::mmc08
Definition at line 24596 of file radlw_datatb.f.
integer, public module_radlw_kgb01::mmn01
Definition at line 1633 of file radlw_datatb.f.
integer, public module_radlw_kgb03::mmn03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb09::mmn09
Definition at line 25381 of file radlw_datatb.f.
integer, public module_radlw_kgb15::mmn15
Definition at line 31284 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mmo05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb11::mmo11
Definition at line 28481 of file radlw_datatb.f.
integer, public module_radlw_kgb13::mmo13
Definition at line 30205 of file radlw_datatb.f.
integer, public module_radlw_kgb01::msb01
Definition at line 1633 of file radlw_datatb.f.
integer, public module_radlw_kgb02::msb02
Definition at line 2430 of file radlw_datatb.f.
integer, public module_radlw_kgb03::msb03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb04::msb04
Definition at line 10077 of file radlw_datatb.f.
integer, public module_radlw_kgb05::msb05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb07::msb07
Definition at line 21969 of file radlw_datatb.f.
integer, public module_radlw_kgb08::msb08
Definition at line 24596 of file radlw_datatb.f.
integer, public module_radlw_kgb09::msb09
Definition at line 25381 of file radlw_datatb.f.
integer, public module_radlw_kgb10::msb10
Definition at line 28022 of file radlw_datatb.f.
integer, public module_radlw_kgb11::msb11
Definition at line 28481 of file radlw_datatb.f.
integer, public module_radlw_kgb14::msb14
Definition at line 31083 of file radlw_datatb.f.
integer, public module_radlw_kgb16::msb16
Definition at line 31676 of file radlw_datatb.f.
integer, public module_radlw_kgb01::msf01
Definition at line 1633 of file radlw_datatb.f.
integer, public module_radlw_kgb02::msf02
Definition at line 2430 of file radlw_datatb.f.
integer, public module_radlw_kgb03::msf03
Definition at line 3274 of file radlw_datatb.f.
integer, public module_radlw_kgb04::msf04
Definition at line 10077 of file radlw_datatb.f.
integer, public module_radlw_kgb05::msf05
Definition at line 15257 of file radlw_datatb.f.
integer, public module_radlw_kgb06::msf06
Definition at line 21730 of file radlw_datatb.f.
integer, public module_radlw_kgb07::msf07
Definition at line 21969 of file radlw_datatb.f.
integer, public module_radlw_kgb08::msf08
Definition at line 24596 of file radlw_datatb.f.
integer, public module_radlw_kgb09::msf09
Definition at line 25381 of file radlw_datatb.f.
integer, public module_radlw_kgb10::msf10
Definition at line 28022 of file radlw_datatb.f.
integer, public module_radlw_kgb11::msf11
Definition at line 28481 of file radlw_datatb.f.
integer, public module_radlw_kgb12::msf12
Definition at line 29150 of file radlw_datatb.f.
integer, public module_radlw_kgb13::msf13
Definition at line 30205 of file radlw_datatb.f.
integer, public module_radlw_kgb14::msf14
Definition at line 31083 of file radlw_datatb.f.
integer, public module_radlw_kgb15::msf15
Definition at line 31284 of file radlw_datatb.f.
integer, public module_radlw_kgb16::msf16
Definition at line 31676 of file radlw_datatb.f.
integer, parameter module_radlw_parameters::nbands = 16
Definition at line 117 of file radlw_param.f.
Referenced by cldprop(), lwrad(), rtrn(), rtrnmc(), rtrnmr(), and setcoef().
integer, parameter module_radlw_parameters::nbdlw = NBANDS
Definition at line 131 of file radlw_param.f.
Referenced by module_radiation_aerosols::aer_init(), module_radiation_aerosols::aer_property(), module_radiation_driver::grrad(), module_radiation_aerosols::setaer(), and module_radiation_aerosols::setgocartaer().
integer module_radlw_parameters::ng01
Definition at line 134 of file radlw_param.f.
Referenced by taugb01().
integer module_radlw_parameters::ng02
Definition at line 134 of file radlw_param.f.
Referenced by taugb02().
integer module_radlw_parameters::ng03
Definition at line 134 of file radlw_param.f.
Referenced by taugb03().
integer module_radlw_parameters::ng04
Definition at line 134 of file radlw_param.f.
Referenced by taugb04().
integer module_radlw_parameters::ng05
Definition at line 134 of file radlw_param.f.
Referenced by taugb05().
integer module_radlw_parameters::ng06
Definition at line 134 of file radlw_param.f.
Referenced by taugb06().
integer module_radlw_parameters::ng07
Definition at line 134 of file radlw_param.f.
Referenced by taugb07().
integer module_radlw_parameters::ng08
Definition at line 134 of file radlw_param.f.
Referenced by taugb08().
integer module_radlw_parameters::ng09
Definition at line 134 of file radlw_param.f.
Referenced by taugb09().
integer module_radlw_parameters::ng10
Definition at line 134 of file radlw_param.f.
Referenced by taugb10().
integer module_radlw_parameters::ng11
Definition at line 134 of file radlw_param.f.
Referenced by taugb11().
integer module_radlw_parameters::ng12
Definition at line 134 of file radlw_param.f.
Referenced by taugb12().
integer module_radlw_parameters::ng13
Definition at line 134 of file radlw_param.f.
Referenced by taugb13().
integer module_radlw_parameters::ng14
Definition at line 134 of file radlw_param.f.
Referenced by taugb14().
integer module_radlw_parameters::ng15
Definition at line 134 of file radlw_param.f.
Referenced by taugb15().
integer module_radlw_parameters::ng16
Definition at line 134 of file radlw_param.f.
Referenced by taugb16().
integer, dimension(ngptlw) module_radlw_parameters::ngb
Definition at line 148 of file radlw_param.f.
Referenced by rtrn(), rtrnmc(), rtrnmr(), and taumol().
integer, parameter module_radlw_parameters::ngptlw = 140
Definition at line 119 of file radlw_param.f.
Referenced by cldprop(), mcica_subcol(), rtrn(), rtrnmc(), rtrnmr(), and taumol().
integer, parameter module_radlw_parameters::nplnk = 181
Definition at line 129 of file radlw_param.f.
integer, parameter module_radlw_parameters::nrates = 6
Definition at line 127 of file radlw_param.f.
integer module_radlw_parameters::ns01
Definition at line 141 of file radlw_param.f.
integer module_radlw_parameters::ns02
Definition at line 141 of file radlw_param.f.
Referenced by taugb02().
integer module_radlw_parameters::ns03
Definition at line 141 of file radlw_param.f.
Referenced by taugb03().
integer module_radlw_parameters::ns04
Definition at line 141 of file radlw_param.f.
Referenced by taugb04().
integer module_radlw_parameters::ns05
Definition at line 141 of file radlw_param.f.
Referenced by taugb05().
integer module_radlw_parameters::ns06
Definition at line 141 of file radlw_param.f.
Referenced by taugb06().
integer module_radlw_parameters::ns07
Definition at line 141 of file radlw_param.f.
Referenced by taugb07().
integer module_radlw_parameters::ns08
Definition at line 141 of file radlw_param.f.
Referenced by taugb08().
integer module_radlw_parameters::ns09
Definition at line 141 of file radlw_param.f.
Referenced by taugb09().
integer module_radlw_parameters::ns10
Definition at line 141 of file radlw_param.f.
Referenced by taugb10().
integer module_radlw_parameters::ns11
Definition at line 141 of file radlw_param.f.
Referenced by taugb11().
integer module_radlw_parameters::ns12
Definition at line 141 of file radlw_param.f.
Referenced by taugb12().
integer module_radlw_parameters::ns13
Definition at line 141 of file radlw_param.f.
Referenced by taugb13().
integer module_radlw_parameters::ns14
Definition at line 141 of file radlw_param.f.
Referenced by taugb14().
integer module_radlw_parameters::ns15
Definition at line 141 of file radlw_param.f.
Referenced by taugb15().
integer module_radlw_parameters::ns16
Definition at line 141 of file radlw_param.f.
Referenced by taugb16().
integer, dimension(nbands) module_radlw_main::nspa private
Definition at line 290 of file radlw_main.f.
Referenced by taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb12(), taugb13(), taugb14(), taugb15(), and taugb16().
integer, dimension(nbands) module_radlw_main::nspb private
Definition at line 290 of file radlw_main.f.
Referenced by taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb14(), and taugb16().
integer, parameter module_radlw_parameters::ntbl = 10000
Definition at line 121 of file radlw_param.f.
Referenced by rlwinit().
real (kind=kind_phys), parameter module_radlw_main::oneminus = 1.0-eps private
Definition at line 276 of file radlw_main.f.
Referenced by taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), dimension(59) module_radlw_ref::preflog
Definition at line 757 of file radlw_datatb.f.
Referenced by setcoef().
real (kind=kind_phys), dimension(ng01,msf01), public module_radlw_kgb01::selfref
Definition at line 1636 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng02,msf02), public module_radlw_kgb02::selfref
Definition at line 2433 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng03,msf03), public module_radlw_kgb03::selfref
Definition at line 3278 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng04,msf04), public module_radlw_kgb04::selfref
Definition at line 10081 of file radlw_datatb.f.
Referenced by taugb04().
real (kind=kind_phys), dimension(ng05,msf05), public module_radlw_kgb05::selfref
Definition at line 15261 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng06,msf06), public module_radlw_kgb06::selfref
Definition at line 21733 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng07,msf07), public module_radlw_kgb07::selfref
Definition at line 21973 of file radlw_datatb.f.
Referenced by taugb07().
real (kind=kind_phys), dimension(ng08,msf08), public module_radlw_kgb08::selfref
Definition at line 24599 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng09,msf09), public module_radlw_kgb09::selfref
Definition at line 25385 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng10,msf10), public module_radlw_kgb10::selfref
Definition at line 28025 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng11,msf11), public module_radlw_kgb11::selfref
Definition at line 28484 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng12,msf12), public module_radlw_kgb12::selfref
Definition at line 29153 of file radlw_datatb.f.
Referenced by taugb12().
real (kind=kind_phys), dimension(ng13,msf13), public module_radlw_kgb13::selfref
Definition at line 30208 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng14,msf14), public module_radlw_kgb14::selfref
Definition at line 31086 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng15,msf15), public module_radlw_kgb15::selfref
Definition at line 31287 of file radlw_datatb.f.
Referenced by taugb15().
real (kind=kind_phys), dimension(ng16,msf16), public module_radlw_kgb16::selfref
Definition at line 31679 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(nbands) module_radlw_main::semiss0 private
Definition at line 334 of file radlw_main.f.
Referenced by lwrad(), and rlwinit().
real (kind=kind_phys), parameter module_radlw_main::stpfac = 296.0/1013.0 private
Definition at line 279 of file radlw_main.f.
Referenced by setcoef().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::tau_tbl private
Definition at line 337 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), parameter module_radlw_main::tblint = ntbl private
Definition at line 281 of file radlw_main.f.
Referenced by rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::tfn_tbl private
Definition at line 339 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(59) module_radlw_ref::tref
Definition at line 757 of file radlw_datatb.f.
Referenced by setcoef().
real (kind=kind_phys) module_radlw_parameters::topflw_type::upfx0
Definition at line 83 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::sfcflw_type::upfx0
Definition at line 93 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::proflw_type::upfx0
Definition at line 109 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::topflw_type::upfxc
Definition at line 81 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::sfcflw_type::upfxc
Definition at line 91 of file radlw_param.f.
real (kind=kind_phys) module_radlw_parameters::proflw_type::upfxc
Definition at line 105 of file radlw_param.f.
real (kind=kind_phys), parameter module_radlw_main::wtdiff = 0.5 private
Definition at line 280 of file radlw_main.f.
Referenced by rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(nbands) module_radlw_parameters::wvnlw1
Definition at line 153 of file radlw_param.f.
Referenced by module_radiation_aerosols::gocart_init(), set_aercoef(), and module_radiation_aerosols::setaer().
real (kind=kind_phys), dimension(nbands) module_radlw_parameters::wvnlw2
Definition at line 153 of file radlw_param.f.
Referenced by module_radiation_aerosols::gocart_init(), set_aercoef(), and module_radiation_aerosols::setaer().