Radiation Scheme in CCPP: module_radiation_gases
module_radiation_gases
RRTMG Radiation Scheme
This module sets up ozone climatological profiles and other constant gas profiles, such as co2, ch4, n2o, o2, and those of cfc gases. All data are entered as mixing ratio by volume, except ozone which is mass mixing ratio (g/g).
Modules
module module_radiation_gases
Functions/Subroutines
subroutine, public module_radiation_gases::gas_init
This subroutine sets up ozone, co2, etc. parameters. if climatology ozone then read in monthly ozone data.
subroutine, public module_radiation_gases::gas_update
This subroutine reads in 2-d monthly co2 data set for a specified year. data are in a 15 degree lat/lon horizontal resolution.
subroutine, public module_radiation_gases::getgases
This subroutine sets up global distribution of radiation absorbing gases in volume mixing ratio. currently only co2 has the options from observed values, all other gases are asigned to the climatological values.
subroutine, public module_radiation_gases::getozn
This subroutine sets up climatological ozone profile for radiation calculation this code is originally written by Shrinivas Moorthi.
Variables
integer, parameter, public module_radiation_gases::nf_vgas = 10
number of gas species
integer, parameter module_radiation_gases::imxco2 = 24
input co2 dat lon points
integer, parameter module_radiation_gases::jmxco2 = 12
input co2 data lat points
integer, parameter module_radiation_gases::minyear = 1957
earlist year 2-d co2 data available
real(kind=kind_phys), parameter module_radiation_gases::resco2 =15.0
real(kind=kind_phys), parameter module_radiation_gases::raddeg =180.0/con_pi
real(kind=kind_phys), parameter module_radiation_gases::prsco2 =788.0
real(kind=kind_phys), parameter module_radiation_gases::hfpi =0.5*con_pi
real(kind=kind_phys), parameter module_radiation_gases::co2vmr_def = 350.0e-6
real(kind=kind_phys), parameter module_radiation_gases::n2ovmr_def = 0.31e-6
real(kind=kind_phys), parameter module_radiation_gases::ch4vmr_def = 1.50e-6
real(kind=kind_phys), parameter module_radiation_gases::o2vmr_def = 0.209
real(kind=kind_phys), parameter module_radiation_gases::covmr_def = 1.50e-8
real(kind=kind_phys), parameter module_radiation_gases::f11vmr_def = 3.520e-10
real(kind=kind_phys), parameter module_radiation_gases::f12vmr_def = 6.358e-10
real(kind=kind_phys), parameter module_radiation_gases::f22vmr_def = 1.500e-10
real(kind=kind_phys), parameter module_radiation_gases::cl4vmr_def = 1.397e-10
real(kind=kind_phys), parameter module_radiation_gases::f113vmr_def = 8.2000e-11
real(kind=kind_phys), dimension(:), allocatable module_radiation_gases::pkstr
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::o3r
integer module_radiation_gases::k1oz = 0
integer module_radiation_gases::k2oz = 0
real(kind=kind_phys) module_radiation_gases::facoz = 0.0
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::co2vmr_sav
real(kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::co2cyc_sav
real(kind=kind_phys) module_radiation_gases::co2_glb = co2vmr_def
real(kind=kind_phys), dimension(12) module_radiation_gases::gco2cyc
integer module_radiation_gases::kyrsav = 0
integer module_radiation_gases::kmonsav = 1
Detailed Description
Function/Subroutine Documentation
subroutine, public module_radiation_gases::gas_init ()
Parameters
[in] me integer, 1, print message control flag
[out] NONE
External Module Variables
physparam::ico2flg - co2 data source control flag
=0: use prescribed co2 global mean value
=1: use input global mean co2 value (co2_glb)
=2: use input 2-d monthly co2 value (co2vmr_sav)
physparam::ictmflg - =yyyy#, data ic time/date control flag
= -2: same as 0, but superimpose seasonal cycle from climatology data set.
= -1: use user provided external data for the fcst time, no extrapolation.
= 0: use data at initial condition time, if not existed then use latest, without extrapolation.
= 1: use data at the forecast time, if not existed then use latest and extrapolate to fcst time.
=yyyy0: use yyyy data for the forecast time, no further data extrapolation.
=yyyy1: use yyyy data for the fcst. if needed, do extrapolation to match the fcst time.
physparam::ioznflg - ozone data control flag
=0: use climatological ozone profile
>0: use interactive ozone profile
physparam::ivflip - vertical profile indexing flag
physparam::co2usr_file - external co2 user defined data table
physparam::co2cyc_file - external co2 climotology monthly cycle data table
Definition at line 225 of file radiation_gases.f.
References co2_glb, co2cyc_sav, co2vmr_def, co2vmr_sav, gco2cyc, imxco2, jmxco2, kmonsav, kyrsav, o3r, pkstr, and vtaggas.
Referenced by module_radiation_driver::radinit().
subroutine, public module_radiation_gases::gas_update ()
Definition at line 540 of file radiation_gases.f.
References co2_glb, co2cyc_sav, co2vmr_sav, facoz, gco2cyc, imxco2, jmxco2, k1oz, k2oz, kmonsav, kyrsav, and minyear.
Referenced by module_radiation_driver::radupdate().
subroutine, public module_radiation_gases::getgases ()
Parameters
[in] plvl real, (IMAX,LMAX+1), pressure at model layer interfaces (mb)
[in] xlon real, (IMAX), grid longitude in radians, ok both 0->2pi or -pi -> +pi arrangements
[in] xlat real, (IMAX), grid latitude in radians, default range to pi/2 -> -pi/2, otherwise see in-line comment
[in] IMAX,LMAX integer, horiz/vert dimensions for output data
[out] gasdat real, (IMAX,LMAX,NF_VGAS) - gases volume mixing ratioes
(:,:,1) - co2
(:,:,2) - n2o
(:,:,3) - ch4
(:,:,4) - o2
(:,:,5) - co
(:,:,6) - cfc11
(:,:,7) - cfc12
(:,:,8) - cfc22
(:,:,9) - ccl4
(:,:,10) - cfc113
External Module Variables
physparam::ico2flg - co2 data source control flag
=0: use prescribed co2 global mean value
=1: use input global mean co2 value (co2_glb)
=2: use input 2-d monthly co2 value (co2vmr_sav)
physparam::ivflip - vertical profile indexing flag
Definition at line 936 of file radiation_gases.f.
References ch4vmr_def, cl4vmr_def, co2_glb, co2vmr_def, co2vmr_sav, covmr_def, f113vmr_def, f11vmr_def, f12vmr_def, f22vmr_def, gco2cyc, hfpi, imxco2, jmxco2, kmonsav, n2ovmr_def, o2vmr_def, prsco2, raddeg, and resco2.
Referenced by module_radiation_driver::grrad().
subroutine, public module_radiation_gases::getozn ()
Parameters
[in] prslk real, (IMAX,LM), exner function = \((p/p0)^{rocp}\)
[in] xlat real, (IMAX), latitude in radians, default to pi/2 -> -pi/2 range, otherwise see in-line comment
[in] IMAX,LM integer, horizontal and vertical dimensions
[out] o3mmr real, (IMAX,LM), output ozone profile in mass mixing ratio (g/g)
Definition at line 1088 of file radiation_gases.f.
References facoz, k1oz, k2oz, o3r, pkstr, and raddeg.
Referenced by module_radiation_driver::grrad().
Variable Documentation
real (kind=kind_phys), parameter module_radiation_gases::ch4vmr_def = 1.50e-6 private
Definition at line 157 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::cl4vmr_def = 1.397e-10 private
Definition at line 163 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys) module_radiation_gases::co2_glb = co2vmr_def private
Definition at line 185 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::co2cyc_sav private
Definition at line 183 of file radiation_gases.f.
Referenced by gas_init(), and gas_update().
real (kind=kind_phys), parameter module_radiation_gases::co2vmr_def = 350.0e-6 private
Definition at line 155 of file radiation_gases.f.
Referenced by gas_init(), and getgases().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::co2vmr_sav private
Definition at line 182 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
real (kind=kind_phys), parameter module_radiation_gases::covmr_def = 1.50e-8 private
Definition at line 159 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::f113vmr_def = 8.2000e-11 private
Definition at line 164 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::f11vmr_def = 3.520e-10 private
Definition at line 160 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::f12vmr_def = 6.358e-10 private
Definition at line 161 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::f22vmr_def = 1.500e-10 private
Definition at line 162 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys) module_radiation_gases::facoz = 0.0 private
Definition at line 179 of file radiation_gases.f.
Referenced by gas_update(), and getozn().
real (kind=kind_phys), dimension(12) module_radiation_gases::gco2cyc private
Definition at line 186 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
real (kind=kind_phys), parameter module_radiation_gases::hfpi =0.5*con_pi private
Definition at line 152 of file radiation_gases.f.
Referenced by getgases().
integer, parameter module_radiation_gases::imxco2 = 24 private
Definition at line 142 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
integer, parameter module_radiation_gases::jmxco2 = 12 private
Definition at line 144 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
integer module_radiation_gases::k1oz = 0 private
Definition at line 178 of file radiation_gases.f.
Referenced by gas_update(), and getozn().
integer module_radiation_gases::k2oz = 0 private
Definition at line 178 of file radiation_gases.f.
Referenced by gas_update(), and getozn().
integer module_radiation_gases::kmonsav = 1 private
Definition at line 190 of file radiation_gases.f.
Referenced by gas_init(), gas_update(), and getgases().
integer module_radiation_gases::kyrsav = 0 private
Definition at line 189 of file radiation_gases.f.
Referenced by gas_init(), and gas_update().
integer, parameter module_radiation_gases::minyear = 1957 private
Definition at line 146 of file radiation_gases.f.
Referenced by gas_update().
real (kind=kind_phys), parameter module_radiation_gases::n2ovmr_def = 0.31e-6 private
Definition at line 156 of file radiation_gases.f.
Referenced by getgases().
integer, parameter, public module_radiation_gases::nf_vgas = 10
Definition at line 140 of file radiation_gases.f.
real (kind=kind_phys), parameter module_radiation_gases::o2vmr_def = 0.209 private
Definition at line 158 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_gases::o3r private
Definition at line 177 of file radiation_gases.f.
Referenced by gas_init(), and getozn().
real (kind=kind_phys), dimension(:), allocatable module_radiation_gases::pkstr private
Definition at line 177 of file radiation_gases.f.
Referenced by gas_init(), and getozn().
real (kind=kind_phys), parameter module_radiation_gases::prsco2 =788.0 private
Definition at line 151 of file radiation_gases.f.
Referenced by getgases().
real (kind=kind_phys), parameter module_radiation_gases::raddeg =180.0/con_pi private
Definition at line 150 of file radiation_gases.f.
Referenced by getgases(), and getozn().
real (kind=kind_phys), parameter module_radiation_gases::resco2 =15.0 private
Definition at line 149 of file radiation_gases.f.
Referenced by getgases().