Radiation Scheme in CCPP: module_radlw_kgb03 Module Reference
module_radlw_kgb03 Module Reference
This module sets up absorption coefficients for band 03: 500-630 cm-1 (low - h2o, co2; high - h2o, co2)
Variables
integer, public msa03
integer, public msb03
integer, public msf03
integer, public mfr03
integer, public maf03
integer, public mbf03
integer, public mmn03
real(kind=kind_phys), dimension(ng03, mfr03), public forref
real(kind=kind_phys), dimension(ng03, msa03), public absa
real(kind=kind_phys), dimension(ng03, msb03), public absb
real(kind=kind_phys), dimension(ng03, msf03), public selfref
real(kind=kind_phys), dimension(ng03, maf03), public fracrefa
real(kind=kind_phys), dimension(ng03, mbf03), public fracrefb
real(kind=kind_phys), dimension(ng03, maf03, mmn03), public ka_mn2o
real(kind=kind_phys), dimension(ng03, mbf03, mmn03), public kb_mn2o
Variable Documentation
real (kind=kind_phys), dimension(ng03,msa03), public module_radlw_kgb03::absa
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,msb03), public module_radlw_kgb03::absb
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,mfr03), public module_radlw_kgb03::forref
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,maf03), public module_radlw_kgb03::fracrefa
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,mbf03), public module_radlw_kgb03::fracrefb
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,maf03,mmn03), public module_radlw_kgb03::ka_mn2o
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
real (kind=kind_phys), dimension(ng03,mbf03,mmn03), public module_radlw_kgb03::kb_mn2o
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().
integer, public module_radlw_kgb03::maf03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::mbf03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::mfr03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::mmn03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::msa03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::msb03
Definition at line 3256 of file radlw_datatb.f.
integer, public module_radlw_kgb03::msf03
Definition at line 3256 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng03,msf03), public module_radlw_kgb03::selfref
Definition at line 3260 of file radlw_datatb.f.
Referenced by taugb03().