Radiation Scheme in CCPP: module_radlw_kgb14 Module Reference
module_radlw_kgb14 Module Reference
This module sets up absorption coefficients for band 14: 2250-2380 cm-1 (low - co2; high - co2)
Variables
integer, public msa14
integer, public msb14
integer, public msf14
integer, public mfr14
real(kind=kind_phys), dimension(ng14, msa14), public absa
real(kind=kind_phys), dimension(ng14, msb14), public absb
real(kind=kind_phys), dimension(ng14, msf14), public selfref
real(kind=kind_phys), dimension(ng14, mfr14), public forref
real(kind=kind_phys), dimension(ng14), public fracrefa
real(kind=kind_phys), dimension(ng14), public fracrefb
Variable Documentation
real (kind=kind_phys), dimension(ng14,msa14), public module_radlw_kgb14::absa
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng14,msb14), public module_radlw_kgb14::absb
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng14,mfr14), public module_radlw_kgb14::forref
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefa
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().
real (kind=kind_phys), dimension(ng14), public module_radlw_kgb14::fracrefb
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().
integer, public module_radlw_kgb14::mfr14
Definition at line 31054 of file radlw_datatb.f.
integer, public module_radlw_kgb14::msa14
Definition at line 31054 of file radlw_datatb.f.
integer, public module_radlw_kgb14::msb14
Definition at line 31054 of file radlw_datatb.f.
integer, public module_radlw_kgb14::msf14
Definition at line 31054 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng14,msf14), public module_radlw_kgb14::selfref
Definition at line 31057 of file radlw_datatb.f.
Referenced by taugb14().