Radiation Scheme in CCPP: module_radlw_kgb10 Module Reference
module_radlw_kgb10 Module Reference
This module sets up absorption coefficients for band 10: 1390-1480 cm-1 (low - h2o; high - h2o)
Variables
integer, public msa10
integer, public msb10
integer, public msf10
integer, public mfr10
real(kind=kind_phys), dimension(ng10, msa10), public absa
real(kind=kind_phys), dimension(ng10, msb10), public absb
real(kind=kind_phys), dimension(ng10, msf10), public selfref
real(kind=kind_phys), dimension(ng10, mfr10), public forref
real(kind=kind_phys), dimension(ng10), public fracrefa
real(kind=kind_phys), dimension(ng10), public fracrefb
Variable Documentation
real (kind=kind_phys), dimension(ng10,msa10), public module_radlw_kgb10::absa
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng10,msb10), public module_radlw_kgb10::absb
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng10,mfr10), public module_radlw_kgb10::forref
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefa
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().
real (kind=kind_phys), dimension(ng10), public module_radlw_kgb10::fracrefb
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().
integer, public module_radlw_kgb10::mfr10
Definition at line 27997 of file radlw_datatb.f.
integer, public module_radlw_kgb10::msa10
Definition at line 27997 of file radlw_datatb.f.
integer, public module_radlw_kgb10::msb10
Definition at line 27997 of file radlw_datatb.f.
integer, public module_radlw_kgb10::msf10
Definition at line 27997 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng10,msf10), public module_radlw_kgb10::selfref
Definition at line 28000 of file radlw_datatb.f.
Referenced by taugb10().