Radiation Scheme in CCPP: module_radlw_kgb11 Module Reference
module_radlw_kgb11 Module Reference
This module sets up absorption coefficients for band 11: 1480-1800 cm-1 (low - h2o; high - h2o)
Variables
integer, public msa11
integer, public msb11
integer, public msf11
integer, public mfr11
integer, public mmo11
real(kind=kind_phys), dimension(ng11, msa11), public absa
real(kind=kind_phys), dimension(ng11, msb11), public absb
real(kind=kind_phys), dimension(ng11, msf11), public selfref
real(kind=kind_phys), dimension(ng11, mfr11), public forref
real(kind=kind_phys), dimension(ng11), public fracrefa
real(kind=kind_phys), dimension(ng11), public fracrefb
real(kind=kind_phys), dimension(ng11, mmo11), public ka_mo2
real(kind=kind_phys), dimension(ng11, mmo11), public kb_mo2
Variable Documentation
real (kind=kind_phys), dimension(ng11,msa11), public module_radlw_kgb11::absa
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11,msb11), public module_radlw_kgb11::absb
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11,mfr11), public module_radlw_kgb11::forref
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefa
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11), public module_radlw_kgb11::fracrefb
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11,mmo11), public module_radlw_kgb11::ka_mo2
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
real (kind=kind_phys), dimension(ng11,mmo11), public module_radlw_kgb11::kb_mo2
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().
integer, public module_radlw_kgb11::mfr11
Definition at line 28455 of file radlw_datatb.f.
integer, public module_radlw_kgb11::mmo11
Definition at line 28455 of file radlw_datatb.f.
integer, public module_radlw_kgb11::msa11
Definition at line 28455 of file radlw_datatb.f.
integer, public module_radlw_kgb11::msb11
Definition at line 28455 of file radlw_datatb.f.
integer, public module_radlw_kgb11::msf11
Definition at line 28455 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng11,msf11), public module_radlw_kgb11::selfref
Definition at line 28458 of file radlw_datatb.f.
Referenced by taugb11().