Radiation Scheme in CCPP: module_radsw_kgb16 Module Reference
module_radsw_kgb16 Module Reference
This module sets up absorption coefficients for band 16: 2600-3250 cm-1 (low - h2o, ch4; high - ch4)
Variables
integer, public msa16
integer, public msb16
integer, public msf16
integer, public mfr16
real(kind=kind_phys), dimension(msf16, ng16), public selfref
real(kind=kind_phys), dimension(msa16, ng16), public absa
real(kind=kind_phys), dimension(msb16, ng16), public absb
real(kind=kind_phys), dimension(mfr16, ng16), public forref
real(kind=kind_phys), parameter, public rayl = 2.91e-10
Variable Documentation
real (kind=kind_phys), dimension(msa16,ng16), public module_radsw_kgb16::absa
Definition at line 2165 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(msb16,ng16), public module_radsw_kgb16::absb
Definition at line 2165 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(mfr16,ng16), public module_radsw_kgb16::forref
Definition at line 2165 of file radsw_datatb.f.
Referenced by taumol16().
integer, public module_radsw_kgb16::mfr16
Definition at line 2162 of file radsw_datatb.f.
integer, public module_radsw_kgb16::msa16
Definition at line 2162 of file radsw_datatb.f.
integer, public module_radsw_kgb16::msb16
Definition at line 2162 of file radsw_datatb.f.
integer, public module_radsw_kgb16::msf16
Definition at line 2162 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb16::rayl = 2.91e-10
Definition at line 2169 of file radsw_datatb.f.
Referenced by taumol16().
real (kind=kind_phys), dimension(msf16,ng16), public module_radsw_kgb16::selfref
Definition at line 2165 of file radsw_datatb.f.
Referenced by taumol16().