Radiation Scheme in CCPP: module_radlw_cldprlw Module Reference
module_radlw_cldprlw Module Reference
This module contains cloud property coefficients.
Variables
integer, dimension(nbands) ipat
ipat is bands index for ebert&curry ice cloud (for iflagice=1)
real(kind=kind_phys), parameter absrain = 0.33e-3
absrain is the rain drop absorption coefficient (m2/g)
real(kind=kind_phys), parameter abssnow0 = 1.5
abssnow0 is the snow flake absorption coefficient (micron), fu coeff
real(kind=kind_phys), parameter abssnow1 = 2.34e-3
abssnow1 is the snow flake absorption coefficient (m2/g), ncar coeff
real(kind=kind_phys), dimension(58, nbands) absliq1
Hu and Stamnes method. the liquid water absorption coefficients are listed for a range of effective radii from 2.5 to 59.5 microns in increments of 1.0 micron.
real(kind=kind_phys), dimension(2) absice0
for iflagice = 2 or 3, absice0 are the ice water absorption coefficients used for large ice partical size such as refice > 131 microns.
real(kind=kind_phys), dimension(2, 5) absice1
for iflagice = 1, absice1 are the ice water absorption coefficients used for ebert and curry method
real(kind=kind_phys), dimension(43, nbands) absice2
for iflagice =2, absice2 are the ice water absorption coefficients used for streamer method. the absorption coefficients are listed for a range of effective radii from 5.0 to 131.0 microns in increments of 3.0 microns. spherical ice particle parameterization absorption units (abs coef/iwc): [(m^-1)/(g m^-3)]
real(kind=kind_phys), dimension(46, nbands) absice3
for iflagice = 3, absice3 are the ice water absorption coefficients used for fu parameterization. particle size 5 - 140 micron in increments of 3 microns. units = m2/g. hexagonal ice particle parameterization absorption units (abs coef/iwc): [(m^-1)/(g m^-3)]
Variable Documentation
real (kind=kind_phys), dimension(2) module_radlw_cldprlw::absice0
Definition at line 1189 of file radlw_datatb.f.
real (kind=kind_phys), dimension(2,5) module_radlw_cldprlw::absice1
Definition at line 1198 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), dimension(43,nbands) module_radlw_cldprlw::absice2
Definition at line 1212 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), dimension(46,nbands) module_radlw_cldprlw::absice3
Definition at line 1400 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), dimension(58,nbands) module_radlw_cldprlw::absliq1
Definition at line 952 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::absrain = 0.33e-3
Definition at line 928 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::abssnow0 = 1.5
Definition at line 932 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().
real (kind=kind_phys), parameter module_radlw_cldprlw::abssnow1 = 2.34e-3
Definition at line 935 of file radlw_datatb.f.
integer, dimension(nbands) module_radlw_cldprlw::ipat
Definition at line 921 of file radlw_datatb.f.
Referenced by module_radlw_main::cldprop().