Radiation Scheme in CCPP: physcons Module Reference
physcons Module Reference
This module contains some the most frequently used math and physics constants for gcm models.
Variables
Math constants
real(kind=kind_phys), parameter con_pi =3.1415926535897931
real(kind=kind_phys), parameter con_sqrt2 =1.414214e+0
square root of 2
real(kind=kind_phys), parameter con_sqrt3 =1.732051e+0
square root of 3
Geophysics/Astronomy constants
real(kind=kind_phys), parameter con_rerth =6.3712e+6
real(kind=kind_phys), parameter con_g =9.80665e+0
gravity (m/s2)
real(kind=kind_phys), parameter con_omega =7.2921e-5
ang vel of earth (1/s)
real(kind=kind_phys), parameter con_p0 =1.01325e5
std atms pressure (ps)
real(kind=kind_phys), parameter con_solr_old =1.3660e+3
solar constant (W/m2)-liu(2002)
real(kind=kind_phys), parameter con_solr =1.3608e+3
solar constant (W/m2)-nasa-sorce tim(2008)
Thermodynamics constants
real(kind=kind_phys), parameter con_rgas =8.314472
real(kind=kind_phys), parameter con_rd =2.8705e+2
gas constant air (J/kg/K)
real(kind=kind_phys), parameter con_rv =4.6150e+2
gas constant H2O (J/kg/K)
real(kind=kind_phys), parameter con_cp =1.0046e+3
spec heat air at p (J/kg/K)
real(kind=kind_phys), parameter con_cv =7.1760e+2
spec heat air at v (J/kg/K)
real(kind=kind_phys), parameter con_cvap =1.8460e+3
spec heat H2O gas (J/kg/K)
real(kind=kind_phys), parameter con_cliq =4.1855e+3
spec heat H2O liq (J/kg/K)
real(kind=kind_phys), parameter con_csol =2.1060e+3
spec heat H2O ice (J/kg/K)
real(kind=kind_phys), parameter con_hvap =2.5000e+6
lat heat H2O cond (J/kg)
real(kind=kind_phys), parameter con_hfus =3.3358e+5
lat heat H2O fusion (J/kg)
real(kind=kind_phys), parameter con_psat =6.1078e+2
pres at H2O 3pt (Pa)
real(kind=kind_phys), parameter con_t0c =2.7315e+2
temp at 0C (K)
real(kind=kind_phys), parameter con_ttp =2.7316e+2
temp at H2O 3pt (K)
real(kind=kind_phys), parameter con_tice =2.7120e+2
temp freezing sea (K)
real(kind=kind_phys), parameter con_jcal =4.1855E+0
joules per calorie
real(kind=kind_phys), parameter con_rhw0 =1022.0
sea water reference density (kg/m^3)
real(kind=kind_phys), parameter con_epsq =1.0E-12
min q for computing precip type
Secondary constants
real(kind=kind_phys), parameter con_rocp =con_rd/con_cp
real(kind=kind_phys), parameter con_cpor =con_cp/con_rd
real(kind=kind_phys), parameter con_rog =con_rd/con_g
real(kind=kind_phys), parameter con_fvirt =con_rv/con_rd-1.
real(kind=kind_phys), parameter con_eps =con_rd/con_rv
real(kind=kind_phys), parameter con_epsm1 =con_rd/con_rv-1.
real(kind=kind_phys), parameter con_dldt =con_cvap-con_cliq
real(kind=kind_phys), parameter con_xpona =-con_dldt/con_rv
real(kind=kind_phys), parameter con_xponb =-con_dldt/con_rv+con_hvap/(con_rv*con_ttp)
Other Physics/Chemistry constants (source: 2002 CODATA)
real(kind=kind_phys), parameter con_c =2.99792458e+8
real(kind=kind_phys), parameter con_plnk =6.6260693e-34
planck constant (J/s)
real(kind=kind_phys), parameter con_boltz =1.3806505e-23
boltzmann constant (J/K)
real(kind=kind_phys), parameter con_sbc =5.670400e-8
stefan-boltzmann (W/m2/K4)
real(kind=kind_phys), parameter con_avgd =6.0221415e23
avogadro constant (1/mol)
real(kind=kind_phys), parameter con_gasv =22413.996e-6
vol of ideal gas at 273.15k, 101.325kpa(m3/mol)
real(kind=kind_phys), parameter con_amd =28.9644
molecular wght of dry air (g/mol)
real(kind=kind_phys), parameter con_amw =18.0154
molecular wght of water vapor (g/mol)
real(kind=kind_phys), parameter con_amo3 =47.9982
molecular wght of o3 (g/mol)
real(kind=kind_phys), parameter con_amco2 =44.011
molecular wght of co2 (g/mol)
real(kind=kind_phys), parameter con_amo2 =31.9999
molecular wght of o2 (g/mol)
real(kind=kind_phys), parameter con_amch4 =16.043
molecular wght of ch4 (g/mol)
real(kind=kind_phys), parameter con_amn2o =44.013
molecular wght of n2o (g/mol)
real(kind=kind_phys), parameter con_thgni =-38.15
temperature the H.G.Nuc. ice starts
Miscellaneous physics related constants (Moorthi - Jul 2014)
integer, parameter max_lon =5000
integer, parameter max_lat =2000
integer, parameter min_lon =192
integer, parameter min_lat =94
real(kind=kind_phys), parameter rlapse = 0.65e-2
real(kind=kind_phys), parameter rhc_max = 0.9999
real(kind=kind_phys), parameter cb2mb = 10.0
real(kind=kind_phys), parameter pa2mb = 0.01
real(kind=kind_phys) dxmax
real(kind=kind_phys) dxmin
real(kind=kind_phys) dxinv
Variable Documentation
real(kind=kind_phys), parameter physcons::cb2mb = 10.0
Definition at line 157 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amch4 =16.043
Definition at line 141 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amco2 =44.011
Definition at line 137 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amd =28.9644
Definition at line 130 of file physcons.f.
Referenced by module_radlw_main::lwrad(), module_radiation_aerosols::setgocartaer(), and module_radsw_main::swrad().
real(kind=kind_phys), parameter physcons::con_amn2o =44.013
Definition at line 143 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amo2 =31.9999
Definition at line 139 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amo3 =47.9982
Definition at line 134 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_amw =18.0154
Definition at line 132 of file physcons.f.
Referenced by module_radlw_main::lwrad(), and module_radsw_main::swrad().
real(kind=kind_phys), parameter physcons::con_avgd =6.0221415e23
Definition at line 125 of file physcons.f.
Referenced by module_radlw_main::lwrad(), and module_radsw_main::swrad().
real(kind=kind_phys), parameter physcons::con_boltz =1.3806505e-23
Definition at line 121 of file physcons.f.
Referenced by set_spectrum().
real(kind=kind_phys), parameter physcons::con_c =2.99792458e+8
Definition at line 117 of file physcons.f.
Referenced by set_spectrum().
real(kind=kind_phys), parameter physcons::con_cliq =4.1855e+3
Definition at line 79 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_cp =1.0046e+3
Definition at line 73 of file physcons.f.
Referenced by module_radlw_main::rlwinit(), and module_radsw_main::rswinit().
real(kind=kind_phys), parameter physcons::con_cpor =con_cp/con_rd
Definition at line 105 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_csol =2.1060e+3
Definition at line 81 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_cv =7.1760e+2
Definition at line 75 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_cvap =1.8460e+3
Definition at line 77 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_dldt =con_cvap-con_cliq
Definition at line 110 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_eps =con_rd/con_rv
Definition at line 108 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_epsm1 =con_rd/con_rv-1.
Definition at line 109 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_epsq =1.0E-12
Definition at line 99 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_fvirt =con_rv/con_rd-1.
Definition at line 107 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_g =9.80665e+0
Definition at line 52 of file physcons.f.
Referenced by module_radlw_main::lwrad(), module_radiation_clouds::progcld2(), module_radlw_main::rlwinit(), module_radsw_main::rswinit(), module_radiation_aerosols::setaer(), and module_radsw_main::swrad().
real(kind=kind_phys), parameter physcons::con_gasv =22413.996e-6
Definition at line 127 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_hfus =3.3358e+5
Definition at line 85 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_hvap =2.5000e+6
Definition at line 83 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_jcal =4.1855E+0
Definition at line 95 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_omega =7.2921e-5
Definition at line 54 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_p0 =1.01325e5
Definition at line 56 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_pi =3.1415926535897931
Definition at line 41 of file physcons.f.
Referenced by module_radiation_clouds::diagcld1(), module_radiation_gases::getgases(), module_radiation_clouds::progcld1(), module_radiation_clouds::progcld2(), module_radiation_clouds::progcld3(), set_spectrum(), and module_radiation_astronomy::solar().
real(kind=kind_phys), parameter physcons::con_plnk =6.6260693e-34
Definition at line 119 of file physcons.f.
Referenced by set_spectrum().
real(kind=kind_phys), parameter physcons::con_psat =6.1078e+2
Definition at line 87 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_rd =2.8705e+2
Definition at line 69 of file physcons.f.
Referenced by module_radiation_clouds::progcld2(), and module_radiation_aerosols::setgocartaer().
real(kind=kind_phys), parameter physcons::con_rerth =6.3712e+6
Definition at line 50 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_rgas =8.314472
Definition at line 67 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_rhw0 =1022.0
Definition at line 97 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_rocp =con_rd/con_cp
Definition at line 104 of file physcons.f.
Referenced by module_radiation_clouds::diagcld1().
real(kind=kind_phys), parameter physcons::con_rog =con_rd/con_g
Definition at line 106 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_rv =4.6150e+2
Definition at line 71 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_sbc =5.670400e-8
Definition at line 123 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_solr =1.3608e+3
Definition at line 61 of file physcons.f.
Referenced by module_radiation_astronomy::sol_init().
real(kind=kind_phys), parameter physcons::con_solr_old =1.3660e+3
Definition at line 59 of file physcons.f.
Referenced by module_radiation_astronomy::sol_init().
real(kind=kind_phys), parameter physcons::con_sqrt2 =1.414214e+0
Definition at line 43 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_sqrt3 =1.732051e+0
Definition at line 45 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_t0c =2.7315e+2
Definition at line 89 of file physcons.f.
Referenced by module_radiation_clouds::progcld2(), set_spectrum(), and module_radiation_surface::setalb().
real(kind=kind_phys), parameter physcons::con_thgni =-38.15
Definition at line 145 of file physcons.f.
Referenced by module_radiation_clouds::progcld3().
real(kind=kind_phys), parameter physcons::con_tice =2.7120e+2
Definition at line 93 of file physcons.f.
Referenced by module_radiation_surface::setalb().
real(kind=kind_phys), parameter physcons::con_ttp =2.7316e+2
Definition at line 91 of file physcons.f.
Referenced by module_radiation_clouds::diagcld1(), module_radiation_clouds::progcld1(), module_radiation_clouds::progcld2(), module_radiation_clouds::progcld3(), and module_radiation_surface::setalb().
real(kind=kind_phys), parameter physcons::con_xpona =-con_dldt/con_rv
Definition at line 111 of file physcons.f.
real(kind=kind_phys), parameter physcons::con_xponb =-con_dldt/con_rv+con_hvap/(con_rv*con_ttp)
Definition at line 112 of file physcons.f.
real(kind=kind_phys) physcons::dxinv
Definition at line 159 of file physcons.f.
real(kind=kind_phys) physcons::dxmax
Definition at line 159 of file physcons.f.
real(kind=kind_phys) physcons::dxmin
Definition at line 159 of file physcons.f.
integer, parameter physcons::max_lat =2000
Definition at line 154 of file physcons.f.
integer, parameter physcons::max_lon =5000
Definition at line 154 of file physcons.f.
integer, parameter physcons::min_lat =94
Definition at line 154 of file physcons.f.
integer, parameter physcons::min_lon =192
Definition at line 154 of file physcons.f.
real(kind=kind_phys), parameter physcons::pa2mb = 0.01
Definition at line 157 of file physcons.f.
real(kind=kind_phys), parameter physcons::rhc_max = 0.9999
Definition at line 155 of file physcons.f.
real(kind=kind_phys), parameter physcons::rlapse = 0.65e-2
Definition at line 155 of file physcons.f.