Radiation Scheme in CCPP: module_radsw_kgb25 Module Reference
module_radsw_kgb25 Module Reference
This module sets up absorption coeffients for band 25: 16000-22650 cm-1 (low - h2o; high - nothing)
Variables
integer, public msa25
real(kind=kind_phys), dimension(msa25, ng25), public absa
real(kind=kind_phys), dimension(ng25), public rayl
real(kind=kind_phys), dimension(ng25), public abso3a
real(kind=kind_phys), dimension(ng25), public abso3b
Variable Documentation
real (kind=kind_phys), dimension(msa25,ng25), public module_radsw_kgb25::absa
Definition at line 17753 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3a
Definition at line 17753 of file radsw_datatb.f.
Referenced by taumol25().
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::abso3b
Definition at line 17753 of file radsw_datatb.f.
Referenced by taumol25().
integer, public module_radsw_kgb25::msa25
Definition at line 17750 of file radsw_datatb.f.
real (kind=kind_phys), dimension(ng25), public module_radsw_kgb25::rayl
Definition at line 17753 of file radsw_datatb.f.
Referenced by taumol25().