Radiation Scheme in CCPP: module_radiation_aerosols Module Reference
module_radiation_aerosols Module Reference
This module contains climatological atmospheric aerosol schemes for radiation computations.
Data Types
type gocart_index_type
type tracer_index_type
Functions/Subroutines
subroutine, public aer_init
The initialization program to set up necessary parameters and working arrays.
subroutine clim_aerinit
This subroutine is the opac-climatology aerosol initialization program to set up necessary parameters and working arrays.
subroutine, public aer_update
This subroutine checks and updates time varying climatology aerosol data sets.
subroutine gocart_init
the initialization program for gocart aerosols
subroutine setgocartaer
This subroutine computes SW + LW aerosol optical properties for gocart aerosol species (merged from fcst and clim fields).
subroutine, public setaer
This subroutine computes aerosols optical properties.
subroutine aer_property
This subroutine maps the 5 degree global climatological aerosol data set onto model grids, and compute aerosol optical properties for SW and LW radiations.
Variables
character(40), parameter vtagaer ='NCEP-Radiation_aerosols v5.2 Jan 2013 '
integer, parameter, public nf_aesw = 3
num of output fields for sw rad
integer, parameter, public nf_aelw = 3
num of output fields for lw rad
integer, parameter, public nlwstr = 1
starting band number in ir region
integer, parameter, public nspc = 5
num of species for output aod (opnl)
integer, parameter, public nspc1 = NSPC + 1
total+species
real(kind=kind_phys), parameter f_zero = 0.0
real(kind=kind_phys), parameter f_one = 1.0
integer, save nswbnd = NBDSW
integer, save nlwbnd = NBDLW
integer, save nswlwbd = NBDSW+NBDLW
integer, parameter, public nwvsol = 151
num of wvnum regions where solar flux is constant
integer, parameter, public nwvtot = 57600
total num of wvnum included
integer, parameter, public nwvtir = 4000
total num of wvnum in ir range
integer, dimension(nwvsol), save nwvns0
real(kind=kind_phys), dimension(nwvsol), save s0intv
integer, parameter minvyr = 1850
integer, parameter maxvyr = 1999
integer, dimension(:,:,:), allocatable, save ivolae
integer kyrstr
integer kyrend
integer kyrsav
integer kmonsav
integer, parameter nxc = 5
integer, parameter nae = 7
integer, parameter ndm = 5
integer, parameter imxae = 72
integer, parameter jmxae = 37
integer, parameter naerbnd =61
integer, parameter nrhlev =8
integer, parameter ncm1 = 6
integer, parameter ncm2 = 4
integer, parameter ncm = NCM1+NCM2
real(kind=kind_phys), dimension(nrhlev), save rhlev
real(kind=kind_phys), dimension(ndm, nae), save haer
real(kind=kind_phys), dimension(ndm, nae), save prsref
real(kind=kind_phys), dimension(ndm, nae), save sigref
real(kind=kind_phys), dimension(:,:), allocatable, save extrhi
real(kind=kind_phys), dimension(:,:), allocatable, save scarhi
real(kind=kind_phys), dimension(:,:), allocatable, save ssarhi
real(kind=kind_phys), dimension(:,:), allocatable, save asyrhi
real(kind=kind_phys), dimension(:,:,:), allocatable, save extrhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save scarhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save ssarhd
real(kind=kind_phys), dimension(:,:,:), allocatable, save asyrhd
real(kind=kind_phys), dimension(:), allocatable, save extstra
real(kind=kind_phys), dimension(nxc, imxae, jmxae), save cmixg
real(kind=kind_phys), dimension(2,imxae, jmxae), save denng
integer, dimension(nxc, imxae, jmxae), save idxcg
integer, dimension(imxae, jmxae), save kprfg
integer, parameter kaerbnd =61
integer, parameter krhlev =36
integer, save kcm1 = 0
integer, save kcm2 = 0
integer, save kcm
real(kind=kind_phys), dimension(:) rhlev_grt
real(kind=kind_phys), dimension(krhlev) data
integer, dimension(:), allocatable iendwv_grt
real(kind=kind_phys), dimension(:,:), allocatable rhidext0_grt
real(kind=kind_phys), dimension(:,:), allocatable rhidssa0_grt
real(kind=kind_phys), dimension(:,:), allocatable rhidasy0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable rhdpext0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable rhdpssa0_grt
real(kind=kind_phys), dimension(:,:,:), allocatable rhdpasy0_grt
real(kind=kind_phys), dimension(:,:), allocatable, save extrhi_grt
real(kind=kind_phys), dimension(:,:), allocatable, save ssarhi_grt
real(kind=kind_phys), dimension(:,:), allocatable, save asyrhi_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save extrhd_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save ssarhd_grt
real(kind=kind_phys), dimension(:,:,:), allocatable, save asyrhd_grt
integer, parameter imxg = 144
integer, parameter jmxg = 91
integer, parameter kmxg = 30
integer, save nmxg
real(kind=kind_phys), parameter dltx = 360.0 / float(IMXG)
real(kind=kind_phys), parameter dlty = 180.0 / float(JMXG-1)
real(kind=kind_phys), dimension(:,:,:), allocatable, save psclmg
real(kind=kind_phys), dimension(:,:,:,:), allocatable, save dmclmg
real(kind=kind_phys), dimension(:), allocatable, save geos_rlon
real(kind=kind_phys), dimension(:), allocatable, save geos_rlat
character *4, save gocart_climo = 'xxxx'
real(kind=kind_io4), dimension(:), allocatable molwgt
logical, save lgrtint = .true.
logical, save lckprnt = .false.
real(kind=kind_phys), save ctaer = f_zero
logical, save get_fcst = .true.
logical, save get_clim = .true.
integer, save isoot
integer, save iwaso
integer, save isuso
integer, save issam
integer, save isscm
type(gocart_index_type), save dm_indx
type(tracer_index_type), save dmfcs_indx
integer, save num_gridcomp = 0
character, dimension(:), allocatable, save gridcomp
integer, parameter max_num_gridcomp = 5
character *2, dimension(max_num_gridcomp) max_gridcomp
integer, dimension(ncm) idxspc
real(kind=kind_phys), parameter wvn550 = 1.0e4/0.55
integer, save nv_aod = 1
Function/Subroutine Documentation
subroutine, public module_radiation_aerosols::aer_init ()
Parameters
[in] NLAY integer, number of model vertical layers (not used)
[in] me integer, print message control flag
[in] NONE
External Module Variables
physparam::iaermdl: tropospheric aerosol model scheme flag. =0 opac-clim; =1 gocart-clim; =2 gocart-prognostic
physparam::lalwflg: logical lw aerosol effect control flag. =t compute lw aerosol optical property
physparam::laswflg: logical sw aerosols effect control flag. =t compute sw aerosol optical property
physparam::lavoflg: logical stratosphere volcanic aerosol control flag. =t include volcanic aerosol effect
physparam::lalw1bd: logical lw aerosol property 1 band vs multi-band control flag. =t use 1 broad band optical property; =f use multi bands optical property
Subprograms Called
- clim_aerinit: This subprogram is the opac-climatology aerosol initialization program to set up necessary parameters and working arrays.
- wrt_aerlog: This subprogram writes aerosol parameter configuration to run log file.
- set_volcaer: This is the initialization program for stratospheric volcanic aerosols.
- set_spectrum: This subprogram defines the one wavenumber solar fluxes based on toa solar spectral distribution, and define the one wavenumber ir fluxes based on black-body emission distribution at a predefined temperature.
- set_aercoef: This is the initialization program for climatological aerosols. The program reads and maps the pre-tabulated aerosol optical spectral data onto corresponding sw radiation spectral bands.
- optavg: This subprogram computes mean aerosols optical properties over each sw radiation spectral band for each of the species components. This program follows gfdl's approach for thick cloud optical property in sw radiation scheme.
Definition at line 565 of file radiation_aerosols.f.
References clim_aerinit(), physparam::iaerflg, physparam::iaermdl, kmonsav, kyrend, kyrsav, kyrstr, physparam::lalw1bd, physparam::lalwflg, physparam::laswflg, physparam::lavoflg, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nswbnd, nswlwbd, set_spectrum(), set_volcaer(), and wrt_aerlog().
Referenced by module_radiation_driver::radinit().
subroutine module_radiation_aerosols::aer_property () private
Parameters
[in] prsi real, (IMAX,NLP1), pressure at interface in mb
[in] prsl real, (IMAX,NLAY), layer mean pressure(not used)
[in] prslk real, (IMAX,NLAY), exner function= \((p/p0)^{rocp}\) (not used)
[in] tvly real, (IMAX,NLAY), layer virtual temperature (not used)
[in] rhlay real, (IMAX,NLAY), layer mean relative humidity
[in] dz real, (IMAX,NLAY), layer thickness in m
[in] hz real, (IMAX,NLP1), level high in m
[in] tracer real, (IMAX,NLAY,NTRAC), aer tracer concentrations (not used)
[in] alon,alat real, (IMAX), longitude and latitude of given points in degree
[in] slmsk real, (IMAX), sea/land mask (sea:0,land:1,sea-ice:2)
[in] laersw,laerlw logical, 1, logical flag for sw/lw aerosol calculations
[in] IMAX integer, 1, horizontal dimension of arrays
[in] NLAY,NLP1 integer, 1, vertical dimensions of arrays
[in] NSPC integer, 1, num of species for optional aod output fields
[out] aerosw real, (IMAX,NLAY,NBDSW,NF_AESW), aeros opt properties for sw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerolw real, (IMAX,NLAY,NBDLW,NF_AELW), aeros opt properties for lw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerodp real, (IMAX,NSPC+1), vertically integrated aer-opt-depth
Map aerosol data to model grids
Map grid in longitude direction, lon from 0 to 355 deg resolution
Map grid in latitude direction, lat from 90n to 90s in 5 deg resolution
Determin the type of aerosol profile (kp) and scale hight for domain 1 (h1) to be used at this grid point
Compute horizontal bi-linear interpolation weights
Do horizontal bi-linear interpolation on aerosol partical density (denn)
Do horizontal bi-linear interpolation on mixing ratios
Prepare to setup domain index array and effective layer thickness. also convert pressure level to sigma level to follow the terrain
Call radclimaer() to calculate sw/lw aerosol optical properties for the corresponding frequency bands
Definition at line 2608 of file radiation_aerosols.f.
References cmixg, denng, f_one, f_zero, haer, idxcg, imxae, physparam::ivflip, jmxae, kprfg, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nspc, nswbnd, nv_aod, nxc, prsref, radclimaer(), and sigref.
Referenced by setaer().
subroutine, public module_radiation_aerosols::aer_update ()
Parameters
[in] iyear integer, 1, 4-digit calender year
[in] imon integer, 1, month of the year
[in] me integer, 1, print message control flag
[out] NONE
External Module Variables
physparam::lalwflg - control flag for tropospheric lw aerosol
physparam::laswflg - control flag for tropospheric sw aerosol
physparam::lavoflg - control flag for stratospheric volcanic aerosol
Subprograms Called
- trop_update: This subprogram updates the monthly global distribution of aerosol profiles in five degree horizontal resolution.
- volc_update: This subprogram searches historical volcanic data sets to find and read in monthly 45-degree lat-zone band data of optical depth
Definition at line 1648 of file radiation_aerosols.f.
References physparam::lalwflg, physparam::laswflg, physparam::lavoflg, trop_update(), and volc_update().
Referenced by module_radiation_driver::radupdate().
subroutine module_radiation_aerosols::clim_aerinit () private
Parameters
[in] solfwv real, (NWVTOT), solar flux for each individual wavenumber \((w/m^2)\)
[in] eirfwv real, (NWVTIR), ir flux(273k) for each individual wavenum \((w/m^2)\)
[in] me integer, 1, print message control flag
Definition at line 946 of file radiation_aerosols.f.
References set_aercoef().
Referenced by aer_init().
subroutine module_radiation_aerosols::gocart_init () private
determine weight and index for aerosol composition/luts
read in monthly global distribution of gocart aerosols
read and map the tabulated aerosol optical spectral data onto corresponding SW/LW radiation spectral bands.
Definition at line 3374 of file radiation_aerosols.f.
References extrhd_grt, extrhi_grt, f_zero, get_clim, iendwv_grt, kaerbnd, krhlev, lckprnt, lgrtint, module_radsw_parameters::nbdsw, nlwbnd, nswlwbd, module_radsw_parameters::nswstr, nv_aod, nwvtir, nwvtot, optavg_grt(), rd_gocart_clim(), rd_gocart_luts(), rhdpasy0_grt, rhdpext0_grt, rhdpssa0_grt, rhidasy0_grt, rhidext0_grt, rhidssa0_grt, rhlev_grt, set_aerspc(), module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
subroutine, public module_radiation_aerosols::setaer ()
Parameters
[in] prsi (IMAX,NLP1), pressure at interface in mb
[in] prsl (IMAX,NLAY), layer mean pressure in mb
[in] prslk (IMAX,NLAY), exner function = \((p/p0)^{rocp}\)
[in] tvly (IMAX,NLAY), layer virtual temperature in K
[in] rhlay (IMAX,NLAY), layer mean relative humidity
[in] slmsk (IMAX), sea/land mask (sea:0,land:1,sea-ice:2)
[in] tracer (IMAX,NLAY,NTRAC), aerosol tracer concentration
[in] xlon (IMAX), longitude of given points in radiance, ok for both 0->2pi or -pi->+pi ranges
[in] xlat (IMAX), latitude of given points in radiance, default to pi/2 -> -pi/2, otherwise see in-line comment
[in] IMAX 1, horizontal dimension of arrays
[in] NLAY,NLP1 1, vertical dimensions of arrays
[in] lsswr,lslwr logical flags for sw/lw radiation calls
[out] aerosw (IMAX,NLAY,NBDSW,NF_AESW), aeros opt properties for sw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] aerolw (IMAX,NLAY,NBDLW,NF_AELW), aeros opt properties for lw
(:,:,:,1): optical depth
(:,:,:,2): single scattering albedo
(:,:,:,3): asymmetry parameter
[out] tau_gocart (IMAX,NLAY,MAX_NUM_GRIDCOMP), 550nm aeros opt depth
[out] aerodp (IMAX,NSPC1), vertically integrated optical depth
General Algorithm
Convert lat/lon from radiance to degree
Compute level height and layer thickness
Calculate sw aerosol optical properties for the corresponding frequency bands
if opac aerosol climatology is used, call aer_property(): this subroutine maps the 5 degree global climatological aerosol data set onto model grids, and compute aerosol optical properties for sw and lw radiations.
if gocart aerosol scheme is used, call setgocartaer(): this subroutine computes sw + lw aerosol optical properties for gocart aerosol species (merged from fcst and clim fields)
Compute stratosphere volcanic forcing
select data in 4 lat bands, interpolation at the boundaries
Find lower boundary of stratosphere: polar, fixed at 25000pa (250mb); tropic, fixed at 15000pa (150mb); mid-lat, interpolation
sw: add volcanic aerosol optical depth to the background value
Smoothing profile at boundary if needed
lw: add volcanic aerosol optical depth to the background value
Definition at line 2019 of file radiation_aerosols.f.
References aer_property(), physcons::con_g, f_one, f_zero, physparam::iaerflg, physparam::iaermdl, physparam::ivflip, ivolae, kmonsav, kyrsav, physparam::lalwflg, physparam::laswflg, physparam::lavoflg, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nf_aelw, nf_aesw, nlwbnd, nspc1, nswlwbd, module_radsw_parameters::nswstr, setgocartaer(), module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
Referenced by module_radiation_driver::grrad().
subroutine module_radiation_aerosols::setgocartaer () private
Definition at line 4706 of file radiation_aerosols.f.
References aeropt_grt(), physcons::con_amd, physcons::con_rd, ctaer, dmclmg, f_one, f_zero, geos_rlat, geos_rlon, get_clim, get_fcst, gocart_climo, imxg, physparam::ivflip, jmxg, kmxg, physparam::lalwflg, physparam::laswflg, map_aermr(), molwgt, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, nlwbnd, nmxg, nswlwbd, and psclmg.
Referenced by setaer().
Variable Documentation
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd private
Definition at line 299 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::asyrhd_grt private
Definition at line 385 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi private
Definition at line 297 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::asyrhi_grt private
Definition at line 383 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
real (kind=kind_phys), dimension(nxc,imxae,jmxae), save module_radiation_aerosols::cmixg private
Definition at line 311 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
real (kind=kind_phys), save module_radiation_aerosols::ctaer = f_zero private
Definition at line 450 of file radiation_aerosols.f.
Referenced by set_aerspc(), and setgocartaer().
real (kind=kind_phys), dimension(krhlev) module_radiation_aerosols::data private
Definition at line 331 of file radiation_aerosols.f.
real (kind=kind_phys), dimension(2 ,imxae,jmxae), save module_radiation_aerosols::denng private
Definition at line 312 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
real (kind=kind_phys), parameter module_radiation_aerosols::dltx = 360.0 / float(IMXG) private
Definition at line 410 of file radiation_aerosols.f.
Referenced by rd_gocart_clim().
real (kind=kind_phys), parameter module_radiation_aerosols::dlty = 180.0 / float(JMXG-1) private
Definition at line 411 of file radiation_aerosols.f.
Referenced by rd_gocart_clim().
type (gocart_index_type), save module_radiation_aerosols::dm_indx private
Definition at line 491 of file radiation_aerosols.f.
Referenced by aeropt_grt(), map_aermr(), rd_gocart_clim(), and set_aerspc().
real (kind=kind_phys), dimension(:,:,:,:), allocatable, save module_radiation_aerosols::dmclmg private
Definition at line 419 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
type (tracer_index_type), save module_radiation_aerosols::dmfcs_indx private
Definition at line 501 of file radiation_aerosols.f.
Referenced by map_aermr(), and set_aerspc().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd private
Definition at line 299 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::extrhd_grt private
Definition at line 385 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi private
Definition at line 297 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::extrhi_grt private
Definition at line 383 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), and optavg_grt().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::extstra private
Definition at line 301 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), parameter module_radiation_aerosols::f_one = 1.0 private
Definition at line 156 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), optavg(), optavg_grt(), radclimaer(), set_aerspc(), setaer(), setgocartaer(), and trop_update().
real (kind=kind_phys), parameter module_radiation_aerosols::f_zero = 0.0 private
Definition at line 155 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), gocart_init(), map_aermr(), optavg(), optavg_grt(), radclimaer(), rd_gocart_clim(), set_aercoef(), set_aerspc(), setaer(), setgocartaer(), and trop_update().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlat private
Definition at line 423 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
real (kind=kind_phys), dimension(:), allocatable, save module_radiation_aerosols::geos_rlon private
Definition at line 423 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
logical, save module_radiation_aerosols::get_clim = .true. private
Definition at line 454 of file radiation_aerosols.f.
Referenced by gocart_init(), set_aerspc(), and setgocartaer().
logical, save module_radiation_aerosols::get_fcst = .true. private
Definition at line 453 of file radiation_aerosols.f.
Referenced by set_aerspc(), and setgocartaer().
character*4, save module_radiation_aerosols::gocart_climo = 'xxxx' private
Definition at line 428 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
character, dimension(:), allocatable, save module_radiation_aerosols::gridcomp private
Definition at line 505 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_clim(), and set_aerspc().
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::haer private
Definition at line 274 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
integer, dimension(nxc,imxae,jmxae), save module_radiation_aerosols::idxcg private
Definition at line 313 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
integer, dimension(ncm) module_radiation_aerosols::idxspc private
Definition at line 524 of file radiation_aerosols.f.
Referenced by radclimaer().
integer, dimension(:), allocatable module_radiation_aerosols::iendwv_grt private
Definition at line 368 of file radiation_aerosols.f.
Referenced by gocart_init(), and rd_gocart_luts().
integer, parameter module_radiation_aerosols::imxae = 72 private
Definition at line 256 of file radiation_aerosols.f.
Referenced by aer_property(), set_aercoef(), and trop_update().
integer, parameter module_radiation_aerosols::imxg = 144 private
Definition at line 404 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, save module_radiation_aerosols::isoot private
Definition at line 476 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::issam private
Definition at line 476 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::isscm private
Definition at line 476 of file radiation_aerosols.f.
Referenced by rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::isuso private
Definition at line 476 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, dimension(:,:,:), allocatable, save module_radiation_aerosols::ivolae private
Definition at line 242 of file radiation_aerosols.f.
Referenced by set_volcaer(), setaer(), and volc_update().
integer, save module_radiation_aerosols::iwaso private
Definition at line 476 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_luts(), and set_aerspc().
integer, parameter module_radiation_aerosols::jmxae = 37 private
Definition at line 257 of file radiation_aerosols.f.
Referenced by aer_property(), set_aercoef(), and trop_update().
integer, parameter module_radiation_aerosols::jmxg = 91 private
Definition at line 405 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, parameter module_radiation_aerosols::kaerbnd =61 private
Definition at line 322 of file radiation_aerosols.f.
Referenced by gocart_init(), and rd_gocart_luts().
integer, save module_radiation_aerosols::kcm private
Definition at line 329 of file radiation_aerosols.f.
Referenced by set_aerspc().
integer, save module_radiation_aerosols::kcm1 = 0 private
Definition at line 327 of file radiation_aerosols.f.
Referenced by aeropt_grt(), optavg_grt(), rd_gocart_luts(), and set_aerspc().
integer, save module_radiation_aerosols::kcm2 = 0 private
Definition at line 328 of file radiation_aerosols.f.
Referenced by optavg_grt(), rd_gocart_luts(), and set_aerspc().
integer module_radiation_aerosols::kmonsav private
Definition at line 245 of file radiation_aerosols.f.
Referenced by aer_init(), setaer(), and volc_update().
integer, parameter module_radiation_aerosols::kmxg = 30 private
Definition at line 406 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, dimension(imxae,jmxae), save module_radiation_aerosols::kprfg private
Definition at line 314 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
integer, parameter module_radiation_aerosols::krhlev =36 private
Definition at line 323 of file radiation_aerosols.f.
Referenced by aeropt_grt(), gocart_init(), optavg_grt(), and rd_gocart_luts().
integer module_radiation_aerosols::kyrend private
Definition at line 245 of file radiation_aerosols.f.
Referenced by aer_init(), and volc_update().
integer module_radiation_aerosols::kyrsav private
Definition at line 245 of file radiation_aerosols.f.
Referenced by aer_init(), setaer(), and volc_update().
integer module_radiation_aerosols::kyrstr private
Definition at line 245 of file radiation_aerosols.f.
Referenced by aer_init(), and volc_update().
logical, save module_radiation_aerosols::lckprnt = .false. private
Definition at line 445 of file radiation_aerosols.f.
Referenced by gocart_init(), rd_gocart_luts(), and set_aerspc().
logical, save module_radiation_aerosols::lgrtint = .true. private
Definition at line 441 of file radiation_aerosols.f.
Referenced by gocart_init().
character*2, dimension(max_num_gridcomp) module_radiation_aerosols::max_gridcomp private
Definition at line 509 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and set_aerspc().
integer, parameter module_radiation_aerosols::max_num_gridcomp = 5 private
Definition at line 508 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and set_aerspc().
integer, parameter module_radiation_aerosols::maxvyr = 1999 private
Definition at line 239 of file radiation_aerosols.f.
Referenced by volc_update().
integer, parameter module_radiation_aerosols::minvyr = 1850 private
Definition at line 238 of file radiation_aerosols.f.
Referenced by volc_update().
real (kind=kind_io4), dimension(:), allocatable module_radiation_aerosols::molwgt private
Definition at line 431 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
integer, parameter module_radiation_aerosols::nae = 7 private
Definition at line 254 of file radiation_aerosols.f.
integer, parameter module_radiation_aerosols::naerbnd =61 private
Definition at line 258 of file radiation_aerosols.f.
Referenced by set_aercoef().
integer, parameter module_radiation_aerosols::ncm = NCM1+NCM2 private
Definition at line 262 of file radiation_aerosols.f.
Referenced by radclimaer().
integer, parameter module_radiation_aerosols::ncm1 = 6 private
Definition at line 260 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
integer, parameter module_radiation_aerosols::ncm2 = 4 private
Definition at line 261 of file radiation_aerosols.f.
Referenced by optavg(), and set_aercoef().
integer, parameter module_radiation_aerosols::ndm = 5 private
Definition at line 255 of file radiation_aerosols.f.
integer, parameter, public module_radiation_aerosols::nf_aelw = 3
Definition at line 147 of file radiation_aerosols.f.
Referenced by setaer().
integer, parameter, public module_radiation_aerosols::nf_aesw = 3
Definition at line 145 of file radiation_aerosols.f.
Referenced by setaer().
integer, save module_radiation_aerosols::nlwbnd = NBDLW private
Definition at line 161 of file radiation_aerosols.f.
Referenced by aer_init(), aer_property(), gocart_init(), optavg(), set_aercoef(), setaer(), and setgocartaer().
integer, parameter, public module_radiation_aerosols::nlwstr = 1
Definition at line 149 of file radiation_aerosols.f.
Referenced by set_aercoef().
integer, save module_radiation_aerosols::nmxg private
Definition at line 408 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), set_aerspc(), and setgocartaer().
integer, parameter module_radiation_aerosols::nrhlev =8 private
Definition at line 259 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
integer, parameter, public module_radiation_aerosols::nspc = 5
Definition at line 151 of file radiation_aerosols.f.
Referenced by aer_property().
integer, parameter, public module_radiation_aerosols::nspc1 = NSPC + 1
Definition at line 153 of file radiation_aerosols.f.
Referenced by setaer().
integer, save module_radiation_aerosols::nswbnd = NBDSW private
Definition at line 159 of file radiation_aerosols.f.
Referenced by aer_init(), aer_property(), optavg(), radclimaer(), and set_aercoef().
integer, save module_radiation_aerosols::nswlwbd = NBDSW+NBDLW private
Definition at line 163 of file radiation_aerosols.f.
Referenced by aer_init(), gocart_init(), radclimaer(), set_aercoef(), setaer(), and setgocartaer().
integer, save module_radiation_aerosols::num_gridcomp = 0 private
Definition at line 504 of file radiation_aerosols.f.
Referenced by aeropt_grt(), rd_gocart_clim(), and set_aerspc().
integer, save module_radiation_aerosols::nv_aod = 1 private
Definition at line 531 of file radiation_aerosols.f.
Referenced by aer_property(), aeropt_grt(), gocart_init(), radclimaer(), and set_aercoef().
integer, dimension(nwvsol), save module_radiation_aerosols::nwvns0 private
Definition at line 180 of file radiation_aerosols.f.
Referenced by set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvsol = 151
Definition at line 172 of file radiation_aerosols.f.
Referenced by set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvtir = 4000
Definition at line 177 of file radiation_aerosols.f.
Referenced by gocart_init(), and set_spectrum().
integer, parameter, public module_radiation_aerosols::nwvtot = 57600
Definition at line 175 of file radiation_aerosols.f.
Referenced by gocart_init().
integer, parameter module_radiation_aerosols::nxc = 5 private
Definition at line 253 of file radiation_aerosols.f.
Referenced by aer_property(), and trop_update().
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::prsref private
Definition at line 274 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::psclmg private
Definition at line 419 of file radiation_aerosols.f.
Referenced by rd_gocart_clim(), and setgocartaer().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpasy0_grt private
Definition at line 371 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpext0_grt private
Definition at line 371 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:,:), allocatable module_radiation_aerosols::rhdpssa0_grt private
Definition at line 371 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidasy0_grt private
Definition at line 369 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidext0_grt private
Definition at line 369 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(:,:), allocatable module_radiation_aerosols::rhidssa0_grt private
Definition at line 369 of file radiation_aerosols.f.
Referenced by gocart_init(), optavg_grt(), and rd_gocart_luts().
real (kind=kind_phys), dimension(nrhlev), save module_radiation_aerosols::rhlev private
Definition at line 264 of file radiation_aerosols.f.
Referenced by radclimaer().
real (kind=kind_phys), dimension (:) module_radiation_aerosols::rhlev_grt private
Definition at line 331 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and gocart_init().
real (kind=kind_phys), dimension(nwvsol), save module_radiation_aerosols::s0intv private
Definition at line 196 of file radiation_aerosols.f.
Referenced by set_spectrum().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::scarhd private
Definition at line 299 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::scarhi private
Definition at line 297 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(ndm,nae), save module_radiation_aerosols::sigref private
Definition at line 274 of file radiation_aerosols.f.
Referenced by aer_property(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd private
Definition at line 299 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:,:), allocatable, save module_radiation_aerosols::ssarhd_grt private
Definition at line 385 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi private
Definition at line 297 of file radiation_aerosols.f.
Referenced by optavg(), radclimaer(), and set_aercoef().
real (kind=kind_phys), dimension(:,:), allocatable, save module_radiation_aerosols::ssarhi_grt private
Definition at line 383 of file radiation_aerosols.f.
Referenced by aeropt_grt(), and optavg_grt().
character(40), parameter module_radiation_aerosols::vtagaer ='NCEP-Radiation_aerosols v5.2 Jan 2013 ' private
Definition at line 138 of file radiation_aerosols.f.
Referenced by wrt_aerlog().
real (kind=kind_phys), parameter module_radiation_aerosols::wvn550 = 1.0e4/0.55 private
Definition at line 530 of file radiation_aerosols.f.
Referenced by set_aercoef().