Radiation Scheme in CCPP: module_radsw_kgb19 Module Reference
module_radsw_kgb19 Module Reference
This module sets up absorption coeffients for band 19: 4650-5150 cm-1 (low - h2o,co2; high - co2)
Variables
integer, public msa19
integer, public msb19
integer, public msf19
integer, public mfr19
real(kind=kind_phys), dimension(msf19, ng19), public selfref
real(kind=kind_phys), dimension(msa19, ng19), public absa
real(kind=kind_phys), dimension(msb19, ng19), public absb
real(kind=kind_phys), dimension(mfr19, ng19), public forref
real(kind=kind_phys), parameter, public rayl = 2.29e-09
Variable Documentation
real (kind=kind_phys), dimension(msa19,ng19), public module_radsw_kgb19::absa
Definition at line 9420 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(msb19,ng19), public module_radsw_kgb19::absb
Definition at line 9420 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(mfr19,ng19), public module_radsw_kgb19::forref
Definition at line 9420 of file radsw_datatb.f.
Referenced by taumol19().
integer, public module_radsw_kgb19::mfr19
Definition at line 9417 of file radsw_datatb.f.
integer, public module_radsw_kgb19::msa19
Definition at line 9417 of file radsw_datatb.f.
integer, public module_radsw_kgb19::msb19
Definition at line 9417 of file radsw_datatb.f.
integer, public module_radsw_kgb19::msf19
Definition at line 9417 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb19::rayl = 2.29e-09
Definition at line 9424 of file radsw_datatb.f.
Referenced by taumol19().
real (kind=kind_phys), dimension(msf19,ng19), public module_radsw_kgb19::selfref
Definition at line 9420 of file radsw_datatb.f.
Referenced by taumol19().