Radiation Scheme in CCPP: module_radlw_kgb06 Module Reference
module_radlw_kgb06 Module Reference
This module sets up absorption coefficients for band 06: 820-980 cm-1 (low - h2o; high - /)
Variables
integer, public msa06
integer, public msf06
integer, public mfr06
integer, public mmc06
real(kind=kind_phys), dimension(ng06, mfr06), public forref
real(kind=kind_phys), dimension(ng06, msa06), public absa
real(kind=kind_phys), dimension(ng06), public fracrefa
real(kind=kind_phys), dimension(ng06, msf06), public selfref
real(kind=kind_phys), dimension(ng06, mmc06), public ka_mco2
real(kind=kind_phys), dimension(ng06), public cfc11adj
real(kind=kind_phys), dimension(ng06), public cfc12
Variable Documentation
real (kind=kind_phys), dimension(ng06,msa06), public module_radlw_kgb06::absa
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc11adj
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::cfc12
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06,mfr06), public module_radlw_kgb06::forref
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06), public module_radlw_kgb06::fracrefa
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
real (kind=kind_phys), dimension(ng06,mmc06), public module_radlw_kgb06::ka_mco2
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().
integer, public module_radlw_kgb06::mfr06
Definition at line 21709 of file radlw_datatb.f.
integer, public module_radlw_kgb06::mmc06
Definition at line 21709 of file radlw_datatb.f.
integer, public module_radlw_kgb06::msa06
Definition at line 21709 of file radlw_datatb.f.
integer, public module_radlw_kgb06::msf06
Definition at line 21709 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng06,msf06), public module_radlw_kgb06::selfref
Definition at line 21712 of file radlw_datatb.f.
Referenced by taugb06().