Radiation Scheme in CCPP: module_radlw_ref Module Reference
module_radlw_ref Module Reference
This module contains reference temperature and pressure.
Variables
real(kind=kind_phys), dimension(59) pref
real(kind=kind_phys), dimension(59) preflog
real(kind=kind_phys), dimension(59) tref
real(kind=kind_phys), dimension(7, 59) chi_mls
Variable Documentation
real (kind=kind_phys), dimension(7,59) module_radlw_ref::chi_mls
Definition at line 791 of file radlw_datatb.f.
Referenced by module_radlw_main::setcoef(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), dimension(59) module_radlw_ref::pref
Definition at line 743 of file radlw_datatb.f.
real (kind=kind_phys), dimension(59) module_radlw_ref::preflog
Definition at line 743 of file radlw_datatb.f.
Referenced by module_radlw_main::setcoef().
real (kind=kind_phys), dimension(59) module_radlw_ref::tref
Definition at line 743 of file radlw_datatb.f.
Referenced by module_radlw_main::setcoef().