Radiation Scheme in CCPP: module_radsw_kgb22 Module Reference
module_radsw_kgb22 Module Reference
This module sets up absorption coeffients for band 22: 7700-8050 cm-1 (low - h2o, o2; high - o2)
Variables
integer, public msa22
integer, public msb22
integer, public msf22
integer, public mfr22
real(kind=kind_phys), dimension(mfr22, ng22), public forref
real(kind=kind_phys), dimension(msa22, ng22), public absa
real(kind=kind_phys), dimension(msb22, ng22), public absb
real(kind=kind_phys), dimension(msf22, ng22), public selfref
real(kind=kind_phys), parameter, public rayl = 1.54e-08
Variable Documentation
real (kind=kind_phys), dimension(msa22,ng22), public module_radsw_kgb22::absa
Definition at line 15542 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(msb22,ng22), public module_radsw_kgb22::absb
Definition at line 15542 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(mfr22,ng22), public module_radsw_kgb22::forref
Definition at line 15542 of file radsw_datatb.f.
Referenced by taumol22().
integer, public module_radsw_kgb22::mfr22
Definition at line 15539 of file radsw_datatb.f.
integer, public module_radsw_kgb22::msa22
Definition at line 15539 of file radsw_datatb.f.
integer, public module_radsw_kgb22::msb22
Definition at line 15539 of file radsw_datatb.f.
integer, public module_radsw_kgb22::msf22
Definition at line 15539 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb22::rayl = 1.54e-08
Definition at line 15546 of file radsw_datatb.f.
Referenced by taumol22().
real (kind=kind_phys), dimension(msf22,ng22), public module_radsw_kgb22::selfref
Definition at line 15542 of file radsw_datatb.f.
Referenced by taumol22().