Radiation Scheme in CCPP: module_radsw_kgb17 Module Reference
module_radsw_kgb17 Module Reference
This module sets up absorption coeffients for band 17: 3250-4000 cm-1 (low - h2o,co2; high - h2o,co2)
Variables
integer, public msa17
integer, public msb17
integer, public msf17
integer, public mfr17
real(kind=kind_phys), dimension(msf17, ng17), public selfref
real(kind=kind_phys), dimension(msa17, ng17), public absa
real(kind=kind_phys), dimension(msb17, ng17), public absb
real(kind=kind_phys), dimension(mfr17, ng17), public forref
real(kind=kind_phys), parameter, public rayl = 6.86e-10
Variable Documentation
real (kind=kind_phys), dimension(msa17,ng17), public module_radsw_kgb17::absa
Definition at line 3314 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(msb17,ng17), public module_radsw_kgb17::absb
Definition at line 3314 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(mfr17,ng17), public module_radsw_kgb17::forref
Definition at line 3314 of file radsw_datatb.f.
Referenced by taumol17().
integer, public module_radsw_kgb17::mfr17
Definition at line 3311 of file radsw_datatb.f.
integer, public module_radsw_kgb17::msa17
Definition at line 3311 of file radsw_datatb.f.
integer, public module_radsw_kgb17::msb17
Definition at line 3311 of file radsw_datatb.f.
integer, public module_radsw_kgb17::msf17
Definition at line 3311 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb17::rayl = 6.86e-10
Definition at line 3318 of file radsw_datatb.f.
Referenced by taumol17().
real (kind=kind_phys), dimension(msf17,ng17), public module_radsw_kgb17::selfref
Definition at line 3314 of file radsw_datatb.f.
Referenced by taumol17().