Radiation Scheme in CCPP: module_radsw_kgb27 Module Reference
module_radsw_kgb27 Module Reference
This module sets up absorption coeffients for band 27: 29000-38000 cm-1 (low - o3; high - o3)
Variables
integer, public msa27
integer, public msb27
real(kind=kind_phys), dimension(msa27, ng27), public absa
real(kind=kind_phys), dimension(msb27, ng27), public absb
real(kind=kind_phys), dimension(ng27), public rayl
Variable Documentation
real (kind=kind_phys), dimension(msa27,ng27), public module_radsw_kgb27::absa
Definition at line 17940 of file radsw_datatb.f.
Referenced by taumol27().
real (kind=kind_phys), dimension(msb27,ng27), public module_radsw_kgb27::absb
Definition at line 17940 of file radsw_datatb.f.
Referenced by taumol27().
integer, public module_radsw_kgb27::msa27
Definition at line 17937 of file radsw_datatb.f.
integer, public module_radsw_kgb27::msb27
Definition at line 17937 of file radsw_datatb.f.
real (kind=kind_phys), dimension(ng27), public module_radsw_kgb27::rayl
Definition at line 17940 of file radsw_datatb.f.
Referenced by taumol27().