Radiation Scheme in CCPP: module_radlw_kgb16 Module Reference
module_radlw_kgb16 Module Reference
This module sets up absorption coefficients for band 16: 2600-3000 cm-1 (low - h2o, ch4; high - /)
Variables
integer, public msa16
integer, public msb16
integer, public msf16
integer, public mfr16
integer, public maf16
real(kind=kind_phys), dimension(ng16, mfr16), public forref
real(kind=kind_phys), dimension(ng16, msa16), public absa
real(kind=kind_phys), dimension(ng16, msb16), public absb
real(kind=kind_phys), dimension(ng16, msf16), public selfref
real(kind=kind_phys), dimension(ng16, maf16), public fracrefa
real(kind=kind_phys), dimension(ng16), public fracrefb
Variable Documentation
real (kind=kind_phys), dimension(ng16,msa16), public module_radlw_kgb16::absa
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng16,msb16), public module_radlw_kgb16::absb
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng16,mfr16), public module_radlw_kgb16::forref
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng16,maf16), public module_radlw_kgb16::fracrefa
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().
real (kind=kind_phys), dimension(ng16), public module_radlw_kgb16::fracrefb
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().
integer, public module_radlw_kgb16::maf16
Definition at line 31645 of file radlw_datatb.f.
integer, public module_radlw_kgb16::mfr16
Definition at line 31645 of file radlw_datatb.f.
integer, public module_radlw_kgb16::msa16
Definition at line 31645 of file radlw_datatb.f.
integer, public module_radlw_kgb16::msb16
Definition at line 31645 of file radlw_datatb.f.
integer, public module_radlw_kgb16::msf16
Definition at line 31645 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng16,msf16), public module_radlw_kgb16::selfref
Definition at line 31648 of file radlw_datatb.f.
Referenced by taugb16().