Radiation Scheme in CCPP: module_radlw_kgb13 Module Reference
module_radlw_kgb13 Module Reference
This module sets up absorption coefficients for band 13: 2080-2250 cm-1 (low - h2o, n2o; high - /)
Variables
integer, public msa13
integer, public msf13
integer, public mfr13
integer, public maf13
integer, public mmo13
real(kind=kind_phys), dimension(ng13, msa13), public absa
real(kind=kind_phys), dimension(ng13, mfr13), public forref
real(kind=kind_phys), dimension(ng13, msf13), public selfref
real(kind=kind_phys), dimension(ng13, maf13), public fracrefa
real(kind=kind_phys), dimension(ng13), public fracrefb
real(kind=kind_phys), dimension(ng13, maf13, mmo13), public ka_mco2
real(kind=kind_phys), dimension(ng13, maf13, mmo13), public ka_mco
real(kind=kind_phys), dimension(ng13, mmo13), public kb_mo3
Variable Documentation
real (kind=kind_phys), dimension(ng13,msa13), public module_radlw_kgb13::absa
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13,mfr13), public module_radlw_kgb13::forref
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13,maf13), public module_radlw_kgb13::fracrefa
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13), public module_radlw_kgb13::fracrefb
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13,maf13,mmo13), public module_radlw_kgb13::ka_mco
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13,maf13,mmo13), public module_radlw_kgb13::ka_mco2
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
real (kind=kind_phys), dimension(ng13,mmo13), public module_radlw_kgb13::kb_mo3
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().
integer, public module_radlw_kgb13::maf13
Definition at line 30177 of file radlw_datatb.f.
integer, public module_radlw_kgb13::mfr13
Definition at line 30177 of file radlw_datatb.f.
integer, public module_radlw_kgb13::mmo13
Definition at line 30177 of file radlw_datatb.f.
integer, public module_radlw_kgb13::msa13
Definition at line 30177 of file radlw_datatb.f.
integer, public module_radlw_kgb13::msf13
Definition at line 30177 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng13,msf13), public module_radlw_kgb13::selfref
Definition at line 30180 of file radlw_datatb.f.
Referenced by taugb13().