Radiation Scheme in CCPP: module_radlw_main Module Reference
module_radlw_main Module Reference
This module includes ncep's modifications of the rrtm-lw radiation ! code from aer inc.
Functions/Subroutines
subroutine, public rlwinit
This subroutine performs calculations necessary for the initialization of the longwave model. lookup tables are computed for use in the lw radiative transfer, and input absorption coefficient data for each spectral band are reduced from 256 g-point intervals to 140.
subroutine mcica_subcol
This suroutine computes sub-colum cloud profile flag array.
subroutine setcoef
This subroutine computes various coefficients needed in radiative transfer calculations.
subroutine rtrn
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds assumed as randomly overlaping in a vertical column.
subroutine taumol
This subroutine contains optical depths developed for the rapid radiative transfer model.
subroutine, public lwrad
This subroutine is the main lw radiation routine.
subroutine cldprop
This subroutine computes the cloud optical depth(s) for each cloudy layer and g-point interval.
subroutine rtrnmr
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds are assumed as in maximum-randomly overlaping in a vertical column.
subroutine rtrnmc
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere.Clouds are treated with the mcica stochastic approach.
Variables
character(40), parameter vtaglw ='NCEP LW v5.1 Nov 2012 -RRTMG-LW v4.82 '
real(kind=kind_phys), parameter eps = 1.0e-6
real(kind=kind_phys), parameter oneminus = 1.0-eps
real(kind=kind_phys), parameter cldmin = 1.0e-80
real(kind=kind_phys), parameter bpade = 1.0/0.278
real(kind=kind_phys), parameter stpfac = 296.0/1013.0
real(kind=kind_phys), parameter wtdiff = 0.5
real(kind=kind_phys), parameter tblint = ntbl
real(kind=kind_phys), parameter f_zero = 0.0
real(kind=kind_phys), parameter f_one = 1.0
real(kind=kind_phys), parameter amdw = con_amd/con_amw
real(kind=kind_phys), parameter amdo3 = con_amd/con_amo3
integer, dimension(nbands) nspa
integer, dimension(nbands) nspb
real(kind=kind_phys), dimension(nbands) a0
real(kind=kind_phys), dimension(nbands) a1
real(kind=kind_phys), dimension(nbands) a2
logical lhlwb = .false.
logical lhlw0 = .false.
logical lflxprf = .false.
real(kind=kind_phys) fluxfac
real(kind=kind_phys) heatfac
real(kind=kind_phys), dimension(nbands) semiss0
real(kind=kind_phys), dimension(0:ntbl) tau_tbl
real(kind=kind_phys), dimension(0:ntbl) exp_tbl
real(kind=kind_phys), dimension(0:ntbl) tfn_tbl
integer, parameter ipsdlw0 = ngptlw
Function/Subroutine Documentation
subroutine module_radlw_main::cldprop () private
Parameters
[in] cfrac real, (0:nlp1), layer cloud fraction
..... for ilwcliq > 0 (prognostic cloud scheme) - - -
[in] cliqp real, (nlay), layer in-cloud liq water path (\(g/m^2\))
[in] reliq real, (nlay), mean eff radius for liq cloud (micron)
[in] cicep real, (nlay), layer in-cloud ice water path (\(g/m^2\))
[in] reice real, (nlay), mean eff radius for ice cloud (micron)
[in] cdat1 real, (nlay), layer rain drop water path (\(g/m^2\))
[in] cdat2 real, (nlay), effective radius for rain drop (micron)
[in] cdat3 real, (nlay), layer snow flake water path(\(g/m^2\))
[in] cdat4 real, (nlay), mean eff radius for snow flake(micron)
..... for ilwcliq = 0 (diagnostic cloud scheme) - - -
[in] cliqp real, (nlay), not used
[in] cicep real, (nlay), not used
[in] reliq real, (nlay), not used
[in] reice real, (nlay), not used
[in] cdat1 real, (nlay), layer cloud optical depth
[in] cdat2 real, (nlay), layer cloud single scattering albedo
[in] cdat3 real, (nlay), layer cloud asymmetry factor
[in] cdat4 real, (nlay), optional use
[in] nlay integer, 1, number of layer number
[in] nlp1 integer, 1, number of veritcal levels
[in] ipseed integer, 1, permutation seed for generating random numbers (isubclw>0)
[out] cldfmc real,(ngptlw,nlay), cloud fraction for each sub-column
[out] taucld real,(nbands,nlay), cloud optical depth for bands (non-mcica)
General Algorithm
Compute cloud radiative properties for a cloudy column
- Compute cloud radiative properties for rain and snow (tauran,tausnw)
- Calculation of absorption coefficients due to water clouds(tauliq)
- Calculation of absorption coefficients due to ice clouds (tauice).
- For prognostic cloud scheme: sum up the cloud optical property:
\(taucld=tauice+tauliq+tauran+tausnw \)
if physparam::isubclw > 0, call mcica_subcol() to distribute cloud properties to each g-point.
Definition at line 1475 of file radlw_main.f.
References module_radlw_cldprlw::absice1, module_radlw_cldprlw::absice2, module_radlw_cldprlw::absice3, module_radlw_cldprlw::absliq1, module_radlw_cldprlw::absrain, module_radlw_cldprlw::abssnow0, cldmin, f_one, f_zero, physparam::ilwcice, physparam::ilwcliq, module_radlw_cldprlw::ipat, physparam::isubclw, mcica_subcol(), module_radlw_parameters::nbands, and module_radlw_parameters::ngptlw.
Referenced by lwrad().
subroutine, public module_radlw_main::lwrad ()
Parameters
[in] plyr (npts,nlay),model layer mean pressure in mb
[in] plvl (npts,nlp1),model interface pressure in mb
[in] tlyr (npts,nlay),model layer mean temperature in K
[in] tlvl (npts,nlp1),model interface temperature in K
[in] qlyr (npts,nlay),layer specific humidity in gm/gm *see inside
[in] olyr (npts,nlay),layer ozone concentration in gm/gm *see inside
[in] gasvmr (npts,nlay,:),atmospheric gases amount:(check module_radiation_gases for definition)
(:,:,1) - co2 volume mixing ratio
(:,:,2) - n2o volume mixing ratio
(:,:,3) - ch4 volume mixing ratio
(:,:,4) - o2 volume mixing ratio
(:,:,5) - co volume mixing ratio
(:,:,6) - cfc11 volume mixing ratio
(:,:,7) - cfc12 volume mixing ratio
(:,:,8) - cfc22 volume mixing ratio
(:,:,9) - ccl4 volume mixing ratio
[in] clouds (npts,nlay,:),layer cloud profile(check module_radiation_clouds for definition)
— for ilwcliq > 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer in-cloud liq water path (\(g/m^2 \))
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer in-cloud ice water path (\(g/m^2 \))
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path (\(g/m^2 \))
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path (\(g/m^2 \))
(:,:,9) - mean eff radius for snow flake (micron)
— for ilwcliq = 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud optical depth
(:,:,3) - layer cloud single scattering albedo
(:,:,4) - layer cloud asymmetry factor
[in] icseed (npts),auxiliary special cloud related array.when module variable isubclw=2, it provides permutation seed for each column profile that are used for generating random numbers.when isubclw /=2, it will not be used.
[in] aerosols (npts,nlay,nbdsw,:),aerosol optical properties (check module_radiation_aerosols for definition)
(:,:,:,1) - optical depth
(:,:,:,2) - single scattering albedo
(:,:,:,3) - asymmetry parameter
[in] sfemis (npts),surface emissivity
[in] sfgtmp (npts),surface ground temperature in K
[in] npts total number of horizontal points
[in] nlay,nlp1 total number of vertical layers, levels
[in] lprnt cntl flag for diagnostic print out
[out] hlwc (npts,nlay),total sky heating rate in k/day or k/sec
[out] topflx (npts),radiation fluxes at top, components (check module_radlw_parameters for definition)
upfxc - total sky upward flux at top (\(w/m^2 \))
upfx0 - clear sky upward flux at top (\(w/m^2 \))
[out] sfcflx (npts),radiation fluxes at sfc, components (check module_radlw_parameters for definition)
upfxc - total sky upward flux at sfc (\(w/m^2 \))
dnfxc - total sky downward flux at sfc (\(w/m^2 \))
upfx0 - clear sky upward flux at sfc (\(w/m^2 \))
dnfx0 - clear sky downward flux at sfc (\(w/m^2 \))
Optional:
[out] hlwb (npts,nlay,nbands),spectral band total sky heating rates
[out] hlw0 (npts,nlay),clear sky heating rates (k/sec or k/day)
[out] flxprf (npts,nlp1),level radiation fluxes (\(w/m^2 \)), components (check module_radlw_parameters for definition)
dnfxc - total sky downward flux
upfxc - total sky upward flux
dnfx0 - clear sky downward flux
upfx0 - clear sky upward flux
General Algorithm
Change random number seed value for each radiation invocation (isubclw =1 or 2)
Read surface emissivity
Prepare atmospheric profile for use in rrtm
Set absorber amount for h2o, co2, and o3
Set up column amount for rare gases n2o,ch4,o2,co,ccl4,cf11,cf12,cf22, convert from volume mixing ratio to molec/cm2 based on coldry (scaled to 1.0e-20).
Set aerosol optical properties
Read cloud optical properties
Compute precipitable water vapor for diffusivity angle adjustments
Compute column amount for broadening gases
Compute diffusivity angle adjustments
For cloudy atmosphere, call cldprop() to set cloud optical properties
Calling setcoef() to compute various coefficients needed in radiative transfer calculations.
Call taumol to calculte the gaseous optical depths and Plank fractions for each longwave spectral band.
Call the radiative transfer routine based on cloud scheme selection. compute the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere.
- call rtrn(): clouds are assumed as randomly overlaping in a vertical column
- call rtrnmr(): clouds are assumed as in maximum-randomly overlaping in a vertical column;
- call rtrnmc(): clouds are treated with the mcica stochastic approach.
Save outputs
Definition at line 415 of file radlw_main.f.
References a0, a1, a2, amdo3, amdw, cldprop(), physcons::con_amd, physcons::con_amw, physcons::con_avgd, physcons::con_g, eps, f_one, f_zero, physparam::ilwcliq, physparam::ilwrgas, physparam::iovrlw, ipsdlw0, physparam::isubclw, physparam::ivflip, lflxprf, lhlw0, lhlwb, module_radlw_parameters::maxgas, module_radlw_parameters::nbands, rtrn(), rtrnmc(), rtrnmr(), semiss0, setcoef(), and taumol().
Referenced by module_radiation_driver::grrad().
subroutine module_radlw_main::mcica_subcol () private
Parameters
[in] cldf real, (nlay), layer cloud fraction
[in] nlay integer, 1, number of model vertical layers
[in] ipseed integer, 1, permute seed for random num generator
[out] lcloudy logical, (ngptlw,nlay),sub-colum cloud profile flag array
External Module Variables
physparam::iovrlw - control flag for cloud overlapping method
=0:random; =1:maximum/random: =2:maximum
Definition at line 1786 of file radlw_main.f.
References f_one, physparam::iovrlw, and module_radlw_parameters::ngptlw.
Referenced by cldprop().
subroutine, public module_radlw_main::rlwinit ()
Parameters
[in] me integer, print control for parallel process
[out] NONE
External Module Variables
physparam::ilwrate - heating rate unit selections
=1: output in k/day
=2: output in k/second
physparam::ilwrgas - control flag for rare gases (ch4,n2o,o2,cfcs, etc.)
=0: do not include rare gases
>0: include all rare gases
physparam::ilwcliq - liquid cloud optical properties contrl flag
=0: input cloud opt depth from diagnostic scheme
>0: input cwp,rew, and other cloud content parameters
physparam::isubclw - sub-column cloud approximation control flag
=0: no sub-col cld treatment, use grid-mean cld quantities
=1: mcica sub-col, prescribed seeds to get random numbers
=2: mcica sub-col, providing array icseed for random numbers
physparam::icldflg - cloud scheme control flag
=0: diagnostic scheme gives cloud tau, omiga, and g.
=1: prognostic scheme gives cloud liq/ice path, etc.
physparam::iovrlw - clouds vertical overlapping control flag
=0: random overlapping clouds
=1: maximum/random overlapping clouds
=2: maximum overlap cloud (isubcol>0 only)
Definition at line 1249 of file radlw_main.f.
References bpade, physcons::con_cp, physcons::con_g, exp_tbl, f_one, f_zero, fluxfac, heatfac, physparam::icldflg, physparam::ilwcliq, physparam::ilwrate, physparam::ilwrgas, physparam::iovrlw, physparam::isubclw, module_radlw_parameters::ntbl, semiss0, tau_tbl, tfn_tbl, and vtaglw.
Referenced by module_radiation_driver::radinit().
subroutine module_radlw_main::rtrn () private
Original Code Description: this program calculates the upward fluxes, downward fluxes, and heating rates for an arbitrary clear or cloudy atmosphere. The input to this program is the atmospheric profile, all Planck function information, and the cloud fraction by layer. A variable diffusivity angle (secdif) is used for the angle integration. Bands 2-3 and 5-9 use a value for secdif that varies from 1.50 to 1.80 as a function of the column water vapor, and other bands use a value of 1.66. The gaussian weight appropriate to this angle (wtdiff =0.5) is applied here. Note that use of the emissivity angle for the flux integration can cause errors of 1 to 4 \(W/m^2\) within cloudy layers. Clouds are treated with a random cloud overlap method.
Parameters
[in] semiss real,(nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfrc real, (0:nlp1), layer cloud fraction
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux \((w/m^2)\)
[out] totdflux real, (0:nlay), total sky downward flux \((w/m^2)\)
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux \((w/m^2)\)
[out] totdclfl real, (0:nlay), clear sky downward flux \((w/m^2)\)
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay,nbands), spectral band lw heating rate (k/day)
General Algorithm
Downward radiative transfer loop
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop
Process longwave output from band for total and clear streams. Calculate upward, downward, and net flux.
Definition at line 2267 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::rtrnmc () private
Parameters
[in] semiss real, (nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfmc real, (ngptlw,nlay), layer cloud fraction (sub-column)
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux \((w/m^2)\)
[out] totdflux real, (0:nlay), total sky downward flux \((w/m^2)\)
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux \((w/m^2)\)
[out] totdclfl real, (0:nlay), clear sky downward flux \((w/m^2)\)
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay,nbands), spectral band lw heating rate (k/day)
General Algorithm
Downward radiative transfer loop.
- Clear sky, gases contribution
- Total sky, gases+clouds contribution
- Cloudy layer
- Total sky radiance
- Clear sky radiance
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop
- Compute total sky radiance
- Compute clear sky radiance
Process longwave output from band for total and clear streams. Calculate upward, downward, and net flux.
Definition at line 3256 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::rtrnmr () private
Parameters
[in] semiss real, (nbands), lw surface emissivity
[in] delp real, (nlay), layer pressure thickness (mb)
[in] cldfrc real, (0:nlp1), layer cloud fraction
[in] taucld real, (nbands,nlay), layer cloud opt depth
[in] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
[in] pklay real, (nbands*0:nlay), integrated planck func at lay temp
[in] pklev real, (nbands*0:nlay), integrated planck func at lev temp
[in] fracs real, (ngptlw,nlay), planck fractions
[in] secdif real, (nbands), secant of diffusivity angle
[in] nlay integer, 1, number of vertical layers
[in] nlp1 integer, 1, number of vertical levels (interfaces)
[out] totuflux real, (0:nlay), total sky upward flux (\(w/m^2\))
[out] totdflux real, (0:nlay), total sky downward flux (\(w/m^2\))
[out] htr real, (nlay), total sky heating rate (k/sec or k/day)
[out] totuclfl real, (0:nlay), clear sky upward flux (\(w/m^2\))
[out] totdclfl real, (0:nlay), clear sky downward flux (\(w/m^2\))
[out] htrcl real, (nlay), clear sky heating rate (k/sec or k/day)
[out] htrb real, (nlay*nbands), spectral band lw heating rate (k/day)
General Algorithm
Setup maximum/random cloud overlap
Initialize for radiative transfer
Downward radiative transfer loop:
cloudy layer
total sky radiance
clear sky radiance
Compute spectral emissivity & reflectance, include the contribution of spectrally varying longwave emissivity and reflection from the surface to the upward radiative transfer.
Compute total sky radiance
Compute clear sky radiance
Upward radiative transfer loop:
cloudy layer radiance
total sky radiance
clear sky radiance
Process longwave output from band for total and clear streams. calculate upward, downward, and net flux.
Definition at line 2658 of file radlw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, fluxfac, heatfac, lhlw0, lhlwb, module_radlw_parameters::nbands, module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, tau_tbl, tblint, tfn_tbl, and wtdiff.
Referenced by lwrad().
subroutine module_radlw_main::setcoef () private
Parameters
[in] pavel real, (nlay), layer pressure (mb)
[in] tavel real, (nlay), layer temperature (K)
[in] tz real, (0:nlay), level(interface) temperatures (K)
[in] stemp real, 1, surface ground temperature (K)
[in] h2ovmr real, (nlay), layer w.v. volumn mixing ratio (kg/kg)
[in] colamt real, (nlay,maxgas), column amounts of absorbing gases. 2nd indices range: 1-maxgas, for watervapor,carbon dioxide, ozone, nitrous oxide, methane,oxigen, carbon monoxide,etc. \((mol/cm^2)\)
[in] coldry real, (nlay), dry air column amount
[in] colbrd real, (nlay), column amount of broadening gases
[in] nlay integer, 1, total number of vertical layers
[in] nlp1 integer, 1, total number of vertical levels
[out] laytrop integer, 1, tropopause layer index (unitless)
[out] pklay real, (nbands,0:nlay), integrated planck func at lay temp
[out] pklev real, (nbands,0:nlay), integrated planck func at lev temp
[out] jp integer, (nlay), indices of lower reference pressure
[out] jt,jt1 integer, (nlay), indices of lower reference temperatures
[out] rfrate real, (nlay,nrates,2), ref ratios of binary species param
(:,m,:)m=1-h2o/co2,2-h2o/o3,3-h2o/n2o,4-h2o/ch4,5-n2o/co2,6-o3/co2
(:,:,n)n=1,2: the rates of ref press at the 2 sides of the layer
[out] facij real, (nlay), factors multiply the reference ks, i,j=0/1 for lower/higher of the 2 appropriate temperatures and altitudes.
[out] selffac real, (nlay), scale factor for w. v. self-continuum equals (w. v. density)/(atmospheric density at 296k and 1013 mb)
[out] selffrac real, (nlay), factor for temperature interpolation of reference w. v. self-continuum data
[out] indself integer, (nlay), index of lower ref temp for selffac
[out] forfac real, (nlay), scale factor for w. v. foreign-continuum
[out] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[out] indfor integer, (nlay), index of lower ref temp for forfac
[out] minorfrac real, (nlay), factor for minor gases
[out] scaleminor,scaleminorn2 real, (nlay), scale factors for minor gases
[out] indminor integer, (nlay), index of lower ref temp for minor gases
Definition at line 1976 of file radlw_main.f.
References module_radlw_ref::chi_mls, module_radlw_parameters::delwave, f_one, f_zero, module_radlw_parameters::nbands, module_radlw_ref::preflog, stpfac, module_radlw_avplank::totplnk, and module_radlw_ref::tref.
Referenced by lwrad().
subroutine module_radlw_main::taumol () private
This file contains the subroutines taugbn (where n goes from 1 to 16). taugbn calculates the optical depths and planck fractions per g-value and layer for band n.
Parameters
[in] laytrop integer, 1, tropopause layer index (unitless) layer at which switch is made for key species
[in] pavel real, (nlay), layer pressures (mb)
[in] coldry real, (nlay), column amount for dry air \((mol/cm^2)\)
[in] colamt real, (nlay,maxgas), column amounts of h2o, co2, o3, n2o, ch4,o2, co \((mol/cm^2)\)
[in] colbrd real, (nlay), column amount of broadening gases
[in] wx real, (nlay,maxxsec), cross-section amounts \((mol/cm^2)\)
[in] tauaer real, (nbands,nlay), aerosol optical depth
[in] rfrate real, (nlay,nrates,2), reference ratios of binary species parameter
(:,m,:)m=1-h2o/co2,2-h2o/o3,3-h2o/n2o,4-h2o/ch4,5-n2o/co2,6-o3/co2
(:,:,n)n=1,2: the rates of ref press at the 2 sides of the layer
[in] facij real, (nlay), factors multiply the reference ks, i,j of 0/1 for lower/higher of the 2 appropriate temperatures and altitudes
[in] jp integer, (nlay), index of lower reference pressure
[in] jt,jt1 integer, (nlay), indices of lower reference temperatures for pressure levels jp and jp+1, respectively
[in] selffac real, (nlay), scale factor for water vapor self-continuum equals (water vapor density)/(atmospheric density at 296k and 1013 mb)
[in] selffrac real, (nlay), factor for temperature interpolation of reference water vapor self-continuum data
[in] indself integer, (nlay), index of lower reference temperature for the self-continuum interpolation
[in] forfac real, (nlay), scale factor for w. v. foreign-continuum
[in] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[in] indfor integer, (nlay), index of lower reference temperature for the foreign-continuum interpolation
[in] minorfrac real, (nlay), factor for minor gases
[in] scaleminor,scaleminorn2 real, (nlay), scale factors for minor gases
[in] indminor integer, (nlay), index of lower reference temperature for minor gases
[in] nlay integer, 1, total number of layers
[out] fracs real, (ngptlw,nlay), planck fractions
[out] tautot real, (ngptlw,nlay), total optical depth (gas+aerosols)
Definition at line 3662 of file radlw_main.f.
References module_radlw_parameters::ngb, module_radlw_parameters::ngptlw, taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb12(), taugb13(), taugb14(), taugb15(), and taugb16().
Referenced by lwrad().
Variable Documentation
real (kind=kind_phys), dimension(nbands) module_radlw_main::a0 private
Definition at line 306 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(nbands) module_radlw_main::a1 private
Definition at line 306 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), dimension(nbands) module_radlw_main::a2 private
Definition at line 306 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), parameter module_radlw_main::amdo3 = con_amd/con_amo3 private
Definition at line 280 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), parameter module_radlw_main::amdw = con_amd/con_amw private
Definition at line 279 of file radlw_main.f.
Referenced by lwrad().
real (kind=kind_phys), parameter module_radlw_main::bpade = 1.0/0.278 private
Definition at line 271 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), parameter module_radlw_main::cldmin = 1.0e-80 private
Definition at line 270 of file radlw_main.f.
Referenced by cldprop().
real (kind=kind_phys), parameter module_radlw_main::eps = 1.0e-6 private
Definition at line 268 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::exp_tbl private
Definition at line 331 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), parameter module_radlw_main::f_one = 1.0 private
Definition at line 276 of file radlw_main.f.
Referenced by cldprop(), lwrad(), mcica_subcol(), rlwinit(), rtrn(), rtrnmc(), rtrnmr(), setcoef(), taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), parameter module_radlw_main::f_zero = 0.0 private
Definition at line 275 of file radlw_main.f.
Referenced by cldprop(), lwrad(), rlwinit(), rtrn(), rtrnmc(), rtrnmr(), setcoef(), taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys) module_radlw_main::fluxfac private
Definition at line 327 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys) module_radlw_main::heatfac private
Definition at line 327 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
integer, parameter module_radlw_main::ipsdlw0 = ngptlw private
Definition at line 339 of file radlw_main.f.
Referenced by lwrad().
logical module_radlw_main::lflxprf = .false. private
Definition at line 319 of file radlw_main.f.
Referenced by lwrad().
logical module_radlw_main::lhlw0 = .false. private
Definition at line 318 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
logical module_radlw_main::lhlwb = .false. private
Definition at line 317 of file radlw_main.f.
Referenced by lwrad(), rtrn(), rtrnmc(), and rtrnmr().
integer, dimension(nbands) module_radlw_main::nspa private
Definition at line 283 of file radlw_main.f.
Referenced by taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb06(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb12(), taugb13(), taugb14(), taugb15(), and taugb16().
integer, dimension(nbands) module_radlw_main::nspb private
Definition at line 283 of file radlw_main.f.
Referenced by taugb01(), taugb02(), taugb03(), taugb04(), taugb05(), taugb07(), taugb08(), taugb09(), taugb10(), taugb11(), taugb14(), and taugb16().
real (kind=kind_phys), parameter module_radlw_main::oneminus = 1.0-eps private
Definition at line 269 of file radlw_main.f.
Referenced by taugb03(), taugb04(), taugb05(), taugb07(), taugb09(), taugb12(), taugb13(), taugb15(), and taugb16().
real (kind=kind_phys), dimension(nbands) module_radlw_main::semiss0 private
Definition at line 327 of file radlw_main.f.
Referenced by lwrad(), and rlwinit().
real (kind=kind_phys), parameter module_radlw_main::stpfac = 296.0/1013.0 private
Definition at line 272 of file radlw_main.f.
Referenced by setcoef().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::tau_tbl private
Definition at line 330 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), parameter module_radlw_main::tblint = ntbl private
Definition at line 274 of file radlw_main.f.
Referenced by rtrn(), rtrnmc(), and rtrnmr().
real (kind=kind_phys), dimension(0:ntbl) module_radlw_main::tfn_tbl private
Definition at line 332 of file radlw_main.f.
Referenced by rlwinit(), rtrn(), rtrnmc(), and rtrnmr().
character(40), parameter module_radlw_main::vtaglw ='NCEP LW v5.1 Nov 2012 -RRTMG-LW v4.82 ' private
Definition at line 257 of file radlw_main.f.
Referenced by rlwinit().
real (kind=kind_phys), parameter module_radlw_main::wtdiff = 0.5 private
Definition at line 273 of file radlw_main.f.
Referenced by rtrn(), rtrnmc(), and rtrnmr().