Radiation Scheme in CCPP: module_radsw_main Module Reference
module_radsw_main Module Reference
This module includes ncep's modifications of the rrtm-sw radiation code from aer inc.
Functions/Subroutines
subroutine, public rswinit
This subroutine initializes non-varying module variables, conversion factors, and look-up tables.
subroutine mcica_subcol
This subroutine computes the sub-colum cloud profile flag array.
subroutine setcoef
This subroutine computes various coefficients needed in radiative transfer calculation.
subroutine spcvrtm
This subroutine computes the shortwave radiative fluxes using two-stream method of h. barder and mcica,the monte-carlo independent column approximation, for the representation of sub-grid cloud variability (i.e. cloud overlap).
subroutine taumol
This subroutine calculates optical depths for gaseous absorption and rayleigh scattering
subroutine called taugb## (## = 16-29)
subroutine, public swrad
This subroutine is the main sw radiation routine.
subroutine cldprop
This subroutine computes the cloud optical properties for each cloudy layer and g-point interval.
subroutine spcvrtc
This subroutine computes the shortwave radiative fluxes using two-stream method.
subroutine swflux
This subroutine computes the upward and downward radiation fluxes.
Variables
character(40), parameter vtagsw ='NCEP SW v5.1 Nov 2012 -RRTMG-SW v3.8 '
real(kind=kind_phys), parameter eps = 1.0e-6
real(kind=kind_phys), parameter oneminus = 1.0 - eps
real(kind=kind_phys), parameter bpade = 1.0/0.278
real(kind=kind_phys), parameter stpfac = 296.0/1013.0
real(kind=kind_phys), parameter ftiny = 1.0e-12
real(kind=kind_phys), parameter s0 = 1368.22
real(kind=kind_phys), parameter f_zero = 0.0
real(kind=kind_phys), parameter f_one = 1.0
real(kind=kind_phys), parameter amdw = con_amd/con_amw
real(kind=kind_phys), parameter amdo3 = con_amd/con_amo3
integer, dimension(nblow:nbhgh) nspa
integer, dimension(nblow:nbhgh) nspb
integer, dimension(nblow:nbhgh) idxebc
integer, dimension(nblow:nbhgh) idxsfc
integer, parameter nuvb = 27
logical lhswb = .false.
logical lhsw0 = .false.
logical lflxprf = .false.
logical lfdncmp = .false.
real(kind=kind_phys), dimension(0:ntbmx) exp_tbl
real(kind=kind_phys) heatfac
integer, parameter ipsdsw0 = 1
Function/Subroutine Documentation
subroutine module_radsw_main::cldprop () private
Parameters
[in] cfrac real, (nlay), layer cloud fraction
..... for physparam::iswcliq > 0 (prognostic cloud scheme) - - -
[in] cliqp real, (nlay), layer in-cloud liq water path (\(g/m^2\))
[in] reliq real, (nlay), mean eff radius for liq cloud (micron)
[in] cicep real, (nlay), layer in-cloud ice water path (\(g/m^2\))
[in] reice real, (nlay), mean eff radius for ice cloud (micron)
[in] cdat1 real, (nlay), layer rain drop water path (\(g/m^2\))
[in] cdat2 real, (nlay), effective radius for rain drop (micron)
[in] cdat3 real, (nlay), layer snow flake water path(\(g/m^2\))
[in] cdat4 real, (nlay), mean eff radius for snow flake(micron)
..... for physparam::iswcliq = 0 (diagnostic cloud scheme) - - -
[in] cliqp real, (nlay), not used
[in] cicep real, (nlay), not used
[in] reliq real, (nlay), not used
[in] reice real, (nlay), not used
[in] cdat1 real, (nlay), layer cloud optical depth
[in] cdat2 real, (nlay), layer cloud single scattering albedo
[in] cdat3 real, (nlay), layer cloud asymmetry factor
[in] cdat4 real, (nlay), optional use
[in] cf1 real, 1, effective total cloud cover at surface
[in] nlay integer, 1, vertical layer number
[in] ipseed integer, 1, permutation seed for generating random numbers (isubcsw>0)
[out] taucw real,(nlay,nbdsw), cloud optical depth, w/o delta scaled
[out] ssacw real,(nlay,nbdsw), weighted cloud single scattering albedo (ssa = ssacw / taucw)
[out] asycw real,(nlay,nbdsw), weighted cloud asymmetry factor (asy = asycw / ssacw)
[out] cldfrc real,(nlay), cloud fraction of grid mean value
[out] cldfmc real,(nlay,ngptsw), cloud fraction for each sub-column
General Algorithm
Compute cloud radiative properties for a cloudy column.
Compute optical properties for rain and snow
For rain: tauran/ssaran/asyran
For snow: tausnw/ssasnw/asysnw
Calculation of absorption coefficients due to water clouds
For water clouds: tauliq/ssaliq/asyliq
Calculation of absorption coefficients due to ice clouds
For ice clouds: tauice/ssaice/asyice
For Prognostic cloud scheme: sum up the cloud optical property:
\(taucw=tauliq+tauice+tauran+tausnw \)
\(ssacw=ssaliq+ssaice+ssaran+ssasnw \)
\(asycw=asyliq+asyice+asyran+asysnw \)
if physparam::isubcsw > 0, call mcica_subcol() to distribute cloud properties to each g-point
Definition at line 1455 of file radsw_main.f.
References module_radsw_cldprtb::a0r, module_radsw_cldprtb::a0s, module_radsw_cldprtb::a1s, module_radsw_cldprtb::abari, module_radsw_cldprtb::asyice2, module_radsw_cldprtb::asyice3, module_radsw_cldprtb::asyliq1, module_radsw_cldprtb::b0r, module_radsw_cldprtb::b0s, module_radsw_cldprtb::b1s, module_radsw_cldprtb::bbari, module_radsw_cldprtb::c0r, module_radsw_cldprtb::c0s, module_radsw_cldprtb::cbari, module_radsw_cldprtb::dbari, module_radsw_cldprtb::ebari, module_radsw_cldprtb::extice2, module_radsw_cldprtb::extice3, module_radsw_cldprtb::extliq1, f_one, f_zero, module_radsw_cldprtb::fbari, ftiny, idxebc, physparam::isubcsw, physparam::iswcice, physparam::iswcliq, mcica_subcol(), module_radsw_parameters::nbdsw, module_radsw_parameters::nbhgh, module_radsw_parameters::nblow, module_radsw_parameters::ngptsw, module_radsw_cldprtb::ssaice2, module_radsw_cldprtb::ssaice3, and module_radsw_cldprtb::ssaliq1.
Referenced by swrad().
subroutine module_radsw_main::mcica_subcol () private
Parameters
[in] cldf real, (nlay), layer cloud fraction
[in] nlay integer, 1, number of model vertical layers
[in] ipseed integer, 1, permute seed for random num generator
[out] lcloudy logical, (nlay,ngptsw), sub-colum cloud profile flag array
External Module Variables
physparam::iovrsw - control flag for cloud overlapping method
=0:random; =1:maximum/random; =2:maximum
Definition at line 1821 of file radsw_main.f.
References f_one, physparam::iovrsw, and module_radsw_parameters::ngptsw.
Referenced by cldprop().
subroutine, public module_radsw_main::rswinit ()
Parameters
[in] me integer, print control for parallel process
[out] NONE
External Module Variables
physparam::iswrate - heating rate unit selections
=1: output in k/day
=2: output in k/second
physparam::iswrgas - control flag for rare gases (ch4,n2o,o2, etc.)
=0: do not include rare gases
>0: include all rare gases
physparam::iswcliq - liquid cloud optical properties contrl flag
=0: input cloud opt depth from diagnostic scheme
>0: input cwp,rew, and other cloud content parameters
physparam::isubcsw - sub-column cloud approximation control flag
=0: no sub-col cld treatment, use grid-mean cld quantities
=1: mcica sub-col, prescribed seeds to get random numbers
=2: mcica sub-col, providing array icseed for random numbers
physparam::icldflg - cloud scheme control flag
=0: diagnostic scheme gives cloud tau, omiga, and g.
=1: prognostic scheme gives cloud liq/ice path, etc.
physparam::iovrsw - clouds vertical overlapping control flag
=0: random overlapping clouds
=1: maximum/random overlapping clouds
=2: maximum overlap cloud
physparam::iswmode - control flag for 2-stream transfer scheme
=1; delta-eddington (joseph et al., 1976)
=2: pifm (zdunkowski et al., 1980)
=3: discrete ordinates (liou, 1973)
Definition at line 1269 of file radsw_main.f.
References bpade, physcons::con_cp, physcons::con_g, exp_tbl, heatfac, physparam::icldflg, physparam::iovrsw, physparam::isubcsw, physparam::iswcliq, physparam::iswmode, physparam::iswrate, physparam::iswrgas, module_radsw_parameters::ntbmx, and vtagsw.
Referenced by module_radiation_driver::radinit().
subroutine module_radsw_main::setcoef () private
Parameters
[in] pavel real, (nlay), layer pressure (mb)
[in] tavel real, (nlay), layer temperature (k)
[in] h2ovmr real, (nlay), layer w.v. volumn mixing ratio (kg/kg)
[in] nlay integer,1, total number of vertical layers
[in] nlp1 integer,1, total number of vertical levels
[out] laytrop integer,1, tropopause layer index (unitless)
[out] jp integer, (nlay), indices of lower reference pressure
[out] jt,jt1 integer, (nlay), indices of lower reference temperatures at levels of jp and jp+1
[out] facij real, (nlay), factors mltiply the reference ks,i,j=0/1 for lower/higher of the 2 appropriate temperature and altitudes.
[out] selffac real, (nlay), scale factor for w. v. self-continuum equals (w.v. density)/(atmospheric density at 296k and 1013 mb)
[out] seffrac real, (nlay), factor for temperature interpolation of reference w.v. self-continuum data
[out] indself integer, (nlay), index of lower ref temp for selffac
[out] forfac real, (nlay), scale factor for w. v. foreign-continuum
[out] forfrac real, (nlay), factor for temperature interpolation of reference w.v. foreign-continuum data
[out] indfor integer, (nlay), index of lower ref temp for forfac
Definition at line 1998 of file radsw_main.f.
References f_one, f_zero, module_radsw_ref::preflog, stpfac, and module_radsw_ref::tref.
Referenced by swrad().
subroutine module_radsw_main::spcvrtc () private
Parameters
[in] ssolar real, 1, incoming solar flux at top
[in] cosz real, 1, cosine solar zenith angle
[in] sntz real, 1, secant solar zenith angle
[in] albbm real, 2, surface albedo for direct beam radiation
[in] albdf real, 2, surface albedo for diffused radiation
[in] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[in] cldfrc real, (nlay),layer cloud fraction
[in] cf1 real, 1, >0: cloudy sky, otherwise: clear sky
[in] cf0 real, 1, =1-cf1
[in] taug real, (nlay,ngptsw), spectral optical depth for gases
[in] taur real, (nlay,ngptsw), optical depth for rayleigh scattering
[in] tauae real, (nlay,nbdsw), aerosols optical depth
[in] ssaae real, (nlay,nbdsw), aerosols single scattering albedo
[in] asyae real, (nlay,nbdsw), aerosols asymmetry factor
[in] taucw real, (nlay,nbdsw), weighted cloud optical depth
[in] ssacw real, (nlay,nbdsw), weighted cloud single scat albedo
[in] asycw real, (nlay,nbdsw), weighted cloud asymmetry factor
[in] nlay,nlp1 integer, 1, number of layers/levels
[out] fxupc real, (nlp1,nbdsw), tot sky upward flux
[out] fxdnc real, (nlp1,nbdsw), tot sky downward flux
[out] fxup0 real, (nlp1,nbdsw), clr sky upward flux
[out] fxdn0 real, (nlp1,nbdsw), clr sky downward flux
[out] ftoauc real, 1, tot sky toa upwd flux
[out] ftoau0 real, 1, clr sky toa upwd flux
[out] ftoadc real, 1, toa downward (incoming) solar flux
[out] fsfcuc real, 1, tot sky sfc upwd flux
[out] fsfcu0 real, 1, clr sky sfc upwd flux
[out] fsfcdc real, 1, tot sky sfc dnwd flux
[out] fsfcd0 real, 1, clr sky sfc dnwd flux
[out] sfbmc real, 2, tot sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdfc real, 2, tot sky sfc dnwd diff flux (nir/uv+vis)
[out] sfbm0 real, 2, clr sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdf0 real, 2, clr sky sfc dnwd diff flux (nir/uv+vis)
[out] suvbfc real, 1, tot sky sfc dnwd uv-b flux
[out] suvbf0 real, 1, clr sky sfc dnwd uv-b flux
External Module Variables
physparam::iswmode - control flag for 2-stream transfer schemes
= 1 delta-eddington (joseph et al., 1976)
= 2 pifm (zdunkowski et al., 1980)
= 3 discrete ordinates (liou, 1973)
General Algorithm
Initialization of output fluxes
Compute clear-sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for clear-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for both conservative and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Compute total sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for total-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for conservative scattering and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Process and save outputs
Definition at line 2195 of file radsw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, ftiny, idxsfc, physparam::iswmode, module_radsw_parameters::nbdsw, module_radsw_parameters::nblow, module_radsw_parameters::ngb, module_radsw_parameters::ngptsw, module_radsw_parameters::ntbmx, nuvb, oneminus, and swflux().
Referenced by swrad().
subroutine module_radsw_main::spcvrtm () private
Parameters
[in] ssolar real, 1, incoming solar flux at top
[in] cosz real, 1, cosine solar zenith angle
[in] sntz real, 1, secant solar zenith angle
[in] albbm real, 2, surface albedo for direct beam radiation
[in] albdf real, 2, surface albedo for diffused radiation
[in] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[in] cldfmc real, (nlay,ngptsw), layer cloud fraction for g-point
[in] cf1 real, 1, >0: cloudy sky, otherwise: clear sky
[in] cf0 real, 1, =1-cf1
[in] taug real, (nlay,ngptsw), spectral optical depth for gases
[in] taur real, (nlay,ngptsw), optical depth for rayleigh scattering
[in] tauae real, (nlay,nbdsw), aerosols optical depth
[in] ssaae real, (nlay,nbdsw), aerosols single scattering albedo
[in] asyae real, (nlay,nbdsw), aerosols asymmetry factor
[in] taucw real, (nlay,nbdsw), weighted cloud optical depth
[in] ssacw real, (nlay,nbdsw), weighted cloud single scat albedo
[in] asycw real, (nlay,nbdsw), weighted cloud asymmetry factor
[in] nlay,nlp1 integer, 1, number of layers/levels
[out] fxupc real, (nlp1,nbdsw), tot sky upward flux
[out] fxdnc real, (nlp1,nbdsw), tot sky downward flux
[out] fxup0 real, (nlp1,nbdsw), clr sky upward flux
[out] fxdn0 real, (nlp1,nbdsw), clr sky downward flux
[out] ftoauc real, 1, tot sky toa upwd flux
[out] ftoau0 real, 1, clr sky toa upwd flux
[out] ftoadc real, 1, toa downward (incoming) solar flux
[out] fsfcuc real, 1, tot sky sfc upwd flux
[out] fsfcu0 real, 1, clr sky sfc upwd flux
[out] fsfcdc real, 1, tot sky sfc dnwd flux
[out] fsfcd0 real, 1, clr sky sfc dnwd flux
[out] sfbmc real, 2, tot sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdfc real, 2, tot sky sfc dnwd diff flux (nir/uv+vis)
[out] sfbm0 real, 2, clr sky sfc dnwd beam flux (nir/uv+vis)
[out] sfdf0 real, 2, clr sky sfc dnwd diff flux (nir/uv+vis)
[out] suvbfc real, 1, tot sky sfc dnwd uv-b flux
[out] suvbf0 real, 1, clr sky sfc dnwd uv-b flux
Initialization of output fluxes
Compute clear-sky optical parameters, layer reflectance andtransmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for clear-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for both conservative and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Compute total sky optical parameters, layer reflectance and transmittance
Set up toa direct beam and surface values (beam and diff)
Delta scaling for total-sky condition
General two-stream expressions for physparam::iswmode
Compute homogeneous reflectance and transmittance for conservative scattering and non-conservative scattering
Pre-delta-scaling clear and cloudy direct beam transmittance
Call swflux() to compute the upward and downward radiation fluxes
Process and save outputs — ... surface downward beam/diffused flux components
Definition at line 2954 of file radsw_main.f.
References bpade, eps, exp_tbl, f_one, f_zero, ftiny, idxsfc, physparam::iswmode, module_radsw_parameters::nbdsw, module_radsw_parameters::nblow, module_radsw_parameters::ngb, module_radsw_parameters::ngptsw, module_radsw_parameters::ntbmx, nuvb, oneminus, and swflux().
Referenced by swrad().
subroutine module_radsw_main::swflux () private
Parameters
[in] zrefb real, (NLP1), layer direct beam reflectivity
[in] zrefd real, (NLP1), layer diffuse reflectivity
[in] ztrab real, (NLP1), layer direct beam transmissivity
[in] ztrad real, (NLP1), layer diffuse transmissivity
[in] zldbt real, (NLP1), layer mean beam transmittance
[in] ztdbt real, (NLP1), total beam transmittance at levels
[in] NLAY,NLP1 integer, number of layers/levels
[out] zfu real, (NLP1), upward flux at layer interface
[out] zfd real, (NLP1), downward flux at layer interface
General Algorithm
Link lowest layer with surface
Pass from bottom to top
Upper boundary conditions
Pass from top to bottom
Up and down-welling fluxes at levels
Definition at line 3658 of file radsw_main.f.
References f_one, and f_zero.
Referenced by spcvrtc(), and spcvrtm().
subroutine, public module_radsw_main::swrad ()
Parameters
[in] plyr (npts,nlay),model layer mean pressure in mb
[in] plvl (npts,nlp1),model level pressure in mb
[in] tlyr (npts,nlay),model layer mean temperature in K
[in] tlvl (npts,nlp1),model level temperature in K (not in use)
[in] qlyr (npts,nlay),layer specific humidity in gm/gm *see inside
[in] olyr (npts,nlay),layer ozone concentration in gm/gm
[in] gasvmr (npts,nlay,:),atmospheric constent gases:(check module_radiation_gases for definition)
(:,:,1) - co2 volume mixing ratio
(:,:,2) - n2o volume mixing ratio
(:,:,3) - ch4 volume mixing ratio
(:,:,4) - o2 volume mixing ratio
(:,:,5) - co volume mixing ratio (not used)
(:,:,6) - cfc11 volume mixing ratio (not used)
(:,:,7) - cfc12 volume mixing ratio (not used)
(:,:,8) - cfc22 volume mixing ratio (not used)
(:,:,9) - ccl4 volume mixing ratio (not used)
[in] clouds (npts,nlay,:),cloud profile(check module_radiation_clouds for definition)
— for iswcliq > 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer in-cloud liq water path (g/m**2)
(:,:,3) - mean eff radius for liq cloud (micron)
(:,:,4) - layer in-cloud ice water path (g/m**2)
(:,:,5) - mean eff radius for ice cloud (micron)
(:,:,6) - layer rain drop water path (g/m**2)
(:,:,7) - mean eff radius for rain drop (micron)
(:,:,8) - layer snow flake water path (g/m**2)
(:,:,9) - mean eff radius for snow flake (micron)
— for iswcliq = 0 —
(:,:,1) - layer total cloud fraction
(:,:,2) - layer cloud optical depth
(:,:,3) - layer cloud single scattering albedo
(:,:,4) - layer cloud asymmetry factor
[in] icseed (npts),auxiliary special cloud related array.when module variable isubcsw=2, it provides permutation seed for each column profile that are used for generating random numbers.when isubcsw /=2, it will not be used.
[in] aerosols (npts,nlay,nbdsw,:),aerosol optical properties (check module_radiation_aerosols for definition)
(:,:,:,1) - optical depth
(:,:,:,2) - single scattering albedo
(:,:,:,3) - asymmetry parameter
[in] sfcalb (npts, :),surface albedo in fraction(check module_radiation_surface for definition)
(:,1) - near ir direct beam albedo
(:,2) - near ir diffused albedo
(:,3) - uv+vis direct beam albedo
(:,4) - uv+vis diffused albedo
[in] cosz (npts),cosine of solar zenith angle
[in] solcon solar constant(w/m**2)
[in] NDAY num of daytime points
[in] idxday (npts),index array for daytime points
[in] npts number of horizontal points
[in] nlay,nlp1 vertical layer/lavel numbers
[in] lprnt logical check print flag
[out] hswc (npts,nlay),total sky heating rates (k/sec or k/day)
[out] topflx (npts),radiation fluxes at toa (w/m**2), components (check module_radsw_parameters for definition)
upfxc - total sky upward flux at toa
dnflx - total sky downward flux at toa
upfx0 - clear sky upward flux at toa
[out] sfcflx (npts),radiation fluxes at sfc (w/m**2), components (check module_radsw_parameters for definition)
upfxc - total sky upward flux at sfc
dnfxc - total sky downward flux at sfc
upfx0 - clear sky upward flux at sfc
dnfx0 - clear sky downward flux at sfc
Optional:
[out] hswb (npts,nlay,nbdsw),spectral band total sky heating rates
[out] hsw0 (npts,nlay),clear sky heating rates (k/sec or k/day)
[out] flxprf (npts,nlp1),level radiation fluxes (w/m**2), components (check module_radsw_parameters for definition)
dnfxc - total sky downward flux at interface
upfxc - total sky upward flux at interface
dnfx0 - clear sky downward flux at interface
upfx0 - clear sky upward flux at interface
[out] fdncmp (npts),component surface downward fluxes (w/m**2)(check module_radsw_parameters for definition) !
uvbfc - total sky downward uv-b flux at sfc
uvbf0 - clear sky downward uv-b flux at sfc
nirbm - downward surface nir direct beam flux
nirdf - downward surface nir diffused flux
visbm - downward surface uv+vis direct beam flux
visdf - downward surface uv+vis diffused flux
General Algorithm
Compute solar constant adjustment factor (s0fac) according to solcon.
\(s0fac = solcon/s0 \)
where s0, the solar constant at toa in \(w/m^2 \), is hard-coded with each spectran band, the total flux is about 1368.22 \(w/m^2 \).
Initial output arrays (and optional) as zero
Change random number seed value for each radiation invocation (isubcsw =1 or 2).
Prepare surface albedo: bm,df - dir,dif; 1,2 - nir,uvv
Prepare atmospheric profile for use in rrtm:
pavel(nlay):layer pressure (mb)
tavel(nlay):layer temperature (k)
delp (nlay):layer pressure thickness (mb)
Set absorber and gas column amount, convert from volume mixing ratio to molec/cm2 based on coldry (scaled to 1.0e-20)
colamt(nlay,maxgas):column amounts of absorbing gases 1 to maxgas are for h2o,co2,o3,n2o,ch4,o2,co, respectively (\(mol/cm^2 \))
Read aerosol optical properties from aerosols (:,:,:,:)
Read cloud optical properties from clouds(:,:,:)
Compute fractions of clear sky view in different overlapping scenario:
random overlapping
max/ran overlapping
maximum overlapping
For cloudy sky column, call cldprop() to compute the cloud optical properties for each cloudy layer
Calling setcoef() to compute various coefficients needed in radiative transfer calculations.
Calling taumol() to calculate optical depths for gaseous absorption and rayleigh scattering
call the 2-stream radiation transfer model
if physparam::isubcsw .le.0, using standard cloud scheme, call spcvrtc().
if physparam::isubcsw .gt.0, using mcica cloud scheme, call spcvrtm().
Save outputs
Definition at line 440 of file radsw_main.f.
References amdo3, amdw, cldprop(), physcons::con_amd, physcons::con_amw, physcons::con_avgd, physcons::con_g, f_one, f_zero, ftiny, heatfac, physparam::iovrsw, ipsdsw0, physparam::isubcsw, physparam::iswcliq, physparam::iswrgas, physparam::ivflip, lfdncmp, lflxprf, lhsw0, lhswb, module_radsw_parameters::nbdsw, oneminus, s0, setcoef(), spcvrtc(), spcvrtm(), and taumol().
Referenced by module_radiation_driver::grrad().
subroutine module_radsw_main::taumol () private
Parameters
[in] colamt real, (nlay,maxgas), column amounts of absorbing gases the index are for h2o, co2, o3, n2o, ch4, and o2,respectively \((mol/cm^2)\)
[in] colmol real, (nlay), total column amount (dry air+water vapor)
[in] facij real, (nlay), for each layer, these are factors that are needed to compute the interpolation factors that multiply the appropriate reference k-values. a value of 0/1 for i,j indicates that the corresponding factor multiplies reference k-value for the lower/higher of the two appropriate temperatures, and altitudes, respectively.
[in] jp integer, (nlay), the index of the lower (in altitude) of the two appropriate ref pressure levels needed for interpolation.
[in] jt,jt1 integer, (nlay), the indices of the lower of the two approp ref temperatures needed for interpolation (for pressure levels jp and jp+1, respectively)
[in] laytrop integer, 1, tropopause layer index
[in] forfac real, (nlay), scale factor needed to foreign-continuum.
[in] forfrac real, (nlay), factor needed for temperature interpolation
[in] indfor integer, (nlay), index of the lower of the two appropriate reference temperatures needed for foreign-continuum interpolation
[in] selffac real, (nlay), scale factor needed to h2o self-continuum.
[in] selffrac real, (nlay), factor needed for temperature interpolation of reference h2o self-continuum data
[in] indself integer, (nlay), index of the lower of the two appropriate reference temperatures needed for the self-continuum interpolation
[in] nlay integer, 1, number of vertical layers
[out] sfluxzen real, (ngptsw), spectral distribution of incoming solar flux
[out] taug real, (nlay,ngptsw), spectral optical depth for gases
[out] taur real, (nlay,ngptsw), opt depth for rayleigh scattering
Definition at line 3785 of file radsw_main.f.
References f_one, module_radsw_sflux::ibx, module_radsw_sflux::ix1, module_radsw_sflux::ix2, module_radsw_sflux::layreffr, module_radsw_parameters::nbhgh, module_radsw_parameters::nblow, module_radsw_parameters::ng, module_radsw_parameters::ngs, nspa, nspb, oneminus, module_radsw_sflux::scalekur, module_radsw_sflux::sfluxref01, module_radsw_sflux::sfluxref02, module_radsw_sflux::sfluxref03, module_radsw_sflux::specwt, module_radsw_sflux::strrat, taumol16(), taumol17(), taumol18(), taumol19(), taumol20(), taumol21(), taumol22(), taumol23(), taumol24(), taumol25(), taumol26(), taumol27(), taumol28(), and taumol29().
Referenced by swrad().
Variable Documentation
real (kind=kind_phys), parameter module_radsw_main::amdo3 = con_amd/con_amo3 private
Definition at line 304 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), parameter module_radsw_main::amdw = con_amd/con_amw private
Definition at line 303 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), parameter module_radsw_main::bpade = 1.0/0.278 private
Definition at line 294 of file radsw_main.f.
Referenced by rswinit(), spcvrtc(), and spcvrtm().
real (kind=kind_phys), parameter module_radsw_main::eps = 1.0e-6 private
Definition at line 292 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
real (kind=kind_phys), dimension(0:ntbmx) module_radsw_main::exp_tbl private
Definition at line 340 of file radsw_main.f.
Referenced by rswinit(), spcvrtc(), and spcvrtm().
real (kind=kind_phys), parameter module_radsw_main::f_one = 1.0 private
Definition at line 300 of file radsw_main.f.
Referenced by cldprop(), mcica_subcol(), setcoef(), spcvrtc(), spcvrtm(), swflux(), swrad(), taumol(), taumol16(), taumol17(), taumol18(), taumol19(), taumol21(), taumol22(), taumol24(), and taumol28().
real (kind=kind_phys), parameter module_radsw_main::f_zero = 0.0 private
Definition at line 299 of file radsw_main.f.
Referenced by cldprop(), setcoef(), spcvrtc(), spcvrtm(), swflux(), swrad(), taumol23(), and taumol26().
real (kind=kind_phys), parameter module_radsw_main::ftiny = 1.0e-12 private
Definition at line 296 of file radsw_main.f.
Referenced by cldprop(), spcvrtc(), spcvrtm(), and swrad().
real (kind=kind_phys) module_radsw_main::heatfac private
Definition at line 345 of file radsw_main.f.
Referenced by rswinit(), and swrad().
integer, dimension(nblow:nbhgh) module_radsw_main::idxebc private
Definition at line 307 of file radsw_main.f.
Referenced by cldprop().
integer, dimension(nblow:nbhgh) module_radsw_main::idxsfc private
Definition at line 307 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
integer, parameter module_radsw_main::ipsdsw0 = 1 private
Definition at line 349 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lfdncmp = .false. private
Definition at line 336 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lflxprf = .false. private
Definition at line 335 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lhsw0 = .false. private
Definition at line 334 of file radsw_main.f.
Referenced by swrad().
logical module_radsw_main::lhswb = .false. private
Definition at line 333 of file radsw_main.f.
Referenced by swrad().
integer, dimension(nblow:nbhgh) module_radsw_main::nspa private
Definition at line 307 of file radsw_main.f.
Referenced by taumol().
integer, dimension(nblow:nbhgh) module_radsw_main::nspb private
Definition at line 307 of file radsw_main.f.
Referenced by taumol().
integer, parameter module_radsw_main::nuvb = 27 private
Definition at line 329 of file radsw_main.f.
Referenced by spcvrtc(), and spcvrtm().
real (kind=kind_phys), parameter module_radsw_main::oneminus = 1.0 - eps private
Definition at line 293 of file radsw_main.f.
Referenced by spcvrtc(), spcvrtm(), swrad(), taumol(), taumol16(), taumol17(), taumol18(), taumol19(), taumol21(), taumol22(), taumol24(), and taumol28().
real (kind=kind_phys), parameter module_radsw_main::s0 = 1368.22 private
Definition at line 297 of file radsw_main.f.
Referenced by swrad().
real (kind=kind_phys), parameter module_radsw_main::stpfac = 296.0/1013.0 private
Definition at line 295 of file radsw_main.f.
Referenced by setcoef().
character(40), parameter module_radsw_main::vtagsw ='NCEP SW v5.1 Nov 2012 -RRTMG-SW v3.8 ' private
Definition at line 280 of file radsw_main.f.
Referenced by rswinit().