Radiation Scheme in CCPP: module_radiation_driver Module Reference
module_radiation_driver Module Reference
This file is the radiation driver module. it prepares atmospheric profiles and invokes main radiation calculation.
Functions/Subroutines
subroutine, public radinit
This subroutine is the initialization of radiation calculations.
subroutine, public radupdate
This subroutine calls many update subroutines to check and update radiation required but time varying data sets and module variables.
subroutine, public grrad
This subroutine is the driver of radiation calculation subroutines. It sets up profile variables for radiation input, including clouds, surface albedos, atmospheric aerosols, ozone, etc.
Variables
character(40), parameter vtagrad ='NCEP-Radiation_driver v5.2 Jan 2013 '
real(kind=kind_phys) qmin
real(kind=kind_phys) qme5
real(kind=kind_phys) qme6
real(kind=kind_phys) epsq
real, parameter prsmin = 1.0e-6
integer itsfc =0
integer month0 =0
integer iyear0 =0
integer monthd =0
logical loz1st =.true.
integer, parameter ltp = 0
logical, parameter lextop = (LTP > 0)
Detailed Description
module_radiation_driver prepares atmospheric profile, invokes main radiation calculations, and computes radiative fluxes and heating rates for some arbitrary number of vertical colums.There are three externally accessible subroutines: radinit, radupdate, and grrad.
Function/Subroutine Documentation
subroutine, public module_radiation_driver::grrad ()
Parameters
[in] prsi real, (IX,LM+1),model level pressure in Pa
[in] prsl real, (IX,LM),model layer mean pressure in Pa
[in] prslk real, (IX,LM),exner function = \((p/p0)^{rocp} \)
[in] tgrs real, (IX,LM),model layer mean temperature in K
[in] qgrs real, (IX,LM),layer specific humidity in gm/gm
[in] tracer real, (IX,LM,NTRAC),layer prognostic tracer amount/mixing-ration; incl: oz,cwc,aeros,etc
[in] vvl real, (IX,LM),layer mean vertical velocity in pa/sec
[in] slmsk real, (IM),sea/land mask array (sea:0,land:1,sea-ice:2)
[in] xlon real, (IM),grid longitude in radians,ok for both 0->2pi or -pi->+pi ranges
[in] xlat real, (IM),grid latitude in radians, default to pi/2->-pi/2 range, otherwise adj in subr called
[in] tsfc real, (IM),surface temperature in K
[in] snowd real, (IM),snow depth water equivalent in mm
[in] sncovr real, (IM),snow cover in fraction
[in] snoalb real, (IM),maximum snow albedo in fraction
[in] zorl real, (IM),surface roughness in cm
[in] hprim real, (IM),topographic standard deviation in m
[in] alvsf real, (IM),mean vis albedo with strong cosz dependency
[in] alnsf real, (IM),mean nir albedo with strong cosz dependency
[in] alvwf real, (IM),mean vis albedo with weak cosz dependency
[in] alnwf real, (IM),mean nir albedo with weak cosz dependency
[in] facsf real, (IM),fractional coverage with strong cosz dependency
[in] facwf real, (IM),fractional coverage with weak cosz dependency
[in] fice real, (IM),ice fraction over open water grid
[in] tisfc real, (IM),surface temperature over ice fraction
[in] sinlat real, (IM),sine of the grids' corresponding latitudes
[in] coslat real, (IM),cosine of the grids' corresponding latitudes
[in] solhr real, 1, hour time after 00z at the t-stepe
[in] jdate integer(8),current forecast date and time (yr, mon, day, t-zone, hr, min, sec, mil-sec)
[in] solcon real, 1, solar constant (sun-earth distant adjusted)
[in] cv real, (IM),fraction of convective cloud
[in] cvt,cvb real, (IM),convective cloud top/bottom pressure in pa
[in] fcice real, (IX,LM),fraction of cloud ice (in ferrier scheme)
[in] frain real, (IX,LM),fraction of rain water (in ferrier scheme)
[in] rrime real, (IX,LM),mass ratio of total to unrimed ice (>= 1)
[in] flgmin real, (IM),minimim large ice fraction
[in] icsdsw,icsdlw integer, (IM),auxiliary cloud control arrays passed to main radiations. if isubcsw/isubclw (input to init) are set to 2, the arrays contains provided random seeds for sub-column clouds generators !
[in] ntcw integer, =0 no cloud condensate calculated; >0 array index location for cloud condensate
[in] ncld integer, only used when ntcw .gt. 0
[in] ntoz integer, =0 climatological ozone profile; >0 interactive ozone profile
[in] NTRAC integer, dimension veriable for array oz
[in] NFXR integer, second dimension of input/output array fluxr
[in] dtlw,dtsw real, time duration for lw/sw radiation call in sec
[in] lsswr,lslwr logical flags for sw/lw radiation calls
[in] lssav logical flag for store 3-d cloud field
[in] IX,IM integer, horizontal dimention and num of used points
[in] LM integer, vertical layer dimension
[in] me integer, control flag for parallel process
[in] lprnt logical, control flag for diagnostic print out
[in] ipt integer, index for diagnostic printout point
[in] kdt integer, time-step number
[in] deltaq real, (IX,LM),half width of uniform total water distribution
[in] sup real, supersaturation in pdf cloud when t is very low
[in] cnvw real, (IX.LM),layer convective cloud water
[in] cnvc real, (IX,LM),layer convective cloud cover
[out] htrsw real, (IX,LM),total sky sw heating rate in k/sec
[out] topfsw type(topfsw_type), (IM),sw radiation fluxes at toa, components: (check module_radsw_parameters for definition)
upfxc - total sky upward sw flux at toa (w/m**2)
dnflx - total sky downward sw flux at toa (w/m**2)
upfx0 - clear sky upward sw flux at toa (w/m**2)
[out] sfcfsw type(sfcfsw_type), (IM),sw radiation fluxes at sfc, components: (check module_radsw_parameters for definition)
upfxc - total sky upward sw flux at sfc (w/m**2)
dnfxc - total sky downward sw flux at sfc (w/m**2)
upfx0 - clear sky upward sw flux at sfc (w/m**2)
dnfx0 - clear sky downward sw flux at sfc (w/m**2)
[out] dswcmp real, (IX,4),dn sfc sw spectral components:
(:, 1) - total sky sfc downward nir direct flux
(:, 2) - total sky sfc downward nir diffused flux
(:, 3) - total sky sfc downward uv+vis direct flux
(:, 4) - total sky sfc downward uv+vis diff flux
[out] uswcmp real, (IX,4),up sfc sw spectral components:
(:, 1) - total sky sfc upward nir direct flux
(:, 2) - total sky sfc upward nir diffused flux
(:, 3) - total sky sfc upward uv+vis direct flux
(:, 4) - total sky sfc upward uv+vis diff flux
[out] sfalb real, (IM),mean surface diffused sw albedo
[out] coszen real, (IM),mean cos of zenith angle over rad call period
[out] coszdg real, (IM),daytime mean cosz over rad call period
[out] htrlw (IX,LM),total sky lw heating rate in k/sec
[out] topflw type(topflw_type), (IM),lw radiation fluxes at top, component:(check module_radlw_paramters for definition)
upfxc - total sky upward lw flux at toa (w/m**2)
upfx0 - clear sky upward lw flux at toa (w/m**2)
[out] sfcflw type(sfcflw_type), (IM),lw radiation fluxes at sfc, component:(check module_radlw_paramters for definition)
upfxc - total sky upward lw flux at sfc (w/m**2)
upfx0 - clear sky upward lw flux at sfc (w/m**2)
dnfxc - total sky downward lw flux at sfc (w/m**2)
dnfx0 - clear sky downward lw flux at sfc (w/m**2)
[out] semis real, (IM),surface lw emissivity in fraction
[out] cldcov real, (IX,LM),3-d cloud fraction
[out] tsflw real, (IM),surface air temp during lw calculation in K
[in,out] fluxr real, (IX,NFXR),to save time accumulated 2-d fields defined as:
1 - toa total sky upwd lw radiation flux
2 - toa total sky upwd sw radiation flux
3 - sfc total sky upwd sw radiation flux
4 - sfc total sky dnwd sw radiation flux
5 - high domain cloud fraction
6 - mid domain cloud fraction
7 - low domain cloud fraction
8 - high domain mean cloud top pressure
9 - mid domain mean cloud top pressure
10 - low domain mean cloud top pressure
11 - high domain mean cloud base pressure
12 - mid domain mean cloud base pressure
13 - low domain mean cloud base pressure
14 - high domain mean cloud top temperature
15 - mid domain mean cloud top temperature
16 - low domain mean cloud top temperature
17 - total cloud fraction
18 - boundary layer domain cloud fraction
19 - sfc total sky dnwd lw radiation flux
20 - sfc total sky upwd lw radiation flux
21 - sfc total sky dnwd sw uv-b radiation flux
22 - sfc clear sky dnwd sw uv-b radiation flux
23 - toa incoming solar radiation flux
24 - sfc vis beam dnwd sw radiation flux
25 - sfc vis diff dnwd sw radiation flux
26 - sfc nir beam dnwd sw radiation flux
27 - sfc nir diff dnwd sw radiation flux
28 - toa clear sky upwd lw radiation flux
29 - toa clear sky upwd sw radiation flux
30 - sfc clear sky dnwd lw radiation flux
31 - sfc clear sky upwd sw radiation flux
32 - sfc clear sky dnwd sw radiation flux
33 - sfc clear sky upwd lw radiation flux
optional:
34 - aeros opt depth at 550nm (all components)
35 - aeros opt depth at 550nm for du component
36 - aeros opt depth at 550nm for bc component
37 - aeros opt depth at 550nm for oc component
38 - aeros opt depth at 550nm for su component
39 - aeros opt depth at 550nm for ss component !
[out] htrswb real, (IX,LM,NBDSW),spectral band total sky sw heating rate
[out] htrlwb real, (IX,LM,NBDLW),spectral band total sky lw heating rate
General Algorithm
Setup surface ground temp and ground/air skin temp (tskn, tsfg)
Prepare atmospheric profiles for radiation input
Compute relative humidity
Get layer ozone mass mixing ratio (olyr)
Compute cosin of zenith angle (coszen, coszdg)
Set up non-prognostic gas volume mixing ratioes(gasvmr)
- gasvmr(:,:,1) - co2 volume mixing ratio
- gasvmr(:,:,2) - n2o volume mixing ratio
- gasvmr(:,:,3) - ch4 volume mixing ratio
- gasvmr(:,:,4) - o2 volume mixing ratio
- gasvmr(:,:,5) - co volume mixing ratio
- gasvmr(:,:,6) - cf11 volume mixing ratio
- gasvmr(:,:,7) - cf12 volume mixing ratio
- gasvmr(:,:,8) - cf22 volume mixing ratio
- gasvmr(:,:,9) - ccl4 volume mixing ratio
Get temperature at layer interface, and layer moisture
Check for daytime points(ndate, idxday)
Setup aerosols property profile for radiation (faersw,faerlw,aerodp)
Call module_radiation_aerosols::setaer
Obtain cloud information for radiation calculations (clouds,cldsa,mtopa,mbota)
— for prognostic cloud —
For zhao/moorthi's prognostic cloud scheme, call module_radiation_clouds::progcld1
For ferrier's microphysics, call module_radiation_clouds::progcld2
For zhao/moorthi's prognostic cloud+pdfcld, call module_radiation_clouds::progcld3
— for diagnostic cloud —
call module_radiation_clouds::diagcld1
Setup surface albedo for sw radiation, incl xw (nov04) sea-ice
subroutine called: module_radiation_surface::setalb
Approximate mean surface albedo from vis (sfcalb(:,4)) and nir (sfcalb(:,2)) diffuse values
Calling module_radsw_main::swrad
Setup surface emissivity (sfcemis) for lw radiation
Call module_radiation_surface::setemis
calling module_radlw_main::lwrad
Save outputs
Definition at line 810 of file grrad.f.
References module_radiation_astronomy::coszmn(), module_radiation_clouds::diagcld1(), epsq, module_radiation_gases::getgases(), module_radiation_gases::getozn(), physparam::icmphys, itsfc, physparam::ivflip, lextop, ltp, module_radlw_main::lwrad(), module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, module_radiation_clouds::progcld1(), module_radiation_clouds::progcld2(), module_radiation_clouds::progcld3(), prsmin, qme5, qme6, qmin, module_radiation_aerosols::setaer(), module_radiation_surface::setalb(), module_radiation_surface::setemis(), and module_radsw_main::swrad().
subroutine, public module_radiation_driver::radinit ()
Parameters
[in] si real, L+1, model vertical sigma interface
[in] nlay integer, 1, number of model vertical layers
[in] me integer, 1, print control flag
General Algorithm
Set up control variables and external module variables in module physparam
Initialization
subroutine called:
astronomy initialization routine: call module_radiation_astronomy::sol_init
aerosols initialization routine: call module_radiation_aerosols::aer_init
co2 and other gases intialization routine: call module_radiation_gases::gas_init
surface intialization routine: call module_radiation_surface::sfc_init
cloud initialization routine: call module_radiation_clouds::cld_init
lw radiation initialization routine: call module_radlw_main::rlwinit
sw radiation initialization routine: call module_radsw_main::rswinit
Definition at line 261 of file grrad.f.
References module_radiation_aerosols::aer_init(), module_radiation_clouds::cld_init(), module_radiation_gases::gas_init(), physparam::iaerflg, physparam::ialbflg, physparam::icldflg, physparam::icmphys, physparam::ico2flg, physparam::ictmflg, physparam::iemsflg, physparam::iovrlw, physparam::iovrsw, physparam::ioznflg, physparam::isolar, physparam::isubclw, physparam::isubcsw, itsfc, physparam::ivflip, iyear0, physparam::lcnorm, physparam::lcrick, lextop, physparam::lnoprec, loz1st, physparam::lsashal, ltp, month0, monthd, module_radlw_main::rlwinit(), module_radsw_main::rswinit(), module_radiation_surface::sfc_init(), module_radiation_astronomy::sol_init(), and vtagrad.
Referenced by rad_initialize().
subroutine, public module_radiation_driver::radupdate ()
Parameters
[in] idate(8) integer, ncep absolute date and time of intial condition (yr,mon,day,t-zone,hr,min,sec,mil-sec)
[in] jdate(8) integer, ncep absolute date and time at fcst time (yr,mon,day,t-zone,hr,min,sec,mil-sec)
[in] deltsw real, 1, sw radiation calling frequency in seconds
[in] deltim real, 1, model timestep in seconds
[in] lsswr logical, logical flags for sw radiation calculations
[in] me integer, 1, print control flag
[out] slag real, equation of time in radians
[out] sdec,cdec real, sin and cos of the solar declination angle
[out] solcon real, sun-earth distance adjusted solar constant (w/m2)
General Algorithm
Set up time stamp at fcst time and that for green house gases (currently co2 only)
Call astronomy updata routine, yearly update, no time interpolation
- subroutine called: module_radiation_astronomy::sol_update
Call aerosols update routine, monthly update, no time interpolation
- subroutine called: module_radiation_aerosols::aer_update
Call co2 and other gases update routine
- subroutine called: module_radiation_gases::gas_update
Call surface update routine (currently not needed)
Call clouds update routine (currently not needed)
Definition at line 495 of file grrad.f.
References module_radiation_aerosols::aer_update(), module_radiation_gases::gas_update(), physparam::ictmflg, physparam::isolar, iyear0, loz1st, month0, monthd, and module_radiation_astronomy::sol_update().
Variable Documentation
real (kind=kind_phys) module_radiation_driver::epsq private
Definition at line 225 of file grrad.f.
Referenced by grrad().
integer module_radiation_driver::itsfc =0 private
Definition at line 232 of file grrad.f.
Referenced by grrad(), and radinit().
integer module_radiation_driver::iyear0 =0 private
Definition at line 235 of file grrad.f.
Referenced by radinit(), and radupdate().
logical, parameter module_radiation_driver::lextop = (LTP > 0) private
Definition at line 241 of file grrad.f.
Referenced by grrad(), and radinit().
logical module_radiation_driver::loz1st =.true. private
Definition at line 236 of file grrad.f.
Referenced by radinit(), and radupdate().
integer, parameter module_radiation_driver::ltp = 0 private
Definition at line 239 of file grrad.f.
Referenced by grrad(), and radinit().
integer module_radiation_driver::month0 =0 private
Definition at line 235 of file grrad.f.
Referenced by radinit(), and radupdate().
integer module_radiation_driver::monthd =0 private
Definition at line 235 of file grrad.f.
Referenced by radinit(), and radupdate().
real, parameter module_radiation_driver::prsmin = 1.0e-6 private
Definition at line 229 of file grrad.f.
Referenced by grrad().
real (kind=kind_phys) module_radiation_driver::qme5 private
Definition at line 225 of file grrad.f.
Referenced by grrad().
real (kind=kind_phys) module_radiation_driver::qme6 private
Definition at line 225 of file grrad.f.
Referenced by grrad().
real (kind=kind_phys) module_radiation_driver::qmin private
Definition at line 225 of file grrad.f.
Referenced by grrad().
character(40), parameter module_radiation_driver::vtagrad ='NCEP-Radiation_driver v5.2 Jan 2013 ' private
Definition at line 219 of file grrad.f.
Referenced by radinit().