Radiation Scheme in CCPP: module_radlw_kgb09 Module Reference
module_radlw_kgb09 Module Reference
This module sets up absorption coefficients for band 09: 1180-1390 cm-1 (low - h2o, ch4; high - ch4)
Variables
integer, public msa09
integer, public msb09
integer, public msf09
integer, public mfr09
integer, public maf09
integer, public mmn09
real(kind=kind_phys), dimension(ng09, mfr09), public forref
real(kind=kind_phys), dimension(ng09, msa09), public absa
real(kind=kind_phys), dimension(ng09, msb09), public absb
real(kind=kind_phys), dimension(ng09, msf09), public selfref
real(kind=kind_phys), dimension(ng09, maf09), public fracrefa
real(kind=kind_phys), dimension(ng09), public fracrefb
real(kind=kind_phys), dimension(ng09, maf09, mmn09), public ka_mn2o
real(kind=kind_phys), dimension(ng09, mmn09), public kb_mn2o
Variable Documentation
real (kind=kind_phys), dimension(ng09,msa09), public module_radlw_kgb09::absa
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09,msb09), public module_radlw_kgb09::absb
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09,mfr09), public module_radlw_kgb09::forref
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09,maf09), public module_radlw_kgb09::fracrefa
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09), public module_radlw_kgb09::fracrefb
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09,maf09,mmn09), public module_radlw_kgb09::ka_mn2o
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
real (kind=kind_phys), dimension(ng09,mmn09), public module_radlw_kgb09::kb_mn2o
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().
integer, public module_radlw_kgb09::maf09
Definition at line 25357 of file radlw_datatb.f.
integer, public module_radlw_kgb09::mfr09
Definition at line 25357 of file radlw_datatb.f.
integer, public module_radlw_kgb09::mmn09
Definition at line 25357 of file radlw_datatb.f.
integer, public module_radlw_kgb09::msa09
Definition at line 25357 of file radlw_datatb.f.
integer, public module_radlw_kgb09::msb09
Definition at line 25357 of file radlw_datatb.f.
integer, public module_radlw_kgb09::msf09
Definition at line 25357 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng09,msf09), public module_radlw_kgb09::selfref
Definition at line 25361 of file radlw_datatb.f.
Referenced by taugb09().