Radiation Scheme in CCPP: module_radlw_kgb08 Module Reference
module_radlw_kgb08 Module Reference
This module sets up absorption coefficients for band 08: 1080-1180 cm-1 (low - h2o; high - o3)
Variables
integer, public msa08
integer, public msb08
integer, public msf08
integer, public mfr08
integer, public mmc08
real(kind=kind_phys), dimension(ng08, mfr08), public forref
real(kind=kind_phys), dimension(ng08, msa08), public absa
real(kind=kind_phys), dimension(ng08, msb08), public absb
real(kind=kind_phys), dimension(ng08, msf08), public selfref
real(kind=kind_phys), dimension(ng08), public fracrefa
real(kind=kind_phys), dimension(ng08), public fracrefb
real(kind=kind_phys), dimension(ng08, mmc08), public ka_mo3
real(kind=kind_phys), dimension(ng08, mmc08), public ka_mco2
real(kind=kind_phys), dimension(ng08, mmc08), public kb_mco2
real(kind=kind_phys), dimension(ng08), public cfc12
real(kind=kind_phys), dimension(ng08, mmc08), public ka_mn2o
real(kind=kind_phys), dimension(ng08, mmc08), public kb_mn2o
real(kind=kind_phys), dimension(ng08), public cfc22adj
Variable Documentation
real (kind=kind_phys), dimension(ng08,msa08), public module_radlw_kgb08::absa
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,msb08), public module_radlw_kgb08::absb
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc12
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::cfc22adj
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mfr08), public module_radlw_kgb08::forref
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefa
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08), public module_radlw_kgb08::fracrefb
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mco2
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mn2o
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::ka_mo3
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::kb_mco2
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
real (kind=kind_phys), dimension(ng08,mmc08), public module_radlw_kgb08::kb_mn2o
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().
integer, public module_radlw_kgb08::mfr08
Definition at line 24573 of file radlw_datatb.f.
integer, public module_radlw_kgb08::mmc08
Definition at line 24573 of file radlw_datatb.f.
integer, public module_radlw_kgb08::msa08
Definition at line 24573 of file radlw_datatb.f.
integer, public module_radlw_kgb08::msb08
Definition at line 24573 of file radlw_datatb.f.
integer, public module_radlw_kgb08::msf08
Definition at line 24573 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng08,msf08), public module_radlw_kgb08::selfref
Definition at line 24576 of file radlw_datatb.f.
Referenced by taugb08().