Radiation Scheme in CCPP: module_radsw_kgb24 Module Reference
module_radsw_kgb24 Module Reference
This module sets up absorption coeffients for band 24: 12850-16000 cm-1 (low - h2o, o2; high - o2)
Variables
integer, public msa24
integer, public msb24
integer, public msf24
integer, public mfr24
integer, public mfx24
real(kind=kind_phys), dimension(mfr24, ng24), public forref
real(kind=kind_phys), dimension(msa24, ng24), public absa
real(kind=kind_phys), dimension(msb24, ng24), public absb
real(kind=kind_phys), dimension(msf24, ng24), public selfref
real(kind=kind_phys), dimension(ng24), public abso3a
real(kind=kind_phys), dimension(ng24), public abso3b
real(kind=kind_phys), dimension(ng24, mfx24), public rayla
real(kind=kind_phys), dimension(ng24), public raylb
Variable Documentation
real (kind=kind_phys), dimension(msa24,ng24), public module_radsw_kgb24::absa
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(msb24,ng24), public module_radsw_kgb24::absb
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3a
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::abso3b
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(mfr24,ng24), public module_radsw_kgb24::forref
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
integer, public module_radsw_kgb24::mfr24
Definition at line 16219 of file radsw_datatb.f.
integer, public module_radsw_kgb24::mfx24
Definition at line 16219 of file radsw_datatb.f.
integer, public module_radsw_kgb24::msa24
Definition at line 16219 of file radsw_datatb.f.
integer, public module_radsw_kgb24::msb24
Definition at line 16219 of file radsw_datatb.f.
integer, public module_radsw_kgb24::msf24
Definition at line 16219 of file radsw_datatb.f.
real (kind=kind_phys), dimension(ng24,mfx24), public module_radsw_kgb24::rayla
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(ng24), public module_radsw_kgb24::raylb
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().
real (kind=kind_phys), dimension(msf24,ng24), public module_radsw_kgb24::selfref
Definition at line 16222 of file radsw_datatb.f.
Referenced by taumol24().