Radiation Scheme in CCPP: module_radlw_kgb05 Module Reference
module_radlw_kgb05 Module Reference
This module sets up absorption coefficients for band 05: 700-820 cm-1 (low - h2o, co2; high - co2, o3)
Variables
integer, public msa05
integer, public msb05
integer, public msf05
integer, public mfr05
integer, public maf05
integer, public mbf05
integer, public mmo05
real(kind=kind_phys), dimension(ng05, mfr05), public forref
real(kind=kind_phys), dimension(ng05, msa05), public absa
real(kind=kind_phys), dimension(ng05, msb05), public absb
real(kind=kind_phys), dimension(ng05, msf05), public selfref
real(kind=kind_phys), dimension(ng05, maf05), public fracrefa
real(kind=kind_phys), dimension(ng05, mbf05), public fracrefb
real(kind=kind_phys), dimension(ng05, maf05, mmo05), public ka_mo3
real(kind=kind_phys), dimension(ng05), public ccl4
Variable Documentation
real (kind=kind_phys), dimension(ng05,msa05), public module_radlw_kgb05::absa
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05,msb05), public module_radlw_kgb05::absb
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05), public module_radlw_kgb05::ccl4
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05,mfr05), public module_radlw_kgb05::forref
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05,maf05), public module_radlw_kgb05::fracrefa
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05,mbf05), public module_radlw_kgb05::fracrefb
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
real (kind=kind_phys), dimension(ng05,maf05,mmo05), public module_radlw_kgb05::ka_mo3
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().
integer, public module_radlw_kgb05::maf05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mbf05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mfr05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::mmo05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::msa05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::msb05
Definition at line 15237 of file radlw_datatb.f.
integer, public module_radlw_kgb05::msf05
Definition at line 15237 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng05,msf05), public module_radlw_kgb05::selfref
Definition at line 15241 of file radlw_datatb.f.
Referenced by taugb05().