Radiation Scheme in CCPP: module_radsw_kgb29 Module Reference
module_radsw_kgb29 Module Reference
This module sets up absorption coeffients for band 29: 820-2600 cm-1 (low - h2o; high - co2)
Variables
integer, public msa29
integer, public msb29
integer, public msf29
integer, public mfr29
real(kind=kind_phys), dimension(mfr29, ng29), public forref
real(kind=kind_phys), dimension(msa29, ng29), public absa
real(kind=kind_phys), dimension(msb29, ng29), public absb
real(kind=kind_phys), dimension(msf29, ng29), public selfref
real(kind=kind_phys), dimension(ng29), public absh2o
real(kind=kind_phys), dimension(ng29), public absco2
real(kind=kind_phys), parameter, public rayl = 9.30e-11
Variable Documentation
real (kind=kind_phys), dimension(msa29,ng29), public module_radsw_kgb29::absa
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(msb29,ng29), public module_radsw_kgb29::absb
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absco2
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(ng29), public module_radsw_kgb29::absh2o
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(mfr29,ng29), public module_radsw_kgb29::forref
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().
integer, public module_radsw_kgb29::mfr29
Definition at line 20843 of file radsw_datatb.f.
integer, public module_radsw_kgb29::msa29
Definition at line 20843 of file radsw_datatb.f.
integer, public module_radsw_kgb29::msb29
Definition at line 20843 of file radsw_datatb.f.
integer, public module_radsw_kgb29::msf29
Definition at line 20843 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb29::rayl = 9.30e-11
Definition at line 20851 of file radsw_datatb.f.
Referenced by taumol29().
real (kind=kind_phys), dimension(msf29,ng29), public module_radsw_kgb29::selfref
Definition at line 20846 of file radsw_datatb.f.
Referenced by taumol29().