Radiation Scheme in CCPP: module_microphysics Module Reference
module_microphysics Module Reference
Functions/Subroutines
subroutine gsmconst (DTPG, mype, first)
subroutine my_growth_rates (DTPH)
subroutine ice_lookup
subroutine rain_lookup
subroutine gsmcolumn (ARAING, ASNOWG, DTPG, I_index, J_index, LSFC, P_col, QI_col, QR_col, QV_col, QW_col, RimeF_col, T_col, THICK_col, WC_col, LM, RHC_col, XNCW, FLGmin, PRINT_diag, psfc)
subroutine rsipath (im, ix, ix2, levs, prsl, prsi, t, q, clw , f_ice, f_rain, f_rime, flgmin , cwatp, cicep, rainp, snowp , recwat, rerain, resnow, lprnt, ipr)
subroutine rsipath2
This subroutine is a modified version of ferrier's original "rsipath" subprogram. It computes layer's cloud liquid, ice, rain, and snow water condensate path and the partical effective radius for liquid droplet, rain drop, and snow flake.
Variables
real, private abfr
real, private cbfr
real, private ciacw
real, private ciacr
real, private c_n0r0
real, private cn0r0
real, private cn0r_dmrmin
real, private cn0r_dmrmax
real, private cracw
real, private craut
real, private esw0
real, private qautx
real, private rfmax
real, private rqr_dr1
real, private rqr_dr2
real, private rqr_dr3
real, private rqr_drmin
real, private rqr_drmax
real, private rr_drmin
real, private rr_dr1
real, private rr_dr2
real, private rr_dr3
real, private rr_drmax
integer, private mic_step
integer, parameter, private my_t1 =1
integer, parameter, private my_t2 =35
real, dimension(my_t1:my_t2), private my_growth
real, parameter, private dmimin =.05e-3
real, parameter, private dmimax =1.e-3
real, parameter, private xmimin =1.e6*DMImin
real, parameter, private xmimax =1.e6*DMImax
real, parameter, private deldmi =1.e-6
integer, parameter, private mdimin =XMImin
integer, parameter, private mdimax =XMImax
real, dimension(mdimin:mdimax), private accri
real, dimension(mdimin:mdimax), private massi
real, dimension(mdimin:mdimax), private sdens
real, dimension(mdimin:mdimax), private vsnowi
real, dimension(mdimin:mdimax), private venti1
real, dimension(mdimin:mdimax), private venti2
real, parameter, private dmrmin =.05e-3
real, parameter, private dmrmax =.45e-3
real, parameter, private xmrmin =1.e6*DMRmin
real, parameter, private xmrmax =1.e6*DMRmax
real, parameter, private deldmr =1.e-6
real, parameter, private nlimin =100.
integer, parameter, private mdrmin =XMRmin
integer, parameter, private mdrmax =XMRmax
integer, parameter, private indexsmin =100
real, parameter, private rerainmin =1.5*XMRmin
real, dimension(mdrmin:mdrmax), private accrr
real, dimension(mdrmin:mdrmax), private massr
real, dimension(mdrmin:mdrmax), private rrate
real, dimension(mdrmin:mdrmax), private vrain
real, dimension(mdrmin:mdrmax), private ventr1
real, dimension(mdrmin:mdrmax), private ventr2
integer, parameter, private nrime =40
real, dimension(2:9, 0:nrime), private vel_rf
integer, parameter itlo =-60
integer, parameter ithi =40
integer, dimension(itlo:ithi, 4) nstats
real, dimension(itlo:ithi, 5) qmax
real, dimension(itlo:ithi, 22) qtot
real, parameter, private thom =T_ICE
real, parameter, private tnw =50.
real, parameter, private toler =1.0E-20
Function/Subroutine Documentation
subroutine module_microphysics::gsmcolumn (real ARAING, real ASNOWG, real DTPG, integer I_index, integer J_index, integer LSFC, real, dimension(lm) P_col, real, dimension(lm) QI_col, real, dimension(lm) QR_col, real, dimension(lm) QV_col, real, dimension(lm) QW_col, real, dimension(lm) RimeF_col, real, dimension(lm) T_col, real, dimension(lm) THICK_col, real, dimension(lm) WC_col, integer LM, real, dimension(lm) RHC_col, real, dimension(lm) XNCW, real FLGmin, logical PRINT_diag, real psfc)
Definition at line 1138 of file module_bfmicrophysics.f.
References abfr, accri, accrr, cbfr, ciacr, ciacw, cn0r0, cn0r_dmrmax, cn0r_dmrmin, condense(), cracw, craut, deldmi, deposit(), dmimax, esw0, ithi, itlo, massi, mdimax, mdrmax, mdrmin, mic_step, my_growth, my_t1, my_t2, nlimin, nrime, nstats, qautx, qmax, qtot, rfmax, rqr_drmax, rqr_drmin, rr_dr1, rr_dr2, rr_dr3, rr_drmax, rr_drmin, toler, vel_rf, venti1, venti2, ventr1, ventr2, vrain, vsnowi, xmimax, and xmimin.
subroutine module_microphysics::gsmconst (real DTPG, integer mype, logical first)
Definition at line 123 of file module_bfmicrophysics.f.
References abfr, accri, accrr, c_n0r0, cbfr, ciacr, ciacw, cn0r0, cn0r_dmrmax, cn0r_dmrmin, cracw, craut, dmrmax, dmrmin, esw0, ice_lookup(), massi, massr, mdimax, mdimin, mdrmax, mdrmin, mic_step, my_growth_rates(), nrime, qautx, rain_lookup(), rfmax, rqr_dr1, rqr_dr2, rqr_dr3, rqr_drmax, rqr_drmin, rr_dr1, rr_dr2, rr_dr3, rr_drmax, rr_drmin, rrate, sdens, vel_rf, venti1, venti2, ventr1, ventr2, vrain, and vsnowi.
subroutine module_microphysics::ice_lookup ()
Definition at line 438 of file module_bfmicrophysics.f.
References accri, deldmi, massi, mdimax, mdimin, nrime, vel_rf, venti1, venti2, and vsnowi.
Referenced by gsmconst().
subroutine module_microphysics::my_growth_rates (real DTPH)
Definition at line 396 of file module_bfmicrophysics.f.
References my_growth.
Referenced by gsmconst().
subroutine module_microphysics::rain_lookup ()
Definition at line 973 of file module_bfmicrophysics.f.
References accrr, deldmr, massr, mdrmax, mdrmin, rrate, ventr1, ventr2, and vrain.
Referenced by gsmconst().
subroutine module_microphysics::rsipath (integer im, integer ix, integer ix2, integer levs, real, dimension(ix,levs) prsl, real, dimension(ix,levs+1) prsi, real, dimension(ix,levs) t, real, dimension(ix,levs) q, real, dimension(ix2,levs) clw, real, dimension(ix2,levs) f_ice, real, dimension(ix2,levs) f_rain, real, dimension(ix2,levs) f_rime, real flgmin, real, dimension(ix,levs) cwatp, real, dimension(ix,levs) cicep, real, dimension(ix,levs) rainp, real, dimension(ix,levs) snowp, real, dimension(ix,levs) recwat, real, dimension(ix,levs) rerain, real, dimension(ix,levs) resnow, logical lprnt, integer ipr)
Definition at line 2641 of file module_bfmicrophysics.f.
References cn0r0, indexsmin, massi, mdimax, mdimin, nlimin, rerainmin, sdens, thom, tnw, xmimax, xmrmax, and xmrmin.
Variable Documentation
real, private module_microphysics::abfr private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, dimension(mdimin:mdimax), private module_microphysics::accri private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
real, dimension(mdrmin:mdrmax), private module_microphysics::accrr private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
real, private module_microphysics::c_n0r0 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, private module_microphysics::cbfr private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::ciacr private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::ciacw private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::cn0r0 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), rsipath(), and rsipath2().
real, private module_microphysics::cn0r_dmrmax private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::cn0r_dmrmin private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::cracw private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::craut private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, parameter, private module_microphysics::deldmi =1.e-6 private
Definition at line 39 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and ice_lookup().
real, parameter, private module_microphysics::deldmr =1.e-6 private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by rain_lookup().
real, parameter, private module_microphysics::dmimax =1.e-3 private
Definition at line 39 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, parameter, private module_microphysics::dmimin =.05e-3 private
Definition at line 39 of file module_bfmicrophysics.f.
real, parameter, private module_microphysics::dmrmax =.45e-3 private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, parameter, private module_microphysics::dmrmin =.05e-3 private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, private module_microphysics::esw0 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
integer, parameter, private module_microphysics::indexsmin =100 private
Definition at line 64 of file module_bfmicrophysics.f.
Referenced by rsipath(), and rsipath2().
integer, parameter module_microphysics::ithi =40
Definition at line 91 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
integer, parameter module_microphysics::itlo =-60
Definition at line 91 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, dimension(mdimin:mdimax), private module_microphysics::massi private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), ice_lookup(), rsipath(), and rsipath2().
real, dimension(mdrmin:mdrmax), private module_microphysics::massr private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmconst(), and rain_lookup().
integer, parameter, private module_microphysics::mdimax =XMImax private
Definition at line 42 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), ice_lookup(), rsipath(), and rsipath2().
integer, parameter, private module_microphysics::mdimin =XMImin private
Definition at line 42 of file module_bfmicrophysics.f.
Referenced by gsmconst(), ice_lookup(), rsipath(), and rsipath2().
integer, parameter, private module_microphysics::mdrmax =XMRmax private
Definition at line 56 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
integer, parameter, private module_microphysics::mdrmin =XMRmin private
Definition at line 56 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
integer, private module_microphysics::mic_step private
Definition at line 22 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, dimension(my_t1:my_t2), private module_microphysics::my_growth private
Definition at line 32 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and my_growth_rates().
integer, parameter, private module_microphysics::my_t1 =1 private
Definition at line 31 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
integer, parameter, private module_microphysics::my_t2 =35 private
Definition at line 31 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, parameter, private module_microphysics::nlimin =100. private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), rsipath(), and rsipath2().
integer, parameter, private module_microphysics::nrime =40 private
Definition at line 86 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
integer, dimension(itlo:ithi,4) module_microphysics::nstats
Definition at line 92 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, private module_microphysics::qautx private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, dimension(itlo:ithi,5) module_microphysics::qmax
Definition at line 93 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, dimension(itlo:ithi,22) module_microphysics::qtot
Definition at line 93 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, parameter, private module_microphysics::rerainmin =1.5*XMRmin private
Definition at line 65 of file module_bfmicrophysics.f.
Referenced by rsipath(), and rsipath2().
real, private module_microphysics::rfmax private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rqr_dr1 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, private module_microphysics::rqr_dr2 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, private module_microphysics::rqr_dr3 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmconst().
real, private module_microphysics::rqr_drmax private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rqr_drmin private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rr_dr1 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rr_dr2 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rr_dr3 private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rr_drmax private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, private module_microphysics::rr_drmin private
Definition at line 17 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), and gsmconst().
real, dimension(mdrmin:mdrmax), private module_microphysics::rrate private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmconst(), and rain_lookup().
real, dimension(mdimin:mdimax), private module_microphysics::sdens private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmconst(), rsipath(), and rsipath2().
real, parameter, private module_microphysics::thom =T_ICE private
Definition at line 103 of file module_bfmicrophysics.f.
Referenced by rsipath().
real, parameter, private module_microphysics::tnw =50. private
Definition at line 103 of file module_bfmicrophysics.f.
Referenced by rsipath(), and rsipath2().
real, parameter, private module_microphysics::toler =1.0E-20 private
Definition at line 103 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, dimension(2:9,0:nrime), private module_microphysics::vel_rf private
Definition at line 87 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
real, dimension(mdimin:mdimax), private module_microphysics::venti1 private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
real, dimension(mdimin:mdimax), private module_microphysics::venti2 private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
real, dimension(mdrmin:mdrmax), private module_microphysics::ventr1 private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
real, dimension(mdrmin:mdrmax), private module_microphysics::ventr2 private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
real, dimension(mdrmin:mdrmax), private module_microphysics::vrain private
Definition at line 77 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and rain_lookup().
real, dimension(mdimin:mdimax), private module_microphysics::vsnowi private
Definition at line 46 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), gsmconst(), and ice_lookup().
real, parameter, private module_microphysics::xmimax =1.e6*DMImax private
Definition at line 39 of file module_bfmicrophysics.f.
Referenced by gsmcolumn(), rsipath(), and rsipath2().
real, parameter, private module_microphysics::xmimin =1.e6*DMImin private
Definition at line 39 of file module_bfmicrophysics.f.
Referenced by gsmcolumn().
real, parameter, private module_microphysics::xmrmax =1.e6*DMRmax private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by rsipath(), and rsipath2().
real, parameter, private module_microphysics::xmrmin =1.e6*DMRmin private
Definition at line 52 of file module_bfmicrophysics.f.
Referenced by rsipath(), and rsipath2().