Radiation Scheme in CCPP: module_radlw_kgb02 Module Reference
module_radlw_kgb02 Module Reference
This module sets up absorption coefficients for band 02: 250-500 cm-1 (low - h2o; high - h2o)
Variables
integer, public msa02
integer, public msb02
integer, public msf02
integer, public mfr02
real(kind=kind_phys), dimension(ng02, msa02), public absa
real(kind=kind_phys), dimension(ng02, msb02), public absb
real(kind=kind_phys), dimension(ng02, msf02), public selfref
real(kind=kind_phys), dimension(ng02, mfr02), public forref
real(kind=kind_phys), dimension(ng02), public fracrefa
real(kind=kind_phys), dimension(ng02), public fracrefb
Variable Documentation
real (kind=kind_phys), dimension(ng02,msa02), public module_radlw_kgb02::absa
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng02,msb02), public module_radlw_kgb02::absb
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng02,mfr02), public module_radlw_kgb02::forref
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefa
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().
real (kind=kind_phys), dimension(ng02), public module_radlw_kgb02::fracrefb
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().
integer, public module_radlw_kgb02::mfr02
Definition at line 2413 of file radlw_datatb.f.
integer, public module_radlw_kgb02::msa02
Definition at line 2413 of file radlw_datatb.f.
integer, public module_radlw_kgb02::msb02
Definition at line 2413 of file radlw_datatb.f.
integer, public module_radlw_kgb02::msf02
Definition at line 2413 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng02,msf02), public module_radlw_kgb02::selfref
Definition at line 2416 of file radlw_datatb.f.
Referenced by taugb02().