Radiation Scheme in CCPP: module_radsw_kgb18 Module Reference
module_radsw_kgb18 Module Reference
This module sets up absorption coeffients for band 18: 4000-4650 cm-1 (low - h2o,ch4; high - ch4)
Variables
integer, public msa18
integer, public msb18
integer, public msf18
integer, public mfr18
real(kind=kind_phys), dimension(msf18, ng18), public selfref
real(kind=kind_phys), dimension(msa18, ng18), public absa
real(kind=kind_phys), dimension(msb18, ng18), public absb
real(kind=kind_phys), dimension(mfr18, ng18), public forref
real(kind=kind_phys), parameter, public rayl = 1.39e-09
Variable Documentation
real (kind=kind_phys), dimension(msa18,ng18), public module_radsw_kgb18::absa
Definition at line 7914 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(msb18,ng18), public module_radsw_kgb18::absb
Definition at line 7914 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(mfr18,ng18), public module_radsw_kgb18::forref
Definition at line 7914 of file radsw_datatb.f.
Referenced by taumol18().
integer, public module_radsw_kgb18::mfr18
Definition at line 7911 of file radsw_datatb.f.
integer, public module_radsw_kgb18::msa18
Definition at line 7911 of file radsw_datatb.f.
integer, public module_radsw_kgb18::msb18
Definition at line 7911 of file radsw_datatb.f.
integer, public module_radsw_kgb18::msf18
Definition at line 7911 of file radsw_datatb.f.
real (kind=kind_phys), parameter, public module_radsw_kgb18::rayl = 1.39e-09
Definition at line 7918 of file radsw_datatb.f.
Referenced by taumol18().
real (kind=kind_phys), dimension(msf18,ng18), public module_radsw_kgb18::selfref
Definition at line 7914 of file radsw_datatb.f.
Referenced by taumol18().