Radiation Scheme in CCPP: module_radlw_kgb01 Module Reference
module_radlw_kgb01 Module Reference
This module sets up absorption coefficients for band 01: 10-250 cm-1 (low - h2o; high - h2o)
Variables
integer, public msa01
integer, public msb01
integer, public msf01
integer, public mfr01
integer, public mmn01
real(kind=kind_phys), dimension(ng01, msa01), public absa
real(kind=kind_phys), dimension(ng01, msb01), public absb
real(kind=kind_phys), dimension(ng01, msf01), public selfref
real(kind=kind_phys), dimension(ng01, mfr01), public forref
real(kind=kind_phys), dimension(ng01), public fracrefa
real(kind=kind_phys), dimension(ng01), public fracrefb
real(kind=kind_phys), dimension(ng01, mmn01), public ka_mn2
real(kind=kind_phys), dimension(ng01, mmn01), public kb_mn2
Variable Documentation
real (kind=kind_phys), dimension(ng01,msa01), public module_radlw_kgb01::absa
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01,msb01), public module_radlw_kgb01::absb
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01,mfr01), public module_radlw_kgb01::forref
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefa
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01), public module_radlw_kgb01::fracrefb
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01,mmn01), public module_radlw_kgb01::ka_mn2
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
real (kind=kind_phys), dimension(ng01,mmn01), public module_radlw_kgb01::kb_mn2
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().
integer, public module_radlw_kgb01::mfr01
Definition at line 1617 of file radlw_datatb.f.
integer, public module_radlw_kgb01::mmn01
Definition at line 1617 of file radlw_datatb.f.
integer, public module_radlw_kgb01::msa01
Definition at line 1617 of file radlw_datatb.f.
integer, public module_radlw_kgb01::msb01
Definition at line 1617 of file radlw_datatb.f.
integer, public module_radlw_kgb01::msf01
Definition at line 1617 of file radlw_datatb.f.
real (kind=kind_phys), dimension(ng01,msf01), public module_radlw_kgb01::selfref
Definition at line 1620 of file radlw_datatb.f.
Referenced by taugb01().