Radiation Scheme in CCPP: module_radsw_cldprtb Module Reference
module_radsw_cldprtb Module Reference
This module contains coefficients of cloud optical properties for each of the spectral bands. It is modified from AER/ECMWF RRTM SW radiation package subroutine "susrtop".
Variables
real(kind=kind_phys), dimension(58, nblow:nbhgh), public extliq1
real(kind=kind_phys), dimension(58, nblow:nbhgh), public ssaliq1
real(kind=kind_phys), dimension(58, nblow:nbhgh), public asyliq1
real(kind=kind_phys), dimension(43, nblow:nbhgh), public extice2
real(kind=kind_phys), dimension(43, nblow:nbhgh), public ssaice2
real(kind=kind_phys), dimension(43, nblow:nbhgh), public asyice2
real(kind=kind_phys), dimension(46, nblow:nbhgh), public extice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public ssaice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public asyice3
real(kind=kind_phys), dimension(46, nblow:nbhgh), public fdlice3
real(kind=kind_phys), dimension(5), public abari
real(kind=kind_phys), dimension(5), public bbari
real(kind=kind_phys), dimension(5), public cbari
real(kind=kind_phys), dimension(5), public dbari
real(kind=kind_phys), dimension(5), public ebari
real(kind=kind_phys), dimension(5), public fbari
real(kind=kind_phys), public a0r
real(kind=kind_phys), public a1r
real(kind=kind_phys), public a0s
real(kind=kind_phys), public a1s
real(kind=kind_phys), dimension(nblow:nbhgh), public b0r
real(kind=kind_phys), dimension(nblow:nbhgh), public b0s
real(kind=kind_phys), dimension(nblow:nbhgh), public b1s
real(kind=kind_phys), dimension(nblow:nbhgh), public c0r
real(kind=kind_phys), dimension(nblow:nbhgh), public c0s
Variable Documentation
real (kind=kind_phys), public module_radsw_cldprtb::a0r
Definition at line 1803 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), public module_radsw_cldprtb::a0s
Definition at line 1803 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), public module_radsw_cldprtb::a1r
Definition at line 1803 of file radsw_datatb.f.
real (kind=kind_phys), public module_radsw_cldprtb::a1s
Definition at line 1803 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::abari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::asyice2
Definition at line 182 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::asyice3
Definition at line 184 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(58,nblow:nbhgh), public module_radsw_cldprtb::asyliq1
Definition at line 180 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0r
Definition at line 1806 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b0s
Definition at line 1806 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::b1s
Definition at line 1806 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::bbari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0r
Definition at line 1806 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(nblow:nbhgh), public module_radsw_cldprtb::c0s
Definition at line 1806 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::cbari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::dbari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::ebari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::extice2
Definition at line 182 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::extice3
Definition at line 184 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(58,nblow:nbhgh), public module_radsw_cldprtb::extliq1
Definition at line 180 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(5), public module_radsw_cldprtb::fbari
Definition at line 186 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::fdlice3
Definition at line 184 of file radsw_datatb.f.
real (kind=kind_phys), dimension(43,nblow:nbhgh), public module_radsw_cldprtb::ssaice2
Definition at line 182 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(46,nblow:nbhgh), public module_radsw_cldprtb::ssaice3
Definition at line 184 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().
real (kind=kind_phys), dimension(58,nblow:nbhgh), public module_radsw_cldprtb::ssaliq1
Definition at line 180 of file radsw_datatb.f.
Referenced by module_radsw_main::cldprop().