Radiation Scheme in CCPP: radlw_main.f File Reference
radlw_main.f File Reference
Modules
module module_radlw_main
This module includes ncep's modifications of the rrtm-lw radiation ! code from aer inc.
Functions/Subroutines
subroutine, public module_radlw_main::rlwinit
This subroutine performs calculations necessary for the initialization of the longwave model. lookup tables are computed for use in the lw radiative transfer, and input absorption coefficient data for each spectral band are reduced from 256 g-point intervals to 140.
subroutine module_radlw_main::mcica_subcol
This suroutine computes sub-colum cloud profile flag array.
subroutine module_radlw_main::setcoef
This subroutine computes various coefficients needed in radiative transfer calculations.
subroutine module_radlw_main::rtrn
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds assumed as randomly overlaping in a vertical column.
subroutine module_radlw_main::taumol
This subroutine contains optical depths developed for the rapid radiative transfer model.
subroutine taugb01
subroutine taugb02
subroutine taugb03
subroutine taugb04
subroutine taugb05
subroutine taugb06
subroutine taugb07
subroutine taugb08
subroutine taugb09
subroutine taugb10
subroutine taugb11
subroutine taugb12
subroutine taugb13
subroutine taugb14
subroutine taugb15
subroutine taugb16
subroutine, public module_radlw_main::lwrad
This subroutine is the main lw radiation routine.
subroutine module_radlw_main::cldprop
This subroutine computes the cloud optical depth(s) for each cloudy layer and g-point interval.
subroutine module_radlw_main::rtrnmr
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere. Clouds are assumed as in maximum-randomly overlaping in a vertical column.
subroutine module_radlw_main::rtrnmc
This subroutine computes the upward/downward radiative fluxes, and heating rates for both clear or cloudy atmosphere.Clouds are treated with the mcica stochastic approach.
Variables
character(40), parameter module_radlw_main::vtaglw ='NCEP LW v5.1 Nov 2012 -RRTMG-LW v4.82 '
real(kind=kind_phys), parameter module_radlw_main::eps = 1.0e-6
real(kind=kind_phys), parameter module_radlw_main::oneminus = 1.0-eps
real(kind=kind_phys), parameter module_radlw_main::cldmin = 1.0e-80
real(kind=kind_phys), parameter module_radlw_main::bpade = 1.0/0.278
real(kind=kind_phys), parameter module_radlw_main::stpfac = 296.0/1013.0
real(kind=kind_phys), parameter module_radlw_main::wtdiff = 0.5
real(kind=kind_phys), parameter module_radlw_main::tblint = ntbl
real(kind=kind_phys), parameter module_radlw_main::f_zero = 0.0
real(kind=kind_phys), parameter module_radlw_main::f_one = 1.0
real(kind=kind_phys), parameter module_radlw_main::amdw = con_amd/con_amw
real(kind=kind_phys), parameter module_radlw_main::amdo3 = con_amd/con_amo3
integer, dimension(nbands) module_radlw_main::nspa
integer, dimension(nbands) module_radlw_main::nspb
real(kind=kind_phys), dimension(nbands) module_radlw_main::a0
real(kind=kind_phys), dimension(nbands) module_radlw_main::a1
real(kind=kind_phys), dimension(nbands) module_radlw_main::a2
logical module_radlw_main::lhlwb = .false.
logical module_radlw_main::lhlw0 = .false.
logical module_radlw_main::lflxprf = .false.
real(kind=kind_phys) module_radlw_main::fluxfac
real(kind=kind_phys) module_radlw_main::heatfac
real(kind=kind_phys), dimension(nbands) module_radlw_main::semiss0
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::tau_tbl
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::exp_tbl
real(kind=kind_phys), dimension(0:ntbl) module_radlw_main::tfn_tbl
integer, parameter module_radlw_main::ipsdlw0 = ngptlw
Function/Subroutine Documentation
subroutine taumol::taugb01 () private
Definition at line 3848 of file radlw_main.f.
References module_radlw_kgb01::absa, module_radlw_kgb01::absb, module_radlw_main::f_one, module_radlw_kgb01::forref, module_radlw_kgb01::fracrefa, module_radlw_kgb01::fracrefb, module_radlw_kgb01::ka_mn2, module_radlw_kgb01::kb_mn2, module_radlw_parameters::ng01, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb01::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb02 ()
Definition at line 3954 of file radlw_main.f.
References module_radlw_kgb02::absa, module_radlw_kgb02::absb, module_radlw_main::f_one, module_radlw_kgb02::forref, module_radlw_kgb02::fracrefa, module_radlw_kgb02::fracrefb, module_radlw_parameters::ng02, module_radlw_parameters::ns02, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb02::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb03 ()
Definition at line 4030 of file radlw_main.f.
References module_radlw_kgb03::absa, module_radlw_kgb03::absb, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb03::forref, module_radlw_kgb03::fracrefa, module_radlw_kgb03::fracrefb, module_radlw_kgb03::ka_mn2o, module_radlw_kgb03::kb_mn2o, module_radlw_parameters::ng03, module_radlw_parameters::ns03, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb03::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb04 ()
Definition at line 4336 of file radlw_main.f.
References module_radlw_kgb04::absa, module_radlw_kgb04::absb, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb04::forref, module_radlw_kgb04::fracrefa, module_radlw_kgb04::fracrefb, module_radlw_parameters::ng04, module_radlw_parameters::ns04, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb04::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb05 ()
Definition at line 4579 of file radlw_main.f.
References module_radlw_kgb05::absa, module_radlw_kgb05::absb, module_radlw_kgb05::ccl4, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb05::forref, module_radlw_kgb05::fracrefa, module_radlw_kgb05::fracrefb, module_radlw_kgb05::ka_mo3, module_radlw_parameters::ng05, module_radlw_parameters::ns05, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb05::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb06 ()
Definition at line 4840 of file radlw_main.f.
References module_radlw_kgb06::absa, module_radlw_kgb06::cfc11adj, module_radlw_kgb06::cfc12, module_radlw_ref::chi_mls, module_radlw_kgb06::forref, module_radlw_kgb06::fracrefa, module_radlw_kgb06::ka_mco2, module_radlw_parameters::ng06, module_radlw_parameters::ns06, module_radlw_main::nspa, and module_radlw_kgb06::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb07 ()
Definition at line 4925 of file radlw_main.f.
References module_radlw_kgb07::absa, module_radlw_kgb07::absb, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb07::forref, module_radlw_kgb07::fracrefa, module_radlw_kgb07::fracrefb, module_radlw_kgb07::ka_mco2, module_radlw_kgb07::kb_mco2, module_radlw_parameters::ng07, module_radlw_parameters::ns07, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb07::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb08 ()
Definition at line 5184 of file radlw_main.f.
References module_radlw_kgb08::absa, module_radlw_kgb08::absb, module_radlw_kgb08::cfc12, module_radlw_kgb08::cfc22adj, module_radlw_ref::chi_mls, module_radlw_kgb08::forref, module_radlw_kgb08::fracrefa, module_radlw_kgb08::fracrefb, module_radlw_kgb08::ka_mco2, module_radlw_kgb08::ka_mn2o, module_radlw_kgb08::ka_mo3, module_radlw_kgb08::kb_mco2, module_radlw_kgb08::kb_mn2o, module_radlw_parameters::ng08, module_radlw_parameters::ns08, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb08::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb09 ()
Definition at line 5307 of file radlw_main.f.
References module_radlw_kgb09::absa, module_radlw_kgb09::absb, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb09::forref, module_radlw_kgb09::fracrefa, module_radlw_kgb09::fracrefb, module_radlw_kgb09::ka_mn2o, module_radlw_kgb09::kb_mn2o, module_radlw_parameters::ng09, module_radlw_parameters::ns09, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb09::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb10 ()
Definition at line 5555 of file radlw_main.f.
References module_radlw_kgb10::absa, module_radlw_kgb10::absb, module_radlw_kgb10::forref, module_radlw_kgb10::fracrefa, module_radlw_kgb10::fracrefb, module_radlw_parameters::ng10, module_radlw_parameters::ns10, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb10::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb11 ()
Definition at line 5629 of file radlw_main.f.
References module_radlw_kgb11::absa, module_radlw_kgb11::absb, module_radlw_kgb11::forref, module_radlw_kgb11::fracrefa, module_radlw_kgb11::fracrefb, module_radlw_kgb11::ka_mo2, module_radlw_kgb11::kb_mo2, module_radlw_parameters::ng11, module_radlw_parameters::ns11, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb11::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb12 ()
Definition at line 5720 of file radlw_main.f.
References module_radlw_kgb12::absa, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb12::forref, module_radlw_kgb12::fracrefa, module_radlw_parameters::ng12, module_radlw_parameters::ns12, module_radlw_main::nspa, module_radlw_main::oneminus, and module_radlw_kgb12::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb13 ()
Definition at line 5904 of file radlw_main.f.
References module_radlw_kgb13::absa, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb13::forref, module_radlw_kgb13::fracrefa, module_radlw_kgb13::fracrefb, module_radlw_kgb13::ka_mco, module_radlw_kgb13::ka_mco2, module_radlw_kgb13::kb_mo3, module_radlw_parameters::ng13, module_radlw_parameters::ns13, module_radlw_main::nspa, module_radlw_main::oneminus, and module_radlw_kgb13::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb14 ()
Definition at line 6150 of file radlw_main.f.
References module_radlw_kgb14::absa, module_radlw_kgb14::absb, module_radlw_kgb14::forref, module_radlw_kgb14::fracrefa, module_radlw_kgb14::fracrefb, module_radlw_parameters::ng14, module_radlw_parameters::ns14, module_radlw_main::nspa, module_radlw_main::nspb, and module_radlw_kgb14::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb15 ()
Definition at line 6218 of file radlw_main.f.
References module_radlw_kgb15::absa, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb15::forref, module_radlw_kgb15::fracrefa, module_radlw_kgb15::ka_mn2, module_radlw_parameters::ng15, module_radlw_parameters::ns15, module_radlw_main::nspa, module_radlw_main::oneminus, and module_radlw_kgb15::selfref.
Referenced by module_radlw_main::taumol().
subroutine taumol::taugb16 ()
Definition at line 6426 of file radlw_main.f.
References module_radlw_kgb16::absa, module_radlw_kgb16::absb, module_radlw_ref::chi_mls, module_radlw_main::f_one, module_radlw_main::f_zero, module_radlw_kgb16::forref, module_radlw_kgb16::fracrefa, module_radlw_kgb16::fracrefb, module_radlw_parameters::ng16, module_radlw_parameters::ns16, module_radlw_main::nspa, module_radlw_main::nspb, module_radlw_main::oneminus, and module_radlw_kgb16::selfref.
Referenced by module_radlw_main::taumol().