Radiation Scheme in CCPP: radsw_main.f File Reference
radsw_main.f File Reference
Modules
module module_radsw_main
This module includes ncep's modifications of the rrtm-sw radiation code from aer inc.
Functions/Subroutines
subroutine, public module_radsw_main::rswinit
This subroutine initializes non-varying module variables, conversion factors, and look-up tables.
subroutine module_radsw_main::mcica_subcol
This subroutine computes the sub-colum cloud profile flag array.
subroutine module_radsw_main::setcoef
This subroutine computes various coefficients needed in radiative transfer calculation.
subroutine module_radsw_main::spcvrtm
This subroutine computes the shortwave radiative fluxes using two-stream method of h. barder and mcica,the monte-carlo independent column approximation, for the representation of sub-grid cloud variability (i.e. cloud overlap).
subroutine module_radsw_main::taumol
This subroutine calculates optical depths for gaseous absorption and rayleigh scattering
subroutine called taugb## (## = 16-29)
subroutine taumol16
The subroutine computes the optical depth in band 16: 2600-3250 cm-1 (low - h2o,ch4; high - ch4)
subroutine taumol17
The subroutine computes the optical depth in band 17: 3250-4000 cm-1 (low - h2o,co2; high - h2o,co2)
subroutine taumol18
The subroutine computes the optical depth in band 18: 4000-4650 cm-1 (low - h2o,ch4; high - ch4)
subroutine taumol19
The subroutine computes the optical depth in band 19: 4650-5150 cm-1 (low - h2o,co2; high - co2)
subroutine taumol20
The subroutine computes the optical depth in band 20: 5150-6150 cm-1 (low - h2o; high - h2o)
subroutine taumol21
The subroutine computes the optical depth in band 21: 6150-7700 cm-1 (low - h2o,co2; high - h2o,co2)
subroutine taumol22
The subroutine computes the optical depth in band 22: 7700-8050 cm-1 (low - h2o,o2; high - o2)
subroutine taumol23
The subroutine computes the optical depth in band 23: 8050-12850 cm-1 (low - h2o; high - nothing)
subroutine taumol24
The subroutine computes the optical depth in band 24: 12850-16000 cm-1 (low - h2o,o2; high - o2)
subroutine taumol25
The subroutine computes the optical depth in band 25: 16000-22650 cm-1 (low - h2o; high - nothing)
subroutine taumol26
The subroutine computes the optical depth in band 26: 22650-29000 cm-1 (low - nothing; high - nothing)
subroutine taumol27
The subroutine computes the optical depth in band 27: 29000-38000 cm-1 (low - o3; high - o3)
subroutine taumol28
The subroutine computes the optical depth in band 28: 38000-50000 cm-1 (low - o3,o2; high - o3,o2)
subroutine taumol29
The subroutine computes the optical depth in band 29: 820-2600 cm-1 (low - h2o; high - co2)
subroutine, public module_radsw_main::swrad
This subroutine is the main sw radiation routine.
subroutine module_radsw_main::cldprop
This subroutine computes the cloud optical properties for each cloudy layer and g-point interval.
subroutine module_radsw_main::spcvrtc
This subroutine computes the shortwave radiative fluxes using two-stream method.
subroutine module_radsw_main::swflux
This subroutine computes the upward and downward radiation fluxes.
Variables
character(40), parameter module_radsw_main::vtagsw ='NCEP SW v5.1 Nov 2012 -RRTMG-SW v3.8 '
real(kind=kind_phys), parameter module_radsw_main::eps = 1.0e-6
real(kind=kind_phys), parameter module_radsw_main::oneminus = 1.0 - eps
real(kind=kind_phys), parameter module_radsw_main::bpade = 1.0/0.278
real(kind=kind_phys), parameter module_radsw_main::stpfac = 296.0/1013.0
real(kind=kind_phys), parameter module_radsw_main::ftiny = 1.0e-12
real(kind=kind_phys), parameter module_radsw_main::s0 = 1368.22
real(kind=kind_phys), parameter module_radsw_main::f_zero = 0.0
real(kind=kind_phys), parameter module_radsw_main::f_one = 1.0
real(kind=kind_phys), parameter module_radsw_main::amdw = con_amd/con_amw
real(kind=kind_phys), parameter module_radsw_main::amdo3 = con_amd/con_amo3
integer, dimension(nblow:nbhgh) module_radsw_main::nspa
integer, dimension(nblow:nbhgh) module_radsw_main::nspb
integer, dimension(nblow:nbhgh) module_radsw_main::idxebc
integer, dimension(nblow:nbhgh) module_radsw_main::idxsfc
integer, parameter module_radsw_main::nuvb = 27
logical module_radsw_main::lhswb = .false.
logical module_radsw_main::lhsw0 = .false.
logical module_radsw_main::lflxprf = .false.
logical module_radsw_main::lfdncmp = .false.
real(kind=kind_phys), dimension(0:ntbmx) module_radsw_main::exp_tbl
real(kind=kind_phys) module_radsw_main::heatfac
integer, parameter module_radsw_main::ipsdsw0 = 1
Function/Subroutine Documentation
subroutine taumol::taumol16 () private
Definition at line 4028 of file radsw_main.f.
References module_radsw_kgb16::absa, module_radsw_kgb16::absb, module_radsw_main::f_one, module_radsw_kgb16::forref, module_radsw_parameters::ng16, module_radsw_parameters::ns16, module_radsw_main::oneminus, module_radsw_kgb16::rayl, module_radsw_kgb16::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol17 ()
Definition at line 4123 of file radsw_main.f.
References module_radsw_kgb17::absa, module_radsw_kgb17::absb, module_radsw_main::f_one, module_radsw_kgb17::forref, module_radsw_parameters::ng17, module_radsw_parameters::ns17, module_radsw_main::oneminus, module_radsw_kgb17::rayl, module_radsw_kgb17::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol18 ()
Definition at line 4244 of file radsw_main.f.
References module_radsw_kgb18::absa, module_radsw_kgb18::absb, module_radsw_main::f_one, module_radsw_kgb18::forref, module_radsw_parameters::ng18, module_radsw_parameters::ns18, module_radsw_main::oneminus, module_radsw_kgb18::rayl, module_radsw_kgb18::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol19 ()
Definition at line 4339 of file radsw_main.f.
References module_radsw_kgb19::absa, module_radsw_kgb19::absb, module_radsw_main::f_one, module_radsw_kgb19::forref, module_radsw_parameters::ng19, module_radsw_parameters::ns19, module_radsw_main::oneminus, module_radsw_kgb19::rayl, module_radsw_kgb19::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol20 ()
Definition at line 4433 of file radsw_main.f.
References module_radsw_kgb20::absa, module_radsw_kgb20::absb, module_radsw_kgb20::absch4, module_radsw_kgb20::forref, module_radsw_parameters::ng20, module_radsw_parameters::ns20, module_radsw_kgb20::rayl, and module_radsw_kgb20::selfref.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol21 ()
Definition at line 4513 of file radsw_main.f.
References module_radsw_kgb21::absa, module_radsw_kgb21::absb, module_radsw_main::f_one, module_radsw_kgb21::forref, module_radsw_parameters::ng21, module_radsw_parameters::ns21, module_radsw_main::oneminus, module_radsw_kgb21::rayl, module_radsw_kgb21::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol22 ()
Definition at line 4633 of file radsw_main.f.
References module_radsw_kgb22::absa, module_radsw_kgb22::absb, module_radsw_main::f_one, module_radsw_kgb22::forref, module_radsw_parameters::ng22, module_radsw_parameters::ns22, module_radsw_main::oneminus, module_radsw_kgb22::rayl, module_radsw_kgb22::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol23 ()
Definition at line 4739 of file radsw_main.f.
References module_radsw_kgb23::absa, module_radsw_main::f_zero, module_radsw_kgb23::forref, module_radsw_kgb23::givfac, module_radsw_parameters::ng23, module_radsw_parameters::ns23, module_radsw_kgb23::rayl, and module_radsw_kgb23::selfref.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol24 ()
Definition at line 4800 of file radsw_main.f.
References module_radsw_kgb24::absa, module_radsw_kgb24::absb, module_radsw_kgb24::abso3a, module_radsw_kgb24::abso3b, module_radsw_main::f_one, module_radsw_kgb24::forref, module_radsw_parameters::ng24, module_radsw_parameters::ns24, module_radsw_main::oneminus, module_radsw_kgb24::rayla, module_radsw_kgb24::raylb, module_radsw_kgb24::selfref, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol25 ()
Definition at line 4894 of file radsw_main.f.
References module_radsw_kgb25::absa, module_radsw_kgb25::abso3a, module_radsw_kgb25::abso3b, module_radsw_parameters::ng25, module_radsw_parameters::ns25, and module_radsw_kgb25::rayl.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol26 ()
Definition at line 4948 of file radsw_main.f.
References module_radsw_main::f_zero, module_radsw_parameters::ng26, module_radsw_parameters::ns26, and module_radsw_kgb26::rayl.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol27 ()
Definition at line 4982 of file radsw_main.f.
References module_radsw_kgb27::absa, module_radsw_kgb27::absb, module_radsw_parameters::ng27, module_radsw_parameters::ns27, and module_radsw_kgb27::rayl.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol28 ()
Definition at line 5042 of file radsw_main.f.
References module_radsw_kgb28::absa, module_radsw_kgb28::absb, module_radsw_main::f_one, module_radsw_parameters::ng28, module_radsw_parameters::ns28, module_radsw_main::oneminus, module_radsw_kgb28::rayl, and module_radsw_sflux::strrat.
Referenced by module_radsw_main::taumol().
subroutine taumol::taumol29 ()
Definition at line 5149 of file radsw_main.f.
References module_radsw_kgb29::absa, module_radsw_kgb29::absb, module_radsw_kgb29::absco2, module_radsw_kgb29::absh2o, module_radsw_kgb29::forref, module_radsw_parameters::ng29, module_radsw_parameters::ns29, module_radsw_kgb29::rayl, and module_radsw_kgb29::selfref.
Referenced by module_radsw_main::taumol().