Radiation Scheme in CCPP: zhang_orig/radiation_aerosols.f File Reference
radiation_aerosols.f File Reference
Data Types
type module_radiation_aerosols::gocart_index_type
type module_radiation_aerosols::tracer_index_type
Modules
module module_radiation_aerosols
This module contains climatological atmospheric aerosol schemes for radiation computations.
Functions/Subroutines
subroutine, public module_radiation_aerosols::aer_init
The initialization program to set up necessary parameters and working arrays.
subroutine wrt_aerlog
This subroutine writes aerosol parameter configuration to run log file.
subroutine set_spectrum
This subroutine defines the one wavenumber solar fluxes based on toa solar spectral distribution, and define the one wavenumber IR fluxes based on black-body emission distribution at a predefined temperature.
subroutine set_volcaer
The initialization program for stratospheric volcanic aerosols.
subroutine module_radiation_aerosols::clim_aerinit
This subroutine is the opac-climatology aerosol initialization program to set up necessary parameters and working arrays.
subroutine set_aercoef
the initialization program for climatological aerosols. the program reads and maps the pre-tabulated aerosol optical spectral data onto corresponding SW radiation spectral bands.
subroutine optavg
compute mean aerosols optical properties over each SW radiation spectral band for each of the species components. This program follows GFDL's approach for thick cloud optical property in SW radiation scheme (2000).
subroutine, public module_radiation_aerosols::aer_update
This subroutine checks and updates time varying climatology aerosol data sets.
subroutine trop_update
update the monthly global distribution of aerosol profiles in five degree horizontal resolution.
subroutine volc_update
search historical volcanic data sets to find and read in monthly 45-degree lat-zone band of optical depth.
subroutine module_radiation_aerosols::gocart_init
the initialization program for gocart aerosols
subroutine set_aerspc (raddt, fdaer)
determine merging coefficients ctaer; setup aerosol specification.
subroutine rd_gocart_luts
This subroutine reads input gocart aerosol optical data from Mie code calculations.
subroutine optavg_grt
This subroutine computes mean aerosols optical properties over each SW/LW radiation spectral band for each of the species components. This program follows GFDL's approach for thick cloud optical property in SW radiation scheme (2000)
subroutine rd_gocart_clim
This subroutine:
subroutine module_radiation_aerosols::setgocartaer
This subroutine computes SW + LW aerosol optical properties for gocart aerosol species (merged from fcst and clim fields).
subroutine map_aermr
This subroutine maps input tracer fields (trcly) to local tracer array (aermr).
subroutine aeropt_grt
This subroutine computes aerosols optical properties in NSWLWBD SW/LW bands. Aerosol distribution at each grid point is composed from up to NMXG aerosol species (from NUM_GRIDCOMP components).
subroutine, public module_radiation_aerosols::setaer
This subroutine computes aerosols optical properties.
subroutine module_radiation_aerosols::aer_property
This subroutine maps the 5 degree global climatological aerosol data set onto model grids, and compute aerosol optical properties for SW and LW radiations.
subroutine radclimaer
This subroutine computes aerosols optical properties in NSWLWBD bands. there are seven different vertical profile structures. in the troposphere, aerosol distribution at each grid point is composed from up to six components out of ten different substances.
Function/Subroutine Documentation
subroutine setgocartaer::aeropt_grt () private
Definition at line 5073 of file radiation_aerosols.f.
References module_radiation_aerosols::asyrhd_grt, module_radiation_aerosols::asyrhi_grt, module_radiation_aerosols::dm_indx, module_radiation_aerosols::extrhd_grt, module_radiation_aerosols::extrhi_grt, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::gridcomp, module_radiation_aerosols::isoot, module_radiation_aerosols::issam, module_radiation_aerosols::isuso, module_radiation_aerosols::iwaso, module_radiation_aerosols::kcm1, module_radiation_aerosols::krhlev, module_radiation_aerosols::max_gridcomp, module_radiation_aerosols::max_num_gridcomp, module_radiation_aerosols::num_gridcomp, module_radiation_aerosols::nv_aod, module_radiation_aerosols::rhlev_grt, module_radiation_aerosols::ssarhd_grt, and module_radiation_aerosols::ssarhi_grt.
subroutine setgocartaer::map_aermr () private
Definition at line 4987 of file radiation_aerosols.f.
References module_radiation_aerosols::dm_indx, module_radiation_aerosols::dmfcs_indx, and module_radiation_aerosols::f_zero.
subroutine clim_aerinit::optavg () private
Definition at line 1373 of file radiation_aerosols.f.
References module_radiation_aerosols::asyrhd, module_radiation_aerosols::asyrhi, module_radiation_aerosols::extrhd, module_radiation_aerosols::extrhi, module_radiation_aerosols::extstra, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, physparam::lalwflg, physparam::laswflg, physparam::lavoflg, module_radiation_aerosols::ncm1, module_radiation_aerosols::ncm2, module_radiation_aerosols::nlwbnd, module_radiation_aerosols::nrhlev, module_radiation_aerosols::nswbnd, module_radiation_aerosols::scarhd, module_radiation_aerosols::scarhi, module_radiation_aerosols::ssarhd, module_radiation_aerosols::ssarhi, trop_update(), and volc_update().
subroutine gocart_init::optavg_grt () private
Definition at line 4166 of file radiation_aerosols.f.
References module_radiation_aerosols::asyrhd_grt, module_radiation_aerosols::asyrhi_grt, module_radiation_aerosols::extrhd_grt, module_radiation_aerosols::extrhi_grt, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::kcm1, module_radiation_aerosols::kcm2, module_radiation_aerosols::krhlev, module_radiation_aerosols::rhdpasy0_grt, module_radiation_aerosols::rhdpext0_grt, module_radiation_aerosols::rhdpssa0_grt, module_radiation_aerosols::rhidasy0_grt, module_radiation_aerosols::rhidext0_grt, module_radiation_aerosols::rhidssa0_grt, module_radiation_aerosols::ssarhd_grt, and module_radiation_aerosols::ssarhi_grt.
subroutine aer_property::radclimaer () private
Parameters
[in] cmix real, (NCM), mixing ratioes of aerosol components
[in] denn real, 2, aerosol number densities
[in] rh1 real, (NLAY), relative humidity
[in] delz real, (NLAY), effective layer thickness in km
[in] idmaer integer, (NLAY), aerosol domain index
[in] NXC integer, 1number of different aerosol components
[in] NLAY integer, 1, vertical dimensions
[out] tauae real, (NLAY, NSWLWBD), optical depth
[out] ssaae real, (NLAY, NSWLWBD), single scattering albedo
[out] asyae real, (NLAY, NSWLWBD), asymmetry parameter
[out] aerodp real, (IMAX, NSPC+1), vertically integrated aer-opt-depth
Definition at line 3059 of file radiation_aerosols.f.
References module_radiation_aerosols::asyrhd, module_radiation_aerosols::asyrhi, module_radiation_aerosols::extrhd, module_radiation_aerosols::extrhd_grt, module_radiation_aerosols::extrhi, module_radiation_aerosols::extrhi_grt, module_radiation_aerosols::extstra, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::get_clim, module_radiation_aerosols::idxspc, module_radiation_aerosols::iendwv_grt, physparam::ivflip, module_radiation_aerosols::kaerbnd, module_radiation_aerosols::krhlev, module_radiation_aerosols::lckprnt, module_radiation_aerosols::lgrtint, module_radsw_parameters::nbdsw, module_radiation_aerosols::ncm, module_radiation_aerosols::ncm1, module_radiation_aerosols::nlwbnd, module_radiation_aerosols::nrhlev, module_radiation_aerosols::nswbnd, module_radiation_aerosols::nswlwbd, module_radsw_parameters::nswstr, module_radiation_aerosols::nv_aod, module_radiation_aerosols::nwvtir, module_radiation_aerosols::nwvtot, optavg_grt(), rd_gocart_clim(), rd_gocart_luts(), module_radiation_aerosols::rhdpasy0_grt, module_radiation_aerosols::rhdpext0_grt, module_radiation_aerosols::rhdpssa0_grt, module_radiation_aerosols::rhidasy0_grt, module_radiation_aerosols::rhidext0_grt, module_radiation_aerosols::rhidssa0_grt, module_radiation_aerosols::rhlev, module_radiation_aerosols::rhlev_grt, module_radiation_aerosols::scarhd, module_radiation_aerosols::scarhi, set_aerspc(), module_radiation_aerosols::ssarhd, module_radiation_aerosols::ssarhi, module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
subroutine gocart_init::rd_gocart_clim () private
read in aerosol dry mass and surface pressure from GEOS3-GOCART C3.1 2000 monthly dataset or aerosol mixing ratio and surface pressure from GEOS4-GOCART 2000-2007 averaged monthly data set.
compute goes lat/lon array (for horizontal mapping)
Definition at line 4384 of file radiation_aerosols.f.
References aeropt_grt(), physcons::con_amd, physcons::con_rd, module_radiation_aerosols::ctaer, module_radiation_aerosols::dltx, module_radiation_aerosols::dlty, module_radiation_aerosols::dm_indx, module_radiation_aerosols::dmclmg, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::geos_rlat, module_radiation_aerosols::geos_rlon, module_radiation_aerosols::get_clim, module_radiation_aerosols::get_fcst, module_radiation_aerosols::gocart_climo, module_radiation_aerosols::gridcomp, module_radiation_aerosols::imxg, physparam::ivflip, module_radiation_aerosols::jmxg, module_radiation_aerosols::kmxg, physparam::lalwflg, physparam::laswflg, map_aermr(), module_radiation_aerosols::molwgt, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, module_radiation_aerosols::nlwbnd, module_radiation_aerosols::nmxg, module_radiation_aerosols::nswlwbd, module_radiation_aerosols::num_gridcomp, and module_radiation_aerosols::psclmg.
subroutine gocart_init::rd_gocart_luts () private
Definition at line 3990 of file radiation_aerosols.f.
References module_radiation_aerosols::iendwv_grt, module_radiation_aerosols::isoot, module_radiation_aerosols::issam, module_radiation_aerosols::isscm, module_radiation_aerosols::isuso, module_radiation_aerosols::iwaso, module_radiation_aerosols::kaerbnd, module_radiation_aerosols::kcm1, module_radiation_aerosols::kcm2, module_radiation_aerosols::krhlev, module_radiation_aerosols::lckprnt, module_radiation_aerosols::rhdpasy0_grt, module_radiation_aerosols::rhdpext0_grt, module_radiation_aerosols::rhdpssa0_grt, module_radiation_aerosols::rhidasy0_grt, module_radiation_aerosols::rhidext0_grt, and module_radiation_aerosols::rhidssa0_grt.
subroutine clim_aerinit::set_aercoef () private
Definition at line 1036 of file radiation_aerosols.f.
References physparam::aeros_file, module_radiation_aerosols::asyrhd, module_radiation_aerosols::asyrhi, module_radiation_aerosols::extrhd, module_radiation_aerosols::extrhi, module_radiation_aerosols::extstra, module_radiation_aerosols::f_zero, module_radiation_aerosols::haer, module_radiation_aerosols::imxae, module_radiation_aerosols::jmxae, physparam::lalwflg, physparam::laswflg, module_radiation_aerosols::naerbnd, module_radiation_aerosols::ncm1, module_radiation_aerosols::ncm2, module_radiation_aerosols::nlwbnd, module_radiation_aerosols::nlwstr, module_radiation_aerosols::nrhlev, module_radiation_aerosols::nswbnd, module_radiation_aerosols::nswlwbd, module_radsw_parameters::nswstr, module_radiation_aerosols::nv_aod, optavg(), module_radiation_aerosols::prsref, module_radiation_aerosols::scarhd, module_radiation_aerosols::scarhi, module_radiation_aerosols::sigref, module_radiation_aerosols::ssarhd, module_radiation_aerosols::ssarhi, module_radiation_aerosols::wvn550, module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
subroutine gocart_init::set_aerspc (real (kind=kind_phys), intent(in) raddt, real (kind=kind_phys), intent(in) fdaer) private
Definition at line 3691 of file radiation_aerosols.f.
References module_radiation_aerosols::ctaer, module_radiation_aerosols::dm_indx, module_radiation_aerosols::dmfcs_indx, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::get_clim, module_radiation_aerosols::get_fcst, module_radiation_aerosols::gridcomp, module_radiation_aerosols::isoot, module_radiation_aerosols::issam, module_radiation_aerosols::isscm, module_radiation_aerosols::isuso, module_radiation_aerosols::iwaso, module_radiation_aerosols::kcm, module_radiation_aerosols::kcm1, module_radiation_aerosols::kcm2, module_radiation_aerosols::lckprnt, module_radiation_aerosols::max_gridcomp, module_radiation_aerosols::max_num_gridcomp, module_radiation_aerosols::nmxg, and module_radiation_aerosols::num_gridcomp.
subroutine aer_init::set_spectrum () private
Definition at line 809 of file radiation_aerosols.f.
References physcons::con_boltz, physcons::con_c, physcons::con_pi, physcons::con_plnk, physcons::con_t0c, module_radiation_aerosols::nwvns0, module_radiation_aerosols::nwvsol, module_radiation_aerosols::nwvtir, and module_radiation_aerosols::s0intv.
subroutine aer_init::set_volcaer () private
Definition at line 898 of file radiation_aerosols.f.
References module_radiation_aerosols::ivolae, and set_aercoef().
subroutine aer_update::trop_update () private
Definition at line 1708 of file radiation_aerosols.f.
References physparam::aeros_file, module_radiation_aerosols::cmixg, module_radiation_aerosols::denng, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::idxcg, module_radiation_aerosols::imxae, module_radiation_aerosols::jmxae, module_radiation_aerosols::kprfg, and module_radiation_aerosols::nxc.
subroutine aer_update::volc_update () private
Definition at line 1866 of file radiation_aerosols.f.
References module_radiation_aerosols::aer_property(), module_radiation_aerosols::cmixg, physcons::con_g, module_radiation_aerosols::denng, module_radiation_aerosols::f_one, module_radiation_aerosols::f_zero, module_radiation_aerosols::haer, physparam::iaerflg, physparam::iaermdl, module_radiation_aerosols::idxcg, module_radiation_aerosols::imxae, physparam::ivflip, module_radiation_aerosols::ivolae, module_radiation_aerosols::jmxae, module_radiation_aerosols::kmonsav, module_radiation_aerosols::kprfg, module_radiation_aerosols::kyrend, module_radiation_aerosols::kyrsav, module_radiation_aerosols::kyrstr, physparam::lalwflg, physparam::laswflg, physparam::lavoflg, module_radiation_aerosols::maxvyr, module_radiation_aerosols::minvyr, module_radlw_parameters::nbdlw, module_radsw_parameters::nbdsw, module_radiation_aerosols::nf_aelw, module_radiation_aerosols::nf_aesw, module_radiation_aerosols::nlwbnd, module_radiation_aerosols::nspc, module_radiation_aerosols::nspc1, module_radiation_aerosols::nswbnd, module_radiation_aerosols::nswlwbd, module_radsw_parameters::nswstr, module_radiation_aerosols::nv_aod, module_radiation_aerosols::nxc, module_radiation_aerosols::prsref, radclimaer(), module_radiation_aerosols::setgocartaer(), module_radiation_aerosols::sigref, module_radlw_parameters::wvnlw1, and module_radlw_parameters::wvnlw2.
subroutine aer_init::wrt_aerlog () private
Definition at line 712 of file radiation_aerosols.f.
References physparam::iaerflg, physparam::iaermdl, physparam::lalw1bd, physparam::lalwflg, physparam::laswflg, physparam::lavoflg, and module_radiation_aerosols::vtagaer.