Microphysics Scheme in CCPP: calpreciptype.f File Reference
calpreciptype.f File Reference
Functions/Subroutines
subroutine calwxt (lm, lp1, t, q, pmid, pint, d608, rog, epsq, zint, iwx, twet)
This subroutine computes precipitation type using a decision tree approach that uses variables such as integrated wet bulb temp below freezing and lowest layer temperature.
subroutine calwxt_ramer (lm, lp1, t, q, pmid, rh, td, pint, ptyp)
This subroutine is written and provided by Jim Ramer at NOAA/FSL.
real function xmytw (t, td, p)
subroutine calwxt_bourg (lm, lp1, rn, g, t, q, pmid, pint, zint, ptype)
This subrtouien computes precipitation type using a decision tree approach that uses the so-called "energy method" of Bourgouin of AES (Canada) 1992.
subroutine calwxt_revised (lm, lp1, t, q, pmid, pint, d608, rog, epsq, zint, twet, iwx)
This subroutine computes precipitation type using a decision tree approach that uses variables such as integrated wet bulb temp below freezing and lowest layer temperature.
subroutine calwxt_explicit (lm, tskin, sr, f_rimef, iwx)
The subroutine computes precipitation type using explicit fields from the model microphysics.
subroutine calwxt_dominant (nalg, rain, freezr, sleet, snow, domr, domzr, domip, doms)
This subroutine takes the precip type solutions from different algorithms and sums them up to give a domain type.
subroutine calpreciptype (kdt, nrcm, im, ix, lm, lp1, randomno, xlat, xlon, gt0, gq0, prsl, prsi, prec, phii, n3dfercld, tskin, sr, phy_f3d, domr, domzr, domip, doms)
This subroutine computes precipitation type. It is adopted from post but was made into column to used by GFS model.
Function/Subroutine Documentation
subroutine calpreciptype (integer, intent(in) kdt, integer, intent(in) nrcm, integer, intent(in) im, integer, intent(in) ix, integer, intent(in) lm, integer, intent(in) lp1, real, dimension(ix,nrcm), intent(in) randomno, real, dimension(im), intent(in) xlat, real, dimension(im), intent(in) xlon, real(kind=kind_phys), dimension(ix,lm), intent(in) gt0, real(kind=kind_phys), dimension(ix,lm), intent(in) gq0, real(kind=kind_phys), dimension(ix,lm), intent(in) prsl, real(kind=kind_phys), dimension(ix,lp1), intent(in) prsi, real(kind=kind_phys), dimension(im), intent(in) prec, real(kind=kind_phys), dimension(ix,lp1), intent(in) phii, integer, intent(in) n3dfercld, real(kind=kind_phys), dimension(im), intent(in) tskin, real(kind=kind_phys), dimension(im), intent(in) sr, real(kind=kind_phys), dimension(ix,lm), intent(in) phy_f3d, real(kind=kind_phys), dimension(im), intent(out) domr, real(kind=kind_phys), dimension(im), intent(out) domzr, real(kind=kind_phys), dimension(im), intent(out) domip, real(kind=kind_phys), dimension(im), intent(out) doms)
Parameters
[in] kdt integer, 1, number of the current time step
[in] nrcm integer, 1, second dimension for the random number array rann
[in] im integer, 1, horizontal number of used pts
[in] ix integer, 1, horizontal dimension
[in] lm integer, 1, vertical layer dimension
[in] lp1 integer, 1, lm+1
[in] randomno real,(ix,nrcm),random number array (0-1)
[in] xlat real,(im),latitude (radian)
[in] xlon real,(im),longitude (radian)
[in] gt0 real,(ix,lm), updated temperature
[in] gq0 real,(ix,lm), updated tracers
Todo:
dimension of gq0 should be (ix,lm,ntrac)?
Parameters
[in] prsl real,(ix,lm), mean layer pressure
[in] prsi real,(ix,lp1), pressure at layer interfaces
[in] prec real,(im), total rain at this time step (rain)
[in] phii real,(ix,lp1), interface geopotential \((m^2/s^2)\)
[in] n3dfercld integer,1,number of 3D arrays needed for microphysics(num_p3d)
[in] tskin real,(im), ground surface temperature in K (tsea)
[in] sr real,(im), ratio of snow to total precipitation
[in] phy_f3d real,(ix,lm), 3d arrays saved for restart
[out] domr real,(im), dominant precip type for rain
[out] domzr real,(im), dominant precip type for freezing rain
[out] domip real,(im), dominant precip type for sleet
[out] doms real,(im), dominant precip type for snow
General Algorithm
Compute wet bulb temperature
call calwxt() to compute instantaneous precipitation type.
For Ramer algorithm, call calwxt_ramer()
For Bourgouin algorithm, call calwxt_bourg()
For revised NCEP algorithm, call calwxt_revised()
For explicit algorithm(n3dfercld=3,ferrier's scheme), call calwxt_explicit()
call calwxt_dominant() to compute dominant precip type
Definition at line 33 of file calpreciptype.f.
References calwxt(), calwxt_bourg(), calwxt_dominant(), calwxt_explicit(), calwxt_ramer(), and calwxt_revised().
Referenced by gbphys().
subroutine calwxt (integer, intent(in) lm, integer, intent(in) lp1, real, dimension(lm), intent(in) t, real, dimension(lm), intent(in) q, real, dimension(lm), intent(in) pmid, real, dimension(lp1), intent(in) pint, real, intent(in) d608, real, intent(in) rog, real, intent(in) epsq, real, dimension(lp1), intent(in) zint, integer, intent(out) iwx, real, dimension(lm), intent(in) twet)
see baldwin and contorno
Definition at line 256 of file calpreciptype.f.
Referenced by calpreciptype().
subroutine calwxt_bourg (integer, intent(in) lm, integer, intent(in) lp1, real, dimension(2), intent(in) rn, real, intent(in) g, real, dimension(lm), intent(in) t, real, dimension(lm), intent(in) q, real, dimension(lm), intent(in) pmid, real, dimension(lp1), intent(in) pint, real, dimension(lp1), intent(in) zint, integer, intent(out) ptype)
Definition at line 908 of file calpreciptype.f.
Referenced by calpreciptype().
subroutine calwxt_dominant (integer, intent(in) nalg, integer, dimension(nalg), intent(in) rain, integer, dimension(nalg), intent(in) freezr, integer, dimension(nalg), intent(in) sleet, integer, dimension(nalg), intent(in) snow, real, intent(out) domr, real, intent(out) domzr, real, intent(out) domip, real, intent(out) doms)
Definition at line 1400 of file calpreciptype.f.
Referenced by calpreciptype().
subroutine calwxt_explicit (integer, intent(in) lm, real, intent(in) tskin, real, intent(in) sr, real, dimension(lm), intent(in) f_rimef, integer, intent(out) iwx)
Definition at line 1337 of file calpreciptype.f.
Referenced by calpreciptype().
subroutine calwxt_ramer (integer, intent(in) lm, integer, intent(in) lp1, real, dimension(lm), intent(in) t, real, dimension(lm), intent(in) q, real, dimension(lm), intent(in) pmid, real, dimension(lm), intent(in) rh, real, dimension(lm), intent(in) td, real, dimension(lp1), intent(in) pint, integer, intent(out) ptyp)
Ramer J, 1993: An expirical technique for diagnosing precipitation type from model output. preprints, 5th conf. on aviation weather systems, vienna, va, Amer. Meteor. Soc., 227-230.
Definition at line 509 of file calpreciptype.f.
Referenced by calpreciptype().
subroutine calwxt_revised (integer, intent(in) lm, integer, intent(in) lp1, real, dimension(lm), intent(in) t, real, dimension(lm), intent(in) q, real, dimension(lm), intent(in) pmid, real, dimension(lp1), intent(in) pint, real, intent(in) d608, real, intent(in) rog, real, intent(in) epsq, real, dimension(lp1), intent(in) zint, real, dimension(lm), intent(in) twet, integer, intent(out) iwx)
see baldwin and contorno preprint from 13th weather analysis and forecasting conference for more details (or baldwin et al, 10th NWP conference preprint)
since the original version of the algorithm has a high bias for freezing rain and sleet, the goal is to balance that bias with a version more likely to predict snow
Definition at line 1080 of file calpreciptype.f.
Referenced by calpreciptype().
real function xmytw (real t, real td, real p)
Definition at line 786 of file calpreciptype.f.