Microphysics Scheme in CCPP: gbphys.f File Reference
gbphys.f File Reference
Functions/Subroutines
subroutine gbphys
Function/Subroutine Documentation
subroutine gbphys ()
Definition at line 469 of file gbphys.f.
References calpreciptype(), gscond(), gscondp(), gsmdrive(), precpd(), precpd_shoc(), and precpdp().