Microphysics Scheme in CCPP: gsmddrive.f File Reference
gsmddrive.f File Reference
Functions/Subroutines
subroutine gsmdrive (im, ix, lm, dt, grav, hvap, hsub, cp, me, lprnt, ipr, prsl, del, rhc, xncw, flgmin, tin, qin, ccin, f_ice, f_rain, f_rimef, aprec, sr)
subroutine micro_init (len1, len2, num_p3d, len4, phy_f3d, DT, FHOUR, me, first)
subroutine init_micro (DTP, len1, len2, num_p3d, len4, phy_f3d, fhour, me)
Function/Subroutine Documentation
subroutine gsmdrive (integer im, integer ix, integer lm, real (kind=kind_phys) dt, real (kind=kind_phys) grav, real (kind=kind_phys) hvap, real (kind=kind_phys) hsub, real (kind=kind_phys) cp, integer me, logical lprnt, integer ipr, real (kind=kind_phys), dimension(ix,lm) prsl, real (kind=kind_phys), dimension(ix,lm) del, real (kind=kind_phys), dimension(im,lm) rhc, real (kind=kind_phys), dimension(im) xncw, real (kind=kind_phys), dimension(im) flgmin, real (kind=kind_phys), dimension(ix,lm) tin, real (kind=kind_phys), dimension(ix,lm) qin, real (kind=kind_phys), dimension(ix,lm) ccin, real (kind=kind_phys), dimension(ix,lm) f_ice, real (kind=kind_phys), dimension(ix,lm) f_rain, real (kind=kind_phys), dimension(ix,lm) f_rimef, real (kind=kind_phys), dimension(im) aprec, real (kind=kind_phys), dimension(im) sr)
Definition at line 16 of file gsmddrive.f.
Referenced by gbphys().
subroutine init_micro (real (kind=kind_phys) DTP, integer len1, integer len2, integer num_p3d, integer len4, real (kind=kind_phys), dimension(len1,len2,num_p3d,len4) phy_f3d, real (kind=kind_phys) fhour, integer me)
Definition at line 458 of file gsmddrive.f.
References micro_init().
subroutine micro_init (integer len1, integer len2, integer num_p3d, integer len4, real (kind=kind_phys), dimension(len1,len2,num_p3d,len4) phy_f3d, real (kind=kind_phys) DT, real (kind=kind_phys) FHOUR, integer me, logical first)
Definition at line 436 of file gsmddrive.f.
Referenced by init_micro().